package planning.autogen;


/**
* planning/autogen/PlanningProblemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlanningData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class PlanningProblemHelper
{
  private static String  _id = "IDL:planning/autogen/PlanningProblem:1.0";

  public static void insert (org.omg.CORBA.Any a, planning.autogen.PlanningProblem that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static planning.autogen.PlanningProblem extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_maplGoal",
            _tcOf_members0,
            null);
          _tcOf_members0 = Planner.ObjectDeclarationHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (Planner.ObjectListHelper.id (), "ObjectList", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "m_objectList",
            _tcOf_members0,
            null);
          _tcOf_members0 = Planner.FactHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (Planner.FactListHelper.id (), "FactList", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "m_factList",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "m_domainFile",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (planning.autogen.PlanningProblemHelper.id (), "PlanningProblem", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static planning.autogen.PlanningProblem read (org.omg.CORBA.portable.InputStream istream)
  {
    planning.autogen.PlanningProblem value = new planning.autogen.PlanningProblem ();
    value.m_maplGoal = istream.read_string ();
    value.m_objectList = Planner.ObjectListHelper.read (istream);
    value.m_factList = Planner.FactListHelper.read (istream);
    value.m_domainFile = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, planning.autogen.PlanningProblem value)
  {
    ostream.write_string (value.m_maplGoal);
    Planner.ObjectListHelper.write (ostream, value.m_objectList);
    Planner.FactListHelper.write (ostream, value.m_factList);
    ostream.write_string (value.m_domainFile);
  }

}
