package BindingData;


/**
* BindingData/binderTokenID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public interface binderTokenID
{

  /// the WM ID of the \p BinderToken
  public static final String value = "BinderToken";
}
