package BindingData;

/**
* BindingData/DisambiguatingUnionFeatureInstanceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class DisambiguatingUnionFeatureInstanceHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingData.DisambiguatingUnionFeatureInstance value = null;

  public DisambiguatingUnionFeatureInstanceHolder ()
  {
  }

  public DisambiguatingUnionFeatureInstanceHolder (BindingData.DisambiguatingUnionFeatureInstance initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingData.DisambiguatingUnionFeatureInstanceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingData.DisambiguatingUnionFeatureInstanceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingData.DisambiguatingUnionFeatureInstanceHelper.type ();
  }

}
