package BindingData;


/**
* BindingData/FeaturePointer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class FeaturePointer implements org.omg.CORBA.portable.IDLEntity
{

  /// through \p m_pointer
  public String m_type = null;

  /// Points to the feature data (storage in Binding WM is assumed)
  public String m_address = null;

  // of this later)
  public String m_immediateProxyID = null;

  public FeaturePointer ()
  {
  } // ctor

  public FeaturePointer (String _m_type, String _m_address, String _m_immediateProxyID)
  {
    m_type = _m_type;
    m_address = _m_address;
    m_immediateProxyID = _m_immediateProxyID;
  } // ctor

} // class FeaturePointer
