package BindingData;

/**
* BindingData/FeaturePointerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class FeaturePointerHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingData.FeaturePointer value = null;

  public FeaturePointerHolder ()
  {
  }

  public FeaturePointerHolder (BindingData.FeaturePointer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingData.FeaturePointerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingData.FeaturePointerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingData.FeaturePointerHelper.type ();
  }

}
