package BindingData;

/**
* BindingData/PortTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/// the type of \p Port that a proxy may have to a relation
public final class PortTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingData.PortType value = null;

  public PortTypeHolder ()
  {
  }

  public PortTypeHolder (BindingData.PortType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingData.PortTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingData.PortTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingData.PortTypeHelper.type ();
  }

}
