package BindingData;


/**
* BindingData/PortType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/// the type of \p Port that a proxy may have to a relation
public class PortType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static BindingData.PortType[] __array = new BindingData.PortType [__size];

  public static final int _SIMPLE_RELATION = 0;
  public static final BindingData.PortType SIMPLE_RELATION = new BindingData.PortType(_SIMPLE_RELATION);
  public static final int _SPATIAL_RELATION = 1;
  public static final BindingData.PortType SPATIAL_RELATION = new BindingData.PortType(_SPATIAL_RELATION);
  public static final int _TEMPORAL_RELATION = 2;
  public static final BindingData.PortType TEMPORAL_RELATION = new BindingData.PortType(_TEMPORAL_RELATION);
  public static final int _PROXY = 3;
  public static final BindingData.PortType PROXY = new BindingData.PortType(_PROXY);

  public int value ()
  {
    return __value;
  }

  public static BindingData.PortType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected PortType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class PortType
