package BindingData;


/**
* BindingData/ProxyUnionScore.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class ProxyUnionScore implements org.omg.CORBA.portable.IDLEntity
{
  public String m_proxyID = null;
  public String m_unionID = null;
  public BindingData.BindingScore m_score = null;

  /// been updated and rescoring is needed.
  public boolean m_updated = false;

  public ProxyUnionScore ()
  {
  } // ctor

  public ProxyUnionScore (String _m_proxyID, String _m_unionID, BindingData.BindingScore _m_score, boolean _m_updated)
  {
    m_proxyID = _m_proxyID;
    m_unionID = _m_unionID;
    m_score = _m_score;
    m_updated = _m_updated;
  } // ctor

} // class ProxyUnionScore
