package BindingData;


/**
* BindingData/WorkingMemoryIDListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/// Used to list a number of binding WM entries
public final class WorkingMemoryIDListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public WorkingMemoryIDListHolder ()
  {
  }

  public WorkingMemoryIDListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingData.WorkingMemoryIDListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingData.WorkingMemoryIDListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingData.WorkingMemoryIDListHelper.type ();
  }

}
