
ADD_DEFINITIONS(-DLINUX)
ADD_DEFINITIONS(-DGL_GLEXT_PROTOTYPES)

SET(ENABLE_FTGL_FONTS 0 CACHE BOOL "Enable ftgl fonts do draw OpenGL fonts?" )
IF(ENABLE_FTGL_FONTS)
  SET(TRUETYPE_FONT /usr/share/fonts/truetype/freefont/FreeSans.ttf CACHE PATH "A valid truetype font on your system")
  ADD_DEFINITIONS(-DTTF_FONT="${TRUETYPE_FONT}")
  INCLUDE_DIRECTORIES(/usr/include/freetype2)
  ADD_DEFINITIONS(-DUSE_FTGL_FONT)
ENDIF(ENABLE_FTGL_FONTS)

SET(TOMGINE_DIR "${V4R_DIR}/v4r/TomGine")

add_definitions(-DTOMGINE_DIR="${TOMGINE_DIR}")

MESSAGE( STATUS "TOMGINE_DIR is ${TOMGINE_DIR}")
