package org.cognitivesystems.common.autogen.Math;

/**
* org/cognitivesystems/common/autogen/Math/Vector3DHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Math.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Vector3DHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cognitivesystems.common.autogen.Math.Vector3D value = null;

  public Vector3DHolder ()
  {
  }

  public Vector3DHolder (org.cognitivesystems.common.autogen.Math.Vector3D initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cognitivesystems.common.autogen.Math.Vector3DHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cognitivesystems.common.autogen.Math.Vector3DHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cognitivesystems.common.autogen.Math.Vector3DHelper.type ();
  }

}
