#! /usr/bin/env python

"""Functional testing for MAPSIM.

usage: %prog [options] 
  -v, --verbose : give verbose output [default: %default]
  -d, --debug   : break testing when errors occur
  -t, --test=TEST : run a test or group of test [default: %default]
  -f, --file=NAME : run a test from a testfile [default: %default]
  -c, --compare: print a detailed comparison between actual and expected result [default: %default]
  -l, --list: print a list of available tests [default: %default]
  --catalogue=FILE: use another file as test catalogue [default: %default]
  --recreate : replace expected results with results of this test run
  --random=SEED : set random seed  [default: %default]
"""

import support
import sys, os.path
from tools.path_tools import path_from_cwd
import functional_tests as ft
import config

catalogue = path_from_cwd(config.functional_tests_file, config.mapsim_dir)

defaults = dict(verbose=False, random=1,test="", file=None, compare=False, list=False, catalogue=catalogue)

def parse_command_line():
    # parse options and required arguments from docstring automatically
    from myoptionparse import OptionParser
    parser = OptionParser(from_doc=__doc__)
    parser.set_defaults_from(defaults)
    options, args = parser.parse_args()
    options.additional_args = " ".join(args)
    return options

if __name__ == "__main__":
    options = parse_command_line()
    config.functional_tests_file = os.path.abspath(options.catalogue)
    os.chdir(config.mapsim_dir)
    ft.run_all_tests(options)

