(define (domain dora-avs-iros11)

(:requirements :quantified-preconditions :equality :action-costs :negative-preconditions :conditional-effects :typing :adl :disjunctive-preconditions)

(:types  node - object
         concept - object
         place_status - object
         agent - object
         feature - object
         boolean - object
         conegroup - object
         subgoal - object
         planning_agent - agent
         visualobject - location
         visualobject - either_visualobject_room
         visualobject - concept
         category - concept
         room - location
         room - either_visualobject_room
         room - concept
         either_visualobject_room - object
         robot - location
         robot - planning_agent
         label - concept
         person - location
         spatial_relation - concept
         place - concept
         location - object
         node_choice - object
         
)

(:constants  place_0__e place_1__e place_5__e place_6__e place_7__e place_9__e place__c__e place__e__e - place
             in on - spatial_relation
             corridor kitchen meetingroom office - category
             placeholder trueplace - place_status
             false true - boolean
             tutor - agent
             dummy-room room_0__t - room
             container - label
             person1 - person
)

(:predicates  (selected ?n - node ?value - node_choice)
              (is-virtual ?o - object)
              (leads_to_room ?p - place ?c - category ?value - boolean)
              (kd-visible_from ?a - agent ?o - visualobject)
              (committed-category ?r - room)
              (engaged ?p - person)
              (virtual-place ?r - room ?value - place)
              (virtual-category ?r - room ?value - category)
              (poss-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (committed-is-in ?o - person)
              (committed-in-room ?p - place)
              (relation ?o - visualobject ?value - spatial_relation)
              (cg-label ?c - conegroup ?value - label)
              (category ?r - room ?value - category)
              (committed-leads_to_room ?p - place ?c - category)
              (kd-is-in ?a - agent ?o - person)
              (trans_related ?o - visualobject ?where - either_visualobject_room)
              (related-to ?o - visualobject ?value - location)
              (kval-related-to ?a - agent ?o - visualobject)
              (placestatus ?n - place ?value - place_status)
              (label ?o - visualobject ?value - label)
              (committed-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (poss-visible_from ?o - visualobject ?v - conegroup)
              (cones_exist ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?value - boolean)
              (committed-relation ?o - visualobject)
              (not-instantiated ?o - object)
              (defined-dora__inobject ?l1 - label ?l2 - label ?c - category)
              (place-exists ?p - place ?value - boolean)
              (poss-leads_to_room ?p - place ?c - category ?v - boolean)
              (poss-is-in ?o - person ?v - place)
              (kd-category ?a - agent ?r - room)
              (committed-contains-a-person-prior ?r - room)
              (poss-category ?r - room ?v - category)
              (visible_from ?o - visualobject ?value - conegroup)
              (started )
              (is-in ?o - robot ?value - place)
              (is-in ?o - person ?value - place)
              (is-visited ?c - conegroup)
              (defined-p-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?c - category)
              (kval-in-room ?a - agent ?p - place)
              (committed-visible_from ?o - visualobject)
              (kval-is-in ?a - agent ?o - person)
              (cg-related-to ?c - conegroup ?value - either_visualobject_room)
              (connected ?p1 - place ?p2 - place)
              (defined-dora__inroom ?l - label ?c - category)
              (kd-in-room ?a - agent ?p - place)
              (kd-related-to ?a - agent ?o - visualobject)
              (poss-in-room ?p - place ?v - room)
              (identity ?r - room ?value - category)
              (unresponsive ?p - person ?value - boolean)
              (cg-relation ?c - conegroup ?value - spatial_relation)
              (unused ?o - object)
              (entity-exists ?o - object ?value - boolean)
              (cg-place ?c - conegroup ?value - place)
              (does-exist ?p - person ?value - boolean)
              (associated-with ?p - person ?value - room)
              (contains-a-person-prior ?r - room ?value - boolean)
              (not_fully_explored ?r - object)
              (in-room ?p - place ?value - room)
              (poss-related-to ?o - visualobject ?v - location)
              (defined-dora__on ?l1 - label ?l2 - label ?c - category)
              (done )
              (poss-contains-a-person-prior ?r - room ?v - boolean)
              (position-reported ?o - visualobject)
              (poss-relation ?o - visualobject ?v - spatial_relation)
              (cones_created ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (committed-related-to ?o - visualobject)
              (attached_to_room ?p - place ?r - room)
)

(:functions  (dora__cost_on ?l1 - label ?l2 - label) - number
             (probability ) - number
             (total-p-cost ) - number
             (dora__on ?l1 - label ?l2 - label ?c - category) - number
             (dora__inroom ?l - label ?c - category) - number
             (search_cost ?l - label ?rel - spatial_relation ?where - either_visualobject_room) - number
             (p-visible ?c - conegroup) - number
             (dora__cost_inroom ?l - label) - number
             (dora__not_inroom ?l - label ?c - category) - number
             (p-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?c - category) - number
             (dora__inobject ?l1 - label ?l2 - label ?c - category) - number
             (roomid ?r - room) - number
             (dora__cost_inobject ?l1 - label ?l2 - label) - number
)


;;LF @e_action(report)
(:action  report_position
          :parameters  (?a - robot ?o - visualobject ?p - place ?h - person)
          :precondition  (and  (kval-related-to ?a ?o)
                               (engaged ?h)
                               (poss-is-in ?h ?p)
                               (kval-is-in ?a ?h)
                               (is-in ?a ?p)
                         )
          :effect  (and  (position-reported ?o)
                         (increase (total-cost ) 1.0000)
                         (started )
                   )
)

(:action  move
          :parameters  (?a - robot ?to - place ?from - place)
          :precondition  (and  (or  (connected ?from ?to)
                                    (connected ?to ?from)
                               )
                               (not (done ))
                               (is-in ?a ?from)
                         )
          :effect  (and  (not (is-in ?a ?from))
                         (is-in ?a ?to)
                         (placestatus ?to trueplace)
                         (kd-in-room ?a ?to)
                         (increase (total-cost ) 2.0000)
                         (started )
                   )
)

(:action  move_direct
          :parameters  (?a - robot ?to - place ?from - place ?via - place)
          :precondition  (and  (or  (connected ?from ?via)
                                    (connected ?via ?from)
                               )
                               (or  (connected ?via ?to)
                                    (connected ?to ?via)
                               )
                               (not (done ))
                               (is-in ?a ?from)
                         )
          :effect  (and  (not (is-in ?a ?from))
                         (is-in ?a ?to)
                         (placestatus ?to trueplace)
                         (kd-in-room ?a ?to)
                         (increase (total-cost ) 3.0000)
                         (started )
                   )
)

(:action  create_cones_in_room
          :parameters  (?a - robot ?l - label ?r - room ?p - place)
          :precondition  (and  (is-in ?a ?p)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                               (poss-obj_exists ?l in ?r true)
                               (not (not_fully_explored ?r))
                               (not (done ))
                         )
          :effect  (and  (cones_created ?l in ?r)
                         (increase (total-cost ) 5.0000)
                         (started )
                   )
)

(:action  create_cones_at_object
          :parameters  (?a - robot ?l - label ?lsupp - label ?rel - spatial_relation ?o - visualobject ?r - room ?p - place)
          :precondition  (and  (is-in ?a ?p)
                               (label ?o ?lsupp)
                               (poss-obj_exists ?l ?rel ?o true)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                               (poss-related-to ?o ?r)
                               (kval-related-to ?a ?o)
                               (not (done ))
                         )
          :effect  (and  (cones_created ?l ?rel ?o)
                         (increase (total-cost ) 4.0000)
                         (started )
                   )
)

(:action  search_for_object_in_room
          :parameters  (?a - robot ?l - label ?r - room ?p - place ?o - visualobject)
          :precondition  (and  (is-in ?a ?p)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                               (label ?o ?l)
                               (or  (cones_created ?l in ?r)
                                    (cones_exist ?l in ?r)
                               )
                               (poss-related-to ?o ?r)
                               (poss-relation ?o in)
                               (not (done ))
                         )
          :effect  (and  (increase (total-cost ) (search_cost ?l in ?r))
                         (started )
                         (when  (poss-related-to ?o ?r)
                                (kd-related-to ?a ?o)
                         )
                   )
)

(:action  search_for_object_at_object
          :parameters  (?a - robot ?l - label ?o - visualobject ?rel - spatial_relation ?p - place ?r - room ?o2 - visualobject)
          :precondition  (and  (is-in ?a ?p)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                               (poss-related-to ?o ?r)
                               (kval-related-to ?a ?o)
                               (label ?o2 ?l)
                               (or  (cones_created ?l ?rel ?o)
                                    (cones_exist ?l ?rel ?o)
                               )
                               (poss-related-to ?o2 ?o)
                               (poss-relation ?o2 ?rel)
                               (not (done ))
                         )
          :effect  (and  (increase (total-cost ) (search_cost ?l ?rel ?o))
                         (started )
                         (kd-related-to ?a ?o2)
                   )
)

(:action  process_conegroup
          :parameters  (?a - robot ?c - conegroup ?p - place ?o - visualobject)
          :precondition  (and  (not (done ))
                               (cg-place ?c ?p)
                               (is-in ?a ?p)
                         )
          :effect  (and  (increase (total-cost ) 15.0000)
                         (started )
                         (when  (poss-visible_from ?o ?c)
                                (kd-visible_from ?a ?o)
                         )
                   )
)

(:action  engage
          :parameters  (?a - robot ?h - person ?p - place)
          :precondition  (and  (not (done ))
                               (not (unresponsive ?h true))
                               (poss-is-in ?h ?p)
                               (kval-is-in ?a ?h)
                               (is-in ?a ?p)
                         )
          :effect  (and  (engaged ?h)
                         (increase (total-cost ) 1.0000)
                         (started )
                   )
)

(:action  ask-for-category-polar
          :parameters  (?a - robot ?r - room ?c - category ?h - person ?p - place)
          :precondition  (and  (not (done ))
                               (engaged ?h)
                               (poss-is-in ?h ?p)
                               (kval-is-in ?a ?h)
                               (is-in ?a ?p)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                         )
          :effect  (and  (increase (total-cost ) 5.0000)
                         (started )
                         (when  (poss-is-in ?h ?p)
                                (kd-is-in ?a ?h)
                         )
                         (when  (poss-category ?r ?c)
                                (kd-category ?a ?r)
                         )
                   )
)

(:action  look-for-people
          :parameters  (?a - robot ?p - place ?p1 - person)
          :precondition  (and  (not (done ))
                               (is-in ?a ?p)
                         )
          :effect  (and  (increase (total-cost ) 10.0000)
                         (started )
                         (when  (poss-is-in ?p1 ?p)
                                (kd-is-in ?a ?p1)
                         )
                   )
)

(:action  __commit-obj_in_room-0
          :parameters  (?a - planning_agent ?l - label ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-category ?r ?c)
                               (defined-dora__inroom ?l ?c)
                               (not (defined-p-obj_exists ?l in ?r ?c))
                               (not (committed-obj_exists ?l in ?r))
                         )
          :effect  (and  (poss-obj_exists ?l in ?r true)
                         (assign (probability ) (dora__inroom ?l ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-obj_in_obj-0
          :parameters  (?a - planning_agent ?l1 - label ?l2 - label ?o - visualobject ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-category ?r ?c)
                               (label ?o ?l2)
                               (poss-related-to ?o ?r)
                               (poss-relation ?o in)
                               (defined-dora__inobject ?l1 ?l2 ?c)
                               (not (defined-p-obj_exists ?l1 in ?o ?c))
                               (not (committed-obj_exists ?l1 in ?o))
                         )
          :effect  (and  (poss-obj_exists ?l1 in ?o true)
                         (assign (probability ) (dora__inobject ?l1 ?l2 ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-obj_on_obj-0
          :parameters  (?a - planning_agent ?l1 - label ?l2 - label ?o - visualobject ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-category ?r ?c)
                               (label ?o ?l2)
                               (poss-related-to ?o ?r)
                               (poss-relation ?o in)
                               (defined-dora__on ?l1 ?l2 ?c)
                               (not (defined-p-obj_exists ?l1 on ?o ?c))
                               (not (committed-obj_exists ?l1 on ?o))
                         )
          :effect  (and  (poss-obj_exists ?l1 on ?o true)
                         (assign (probability ) (dora__on ?l1 ?l2 ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-object_existence_room-0
          :parameters  (?a - planning_agent ?l - label ?rel - spatial_relation ?where - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-category ?where ?c)
                               (defined-p-obj_exists ?l ?rel ?where ?c)
                               (not (committed-obj_exists ?l ?rel ?where))
                         )
          :effect  (and  (poss-obj_exists ?l ?rel ?where true)
                         (assign (probability ) (p-obj_exists ?l ?rel ?where ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-object_existence_object-0
          :parameters  (?a - planning_agent ?l - label ?rel - spatial_relation ?where - visualobject ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-related-to ?where ?r)
                               (poss-category ?r ?c)
                               (defined-p-obj_exists ?l ?rel ?where ?c)
                               (not (committed-obj_exists ?l ?rel ?where))
                         )
          :effect  (and  (poss-obj_exists ?l ?rel ?where true)
                         (assign (probability ) (p-obj_exists ?l ?rel ?where ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-person_in_room-0
          :parameters  (?a - planning_agent ?p - person ?pl - place ?r - room)
          :precondition  (and  (not (started ))
                               (poss-contains-a-person-prior ?r true)
                               (poss-in-room ?pl ?r)
                               (associated-with ?p ?r)
                               (is-virtual ?p)
                               (not (committed-is-in ?p))
                         )
          :effect  (and  (poss-is-in ?p ?pl)
                         (assign (probability ) 1.0000)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-sample_object_location-0
          :parameters  (?a - planning_agent ?o - visualobject ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
          :precondition  (and  (not (started ))
                               (label ?o ?l)
                               (is-virtual ?o)
                               (poss-obj_exists ?l ?rel ?where true)
                               (not (committed-related-to ?o))
                               (not (committed-relation ?o))
                         )
          :effect  (and  (poss-related-to ?o ?where)
                         (poss-relation ?o ?rel)
                         (assign (probability ) 1.0000)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-sample_cone_visibility-0
          :parameters  (?a - planning_agent ?o - visualobject ?c - conegroup ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
          :precondition  (and  (not (started ))
                               (cg-relation ?c ?rel)
                               (cg-related-to ?c ?where)
                               (poss-relation ?o ?rel)
                               (poss-related-to ?o ?where)
                               (cg-label ?c ?l)
                               (label ?o ?l)
                               (not (is-visited ?c))
                               (not (committed-visible_from ?o))
                         )
          :effect  (and  (poss-visible_from ?o ?c)
                         (assign (probability ) (p-visible ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-room_from_placeholder-0
          :parameters  (?a - planning_agent ?p - place ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (placestatus ?p placeholder)
                               (virtual-place ?r ?p)
                               (poss-leads_to_room ?p ?c true)
                               (is-virtual ?r)
                               (not (committed-in-room ?p))
                               (not (committed-category ?r))
                         )
          :effect  (and  (poss-in-room ?p ?r)
                         (poss-category ?r ?c)
                         (assign (probability ) 1.0000)
                         (increase (total-cost ) 10.0000)
                   )
)

(:action  __commit-leads_to_room-place__c__e-meetingroom-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__c__e meetingroom))
                         )
          :effect  (and  (poss-leads_to_room place__c__e meetingroom true)
                         (poss-leads_to_room place__c__e meetingroom true)
                         (assign (probability ) 0.2851)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place_5__e-office-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place_5__e office))
                         )
          :effect  (and  (poss-leads_to_room place_5__e office true)
                         (poss-leads_to_room place_5__e office true)
                         (assign (probability ) 0.2630)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place_5__e-kitchen-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place_5__e kitchen))
                         )
          :effect  (and  (poss-leads_to_room place_5__e kitchen true)
                         (poss-leads_to_room place_5__e kitchen true)
                         (assign (probability ) 0.2630)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__c__e-corridor-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__c__e corridor))
                         )
          :effect  (and  (poss-leads_to_room place__c__e corridor true)
                         (poss-leads_to_room place__c__e corridor true)
                         (assign (probability ) 0.5841)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place_5__e-meetingroom-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place_5__e meetingroom))
                         )
          :effect  (and  (poss-leads_to_room place_5__e meetingroom true)
                         (poss-leads_to_room place_5__e meetingroom true)
                         (assign (probability ) 0.2630)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-contains-a-person-prior-room_0__t-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-contains-a-person-prior room_0__t))
                         )
          :effect  (and  (poss-contains-a-person-prior room_0__t true)
                         (poss-contains-a-person-prior room_0__t true)
                         (assign (probability ) 0.2000)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-is-in-person1-place_5__e
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-is-in person1))
                               (contains-a-person-prior room_0__t true)
                         )
          :effect  (and  (poss-is-in person1 place_5__e)
                         (poss-is-in person1 place_5__e)
                         (assign (probability ) 0.1429)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-is-in-person1-place_6__e
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-is-in person1))
                               (contains-a-person-prior room_0__t true)
                         )
          :effect  (and  (poss-is-in person1 place_6__e)
                         (poss-is-in person1 place_6__e)
                         (assign (probability ) 0.1429)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-is-in-person1-place_9__e
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-is-in person1))
                               (contains-a-person-prior room_0__t true)
                         )
          :effect  (and  (poss-is-in person1 place_9__e)
                         (poss-is-in person1 place_9__e)
                         (assign (probability ) 0.1429)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-is-in-person1-place_7__e
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-is-in person1))
                               (contains-a-person-prior room_0__t true)
                         )
          :effect  (and  (poss-is-in person1 place_7__e)
                         (poss-is-in person1 place_7__e)
                         (assign (probability ) 0.1429)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-is-in-person1-place_0__e
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-is-in person1))
                               (contains-a-person-prior room_0__t true)
                         )
          :effect  (and  (poss-is-in person1 place_0__e)
                         (poss-is-in person1 place_0__e)
                         (assign (probability ) 0.1429)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-is-in-person1-place_1__e
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-is-in person1))
                               (contains-a-person-prior room_0__t true)
                         )
          :effect  (and  (poss-is-in person1 place_1__e)
                         (poss-is-in person1 place_1__e)
                         (assign (probability ) 0.1429)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-is-in-person1-place__e__e
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-is-in person1))
                               (contains-a-person-prior room_0__t true)
                         )
          :effect  (and  (poss-is-in person1 place__e__e)
                         (poss-is-in person1 place__e__e)
                         (assign (probability ) 0.1429)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__c__e-kitchen-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__c__e kitchen))
                         )
          :effect  (and  (poss-leads_to_room place__c__e kitchen true)
                         (poss-leads_to_room place__c__e kitchen true)
                         (assign (probability ) 0.2851)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place_1__e-meetingroom-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place_1__e meetingroom))
                         )
          :effect  (and  (poss-leads_to_room place_1__e meetingroom true)
                         (poss-leads_to_room place_1__e meetingroom true)
                         (assign (probability ) 0.2509)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place_5__e-corridor-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place_5__e corridor))
                         )
          :effect  (and  (poss-leads_to_room place_5__e corridor true)
                         (poss-leads_to_room place_5__e corridor true)
                         (assign (probability ) 0.6465)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__c__e-office-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__c__e office))
                         )
          :effect  (and  (poss-leads_to_room place__c__e office true)
                         (poss-leads_to_room place__c__e office true)
                         (assign (probability ) 0.2851)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place_1__e-corridor-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place_1__e corridor))
                         )
          :effect  (and  (poss-leads_to_room place_1__e corridor true)
                         (poss-leads_to_room place_1__e corridor true)
                         (assign (probability ) 0.6808)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-category-room_0__t-kitchen
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-category room_0__t))
                         )
          :effect  (and  (poss-category room_0__t kitchen)
                         (poss-category room_0__t kitchen)
                         (assign (probability ) 0.1043)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-category-room_0__t-corridor
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-category room_0__t))
                         )
          :effect  (and  (poss-category room_0__t corridor)
                         (poss-category room_0__t corridor)
                         (assign (probability ) 0.5670)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-category-room_0__t-meetingroom
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-category room_0__t))
                         )
          :effect  (and  (poss-category room_0__t meetingroom)
                         (poss-category room_0__t meetingroom)
                         (assign (probability ) 0.1767)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-category-room_0__t-office
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-category room_0__t))
                         )
          :effect  (and  (poss-category room_0__t office)
                         (poss-category room_0__t office)
                         (assign (probability ) 0.1521)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place_1__e-office-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place_1__e office))
                         )
          :effect  (and  (poss-leads_to_room place_1__e office true)
                         (poss-leads_to_room place_1__e office true)
                         (assign (probability ) 0.2509)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place_1__e-kitchen-true
          :parameters  (?a - planning_agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place_1__e kitchen))
                         )
          :effect  (and  (poss-leads_to_room place_1__e kitchen true)
                         (poss-leads_to_room place_1__e kitchen true)
                         (assign (probability ) 0.2509)
                         (increase (total-cost ) 0)
                   )
)

)

