# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Nov 16 14:24:09 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!
from cctextedit import CCastTextEdit

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 668)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtGui.QTabWidget(self.frame_6)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLogs = QtGui.QWidget()
        self.tabLogs.setObjectName("tabLogs")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabLogs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.messageSourceCmbx = QtGui.QComboBox(self.tabLogs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageSourceCmbx.sizePolicy().hasHeightForWidth())
        self.messageSourceCmbx.setSizePolicy(sizePolicy)
        self.messageSourceCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.messageSourceCmbx.setMaxVisibleItems(20)
        self.messageSourceCmbx.setObjectName("messageSourceCmbx")
        self.horizontalLayout_2.addWidget(self.messageSourceCmbx)
        self.componentFilterCmbx = QtGui.QComboBox(self.tabLogs)
        self.componentFilterCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.componentFilterCmbx.setObjectName("componentFilterCmbx")
        self.horizontalLayout_2.addWidget(self.componentFilterCmbx)
        self.btEditFilterComponents = QtGui.QPushButton(self.tabLogs)
        self.btEditFilterComponents.setObjectName("btEditFilterComponents")
        self.horizontalLayout_2.addWidget(self.btEditFilterComponents)
        spacerItem = QtGui.QSpacerItem(88, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btClearMainLog = QtGui.QPushButton(self.tabLogs)
        self.btClearMainLog.setObjectName("btClearMainLog")
        self.horizontalLayout_2.addWidget(self.btClearMainLog)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.ckShowInternalMsgs = QtGui.QCheckBox(self.tabLogs)
        self.ckShowInternalMsgs.setChecked(True)
        self.ckShowInternalMsgs.setObjectName("ckShowInternalMsgs")
        self.horizontalLayout_21.addWidget(self.ckShowInternalMsgs)
        self.ckShowFlushMsgs = QtGui.QCheckBox(self.tabLogs)
        self.ckShowFlushMsgs.setChecked(True)
        self.ckShowFlushMsgs.setObjectName("ckShowFlushMsgs")
        self.horizontalLayout_21.addWidget(self.ckShowFlushMsgs)
        self.ckAutoClearLog = QtGui.QCheckBox(self.tabLogs)
        self.ckAutoClearLog.setObjectName("ckAutoClearLog")
        self.horizontalLayout_21.addWidget(self.ckAutoClearLog)
        spacerItem1 = QtGui.QSpacerItem(88, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.mainLogfileTxt = CCastTextEdit(self.tabLogs)
        self.mainLogfileTxt.setUndoRedoEnabled(False)
        self.mainLogfileTxt.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.mainLogfileTxt.setObjectName("mainLogfileTxt")
        self.verticalLayout.addWidget(self.mainLogfileTxt)
        self.tabWidget.addTab(self.tabLogs, "")
        self.tabBuildLog = QtGui.QWidget()
        self.tabBuildLog.setObjectName("tabBuildLog")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabBuildLog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.buildLogfileTxt = CCastTextEdit(self.tabBuildLog)
        self.buildLogfileTxt.setUndoRedoEnabled(False)
        self.buildLogfileTxt.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.buildLogfileTxt.setObjectName("buildLogfileTxt")
        self.verticalLayout_6.addWidget(self.buildLogfileTxt)
        self.tabWidget.addTab(self.tabBuildLog, "")
        self.tabConfigure = QtGui.QWidget()
        self.tabConfigure.setObjectName("tabConfigure")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabConfigure)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtGui.QFrame(self.tabConfigure)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_4 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_15.addWidget(self.label_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_15.addWidget(self.label_5)
        self.txtLocalHost = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLocalHost.sizePolicy().hasHeightForWidth())
        self.txtLocalHost.setSizePolicy(sizePolicy)
        self.txtLocalHost.setMinimumSize(QtCore.QSize(160, 28))
        self.txtLocalHost.setText("")
        self.txtLocalHost.setMaxLength(128)
        self.txtLocalHost.setObjectName("txtLocalHost")
        self.horizontalLayout_15.addWidget(self.txtLocalHost)
        self.btDetectLocalHost = QtGui.QPushButton(self.frame_4)
        self.btDetectLocalHost.setObjectName("btDetectLocalHost")
        self.horizontalLayout_15.addWidget(self.btDetectLocalHost)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.btDiscoverRemote = QtGui.QPushButton(self.frame_4)
        self.btDiscoverRemote.setObjectName("btDiscoverRemote")
        self.horizontalLayout_15.addWidget(self.btDiscoverRemote)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_16.addWidget(self.label_10)
        self.hostConfigCmbx = QtGui.QComboBox(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostConfigCmbx.sizePolicy().hasHeightForWidth())
        self.hostConfigCmbx.setSizePolicy(sizePolicy)
        self.hostConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.hostConfigCmbx.setObjectName("hostConfigCmbx")
        self.horizontalLayout_16.addWidget(self.hostConfigCmbx)
        self.btBrowseHostFile = QtGui.QPushButton(self.frame_4)
        self.btBrowseHostFile.setObjectName("btBrowseHostFile")
        self.horizontalLayout_16.addWidget(self.btBrowseHostFile)
        self.btEditHostConfig = QtGui.QPushButton(self.frame_4)
        self.btEditHostConfig.setObjectName("btEditHostConfig")
        self.horizontalLayout_16.addWidget(self.btEditHostConfig)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_11 = QtGui.QFrame(self.tabConfigure)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.frame_11)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_3 = QtGui.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_17.addWidget(self.label_3)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtGui.QLabel(self.frame_11)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.clientConfigCmbx = QtGui.QComboBox(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientConfigCmbx.sizePolicy().hasHeightForWidth())
        self.clientConfigCmbx.setSizePolicy(sizePolicy)
        self.clientConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.clientConfigCmbx.setObjectName("clientConfigCmbx")
        self.horizontalLayout_14.addWidget(self.clientConfigCmbx)
        self.btBrowseCastFile = QtGui.QPushButton(self.frame_11)
        self.btBrowseCastFile.setObjectName("btBrowseCastFile")
        self.horizontalLayout_14.addWidget(self.btBrowseCastFile)
        self.btEditClientConfig = QtGui.QPushButton(self.frame_11)
        self.btEditClientConfig.setObjectName("btEditClientConfig")
        self.horizontalLayout_14.addWidget(self.btEditClientConfig)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_2.addWidget(self.frame_11)
        spacerItem4 = QtGui.QSpacerItem(20, 235, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.tabWidget.addTab(self.tabConfigure, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_10 = QtGui.QFrame(self.tab)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_3 = QtGui.QWidget(self.frame_10)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_23.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ckRunPlayer = QtGui.QCheckBox(self.widget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ckRunPlayer.setFont(font)
        self.ckRunPlayer.setChecked(False)
        self.ckRunPlayer.setObjectName("ckRunPlayer")
        self.horizontalLayout_23.addWidget(self.ckRunPlayer)
        spacerItem5 = QtGui.QSpacerItem(473, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem5)
        self.verticalLayout_14.addWidget(self.widget_3)
        self.playerConfigPanel = QtGui.QWidget(self.frame_10)
        self.playerConfigPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.playerConfigPanel.setObjectName("playerConfigPanel")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.playerConfigPanel)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtGui.QLabel(self.playerConfigPanel)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.playerConfigCmbx = QtGui.QComboBox(self.playerConfigPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerConfigCmbx.sizePolicy().hasHeightForWidth())
        self.playerConfigCmbx.setSizePolicy(sizePolicy)
        self.playerConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.playerConfigCmbx.setObjectName("playerConfigCmbx")
        self.horizontalLayout_12.addWidget(self.playerConfigCmbx)
        self.btBrowsePlayerFile = QtGui.QPushButton(self.playerConfigPanel)
        self.btBrowsePlayerFile.setObjectName("btBrowsePlayerFile")
        self.horizontalLayout_12.addWidget(self.btBrowsePlayerFile)
        self.btEditPlayerConfig = QtGui.QPushButton(self.playerConfigPanel)
        self.btEditPlayerConfig.setObjectName("btEditPlayerConfig")
        self.horizontalLayout_12.addWidget(self.btEditPlayerConfig)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout_14.addWidget(self.playerConfigPanel)
        self.verticalLayout_19.addWidget(self.frame_10)
        self.frame_7 = QtGui.QFrame(self.tab)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget = QtGui.QWidget(self.frame_7)
        self.widget.setObjectName("widget")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_20.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ckRunPeekabot = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ckRunPeekabot.setFont(font)
        self.ckRunPeekabot.setChecked(False)
        self.ckRunPeekabot.setObjectName("ckRunPeekabot")
        self.horizontalLayout_20.addWidget(self.ckRunPeekabot)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.verticalLayout_12.addWidget(self.widget)
        self.verticalLayout_19.addWidget(self.frame_7)
        self.frame_8 = QtGui.QFrame(self.tab)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_2 = QtGui.QWidget(self.frame_8)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_22.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.ckRunLog4jServer = QtGui.QCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ckRunLog4jServer.setFont(font)
        self.ckRunLog4jServer.setChecked(False)
        self.ckRunLog4jServer.setObjectName("ckRunLog4jServer")
        self.horizontalLayout_22.addWidget(self.ckRunLog4jServer)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem7)
        self.verticalLayout_13.addWidget(self.widget_2)
        self.log4jConfigPanel = QtGui.QWidget(self.frame_8)
        self.log4jConfigPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.log4jConfigPanel.setObjectName("log4jConfigPanel")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.log4jConfigPanel)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_7 = QtGui.QLabel(self.log4jConfigPanel)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_17.addWidget(self.label_7)
        self.edLo4jServerPort = QtGui.QLineEdit(self.log4jConfigPanel)
        self.edLo4jServerPort.setMinimumSize(QtCore.QSize(0, 0))
        self.edLo4jServerPort.setMaximumSize(QtCore.QSize(120, 16777215))
        self.edLo4jServerPort.setMaxLength(8)
        self.edLo4jServerPort.setObjectName("edLo4jServerPort")
        self.horizontalLayout_17.addWidget(self.edLo4jServerPort)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.label_11 = QtGui.QLabel(self.log4jConfigPanel)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        self.edLog4jOutfile = QtGui.QLineEdit(self.log4jConfigPanel)
        self.edLog4jOutfile.setMaxLength(256)
        self.edLog4jOutfile.setObjectName("edLog4jOutfile")
        self.horizontalLayout_17.addWidget(self.edLog4jOutfile)
        self.btBrowseLog4jOutfile = QtGui.QPushButton(self.log4jConfigPanel)
        self.btBrowseLog4jOutfile.setEnabled(False)
        self.btBrowseLog4jOutfile.setObjectName("btBrowseLog4jOutfile")
        self.horizontalLayout_17.addWidget(self.btBrowseLog4jOutfile)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_12 = QtGui.QLabel(self.log4jConfigPanel)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_19.addWidget(self.label_12)
        self.log4jConsoleLevelCmbx = QtGui.QComboBox(self.log4jConfigPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log4jConsoleLevelCmbx.sizePolicy().hasHeightForWidth())
        self.log4jConsoleLevelCmbx.setSizePolicy(sizePolicy)
        self.log4jConsoleLevelCmbx.setMinimumSize(QtCore.QSize(0, 0))
        self.log4jConsoleLevelCmbx.setObjectName("log4jConsoleLevelCmbx")
        self.horizontalLayout_19.addWidget(self.log4jConsoleLevelCmbx)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.label_16 = QtGui.QLabel(self.log4jConfigPanel)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.log4jFileLevelCmbx = QtGui.QComboBox(self.log4jConfigPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log4jFileLevelCmbx.sizePolicy().hasHeightForWidth())
        self.log4jFileLevelCmbx.setSizePolicy(sizePolicy)
        self.log4jFileLevelCmbx.setObjectName("log4jFileLevelCmbx")
        self.horizontalLayout_19.addWidget(self.log4jFileLevelCmbx)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.verticalLayout_13.addWidget(self.log4jConfigPanel)
        self.verticalLayout_19.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.tab)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_4 = QtGui.QWidget(self.frame_9)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_24.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.ckRunDisplaySrv = QtGui.QCheckBox(self.widget_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ckRunDisplaySrv.setFont(font)
        self.ckRunDisplaySrv.setChecked(False)
        self.ckRunDisplaySrv.setObjectName("ckRunDisplaySrv")
        self.horizontalLayout_24.addWidget(self.ckRunDisplaySrv)
        spacerItem10 = QtGui.QSpacerItem(360, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem10)
        self.verticalLayout_11.addWidget(self.widget_4)
        self.verticalLayout_19.addWidget(self.frame_9)
        self.frame_12 = QtGui.QFrame(self.tab)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frame_12)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_5 = QtGui.QWidget(self.frame_12)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_25.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.ckRunAbducerServer = QtGui.QCheckBox(self.widget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ckRunAbducerServer.setFont(font)
        self.ckRunAbducerServer.setObjectName("ckRunAbducerServer")
        self.horizontalLayout_25.addWidget(self.ckRunAbducerServer)
        spacerItem11 = QtGui.QSpacerItem(420, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem11)
        self.verticalLayout_15.addWidget(self.widget_5)
        self.verticalLayout_19.addWidget(self.frame_12)
        self.frame_13 = QtGui.QFrame(self.tab)
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.frame_13)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_6 = QtGui.QWidget(self.frame_13)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_26.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.ckRunSpeechServer = QtGui.QCheckBox(self.widget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ckRunSpeechServer.setFont(font)
        self.ckRunSpeechServer.setObjectName("ckRunSpeechServer")
        self.horizontalLayout_26.addWidget(self.ckRunSpeechServer)
        spacerItem12 = QtGui.QSpacerItem(420, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem12)
        self.verticalLayout_18.addWidget(self.widget_6)
        self.verticalLayout_19.addWidget(self.frame_13)
        spacerItem13 = QtGui.QSpacerItem(20, 176, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem13)
        self.tabWidget.addTab(self.tab, "")
        self.tabOldInterface = QtGui.QWidget()
        self.tabOldInterface.setEnabled(False)
        self.tabOldInterface.setObjectName("tabOldInterface")
        self.frame_5 = QtGui.QFrame(self.tabOldInterface)
        self.frame_5.setEnabled(False)
        self.frame_5.setGeometry(QtCore.QRect(0, 20, 602, 108))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtGui.QFrame(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btServerStart = QtGui.QPushButton(self.frame)
        self.btServerStart.setObjectName("btServerStart")
        self.horizontalLayout_3.addWidget(self.btServerStart)
        self.btServerStop = QtGui.QPushButton(self.frame)
        self.btServerStop.setObjectName("btServerStop")
        self.horizontalLayout_3.addWidget(self.btServerStop)
        spacerItem14 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.ckCleanupScript = QtGui.QCheckBox(self.frame)
        self.ckCleanupScript.setObjectName("ckCleanupScript")
        self.verticalLayout_3.addWidget(self.ckCleanupScript)
        spacerItem15 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem15)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btClientStart = QtGui.QPushButton(self.frame_2)
        self.btClientStart.setObjectName("btClientStart")
        self.horizontalLayout_4.addWidget(self.btClientStart)
        self.btClientStop = QtGui.QPushButton(self.frame_2)
        self.btClientStop.setObjectName("btClientStop")
        self.horizontalLayout_4.addWidget(self.btClientStop)
        spacerItem16 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem17 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_4.addItem(spacerItem17)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.ckPeekabot = QtGui.QCheckBox(self.frame_3)
        self.ckPeekabot.setChecked(True)
        self.ckPeekabot.setObjectName("ckPeekabot")
        self.horizontalLayout_7.addWidget(self.ckPeekabot)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btPlayerStart = QtGui.QPushButton(self.frame_3)
        self.btPlayerStart.setObjectName("btPlayerStart")
        self.horizontalLayout_8.addWidget(self.btPlayerStart)
        self.btPlayerStop = QtGui.QPushButton(self.frame_3)
        self.btPlayerStop.setObjectName("btPlayerStop")
        self.horizontalLayout_8.addWidget(self.btPlayerStop)
        spacerItem19 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        spacerItem20 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.layoutWidget = QtGui.QWidget(self.tabOldInterface)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 160, 271, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btBuild = QtGui.QPushButton(self.layoutWidget)
        self.btBuild.setObjectName("btBuild")
        self.horizontalLayout_6.addWidget(self.btBuild)
        self.btBuildInstall = QtGui.QPushButton(self.layoutWidget)
        self.btBuildInstall.setObjectName("btBuildInstall")
        self.horizontalLayout_6.addWidget(self.btBuildInstall)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.btCmakeGui = QtGui.QPushButton(self.layoutWidget)
        self.btCmakeGui.setObjectName("btCmakeGui")
        self.horizontalLayout_6.addWidget(self.btCmakeGui)
        self.layoutWidget_2 = QtGui.QWidget(self.tabOldInterface)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 230, 564, 29))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtGui.QLabel(self.layoutWidget_2)
        self.label_13.setEnabled(False)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.playerHostCmbx = QtGui.QComboBox(self.layoutWidget_2)
        self.playerHostCmbx.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerHostCmbx.sizePolicy().hasHeightForWidth())
        self.playerHostCmbx.setSizePolicy(sizePolicy)
        self.playerHostCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.playerHostCmbx.setObjectName("playerHostCmbx")
        self.horizontalLayout_11.addWidget(self.playerHostCmbx)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem22)
        self.layoutWidget_3 = QtGui.QWidget(self.tabOldInterface)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 270, 327, 29))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtGui.QLabel(self.layoutWidget_3)
        self.label_14.setEnabled(False)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.peekabotHostCmbx = QtGui.QComboBox(self.layoutWidget_3)
        self.peekabotHostCmbx.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peekabotHostCmbx.sizePolicy().hasHeightForWidth())
        self.peekabotHostCmbx.setSizePolicy(sizePolicy)
        self.peekabotHostCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.peekabotHostCmbx.setObjectName("peekabotHostCmbx")
        self.horizontalLayout_13.addWidget(self.peekabotHostCmbx)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem23)
        self.layoutWidget_4 = QtGui.QWidget(self.tabOldInterface)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 310, 564, 29))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtGui.QLabel(self.layoutWidget_4)
        self.label_15.setEnabled(False)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.log4jHostCmbx = QtGui.QComboBox(self.layoutWidget_4)
        self.log4jHostCmbx.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log4jHostCmbx.sizePolicy().hasHeightForWidth())
        self.log4jHostCmbx.setSizePolicy(sizePolicy)
        self.log4jHostCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.log4jHostCmbx.setObjectName("log4jHostCmbx")
        self.horizontalLayout_18.addWidget(self.log4jHostCmbx)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem24)
        self.tabWidget.addTab(self.tabOldInterface, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.frame_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 20))
        self.menubar.setObjectName("menubar")
        self.menuCast = QtGui.QMenu(self.menubar)
        self.menuCast.setObjectName("menuCast")
        self.menu_Process = QtGui.QMenu(self.menubar)
        self.menu_Process.setObjectName("menu_Process")
        self.menu_Build = QtGui.QMenu(self.menubar)
        self.menu_Build.setObjectName("menu_Build")
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.processTree = QtGui.QTreeView(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processTree.sizePolicy().hasHeightForWidth())
        self.processTree.setSizePolicy(sizePolicy)
        self.processTree.setMinimumSize(QtCore.QSize(200, 0))
        self.processTree.setMaximumSize(QtCore.QSize(400, 16777215))
        self.processTree.setObjectName("processTree")
        self.verticalLayout_9.addWidget(self.processTree)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.processBar = QtGui.QToolBar(MainWindow)
        self.processBar.setMinimumSize(QtCore.QSize(0, 0))
        self.processBar.setIconSize(QtCore.QSize(24, 24))
        self.processBar.setObjectName("processBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.processBar)
        self.buildBar = QtGui.QToolBar(MainWindow)
        self.buildBar.setMinimumSize(QtCore.QSize(0, 0))
        self.buildBar.setIconSize(QtCore.QSize(24, 24))
        self.buildBar.setObjectName("buildBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.buildBar)
        self.actQuit = QtGui.QAction(MainWindow)
        self.actQuit.setObjectName("actQuit")
        self.actOpenClientConfig = QtGui.QAction(MainWindow)
        self.actOpenClientConfig.setObjectName("actOpenClientConfig")
        self.actOpenPlayerConfig = QtGui.QAction(MainWindow)
        self.actOpenPlayerConfig.setObjectName("actOpenPlayerConfig")
        self.actShowEnv = QtGui.QAction(MainWindow)
        self.actShowEnv.setObjectName("actShowEnv")
        self.actCtxShowBuildError = QtGui.QAction(MainWindow)
        self.actCtxShowBuildError.setObjectName("actCtxShowBuildError")
        self.actStartTerminal = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStartTerminal.setIcon(icon)
        self.actStartTerminal.setObjectName("actStartTerminal")
        self.actOpenHostConfig = QtGui.QAction(MainWindow)
        self.actOpenHostConfig.setObjectName("actOpenHostConfig")
        self.actStartCastServers = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/system-run.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStartCastServers.setIcon(icon1)
        self.actStartCastServers.setObjectName("actStartCastServers")
        self.actStopCastServers = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/system-suspend.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStopCastServers.setIcon(icon2)
        self.actStopCastServers.setObjectName("actStopCastServers")
        self.actStartCastClient = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/cogxStart.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStartCastClient.setIcon(icon3)
        self.actStartCastClient.setObjectName("actStartCastClient")
        self.actStopCastClient = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/cogxStop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStopCastClient.setIcon(icon4)
        self.actStopCastClient.setObjectName("actStopCastClient")
        self.actStartExternalServers = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/go-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStartExternalServers.setIcon(icon5)
        self.actStartExternalServers.setObjectName("actStartExternalServers")
        self.actStopExternalServers = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/res/go-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStopExternalServers.setIcon(icon6)
        self.actStopExternalServers.setObjectName("actStopExternalServers")
        self.actEnableCleanupScript = QtGui.QAction(MainWindow)
        self.actEnableCleanupScript.setCheckable(True)
        self.actEnableCleanupScript.setChecked(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/res/shellscriptOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/res/shellscriptOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actEnableCleanupScript.setIcon(icon7)
        self.actEnableCleanupScript.setObjectName("actEnableCleanupScript")
        self.actRunMake = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/res/svn-update.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actRunMake.setIcon(icon8)
        self.actRunMake.setObjectName("actRunMake")
        self.actRunMakeInstall = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/res/svn-commit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actRunMakeInstall.setIcon(icon9)
        self.actRunMakeInstall.setObjectName("actRunMakeInstall")
        self.actRunMakeClean = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/res/runMakeClean.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actRunMakeClean.setIcon(icon10)
        self.actRunMakeClean.setObjectName("actRunMakeClean")
        self.actConfigureWithCMake = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/res/CMakeSetup128.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actConfigureWithCMake.setIcon(icon11)
        self.actConfigureWithCMake.setObjectName("actConfigureWithCMake")
        self.actEditUserSettings = QtGui.QAction(MainWindow)
        self.actEditUserSettings.setObjectName("actEditUserSettings")
        self.actEditCastEnvironment = QtGui.QAction(MainWindow)
        self.actEditCastEnvironment.setObjectName("actEditCastEnvironment")
        self.menuCast.addAction(self.actShowEnv)
        self.menuCast.addSeparator()
        self.menuCast.addAction(self.actQuit)
        self.menuCast.addAction(self.actStartTerminal)
        self.menu_Process.addAction(self.actStartCastServers)
        self.menu_Process.addAction(self.actStopCastServers)
        self.menu_Process.addAction(self.actStartCastClient)
        self.menu_Process.addAction(self.actStopCastClient)
        self.menu_Process.addAction(self.actStartExternalServers)
        self.menu_Process.addAction(self.actStopExternalServers)
        self.menu_Process.addSeparator()
        self.menu_Process.addAction(self.actEnableCleanupScript)
        self.menu_Build.addAction(self.actRunMake)
        self.menu_Build.addAction(self.actRunMakeInstall)
        self.menu_Build.addAction(self.actConfigureWithCMake)
        self.menu_Build.addSeparator()
        self.menu_Build.addAction(self.actRunMakeClean)
        self.menu_Edit.addAction(self.actEditUserSettings)
        self.menu_Edit.addAction(self.actEditCastEnvironment)
        self.menubar.addAction(self.menuCast.menuAction())
        self.menubar.addAction(self.menu_Process.menuAction())
        self.menubar.addAction(self.menu_Build.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.processBar.addAction(self.actEnableCleanupScript)
        self.processBar.addAction(self.actStartCastServers)
        self.processBar.addAction(self.actStopCastServers)
        self.processBar.addSeparator()
        self.processBar.addAction(self.actStartCastClient)
        self.processBar.addAction(self.actStopCastClient)
        self.processBar.addSeparator()
        self.processBar.addAction(self.actStartExternalServers)
        self.processBar.addAction(self.actStopExternalServers)
        self.processBar.addSeparator()
        self.processBar.addAction(self.actStartTerminal)
        self.buildBar.addAction(self.actConfigureWithCMake)
        self.buildBar.addAction(self.actRunMake)
        self.buildBar.addAction(self.actRunMakeInstall)
        self.buildBar.addSeparator()
        self.buildBar.addAction(self.actRunMakeClean)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.btBrowseCastFile, QtCore.SIGNAL("clicked()"), self.actOpenClientConfig.trigger)
        QtCore.QObject.connect(self.btBrowseHostFile, QtCore.SIGNAL("clicked()"), self.actOpenHostConfig.trigger)
        QtCore.QObject.connect(self.btBrowsePlayerFile, QtCore.SIGNAL("clicked()"), self.actOpenPlayerConfig.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CAST Control", None, QtGui.QApplication.UnicodeUTF8))
        self.messageSourceCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "Active log", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditFilterComponents.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btClearMainLog.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowInternalMsgs.setToolTip(QtGui.QApplication.translate("MainWindow", "Show messages produced by CAST Control", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowInternalMsgs.setText(QtGui.QApplication.translate("MainWindow", "Internal", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowFlushMsgs.setToolTip(QtGui.QApplication.translate("MainWindow", "Flush messages from the message queue after a process has terminated", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowFlushMsgs.setText(QtGui.QApplication.translate("MainWindow", "Flushed", None, QtGui.QApplication.UnicodeUTF8))
        self.ckAutoClearLog.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear the log output when the client process starts", None, QtGui.QApplication.UnicodeUTF8))
        self.ckAutoClearLog.setText(QtGui.QApplication.translate("MainWindow", "AutoClear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLogs), QtGui.QApplication.translate("MainWindow", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBuildLog), QtGui.QApplication.translate("MainWindow", "Build Log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Hosts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "localhost:", None, QtGui.QApplication.UnicodeUTF8))
        self.btDetectLocalHost.setToolTip(QtGui.QApplication.translate("MainWindow", "Detect the address of the local machine.", None, QtGui.QApplication.UnicodeUTF8))
        self.btDetectLocalHost.setText(QtGui.QApplication.translate("MainWindow", "Detect", None, QtGui.QApplication.UnicodeUTF8))
        self.btDiscoverRemote.setToolTip(QtGui.QApplication.translate("MainWindow", "Discover CASTControl Agents on remote machines. See the Logs for results.", None, QtGui.QApplication.UnicodeUTF8))
        self.btDiscoverRemote.setText(QtGui.QApplication.translate("MainWindow", "Discover Agents", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.hostConfigCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "CAST configuration file ", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowseHostFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditHostConfig.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Client", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.clientConfigCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "CAST configuration file ", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowseCastFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditClientConfig.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfigure), QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunPlayer.setToolTip(QtGui.QApplication.translate("MainWindow", "Run Player/Stage with External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunPlayer.setText(QtGui.QApplication.translate("MainWindow", "Run Player", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.playerConfigCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "Player configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowsePlayerFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditPlayerConfig.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunPeekabot.setToolTip(QtGui.QApplication.translate("MainWindow", "Run Peekabot with External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunPeekabot.setText(QtGui.QApplication.translate("MainWindow", "Run Peekabot", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunLog4jServer.setToolTip(QtGui.QApplication.translate("MainWindow", "Run log4j.SimpleSocketServer with External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunLog4jServer.setText(QtGui.QApplication.translate("MainWindow", "Run log4j Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.edLo4jServerPort.setText(QtGui.QApplication.translate("MainWindow", "48143", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.edLog4jOutfile.setText(QtGui.QApplication.translate("MainWindow", "logs/log.xml", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowseLog4jOutfile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Console:", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "Player configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "XML File:", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunDisplaySrv.setText(QtGui.QApplication.translate("MainWindow", "Run Standalone Display Server", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunAbducerServer.setText(QtGui.QApplication.translate("MainWindow", "Run Abducer Server", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunSpeechServer.setText(QtGui.QApplication.translate("MainWindow", "Run Mary TTS Server", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.btServerStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btServerStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.ckCleanupScript.setText(QtGui.QApplication.translate("MainWindow", "Run cleanup script on start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Client", None, QtGui.QApplication.UnicodeUTF8))
        self.btClientStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btClientStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Player", None, QtGui.QApplication.UnicodeUTF8))
        self.ckPeekabot.setText(QtGui.QApplication.translate("MainWindow", "Peekabot", None, QtGui.QApplication.UnicodeUTF8))
        self.btPlayerStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btPlayerStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.btBuild.setText(QtGui.QApplication.translate("MainWindow", "make", None, QtGui.QApplication.UnicodeUTF8))
        self.btBuildInstall.setText(QtGui.QApplication.translate("MainWindow", "make install", None, QtGui.QApplication.UnicodeUTF8))
        self.btCmakeGui.setText(QtGui.QApplication.translate("MainWindow", "Config...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Run on host", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Run on host", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Run on host", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOldInterface), QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCast.setTitle(QtGui.QApplication.translate("MainWindow", "&Cast", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Process.setTitle(QtGui.QApplication.translate("MainWindow", "&Process", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Build.setTitle(QtGui.QApplication.translate("MainWindow", "&Build", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Process tree", None, QtGui.QApplication.UnicodeUTF8))
        self.processBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.buildBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenClientConfig.setText(QtGui.QApplication.translate("MainWindow", "Select Client Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenPlayerConfig.setText(QtGui.QApplication.translate("MainWindow", "Select Player Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actShowEnv.setText(QtGui.QApplication.translate("MainWindow", "Show ENV", None, QtGui.QApplication.UnicodeUTF8))
        self.actCtxShowBuildError.setText(QtGui.QApplication.translate("MainWindow", "Show code", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartTerminal.setText(QtGui.QApplication.translate("MainWindow", "Start Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartTerminal.setToolTip(QtGui.QApplication.translate("MainWindow", "Start Terminal (Configured in castcontrol.conf)", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenHostConfig.setText(QtGui.QApplication.translate("MainWindow", "Select Host Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartCastServers.setText(QtGui.QApplication.translate("MainWindow", "Start CAST Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartCastServers.setShortcut(QtGui.QApplication.translate("MainWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopCastServers.setText(QtGui.QApplication.translate("MainWindow", "Stop CAST Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopCastServers.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartCastClient.setText(QtGui.QApplication.translate("MainWindow", "Start CAST Client", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartCastClient.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopCastClient.setText(QtGui.QApplication.translate("MainWindow", "Stop CAST Client", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopCastClient.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartExternalServers.setText(QtGui.QApplication.translate("MainWindow", "Start External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartExternalServers.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopExternalServers.setText(QtGui.QApplication.translate("MainWindow", "Stop External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopExternalServers.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actEnableCleanupScript.setText(QtGui.QApplication.translate("MainWindow", "Enable Cleanup Script", None, QtGui.QApplication.UnicodeUTF8))
        self.actEnableCleanupScript.setToolTip(QtGui.QApplication.translate("MainWindow", "Enable Cleanup Script (will be executed before CAST servers start)", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMake.setText(QtGui.QApplication.translate("MainWindow", "Make", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMake.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F8", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMakeInstall.setText(QtGui.QApplication.translate("MainWindow", "Make Install", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMakeInstall.setShortcut(QtGui.QApplication.translate("MainWindow", "F8", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMakeClean.setText(QtGui.QApplication.translate("MainWindow", "Make Clean", None, QtGui.QApplication.UnicodeUTF8))
        self.actConfigureWithCMake.setText(QtGui.QApplication.translate("MainWindow", "Configure With CMake", None, QtGui.QApplication.UnicodeUTF8))
        self.actEditUserSettings.setText(QtGui.QApplication.translate("MainWindow", "&User settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actEditCastEnvironment.setText(QtGui.QApplication.translate("MainWindow", "&Cast environment settings", None, QtGui.QApplication.UnicodeUTF8))

import castcontrol_rc
