#!/bin/bash

./ccagent --player=instantiations/player/cogx-platform-sim.cfg  --text2speech --gazebo-world=instantiations/gazebo/george-01.world --build --rsync --golem=dummy --peekabot --abducer --display-server --cleanup-script=svnst.sh
