GARNAME = cogx-distro
GARVERSION =
CATEGORIES = distributions
DISTFILES =
MAINTAINER = ttoenige

DEB_PACKAGES=	libqt4-opengl-dev@ubuntu \
		libqt4-webkit@ubuntu \
		python-qt4@ubuntu \
		libboost-all-dev@ubuntu \
		libqt4-dev@ubuntu \
		libgl1-mesa-dev@ubuntu \
		libglu1-mesa-dev@ubuntu \
		libftgl-dev@ubuntu \
		liblua5.1-0-dev@ubuntu \
		libtolua++5.1-dev@ubuntu \
		libboost-serialization-dev@ubuntu \
		libboost-iostreams-dev@ubuntu \
		libqt4-dev@ubuntu \
		libtolua++5.1-dev@ubuntu \
		libprotobuf-dev@ubuntu \
		python-pygraphviz@ubuntu \
		libglew1.5-dev@ubuntu \
		libdevil-dev@ubuntu \
		nvidia-cg-toolkit@ubuntu \
		cmake-curses-gui@ubuntu \
		libdc1394-22-dev@ubuntu \
		libsdl-dev@ubuntu



LIBDEPS = 	contrib-u11.10/peekabot \
		cogx-u11.10/cast-c++ \
		cogx-u11.10/cast-java \
		contrib-u11.10/opencv \
		contrib/player-3.0.2 \
		contrib/physx_x64 \
		contrib-u11.10/gazebo \
		contrib/openNI \
		contrib/avin2-SensorKinect \
		cogx/golem_katana450_x64

DESCRIPTION = agai-distro

CONFIGURE_SCRIPTS = 
BUILD_SCRIPTS = 
INSTALL_SCRIPTS = 

CONFIGURE_ARGS = 

include ../../gar.extend.mk

checksum-$(DISTFILES):	
	true
