(define (scenario dora-test-world)

  (:domain dora-test-100)

  (:common
   (:objects  rc rb ra - room
              cornflakes fridge mug board-game sink book oven bookshelf table - label
              p2b p3b p1a p1c p5a p6a p3c p3a p4b p2c p1b p2a p4a - place
              bathroom library living_room office kitchen - category
              dora - robot
              obj_book obj_cf obj_shelf obj_mug_a obj_oven obj_table_c obj_fridge obj_mug_b obj_table_b obj_mug_c obj_sink obj_table_a obj_game - visualobject
              human - human
              )

   (:init
    (= (difficulty board-game) medium)
    (= (difficulty book) medium)
    (= (difficulty bookshelf) easy)
    (= (difficulty cornflakes) medium)
    (= (difficulty fridge) easy)
    (= (difficulty mug) hard)
    (= (difficulty oven) easy)
    (= (difficulty sink) medium)
    (= (difficulty table) easy)
    (= (in-room p1a) ra)
    (= (in-room p1b) rb)
    (= (in-room p1c) rc)
    (= (in-room p2a) ra)
    (= (in-room p2b) rb)
    (= (in-room p2c) rc)
    (= (in-room p3a) ra)
    (= (in-room p3b) rb)
    (= (in-room p3c) rc)
    (= (in-room p4a) ra)
    (= (in-room p4b) rb)
    (= (in-room p5a) ra)
    (= (in-room p6a) ra)
    (= (is-in dora) p1a)
    (= (is-in human) p6a)
    (= (label obj_book) book)
    (= (label obj_cf) cornflakes)
    (= (label obj_fridge) fridge)
    (= (label obj_game) board-game)
    (= (label obj_mug_a) mug)
    (= (label obj_mug_b) mug)
    (= (label obj_mug_c) mug)
    (= (label obj_oven) oven)
    (= (label obj_shelf) bookshelf)
    (= (label obj_sink) sink)
    (= (label obj_table_a) table)
    (= (label obj_table_b) table)
    (= (label obj_table_c) table)
    (connected p1a p2a)
    (connected p1a p3a)
    (connected p1b p2b)
    (connected p1c p2c)
    (connected p2a p1b)
    (connected p2a p6a)
    (connected p2b p3b)
    (connected p2c p3c)
    (connected p3a p1c)
    (connected p3a p4a)
    (connected p3b p4b)
    (connected p3c p1c)
    (connected p4a p5a)
    (connected p4b p1b)
    (connected p5a p1a)
    (connected p6a p1a)

    (probabilistic  0.1000  (and  (assign (category rb) bathroom)
                                  (probabilistic  0.3000  (and  (assign (ex-in-room table rb) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_table_b) p2b)
                                                                                0.4000  (assign (is-in obj_table_b) p3b)
                                                                                0.1000  (assign (is-in obj_table_b) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room bookshelf rb) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_shelf) p2b)
                                                                                0.3000  (assign (is-in obj_shelf) p3b)
                                                                                0.2000  (assign (is-in obj_shelf) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.2000  (and  (assign (ex-in-room book rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_book) p2b)
                                                                                0.4000  (assign (is-in obj_book) p3b)
                                                                                0.1000  (assign (is-in obj_book) p1b)
                                                                                0.2000  (assign (is-in obj_book) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room mug rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_mug_b) p2b)
                                                                                0.4000  (assign (is-in obj_mug_b) p3b)
                                                                                0.1000  (assign (is-in obj_mug_b) p1b)
                                                                                0.2000  (assign (is-in obj_mug_b) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9500  (and  (assign (ex-in-room sink rb) true)
                                                                (probabilistic  0.2000  (assign (is-in obj_sink) p2b)
                                                                                0.4000  (assign (is-in obj_sink) p3b)
                                                                                0.4000  (assign (is-in obj_sink) p4b)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.1000  (and  (assign (category rb) living_room)
                                  (probabilistic  0.7000  (and  (assign (ex-in-room table rb) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_table_b) p2b)
                                                                                0.4000  (assign (is-in obj_table_b) p3b)
                                                                                0.1000  (assign (is-in obj_table_b) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.3000  (and  (assign (ex-in-room book rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_book) p2b)
                                                                                0.4000  (assign (is-in obj_book) p3b)
                                                                                0.1000  (assign (is-in obj_book) p1b)
                                                                                0.2000  (assign (is-in obj_book) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.6000  (and  (assign (ex-in-room mug rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_mug_b) p2b)
                                                                                0.4000  (assign (is-in obj_mug_b) p3b)
                                                                                0.1000  (assign (is-in obj_mug_b) p1b)
                                                                                0.2000  (assign (is-in obj_mug_b) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room cornflakes rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_cf) p2b)
                                                                                0.4000  (assign (is-in obj_cf) p3b)
                                                                                0.1000  (assign (is-in obj_cf) p1b)
                                                                                0.2000  (assign (is-in obj_cf) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.6000  (and  (assign (ex-in-room bookshelf rb) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_shelf) p2b)
                                                                                0.3000  (assign (is-in obj_shelf) p3b)
                                                                                0.2000  (assign (is-in obj_shelf) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.7000  (and  (assign (ex-in-room board-game rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_game) p2b)
                                                                                0.4000  (assign (is-in obj_game) p3b)
                                                                                0.1000  (assign (is-in obj_game) p1b)
                                                                                0.2000  (assign (is-in obj_game) p4b)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.2000  (and  (assign (category rb) office)
                                  (probabilistic  0.9000  (and  (assign (ex-in-room table rb) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_table_b) p2b)
                                                                                0.4000  (assign (is-in obj_table_b) p3b)
                                                                                0.1000  (assign (is-in obj_table_b) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room book rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_book) p2b)
                                                                                0.4000  (assign (is-in obj_book) p3b)
                                                                                0.1000  (assign (is-in obj_book) p1b)
                                                                                0.2000  (assign (is-in obj_book) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9000  (and  (assign (ex-in-room mug rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_mug_b) p2b)
                                                                                0.4000  (assign (is-in obj_mug_b) p3b)
                                                                                0.1000  (assign (is-in obj_mug_b) p1b)
                                                                                0.2000  (assign (is-in obj_mug_b) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room fridge rb) true)
                                                                (probabilistic  0.1000  (assign (is-in obj_fridge) p2b)
                                                                                0.7000  (assign (is-in obj_fridge) p3b)
                                                                                0.2000  (assign (is-in obj_fridge) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room sink rb) true)
                                                                (probabilistic  0.2000  (assign (is-in obj_sink) p2b)
                                                                                0.4000  (assign (is-in obj_sink) p3b)
                                                                                0.4000  (assign (is-in obj_sink) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room cornflakes rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_cf) p2b)
                                                                                0.4000  (assign (is-in obj_cf) p3b)
                                                                                0.1000  (assign (is-in obj_cf) p1b)
                                                                                0.2000  (assign (is-in obj_cf) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room bookshelf rb) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_shelf) p2b)
                                                                                0.3000  (assign (is-in obj_shelf) p3b)
                                                                                0.2000  (assign (is-in obj_shelf) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.2000  (and  (assign (ex-in-room board-game rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_game) p2b)
                                                                                0.4000  (assign (is-in obj_game) p3b)
                                                                                0.1000  (assign (is-in obj_game) p1b)
                                                                                0.2000  (assign (is-in obj_game) p4b)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.6000  (and  (assign (category rb) kitchen)
                                  (probabilistic  0.9000  (and  (assign (ex-in-room table rb) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_table_b) p2b)
                                                                                0.4000  (assign (is-in obj_table_b) p3b)
                                                                                0.1000  (assign (is-in obj_table_b) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.2000  (and  (assign (ex-in-room book rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_book) p2b)
                                                                                0.4000  (assign (is-in obj_book) p3b)
                                                                                0.1000  (assign (is-in obj_book) p1b)
                                                                                0.2000  (assign (is-in obj_book) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room mug rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_mug_b) p2b)
                                                                                0.4000  (assign (is-in obj_mug_b) p3b)
                                                                                0.1000  (assign (is-in obj_mug_b) p1b)
                                                                                0.2000  (assign (is-in obj_mug_b) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9000  (and  (assign (ex-in-room fridge rb) true)
                                                                (probabilistic  0.1000  (assign (is-in obj_fridge) p2b)
                                                                                0.7000  (assign (is-in obj_fridge) p3b)
                                                                                0.2000  (assign (is-in obj_fridge) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9500  (and  (assign (ex-in-room sink rb) true)
                                                                (probabilistic  0.2000  (assign (is-in obj_sink) p2b)
                                                                                0.4000  (assign (is-in obj_sink) p3b)
                                                                                0.4000  (assign (is-in obj_sink) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room cornflakes rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_cf) p2b)
                                                                                0.4000  (assign (is-in obj_cf) p3b)
                                                                                0.1000  (assign (is-in obj_cf) p1b)
                                                                                0.2000  (assign (is-in obj_cf) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room oven rb) true)
                                                                (probabilistic  0.1000  (assign (is-in obj_oven) p2b)
                                                                                0.2000  (assign (is-in obj_oven) p3b)
                                                                                0.7000  (assign (is-in obj_oven) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room bookshelf rb) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_shelf) p2b)
                                                                                0.3000  (assign (is-in obj_shelf) p3b)
                                                                                0.2000  (assign (is-in obj_shelf) p4b)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room board-game rb) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_game) p2b)
                                                                                0.4000  (assign (is-in obj_game) p3b)
                                                                                0.1000  (assign (is-in obj_game) p1b)
                                                                                0.2000  (assign (is-in obj_game) p4b)
                                                                                )
                                                                )
                                                  )
                                  )
                    )
    (probabilistic  0.4000  (and  (assign (category rc) bathroom)
                                  (probabilistic  0.0500  (and  (assign (ex-in-room bookshelf rc) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_shelf) p2c)
                                                                                0.5000  (assign (is-in obj_shelf) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.3000  (and  (assign (ex-in-room table rc) true)
                                                                (probabilistic  0.6000  (assign (is-in obj_table_c) p2c)
                                                                                0.4000  (assign (is-in obj_table_c) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room mug rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_mug_c) p2c)
                                                                                0.4000  (assign (is-in obj_mug_c) p3c)
                                                                                0.2000  (assign (is-in obj_mug_c) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.2000  (and  (assign (ex-in-room book rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_book) p2c)
                                                                                0.4000  (assign (is-in obj_book) p3c)
                                                                                0.2000  (assign (is-in obj_book) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9500  (and  (assign (ex-in-room sink rc) true)
                                                                (probabilistic  0.7000  (assign (is-in obj_sink) p2c)
                                                                                0.3000  (assign (is-in obj_sink) p3c)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.1000  (and  (assign (category rc) living_room)
                                  (probabilistic  0.7000  (and  (assign (ex-in-room table rc) true)
                                                                (probabilistic  0.6000  (assign (is-in obj_table_c) p2c)
                                                                                0.4000  (assign (is-in obj_table_c) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.6000  (and  (assign (ex-in-room mug rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_mug_c) p2c)
                                                                                0.4000  (assign (is-in obj_mug_c) p3c)
                                                                                0.2000  (assign (is-in obj_mug_c) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.3000  (and  (assign (ex-in-room book rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_book) p2c)
                                                                                0.4000  (assign (is-in obj_book) p3c)
                                                                                0.2000  (assign (is-in obj_book) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room cornflakes rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_cf) p2c)
                                                                                0.4000  (assign (is-in obj_cf) p3c)
                                                                                0.2000  (assign (is-in obj_cf) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.6000  (and  (assign (ex-in-room bookshelf rc) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_shelf) p2c)
                                                                                0.5000  (assign (is-in obj_shelf) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.7000  (and  (assign (ex-in-room board-game rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_game) p2c)
                                                                                0.4000  (assign (is-in obj_game) p3c)
                                                                                0.2000  (assign (is-in obj_game) p1c)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.3000  (and  (assign (category rc) office)
                                  (probabilistic  0.9000  (and  (assign (ex-in-room table rc) true)
                                                                (probabilistic  0.6000  (assign (is-in obj_table_c) p2c)
                                                                                0.4000  (assign (is-in obj_table_c) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9000  (and  (assign (ex-in-room mug rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_mug_c) p2c)
                                                                                0.4000  (assign (is-in obj_mug_c) p3c)
                                                                                0.2000  (assign (is-in obj_mug_c) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room book rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_book) p2c)
                                                                                0.4000  (assign (is-in obj_book) p3c)
                                                                                0.2000  (assign (is-in obj_book) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room cornflakes rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_cf) p2c)
                                                                                0.4000  (assign (is-in obj_cf) p3c)
                                                                                0.2000  (assign (is-in obj_cf) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room bookshelf rc) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_shelf) p2c)
                                                                                0.5000  (assign (is-in obj_shelf) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.2000  (and  (assign (ex-in-room board-game rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_game) p2c)
                                                                                0.4000  (assign (is-in obj_game) p3c)
                                                                                0.2000  (assign (is-in obj_game) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room fridge rc) true)
                                                                (probabilistic  0.6000  (assign (is-in obj_fridge) p2c)
                                                                                0.4000  (assign (is-in obj_fridge) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room sink rc) true)
                                                                (probabilistic  0.7000  (assign (is-in obj_sink) p2c)
                                                                                0.3000  (assign (is-in obj_sink) p3c)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.2000  (and  (assign (category rc) kitchen)
                                  (probabilistic  0.9000  (and  (assign (ex-in-room table rc) true)
                                                                (probabilistic  0.6000  (assign (is-in obj_table_c) p2c)
                                                                                0.4000  (assign (is-in obj_table_c) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room mug rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_mug_c) p2c)
                                                                                0.4000  (assign (is-in obj_mug_c) p3c)
                                                                                0.2000  (assign (is-in obj_mug_c) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.2000  (and  (assign (ex-in-room book rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_book) p2c)
                                                                                0.4000  (assign (is-in obj_book) p3c)
                                                                                0.2000  (assign (is-in obj_book) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room cornflakes rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_cf) p2c)
                                                                                0.4000  (assign (is-in obj_cf) p3c)
                                                                                0.2000  (assign (is-in obj_cf) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room oven rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_oven) p2c)
                                                                                0.6000  (assign (is-in obj_oven) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room bookshelf rc) true)
                                                                (probabilistic  0.5000  (assign (is-in obj_shelf) p2c)
                                                                                0.5000  (assign (is-in obj_shelf) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room board-game rc) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_game) p2c)
                                                                                0.4000  (assign (is-in obj_game) p3c)
                                                                                0.2000  (assign (is-in obj_game) p1c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9000  (and  (assign (ex-in-room fridge rc) true)
                                                                (probabilistic  0.6000  (assign (is-in obj_fridge) p2c)
                                                                                0.4000  (assign (is-in obj_fridge) p3c)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9500  (and  (assign (ex-in-room sink rc) true)
                                                                (probabilistic  0.7000  (assign (is-in obj_sink) p2c)
                                                                                0.3000  (assign (is-in obj_sink) p3c)
                                                                                )
                                                                )
                                                  )
                                  )
                    )

    (probabilistic  0.2000  (and  (assign (category ra) office)
                                  (probabilistic  0.9000  (and  (assign (ex-in-room mug ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_mug_a) p1a)
                                                                                0.2500  (assign (is-in obj_mug_a) p5a)
                                                                                0.2500  (assign (is-in obj_mug_a) p6a)
                                                                                0.1500  (assign (is-in obj_mug_a) p3a)
                                                                                0.0500  (assign (is-in obj_mug_a) p2a)
                                                                                0.2500  (assign (is-in obj_mug_a) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room book ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_book) p1a)
                                                                                0.2500  (assign (is-in obj_book) p5a)
                                                                                0.2500  (assign (is-in obj_book) p6a)
                                                                                0.1500  (assign (is-in obj_book) p3a)
                                                                                0.0500  (assign (is-in obj_book) p2a)
                                                                                0.2500  (assign (is-in obj_book) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9000  (and  (assign (ex-in-room table ra) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_table_a) p4a)
                                                                                0.3000  (assign (is-in obj_table_a) p6a)
                                                                                0.2000  (assign (is-in obj_table_a) p1a)
                                                                                0.2000  (assign (is-in obj_table_a) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room cornflakes ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_cf) p1a)
                                                                                0.2500  (assign (is-in obj_cf) p5a)
                                                                                0.2500  (assign (is-in obj_cf) p6a)
                                                                                0.1500  (assign (is-in obj_cf) p3a)
                                                                                0.0500  (assign (is-in obj_cf) p2a)
                                                                                0.2500  (assign (is-in obj_cf) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room bookshelf ra) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_shelf) p4a)
                                                                                0.3000  (assign (is-in obj_shelf) p6a)
                                                                                0.4000  (assign (is-in obj_shelf) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room fridge ra) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_fridge) p4a)
                                                                                0.4000  (assign (is-in obj_fridge) p6a)
                                                                                0.2000  (assign (is-in obj_fridge) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room sink ra) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_sink) p4a)
                                                                                0.2000  (assign (is-in obj_sink) p6a)
                                                                                0.4000  (assign (is-in obj_sink) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.2000  (and  (assign (ex-in-room board-game ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_game) p1a)
                                                                                0.2500  (assign (is-in obj_game) p5a)
                                                                                0.2500  (assign (is-in obj_game) p6a)
                                                                                0.1500  (assign (is-in obj_game) p3a)
                                                                                0.0500  (assign (is-in obj_game) p2a)
                                                                                0.2500  (assign (is-in obj_game) p4a)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.6000  (and  (assign (category ra) living_room)
                                  (probabilistic  0.6000  (and  (assign (ex-in-room mug ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_mug_a) p1a)
                                                                                0.2500  (assign (is-in obj_mug_a) p5a)
                                                                                0.2500  (assign (is-in obj_mug_a) p6a)
                                                                                0.1500  (assign (is-in obj_mug_a) p3a)
                                                                                0.0500  (assign (is-in obj_mug_a) p2a)
                                                                                0.2500  (assign (is-in obj_mug_a) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.3000  (and  (assign (ex-in-room book ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_book) p1a)
                                                                                0.2500  (assign (is-in obj_book) p5a)
                                                                                0.2500  (assign (is-in obj_book) p6a)
                                                                                0.1500  (assign (is-in obj_book) p3a)
                                                                                0.0500  (assign (is-in obj_book) p2a)
                                                                                0.2500  (assign (is-in obj_book) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.7000  (and  (assign (ex-in-room table ra) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_table_a) p4a)
                                                                                0.3000  (assign (is-in obj_table_a) p6a)
                                                                                0.2000  (assign (is-in obj_table_a) p1a)
                                                                                0.2000  (assign (is-in obj_table_a) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room cornflakes ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_cf) p1a)
                                                                                0.2500  (assign (is-in obj_cf) p5a)
                                                                                0.2500  (assign (is-in obj_cf) p6a)
                                                                                0.1500  (assign (is-in obj_cf) p3a)
                                                                                0.0500  (assign (is-in obj_cf) p2a)
                                                                                0.2500  (assign (is-in obj_cf) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.6000  (and  (assign (ex-in-room bookshelf ra) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_shelf) p4a)
                                                                                0.3000  (assign (is-in obj_shelf) p6a)
                                                                                0.4000  (assign (is-in obj_shelf) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.7000  (and  (assign (ex-in-room board-game ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_game) p1a)
                                                                                0.2500  (assign (is-in obj_game) p5a)
                                                                                0.2500  (assign (is-in obj_game) p6a)
                                                                                0.1500  (assign (is-in obj_game) p3a)
                                                                                0.0500  (assign (is-in obj_game) p2a)
                                                                                0.2500  (assign (is-in obj_game) p4a)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.1000  (and  (assign (category ra) library)
                                  (probabilistic  0.4000  (and  (assign (ex-in-room mug ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_mug_a) p1a)
                                                                                0.2500  (assign (is-in obj_mug_a) p5a)
                                                                                0.2500  (assign (is-in obj_mug_a) p6a)
                                                                                0.1500  (assign (is-in obj_mug_a) p3a)
                                                                                0.0500  (assign (is-in obj_mug_a) p2a)
                                                                                0.2500  (assign (is-in obj_mug_a) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9900  (and  (assign (ex-in-room book ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_book) p1a)
                                                                                0.2500  (assign (is-in obj_book) p5a)
                                                                                0.2500  (assign (is-in obj_book) p6a)
                                                                                0.1500  (assign (is-in obj_book) p3a)
                                                                                0.0500  (assign (is-in obj_book) p2a)
                                                                                0.2500  (assign (is-in obj_book) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room table ra) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_table_a) p4a)
                                                                                0.3000  (assign (is-in obj_table_a) p6a)
                                                                                0.2000  (assign (is-in obj_table_a) p1a)
                                                                                0.2000  (assign (is-in obj_table_a) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room cornflakes ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_cf) p1a)
                                                                                0.2500  (assign (is-in obj_cf) p5a)
                                                                                0.2500  (assign (is-in obj_cf) p6a)
                                                                                0.1500  (assign (is-in obj_cf) p3a)
                                                                                0.0500  (assign (is-in obj_cf) p2a)
                                                                                0.2500  (assign (is-in obj_cf) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9500  (and  (assign (ex-in-room bookshelf ra) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_shelf) p4a)
                                                                                0.3000  (assign (is-in obj_shelf) p6a)
                                                                                0.4000  (assign (is-in obj_shelf) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room fridge ra) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_fridge) p4a)
                                                                                0.4000  (assign (is-in obj_fridge) p6a)
                                                                                0.2000  (assign (is-in obj_fridge) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room sink ra) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_sink) p4a)
                                                                                0.2000  (assign (is-in obj_sink) p6a)
                                                                                0.4000  (assign (is-in obj_sink) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.1000  (and  (assign (ex-in-room board-game ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_game) p1a)
                                                                                0.2500  (assign (is-in obj_game) p5a)
                                                                                0.2500  (assign (is-in obj_game) p6a)
                                                                                0.1500  (assign (is-in obj_game) p3a)
                                                                                0.0500  (assign (is-in obj_game) p2a)
                                                                                0.2500  (assign (is-in obj_game) p4a)
                                                                                )
                                                                )
                                                  )
                                  )
                    0.1000  (and  (assign (category ra) kitchen)
                                  (probabilistic  0.8000  (and  (assign (ex-in-room mug ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_mug_a) p1a)
                                                                                0.2500  (assign (is-in obj_mug_a) p5a)
                                                                                0.2500  (assign (is-in obj_mug_a) p6a)
                                                                                0.1500  (assign (is-in obj_mug_a) p3a)
                                                                                0.0500  (assign (is-in obj_mug_a) p2a)
                                                                                0.2500  (assign (is-in obj_mug_a) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.2000  (and  (assign (ex-in-room book ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_book) p1a)
                                                                                0.2500  (assign (is-in obj_book) p5a)
                                                                                0.2500  (assign (is-in obj_book) p6a)
                                                                                0.1500  (assign (is-in obj_book) p3a)
                                                                                0.0500  (assign (is-in obj_book) p2a)
                                                                                0.2500  (assign (is-in obj_book) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9000  (and  (assign (ex-in-room table ra) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_table_a) p4a)
                                                                                0.3000  (assign (is-in obj_table_a) p6a)
                                                                                0.2000  (assign (is-in obj_table_a) p1a)
                                                                                0.2000  (assign (is-in obj_table_a) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room oven ra) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_oven) p4a)
                                                                                0.4000  (assign (is-in obj_oven) p6a)
                                                                                0.2000  (assign (is-in obj_oven) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room bookshelf ra) true)
                                                                (probabilistic  0.3000  (assign (is-in obj_shelf) p4a)
                                                                                0.3000  (assign (is-in obj_shelf) p6a)
                                                                                0.4000  (assign (is-in obj_shelf) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9000  (and  (assign (ex-in-room fridge ra) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_fridge) p4a)
                                                                                0.4000  (assign (is-in obj_fridge) p6a)
                                                                                0.2000  (assign (is-in obj_fridge) p5a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.8000  (and  (assign (ex-in-room cornflakes ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_cf) p1a)
                                                                                0.2500  (assign (is-in obj_cf) p5a)
                                                                                0.2500  (assign (is-in obj_cf) p6a)
                                                                                0.1500  (assign (is-in obj_cf) p3a)
                                                                                0.0500  (assign (is-in obj_cf) p2a)
                                                                                0.2500  (assign (is-in obj_cf) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.0500  (and  (assign (ex-in-room board-game ra) true)
                                                                (probabilistic  0.0500  (assign (is-in obj_game) p1a)
                                                                                0.2500  (assign (is-in obj_game) p5a)
                                                                                0.2500  (assign (is-in obj_game) p6a)
                                                                                0.1500  (assign (is-in obj_game) p3a)
                                                                                0.0500  (assign (is-in obj_game) p2a)
                                                                                0.2500  (assign (is-in obj_game) p4a)
                                                                                )
                                                                )
                                                  )
                                  (probabilistic  0.9500  (and  (assign (ex-in-room sink ra) true)
                                                                (probabilistic  0.4000  (assign (is-in obj_sink) p4a)
                                                                                0.2000  (assign (is-in obj_sink) p6a)
                                                                                0.4000  (assign (is-in obj_sink) p5a)
                                                                                )
                                                                )
                                                  )
                                  )
                    )
    )


   )
  (:agent dora
          (:goal  (and (kval dora (is-in obj_cf))
                       (exists (?o - visualobject) (and (= (label ?o) mug) (position-reported ?o)))
                       )
                  )
          )
  )

