package org.cognitivesystems.repr.lf.autogen.LFEssentials;


/**
* org/cognitivesystems/repr/lf/autogen/LFEssentials/Feature.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LFEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Feature implements org.omg.CORBA.portable.IDLEntity
{
  public String feat = null;
  public String value = null;

  public Feature ()
  {
  } // ctor

  public Feature (String _feat, String _value)
  {
    feat = _feat;
    value = _value;
  } // ctor

} // class Feature
