package org.cognitivesystems.repr.lf.autogen.LFEssentials;


/**
* org/cognitivesystems/repr/lf/autogen/LFEssentials/MetaTypeCharacterizationsVectorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LFEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


// end MetaTypeCharacterization
abstract public class MetaTypeCharacterizationsVectorHelper
{
  private static String  _id = "IDL:org/cognitivesystems/repr/lf/autogen/LFEssentials/MetaTypeCharacterizationsVector:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterization[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterization[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterizationHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterizationsVectorHelper.id (), "MetaTypeCharacterizationsVector", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterization[] read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterization value[] = null;
    int _len0 = istream.read_long ();
    value = new org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterization[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterizationHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterization[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      org.cognitivesystems.repr.lf.autogen.LFEssentials.MetaTypeCharacterizationHelper.write (ostream, value[_i0]);
  }

}
