/* Generated By:JavaCC: Do not edit this line. FormulaParserConstants.java */
package de.dfki.lt.tr.dialmanagement.utils.formulaParser;

public interface FormulaParserConstants {

  int EOF = 0;
  int LANGLE = 5;
  int RANGLE = 6;
  int LBRACKET = 7;
  int RBRACKET = 8;
  int NEG = 9;
  int INTEGER = 10;
  int FLOAT = 11;
  int BOOLEAN = 12;
  int KLEENE_STAR = 13;
  int ARGUMENT = 14;
  int INTERROGATION_MARK = 15;
  int SLBRACKET = 16;
  int SRBRACKET = 17;
  int COLON = 18;
  int LAND = 19;
  int LOR = 20;
  int QUOTE = 21;
  int WORD = 22;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "<INTEGER>",
    "<FLOAT>",
    "<BOOLEAN>",
    "\"*\"",
    "<ARGUMENT>",
    "\"?\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"^\"",
    "\"v\"",
    "\"\\\"\"",
    "<WORD>",
  };

}
