#!/bin/sh

SERVER_BIN=abducer-server-mk2
DIR="`pwd`/`dirname $0`/server-mk2"

PATH_TO_BIN="$DIR/$SERVER_BIN"

if [ ! -e "$PATH_TO_BIN" ]; then
	echo "Unable to find the server binary \`$SERVER_BIN' in"
	echo "$DIR"
	echo "--> Is the server compiled?"
	exit 1
fi

ABDUCER_BIN=abducer-lfd

"$PATH_TO_BIN" "$DIR/$ABDUCER_BIN"
