package BindingFeatures;


/**
* BindingFeatures/Group.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingFeatures.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Group implements org.omg.CORBA.portable.IDLEntity
{

  /// if 0, then it means that the group is unbounded in size.
  public int m_size = (int)0;

  /// when individuals are spawned from the group.
  public String m_groupDetailsID = null;
  public BindingFeaturesCommon.ParentFeature m_parent = null;

  public Group ()
  {
  } // ctor

  public Group (int _m_size, String _m_groupDetailsID, BindingFeaturesCommon.ParentFeature _m_parent)
  {
    m_size = _m_size;
    m_groupDetailsID = _m_groupDetailsID;
    m_parent = _m_parent;
  } // ctor

} // class Group
