package BindingFeatures;

/**
* BindingFeatures/SalienceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingFeatures.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class SalienceHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingFeatures.Salience value = null;

  public SalienceHolder ()
  {
  }

  public SalienceHolder (BindingFeatures.Salience initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingFeatures.SalienceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingFeatures.SalienceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingFeatures.SalienceHelper.type ();
  }

}
