package org.cognitivesystems.repr.lf.autogen.LFEssentials;


/**
* org/cognitivesystems/repr/lf/autogen/LFEssentials/EpistemicStatusFeatureHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LFEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/** The struct DynCompStatus provides a data structure for representing dynamic 
	comprehension status of part or all of a logical form. This status reflects the
	"complex truth value" (Kruijff et al,PIT 2006) of the content. The content is
	identified by the referent variable. The complex truth value itself is composed
	of the epistemic status of the content (KNOWN or UNKNOWN) and its update status 
	(TRUE, FALSE, AMB[iguous]). The variable statusSource identifies the source where
	the complex truth value was determined (the "who"), with the variable statusGround
	providing a reference to the ground for the truth value (the "why"). This reference
	is to content in the source. 
	*/
abstract public class EpistemicStatusFeatureHelper
{
  private static String  _id = "IDL:org/cognitivesystems/repr/lf/autogen/LFEssentials/EpistemicStatusFeature:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cognitivesystems.repr.lf.autogen.LFEssentials.EpistemicStatusFeature that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cognitivesystems.repr.lf.autogen.LFEssentials.EpistemicStatusFeature extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (org.cognitivesystems.repr.lf.autogen.LFEssentials.EpistemicStatusFeatureHelper.id (), "EpistemicStatusFeature", new String[] { "EPI_KNOWN", "EPI_UNKNOWN"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cognitivesystems.repr.lf.autogen.LFEssentials.EpistemicStatusFeature read (org.omg.CORBA.portable.InputStream istream)
  {
    return org.cognitivesystems.repr.lf.autogen.LFEssentials.EpistemicStatusFeature.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cognitivesystems.repr.lf.autogen.LFEssentials.EpistemicStatusFeature value)
  {
    ostream.write_long (value.value ());
  }

}
