package org.cognitivesystems.repr.lf.autogen.LFEssentials;


/**
* org/cognitivesystems/repr/lf/autogen/LFEssentials/LFComponent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LFEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class LFComponent implements org.omg.CORBA.portable.IDLEntity
{
  public String componentName = null;
  public org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalForm lf = null;

  public LFComponent ()
  {
  } // ctor

  public LFComponent (String _componentName, org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalForm _lf)
  {
    componentName = _componentName;
    lf = _lf;
  } // ctor

} // class LFComponent
