package org.cognitivesystems.repr.lf.autogen.LFEssentials;


/**
* org/cognitivesystems/repr/lf/autogen/LFEssentials/LFRelation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LFEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class LFRelation implements org.omg.CORBA.portable.IDLEntity
{
  public String head = null;
  public String mode = null;
  public String dep = null;
  public boolean coIndexedDep = false;

  public LFRelation ()
  {
  } // ctor

  public LFRelation (String _head, String _mode, String _dep, boolean _coIndexedDep)
  {
    head = _head;
    mode = _mode;
    dep = _dep;
    coIndexedDep = _coIndexedDep;
  } // ctor

} // class LFRelation
