package org.cognitivesystems.repr.lf.autogen.LFEssentials;


/**
* org/cognitivesystems/repr/lf/autogen/LFEssentials/LogicalFormHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LFEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class LogicalFormHelper
{
  private static String  _id = "IDL:org/cognitivesystems/repr/lf/autogen/LFEssentials/LogicalForm:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalForm that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalForm extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.cognitivesystems.repr.lf.autogen.LFEssentials.IdHelper.id (), "Id", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "logicalFormId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.cognitivesystems.repr.lf.autogen.LFEssentials.LFNominalHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.cognitivesystems.repr.lf.autogen.LFEssentials.NominalsHelper.id (), "Nominals", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "noms",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "preferenceScore",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.cognitivesystems.repr.lf.autogen.LFEssentials.LFNominalHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "root",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "stringPos",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalFormHelper.id (), "LogicalForm", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalForm read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalForm value = new org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalForm ();
    value.logicalFormId = istream.read_string ();
    value.noms = org.cognitivesystems.repr.lf.autogen.LFEssentials.NominalsHelper.read (istream);
    value.preferenceScore = istream.read_float ();
    value.root = org.cognitivesystems.repr.lf.autogen.LFEssentials.LFNominalHelper.read (istream);
    value.stringPos = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalForm value)
  {
    ostream.write_string (value.logicalFormId);
    org.cognitivesystems.repr.lf.autogen.LFEssentials.NominalsHelper.write (ostream, value.noms);
    ostream.write_float (value.preferenceScore);
    org.cognitivesystems.repr.lf.autogen.LFEssentials.LFNominalHelper.write (ostream, value.root);
    ostream.write_long (value.stringPos);
  }

}
