package org.cognitivesystems.repr.lf.autogen.LFEssentials;

/**
* org/cognitivesystems/repr/lf/autogen/LFEssentials/LogicalFormComplexityTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LFEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class LogicalFormComplexityTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalFormComplexityType value = null;

  public LogicalFormComplexityTypeHolder ()
  {
  }

  public LogicalFormComplexityTypeHolder (org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalFormComplexityType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalFormComplexityTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalFormComplexityTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cognitivesystems.repr.lf.autogen.LFEssentials.LogicalFormComplexityTypeHelper.type ();
  }

}
