#include <CAST.idl>

module comedyarch {

  module autogen {
    
    struct Joke {
      string m_setup;
      string m_punchline;
    };
    
    
    typedef sequence < Joke > JokeList;
    
    struct JokeBook {
      string m_title;
      long m_jokeCount;
      JokeList m_jokes;
    };
    
    /**
     * These are the possible things the director can do.
     */
    enum DirectorActionType {
      AskTheAudience, CheckTheReaction
    };
    
    /**
     * This is how they're suggested to the director.
     */
    struct DirectorAction {
      DirectorActionType m_action;
      cast::cdl::WorkingMemoryAddress m_address;
    };
    
  };
  
};
