IF ( "x${V4R_DIR}x" STREQUAL "xx"  )
  SET( V4R_DIR "$ENV{V4R_DIR}" )
    MESSAGE( STATUS " * V4R_DIR is ${V4R_DIR}")
  IF (NOT EXISTS ${V4R_DIR}  )
    MESSAGE( FATAL_ERROR "A Set V4R_DIR in your .profile file with export V4R_DIR=\"$HOME/projects/acin\"")
  ENDIF(NOT EXISTS ${V4R_DIR}  )
ELSE ("x${V4R_DIR}x" STREQUAL "xx" )
    MESSAGE( STATUS " * V4R_DIR is ${V4R_DIR}")
ENDIF("x${V4R_DIR}x" STREQUAL "xx" )

