#
# Unix/Linux Intel ICC Makefile for robust homography estimation
# To be used with "make -f Makefile.icc"
# Under windows, use Makefile.vc for MSVC
#

CC=icc #-w1 # warnings on
CXX=icpc
LEVMAR_PATH=/home/lourakis/levmar-src/levmar-2.4/ # CHANGE THIS TO POINT TO YOUR COMPILED COPY OF LEVMAR
INCLUDES=-I$(LEVMAR_PATH)
CONFIGFLAGS=
ARCHFLAGS=-march=pentium4 -mcpu=pentium4
CFLAGS=$(INCLUDES) $(CONFIGFLAGS) $(ARCHFLAGS) -O3 -tpp7 -xW -ip -ipo -unroll #-g
LAPACKLIBS_PATH=/usr/local/lib # CHANGE THIS TO WHERE YOUR COMPILED LAPACK LIBS ARE!
LDFLAGS=-L. -L$(LEVMAR_PATH) -L$(LAPACKLIBS_PATH)
LIBOBJS=calc_2Dhomog_coeffs.o homest.o lqs.o linalg.o norm.o buckets.o
LIBSRCS=calc_2Dhomog_coeffs.c homest.c lqs.c linalg.c norm.c buckets.c
DEMOBJS=homest_demo.o
DEMOSRCS=homest_demo..c
AR=xiar
#RANLIB=ranlib
LAPACKLIBS=-llapack -lblas -lf2c # comment this line if you are not using LAPACK.
                                 # On systems with a FORTRAN (not f2c'ed) version of LAPACK, -lf2c is
                                 # not necessary; on others, -lf2c is equivalent to -lF77 -lI77

# The following works with the ATLAS updated lapack and Linux_P4SSE2 from http://www.netlib.org/atlas/archives/linux/
#LAPACKLIBS=-L/usr/local/atlas/lib -llapack -lcblas -lf77blas -latlas -lf2c

LIBS=-llevmar $(LAPACKLIBS)

all: libhomest.a homest_demo

libhomest.a: $(LIBOBJS)
	$(AR) crv libhomest.a $(LIBOBJS)
	#$(RANLIB) libhomest.a

calc_2Dhomog_coeffs.o: maplefuncs.h
homest.o: util.h homest.h maplefuncs.h lqs.h
lqs.o: lqs.h compiler.h
linalg.o: compiler.h util.h
norm.o: compiler.h util.h
buckets.o: util.h lqs.h

homest_demo: $(DEMOBJS) libhomest.a
	$(CC) $(ARCHFLAGS) $(LDFLAGS) $(DEMOBJS) -o homest_demo -lhomest $(LIBS) -lm

homest_demo.o: homest.h

clean:
	@rm -f $(LIBOBJS) $(DEMOBJS)

cleanall: clean
	@rm -f libhomest.a

depend:
	makedepend -f Makefile.icc $(LIBSRCS) $(DEMOSRCS)

# DO NOT DELETE THIS LINE -- make depend depends on it.

