package BindingFeaturesCommon;

/**
* BindingFeaturesCommon/TemporalFrameTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingFeaturesCommon.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/// Used in \p TemporalFrame
public final class TemporalFrameTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingFeaturesCommon.TemporalFrameType value = null;

  public TemporalFrameTypeHolder ()
  {
  }

  public TemporalFrameTypeHolder (BindingFeaturesCommon.TemporalFrameType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingFeaturesCommon.TemporalFrameTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingFeaturesCommon.TemporalFrameTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingFeaturesCommon.TemporalFrameTypeHelper.type ();
  }

}
