(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  room_0__t - room
           stapler toiletpaper cerealbox book robot computer - label
           person0 - person
           robot_0__e - robot
           place_2__d place_1__d place_0__d - place
           professorsoffice anteroom bathroom computerlab robotlab singleoffice meetingroom kitchen conferencehall doubleoffice hallway - category
)

(:init  (= (dora__inroom book anteroom) 0.1000)
        (= (dora__inroom book bathroom) 0.1254)
        (= (dora__inroom book computerlab) 0.1000)
        (= (dora__inroom book conferencehall) 0.1000)
        (= (dora__inroom book doubleoffice) 0.4282)
        (= (dora__inroom book hallway) 0.1000)
        (= (dora__inroom book kitchen) 0.1506)
        (= (dora__inroom book meetingroom) 0.1000)
        (= (dora__inroom book professorsoffice) 0.4282)
        (= (dora__inroom book robotlab) 0.1000)
        (= (dora__inroom book singleoffice) 0.4282)
        (= (dora__inroom cerealbox anteroom) 0.1000)
        (= (dora__inroom cerealbox bathroom) 0.1000)
        (= (dora__inroom cerealbox computerlab) 0.1000)
        (= (dora__inroom cerealbox conferencehall) 0.1000)
        (= (dora__inroom cerealbox doubleoffice) 0.1000)
        (= (dora__inroom cerealbox hallway) 0.1000)
        (= (dora__inroom cerealbox kitchen) 0.3360)
        (= (dora__inroom cerealbox meetingroom) 0.1000)
        (= (dora__inroom cerealbox professorsoffice) 0.1000)
        (= (dora__inroom cerealbox robotlab) 0.1000)
        (= (dora__inroom cerealbox singleoffice) 0.1000)
        (= (dora__inroom computer anteroom) 0.1000)
        (= (dora__inroom computer bathroom) 0.1703)
        (= (dora__inroom computer computerlab) 0.2899)
        (= (dora__inroom computer conferencehall) 0.1000)
        (= (dora__inroom computer doubleoffice) 0.8790)
        (= (dora__inroom computer hallway) 0.1000)
        (= (dora__inroom computer kitchen) 0.1000)
        (= (dora__inroom computer meetingroom) 0.1000)
        (= (dora__inroom computer professorsoffice) 0.5790)
        (= (dora__inroom computer robotlab) 0.2899)
        (= (dora__inroom computer singleoffice) 0.5790)
        (= (dora__inroom robot anteroom) 0.1000)
        (= (dora__inroom robot bathroom) 0.1000)
        (= (dora__inroom robot computerlab) 0.1000)
        (= (dora__inroom robot conferencehall) 0.1000)
        (= (dora__inroom robot doubleoffice) 0.1000)
        (= (dora__inroom robot hallway) 0.1000)
        (= (dora__inroom robot kitchen) 0.1000)
        (= (dora__inroom robot meetingroom) 0.1000)
        (= (dora__inroom robot professorsoffice) 0.1000)
        (= (dora__inroom robot robotlab) 0.7000)
        (= (dora__inroom robot singleoffice) 0.1000)
        (= (dora__inroom stapler anteroom) 0.1000)
        (= (dora__inroom stapler bathroom) 0.1000)
        (= (dora__inroom stapler computerlab) 0.1000)
        (= (dora__inroom stapler conferencehall) 0.1000)
        (= (dora__inroom stapler doubleoffice) 0.8038)
        (= (dora__inroom stapler hallway) 0.1000)
        (= (dora__inroom stapler kitchen) 0.2189)
        (= (dora__inroom stapler meetingroom) 0.1000)
        (= (dora__inroom stapler professorsoffice) 0.8038)
        (= (dora__inroom stapler robotlab) 0.1000)
        (= (dora__inroom stapler singleoffice) 0.8038)
        (= (dora__inroom toiletpaper anteroom) 0.1000)
        (= (dora__inroom toiletpaper bathroom) 0.6783)
        (= (dora__inroom toiletpaper computerlab) 0.1000)
        (= (dora__inroom toiletpaper conferencehall) 0.1000)
        (= (dora__inroom toiletpaper doubleoffice) 0.1000)
        (= (dora__inroom toiletpaper hallway) 0.1000)
        (= (dora__inroom toiletpaper kitchen) 0.3818)
        (= (dora__inroom toiletpaper meetingroom) 0.1000)
        (= (dora__inroom toiletpaper professorsoffice) 0.1000)
        (= (dora__inroom toiletpaper robotlab) 0.1000)
        (= (dora__inroom toiletpaper singleoffice) 0.1000)
        (= (in-room place_0__d) room_0__t)
        (= (is-in robot_0__e) place_0__d)
        (= (p-obj_exists book in room_0__t anteroom) 0.1000)
        (= (p-obj_exists book in room_0__t bathroom) 0.1254)
        (= (p-obj_exists book in room_0__t computerlab) 0.1000)
        (= (p-obj_exists book in room_0__t conferencehall) 0.1000)
        (= (p-obj_exists book in room_0__t doubleoffice) 0.4282)
        (= (p-obj_exists book in room_0__t hallway) 0.1000)
        (= (p-obj_exists book in room_0__t kitchen) 0.1506)
        (= (p-obj_exists book in room_0__t meetingroom) 0.1000)
        (= (p-obj_exists book in room_0__t professorsoffice) 0.4282)
        (= (p-obj_exists book in room_0__t robotlab) 0.1000)
        (= (p-obj_exists book in room_0__t singleoffice) 0.4282)
        (= (p-obj_exists cerealbox in room_0__t anteroom) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t bathroom) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t computerlab) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t conferencehall) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t doubleoffice) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t hallway) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t kitchen) 0.3360)
        (= (p-obj_exists cerealbox in room_0__t meetingroom) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t professorsoffice) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t robotlab) 0.1000)
        (= (p-obj_exists cerealbox in room_0__t singleoffice) 0.1000)
        (= (placestatus place_0__d) trueplace)
        (= (placestatus place_1__d) placeholder)
        (= (placestatus place_2__d) placeholder)
        (= (roomid room_0__t) 0)
        (connected place_0__d place_1__d)
        (connected place_0__d place_2__d)
        (probabilistic  0.0748  (assign (leads_to_room place_2__d computerlab) true))
        (probabilistic  0.0748  (assign (leads_to_room place_1__d meetingroom) true))
        (probabilistic  0.0748  (assign (leads_to_room place_2__d kitchen) true))
        (probabilistic  0.9635  (assign (does-exist person0) true))
        (probabilistic  0.4993  (assign (leads_to_room place_2__d hallway) true))
        (probabilistic  0.0748  (assign (leads_to_room place_1__d kitchen) true))
        (probabilistic  0.0748  (assign (leads_to_room place_1__d robotlab) true))
        (probabilistic  0.1161  (assign (leads_to_room place_1__d singleoffice) true))
        (probabilistic  0.0944  (assign (leads_to_room place_2__d bathroom) true))
        (probabilistic  0.9730  (assign (is-in person0) place_0__d))
        (probabilistic  0.0748  (assign (leads_to_room place_2__d robotlab) true))
        (probabilistic  0.1161  (assign (leads_to_room place_1__d doubleoffice) true))
        (probabilistic  0.0909  (assign (category room_0__t) professorsoffice)
                        0.0909  (assign (category room_0__t) conferencehall)
                        0.0909  (assign (category room_0__t) bathroom)
                        0.0909  (assign (category room_0__t) computerlab)
                        0.0909  (assign (category room_0__t) robotlab)
                        0.0909  (assign (category room_0__t) singleoffice)
                        0.0909  (assign (category room_0__t) meetingroom)
                        0.0909  (assign (category room_0__t) kitchen)
                        0.0909  (assign (category room_0__t) anteroom)
                        0.0909  (assign (category room_0__t) doubleoffice)
                        0.0909  (assign (category room_0__t) hallway)
        )
        (probabilistic  0.0944  (assign (leads_to_room place_1__d bathroom) true))
        (probabilistic  0.1715  (assign (leads_to_room place_1__d anteroom) true))
        (probabilistic  0.1161  (assign (leads_to_room place_2__d professorsoffice) true))
        (probabilistic  0.1161  (assign (leads_to_room place_2__d doubleoffice) true))
        (probabilistic  0.0553  (assign (leads_to_room place_1__d conferencehall) true))
        (probabilistic  0.0553  (assign (leads_to_room place_2__d conferencehall) true))
        (probabilistic  0.4993  (assign (leads_to_room place_1__d hallway) true))
        (probabilistic  0.0748  (assign (leads_to_room place_1__d computerlab) true))
        (probabilistic  0.1715  (assign (leads_to_room place_2__d anteroom) true))
        (probabilistic  0.1161  (assign (leads_to_room place_1__d professorsoffice) true))
        (probabilistic  0.0748  (assign (leads_to_room place_2__d meetingroom) true))
        (probabilistic  0.5000  (assign (contains-a-person-prior room_0__t) true))
        (probabilistic  0.1161  (assign (leads_to_room place_2__d singleoffice) true))
)

(:goal  (and  (kval robot_0__e (category room_0__t))))

)
