(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  robot_0_7 - robot
           room_0__r - room
           table stapler marker whiteboardmarker paperclip cerealbox bookcase book mug - label
           place_0_6 place_1_6 place_2_6 place_3_6 place_4_6 - place
           corridor office kitchen meetingroom - category
)

(:init  (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom bookcase) 50.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom marker) 200.0000)
        (= (dora__cost_inroom mug) 200.0000)
        (= (dora__cost_inroom paperclip) 200.0000)
        (= (dora__cost_inroom stapler) 200.0000)
        (= (dora__cost_inroom table) 50.0000)
        (= (dora__inroom book corridor) 0.0100)
        (= (dora__inroom book kitchen) 0.0100)
        (= (dora__inroom book meetingroom) 0.0100)
        (= (dora__inroom book office) 0.9900)
        (= (dora__inroom bookcase corridor) 0.0100)
        (= (dora__inroom bookcase kitchen) 0.0100)
        (= (dora__inroom bookcase meetingroom) 0.0100)
        (= (dora__inroom bookcase office) 0.9900)
        (= (dora__inroom cerealbox corridor) 0)
        (= (dora__inroom cerealbox kitchen) 0.9900)
        (= (dora__inroom cerealbox meetingroom) 0.0100)
        (= (dora__inroom cerealbox office) 0.0100)
        (= (dora__inroom mug corridor) 0.0100)
        (= (dora__inroom mug kitchen) 0.0100)
        (= (dora__inroom mug meetingroom) 0.0100)
        (= (dora__inroom mug office) 0.9900)
        (= (dora__inroom paperclip corridor) 0.0100)
        (= (dora__inroom paperclip kitchen) 0)
        (= (dora__inroom paperclip meetingroom) 0.0100)
        (= (dora__inroom paperclip office) 0.9900)
        (= (dora__inroom stapler corridor) 0.0100)
        (= (dora__inroom stapler kitchen) 0.0100)
        (= (dora__inroom stapler meetingroom) 0.0100)
        (= (dora__inroom stapler office) 0.9900)
        (= (dora__inroom table corridor) 0.0100)
        (= (dora__inroom table kitchen) 0.1000)
        (= (dora__inroom table meetingroom) 0.1000)
        (= (dora__inroom table office) 0.1000)
        (= (dora__inroom whiteboardmarker corridor) 0.0100)
        (= (dora__inroom whiteboardmarker kitchen) 0.0100)
        (= (dora__inroom whiteboardmarker meetingroom) 0.9900)
        (= (dora__inroom whiteboardmarker office) 0.0100)
        (= (in-room place_0_6) room_0__r)
        (= (in-room place_1_6) room_0__r)
        (= (in-room place_2_6) room_0__r)
        (= (in-room place_3_6) room_0__r)
        (= (in-room place_4_6) room_0__r)
        (= (is-in robot_0_7) place_4_6)
        (= (p-obj_exists book in room_0__r) 0.0307)
        (= (p-obj_exists cerealbox in room_0__r) 0.0213)
        (= (placestatus place_0_6) trueplace)
        (= (placestatus place_1_6) trueplace)
        (= (placestatus place_2_6) trueplace)
        (= (placestatus place_3_6) trueplace)
        (= (placestatus place_4_6) trueplace)
        (= (roomid room_0__r) 0)
        (connected place_0_6 place_1_6)
        (connected place_1_6 place_0_6)
        (connected place_1_6 place_2_6)
        (connected place_2_6 place_1_6)
        (connected place_2_6 place_3_6)
        (connected place_3_6 place_2_6)
        (connected place_3_6 place_4_6)
        (connected place_4_6 place_3_6)
        (probabilistic  0.0211  (assign (category room_0__r) office)
                        0.9366  (assign (category room_0__r) corridor)
                        0.0211  (assign (category room_0__r) kitchen)
                        0.0211  (assign (category room_0__r) meetingroom)
        )
        (probabilistic  0.5000  (assign (contains-a-person-prior room_0__r) true))
)

(:goal  (and  ;;(exists (?o - visualobject)  (kval robot_0_7 (related-to ?o)))
                (exists (?p - person)  (kval robot_0_7 (is-in ?p)))
              (and  )
        )
)

)
