package org.cognitivesystems.common.autogen.VisualAttributes;

/**
* org/cognitivesystems/common/autogen/VisualAttributes/ShapeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VisualAttributes.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/**
   * Shape enumeration.
   */
public final class ShapeHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cognitivesystems.common.autogen.VisualAttributes.Shape value = null;

  public ShapeHolder ()
  {
  }

  public ShapeHolder (org.cognitivesystems.common.autogen.VisualAttributes.Shape initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cognitivesystems.common.autogen.VisualAttributes.ShapeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cognitivesystems.common.autogen.VisualAttributes.ShapeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cognitivesystems.common.autogen.VisualAttributes.ShapeHelper.type ();
  }

}
