package NavData;


/**
* NavData/AEdgeSequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NavData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class AEdgeSequenceHelper
{
  private static String  _id = "IDL:NavData/AEdgeSequence:1.0";

  public static void insert (org.omg.CORBA.Any a, NavData.AEdge[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NavData.AEdge[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = NavData.AEdgeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (NavData.AEdgeSequenceHelper.id (), "AEdgeSequence", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NavData.AEdge[] read (org.omg.CORBA.portable.InputStream istream)
  {
    NavData.AEdge value[] = null;
    int _len0 = istream.read_long ();
    value = new NavData.AEdge[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = NavData.AEdgeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NavData.AEdge[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      NavData.AEdgeHelper.write (ostream, value[_i0]);
  }

}
