package NavData;


/**
* NavData/CommandHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NavData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


//
abstract public class CommandHelper
{
  private static String  _id = "IDL:NavData/Command:1.0";

  public static void insert (org.omg.CORBA.Any a, NavData.Command that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NavData.Command extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (NavData.CommandHelper.id (), "Command", new String[] { "GOTO_OBJECT", "GOTO_PLACE", "COME_FORWARD", "GO_BACK", "PERSON_FOLLOW", "TURN", "TURN_TO", "EXPLORE", "STOP", "BLOCK_CONTROL"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NavData.Command read (org.omg.CORBA.portable.InputStream istream)
  {
    return NavData.Command.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NavData.Command value)
  {
    ostream.write_long (value.value ());
  }

}
