package NavData;

/**
* NavData/GoalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NavData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class GoalHolder implements org.omg.CORBA.portable.Streamable
{
  public NavData.Goal value = null;

  public GoalHolder ()
  {
  }

  public GoalHolder (NavData.Goal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NavData.GoalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NavData.GoalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NavData.GoalHelper.type ();
  }

}
