package NavData;


/**
* NavData/Indication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NavData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Indication implements org.omg.CORBA.portable.IDLEntity
{
  public String m_object = null;

  public Indication ()
  {
  } // ctor

  public Indication (String _m_object)
  {
    m_object = _m_object;
  } // ctor

} // class Indication
