package NavData;


/**
* NavData/PersonHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NavData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class PersonHelper
{
  private static String  _id = "IDL:NavData/Person:1.0";

  public static void insert (org.omg.CORBA.Any a, NavData.Person that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NavData.Person extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [8];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = balt.corba.autogen.FrameworkBasics.BALTTimeHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_time",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "m_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "m_x",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[3] = new org.omg.CORBA.StructMember (
            "m_y",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[4] = new org.omg.CORBA.StructMember (
            "m_theta",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[5] = new org.omg.CORBA.StructMember (
            "m_speed",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[6] = new org.omg.CORBA.StructMember (
            "m_visibility",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[7] = new org.omg.CORBA.StructMember (
            "m_areaID",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (NavData.PersonHelper.id (), "Person", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NavData.Person read (org.omg.CORBA.portable.InputStream istream)
  {
    NavData.Person value = new NavData.Person ();
    value.m_time = balt.corba.autogen.FrameworkBasics.BALTTimeHelper.read (istream);
    value.m_id = istream.read_long ();
    value.m_x = istream.read_double ();
    value.m_y = istream.read_double ();
    value.m_theta = istream.read_double ();
    value.m_speed = istream.read_double ();
    value.m_visibility = istream.read_double ();
    value.m_areaID = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NavData.Person value)
  {
    balt.corba.autogen.FrameworkBasics.BALTTimeHelper.write (ostream, value.m_time);
    ostream.write_long (value.m_id);
    ostream.write_double (value.m_x);
    ostream.write_double (value.m_y);
    ostream.write_double (value.m_theta);
    ostream.write_double (value.m_speed);
    ostream.write_double (value.m_visibility);
    ostream.write_long (value.m_areaID);
  }

}
