package TestingData;


/**
* TestingData/TestingCommand.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class TestingCommand implements org.omg.CORBA.portable.IDLEntity
{

  /// Status
  public TestingData.TestingCommandStatus m_status = null;

  /// up to the individual subarchitectures' different testing components
  public String m_command = null;

  public TestingCommand ()
  {
  } // ctor

  public TestingCommand (TestingData.TestingCommandStatus _m_status, String _m_command)
  {
    m_status = _m_status;
    m_command = _m_command;
  } // ctor

} // class TestingCommand
