#!/bin/bash

dot_file=$1
base_fn=${dot_file%.*}
path=`dirname $0`

DEFAULT_EXTENSION="ps"
if [ -n "$2" ]
then
  extension=$2
else  
  extension=$DEFAULT_EXTENSION 
fi  

outfile="$base_fn.$extension"
# produce graph
echo "dot $dot_file -T$extension -o $outfile"
dot $dot_file -T$extension -o $outfile
