#!/bin/bash
# usage: ./this_script dotfile.dot
# generates dotfile.pdf

dot_file=$1
base_fn=${dot_file%.*}
path=`dirname $0`

psext="ps"
"$path/gen_graph" $dot_file $psext
ps_fn="$base_fn.$psext"
pdf_fn="$base_fn.pdf"
echo "ps2eps -l -B -q -f < $ps_fn | epstopdf -f > $pdf_fn"
ps2eps -l -B -q -f < $ps_fn | epstopdf -f > $pdf_fn
