(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  room_0__r - room
           robot_0_7 - robot
           mug paperclip bookcase cerealbox book marker table stapler whiteboardmarker - label
           place_0_6 - place
           corridor office kitchen meetingroom - category
)

(:init  (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom bookcase) 50.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom marker) 200.0000)
        (= (dora__cost_inroom mug) 200.0000)
        (= (dora__cost_inroom paperclip) 200.0000)
        (= (dora__cost_inroom stapler) 200.0000)
        (= (dora__cost_inroom table) 50.0000)
        (= (dora__inroom book corridor) 0.0100)
        (= (dora__inroom book kitchen) 0.0100)
        (= (dora__inroom book meetingroom) 0.0100)
        (= (dora__inroom book office) 0.9900)
        (= (dora__inroom bookcase corridor) 0.0100)
        (= (dora__inroom bookcase kitchen) 0.0100)
        (= (dora__inroom bookcase meetingroom) 0.0100)
        (= (dora__inroom bookcase office) 0.9900)
        (= (dora__inroom cerealbox corridor) 0.0000)
        (= (dora__inroom cerealbox kitchen) 0.9900)
        (= (dora__inroom cerealbox meetingroom) 0.0100)
        (= (dora__inroom cerealbox office) 0.0100)
        (= (dora__inroom mug corridor) 0.0100)
        (= (dora__inroom mug kitchen) 0.0100)
        (= (dora__inroom mug meetingroom) 0.0100)
        (= (dora__inroom mug office) 0.9900)
        (= (dora__inroom paperclip corridor) 0.0100)
        (= (dora__inroom paperclip kitchen) 0.0000)
        (= (dora__inroom paperclip meetingroom) 0.0100)
        (= (dora__inroom paperclip office) 0.9900)
        (= (dora__inroom stapler corridor) 0.0100)
        (= (dora__inroom stapler kitchen) 0.0100)
        (= (dora__inroom stapler meetingroom) 0.0100)
        (= (dora__inroom stapler office) 0.9900)
        (= (dora__inroom table corridor) 0.0100)
        (= (dora__inroom table kitchen) 0.1000)
        (= (dora__inroom table meetingroom) 0.1000)
        (= (dora__inroom table office) 0.1000)
        (= (dora__inroom whiteboardmarker corridor) 0.0100)
        (= (dora__inroom whiteboardmarker kitchen) 0.0100)
        (= (dora__inroom whiteboardmarker meetingroom) 0.9900)
        (= (dora__inroom whiteboardmarker office) 0.0100)
        (= (in-room place_0_6) room_0__r)
        (= (is-in robot_0_7) place_0_6)
        (= (p-obj_exists book in room_0__r) 0.1991)
        (= (p-obj_exists cerealbox in room_0__r) 0.1949)
        (= (placestatus place_0_6) trueplace)
        (= (roomid room_0__r) 0.0000)
        (probabilistic  0.1929  (assign (category room_0__r) office)
                        0.4212  (assign (category room_0__r) corridor)
                        0.1929  (assign (category room_0__r) kitchen)
                        0.1929  (assign (category room_0__r) meetingroom)
        )
        (probabilistic  0.5000  (assign (contains-a-person-prior room_0__r) true))
)

(:goal  (and  (kval robot_0_7 (category room_0__r))))

)
