package BindingData;

/**
* BindingData/BindTheseProxiesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class BindTheseProxiesHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingData.BindTheseProxies value = null;

  public BindTheseProxiesHolder ()
  {
  }

  public BindTheseProxiesHolder (BindingData.BindTheseProxies initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingData.BindTheseProxiesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingData.BindTheseProxiesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingData.BindTheseProxiesHelper.type ();
  }

}
