package BindingData;

/**
* BindingData/ComparisonTrustHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/// comparator
public final class ComparisonTrustHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingData.ComparisonTrust value = null;

  public ComparisonTrustHolder ()
  {
  }

  public ComparisonTrustHolder (BindingData.ComparisonTrust initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingData.ComparisonTrustHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingData.ComparisonTrustHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingData.ComparisonTrustHelper.type ();
  }

}
