package BindingData;

/**
* BindingData/FeatureComparisonTaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class FeatureComparisonTaskHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingData.FeatureComparisonTask value = null;

  public FeatureComparisonTaskHolder ()
  {
  }

  public FeatureComparisonTaskHolder (BindingData.FeatureComparisonTask initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingData.FeatureComparisonTaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingData.FeatureComparisonTaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingData.FeatureComparisonTaskHelper.type ();
  }

}
