(define (domain dora-avs-iros11)

(:requirements :quantified-preconditions :equality :typing :negative-preconditions :conditional-effects :action-costs :adl :disjunctive-preconditions)

(:types  node - object
         spatial_relation - object
         place_status - object
         agent - object
         movable - object
         boolean - object
         human - movable
         conegroup - object
         subgoal - object
         planning_agent - agent
         node_choice - object
         category - object
         visualobject - either_visualobject_room
         room - either_visualobject_room
         either_visualobject_room - object
         feature - object
         label - object
         place - object
         robot - movable
         robot - agent
         
)

(:constants  room_0__t - room
             in on - spatial_relation
             place__f__f place__g__f - place
             office corridor kitchen meetingroom - category
             placeholder trueplace - place_status
             true false - boolean
)

(:predicates  (leads_to_room ?p - place ?c - category ?value - boolean)
              (in-domain-virtual-category ?r - room ?v - category)
              (kd-in-room ?a - agent ?p - place)
              (i_in-domain-virtual-category ?r - room ?v - category)
              (poss-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (committed-is-in ?o - human)
              (committed-is-in ?o - robot)
              (relation ?o - visualobject ?value - spatial_relation)
              (kval-placestatus ?a - agent ?n - place)
              (attributed-is-in ?a - agent ?o - robot ?v - place)
              (attributed-is-in ?a - agent ?o - human ?v - place)
              (update-cg-relation ?c - conegroup ?v - spatial_relation)
              (in-domain-label ?o - visualobject ?v - label)
              (poss-selected ?n - node ?v - node_choice)
              (committed-cg-label ?c - conegroup)
              (poss-cg-relation ?c - conegroup ?v - spatial_relation)
              (in-domain-related-to ?o - visualobject ?v - either_visualobject_room)
              (kval-related-to ?a - agent ?o - visualobject)
              (neg-attributed-related-to ?a - agent ?o - visualobject ?v - either_visualobject_room)
              (kval-selected ?a - agent ?n - node)
              (in-domain-cg-related-to ?c - conegroup ?v - either_visualobject_room)
              (committed-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (update-in-room ?p - place ?v - room)
              (in-domain-placestatus ?n - place ?v - place_status)
              (defined-dora__cost_inroom ?l - label)
              (neg-attributed-selected ?a - agent ?n - node ?v - node_choice)
              (started )
              (committed-cg-place ?c - conegroup)
              (observed-virtual-category ?r - room ?v - category)
              (observed-cg-related-to ?c - conegroup ?v - either_visualobject_room)
              (obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?value - boolean)
              (in-domain-relation ?o - visualobject ?v - spatial_relation)
              (i_in-domain-relation ?o - visualobject ?v - spatial_relation)
              (i_in-domain-cg-label ?c - conegroup ?v - label)
              (defined-p-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (in-domain-is-in ?o - robot ?v - place)
              (in-domain-is-in ?o - human ?v - place)
              (defined-dora__inroom ?l - label ?c - category)
              (i_in-domain-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (kd-related-to ?a - agent ?o - visualobject)
              (kval-cg-related-to ?a - agent ?c - conegroup)
              (attributed-placestatus ?a - agent ?n - place ?v - place_status)
              (update-cg-place ?c - conegroup ?v - place)
              (committed-label ?o - visualobject)
              (in-domain-leads_to_room ?p - place ?c - category ?v - boolean)
              (in-domain-cg-label ?c - conegroup ?v - label)
              (i_in-domain-placestatus ?n - place ?v - place_status)
              (attributed-obj_exists ?a - agent ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (kd-label ?a - agent ?o - visualobject)
              (poss-placestatus ?n - place ?v - place_status)
              (poss-label ?o - visualobject ?v - label)
              (kval-is-in ?a - agent ?o - human)
              (kval-is-in ?a - agent ?o - robot)
              (update-failed-in-room ?p - place ?v - room)
              (defined-total-p-cost )
              (kval-cg-place ?a - agent ?c - conegroup)
              (done )
              (attributed-cg-place ?a - agent ?c - conegroup ?v - place)
              (in-domain-cg-relation ?c - conegroup ?v - spatial_relation)
              (cones_created ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (committed-cg-relation ?c - conegroup)
              (update-failed-selected ?n - node ?v - node_choice)
              (is-virtual ?o - object)
              (kd-visible_from ?a - agent ?o - visualobject)
              (update-is-in ?o - robot ?v - place)
              (update-is-in ?o - human ?v - place)
              (attributed-cg-related-to ?a - agent ?c - conegroup ?v - either_visualobject_room)
              (virtual-category ?r - room ?value - category)
              (observed-cg-label ?c - conegroup ?v - label)
              (committed-in-room ?p - place)
              (attributed-selected ?a - agent ?n - node ?v - node_choice)
              (update-category ?r - room ?v - category)
              (observed-cg-relation ?c - conegroup ?v - spatial_relation)
              (category ?r - room ?value - category)
              (committed-leads_to_room ?p - place ?c - category)
              (kd-is-in ?a - agent ?o - human)
              (kd-is-in ?a - agent ?o - robot)
              (observed-label ?o - visualobject ?v - label)
              (observed-relation ?o - visualobject ?v - spatial_relation)
              (neg-attributed-placestatus ?a - agent ?n - place ?v - place_status)
              (related-to ?o - visualobject ?value - either_visualobject_room)
              (observed-is-in ?o - robot ?v - place)
              (observed-is-in ?o - human ?v - place)
              (selected ?n - node ?value - node_choice)
              (update-visible_from ?o - visualobject ?v - conegroup)
              (label ?o - visualobject ?value - label)
              (defined-search_cost ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (attributed-relation ?a - agent ?o - visualobject ?v - spatial_relation)
              (neg-attributed-cg-place ?a - agent ?c - conegroup ?v - place)
              (committed-visible_from ?o - visualobject)
              (defined-dora__cost_on ?l1 - label ?l2 - label)
              (neg-attributed-leads_to_room ?a - agent ?p - place ?c - category ?v - boolean)
              (observed-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (kd-cg-relation ?a - agent ?c - conegroup)
              (visible_from ?o - visualobject ?value - conegroup)
              (committed-virtual-category ?r - room)
              (update-leads_to_room ?p - place ?c - category ?v - boolean)
              (i_in-domain-leads_to_room ?p - place ?c - category ?v - boolean)
              (poss-related-to ?o - visualobject ?v - either_visualobject_room)
              (observed-selected ?n - node ?v - node_choice)
              (poss-in-room ?p - place ?v - room)
              (kval-in-room ?a - agent ?p - place)
              (attributed-cg-relation ?a - agent ?c - conegroup ?v - spatial_relation)
              (poss-relation ?o - visualobject ?v - spatial_relation)
              (i_in-domain-label ?o - visualobject ?v - label)
              (poss-cg-place ?c - conegroup ?v - place)
              (observed-placestatus ?n - place ?v - place_status)
              (update-related-to ?o - visualobject ?v - either_visualobject_room)
              (position-reported ?o - visualobject)
              (attached_to_room ?p - place ?r - room)
              (update-placestatus ?n - place ?v - place_status)
              (neg-attributed-relation ?a - agent ?o - visualobject ?v - spatial_relation)
              (neg-attributed-label ?a - agent ?o - visualobject ?v - label)
              (in-domain-cg-place ?c - conegroup ?v - place)
              (i_in-domain-related-to ?o - visualobject ?v - either_visualobject_room)
              (observed-in-room ?p - place ?v - room)
              (cg-label ?c - conegroup ?value - label)
              (kval-obj_exists ?a - agent ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (update-failed-is-in ?o - robot ?v - place)
              (update-failed-is-in ?o - human ?v - place)
              (kval-leads_to_room ?a - agent ?p - place ?c - category)
              (attributed-visible_from ?a - agent ?o - visualobject ?v - conegroup)
              (trans_related ?o - visualobject ?where - either_visualobject_room)
              (committed-selected ?n - node)
              (kval-label ?a - agent ?o - visualobject)
              (kd-relation ?a - agent ?o - visualobject)
              (poss-visible_from ?o - visualobject ?v - conegroup)
              (defined-roomid ?r - room)
              (i_in-domain-cg-relation ?c - conegroup ?v - spatial_relation)
              (committed-category ?r - room)
              (neg-attributed-cg-relation ?a - agent ?c - conegroup ?v - spatial_relation)
              (neg-attributed-is-in ?a - agent ?o - robot ?v - place)
              (neg-attributed-is-in ?a - agent ?o - human ?v - place)
              (poss-leads_to_room ?p - place ?c - category ?v - boolean)
              (kval-visible_from ?a - agent ?o - visualobject)
              (poss-category ?r - room ?v - category)
              (i_in-domain-visible_from ?o - visualobject ?v - conegroup)
              (not_fully_explored ?r - object)
              (is-in ?o - robot ?value - place)
              (is-in ?o - human ?value - place)
              (defined-dora__cost_inobject ?l1 - label ?l2 - label)
              (update-cg-label ?c - conegroup ?v - label)
              (update-failed-label ?o - visualobject ?v - label)
              (update-failed-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (neg-attributed-obj_exists ?a - agent ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (update-virtual-category ?r - room ?v - category)
              (attributed-label ?a - agent ?o - visualobject ?v - label)
              (update-label ?o - visualobject ?v - label)
              (attributed-related-to ?a - agent ?o - visualobject ?v - either_visualobject_room)
              (defined-probability )
              (cg-relation ?c - conegroup ?value - spatial_relation)
              (attributed-cg-label ?a - agent ?c - conegroup ?v - label)
              (attributed-category ?a - agent ?r - room ?v - category)
              (kval-virtual-category ?a - agent ?r - room)
              (poss-is-in ?o - robot ?v - place)
              (poss-is-in ?o - human ?v - place)
              (update-failed-leads_to_room ?p - place ?c - category ?v - boolean)
              (update-failed-placestatus ?n - place ?v - place_status)
              (update-failed-relation ?o - visualobject ?v - spatial_relation)
              (i_in-domain-in-room ?p - place ?v - room)
              (committed-cg-related-to ?c - conegroup)
              (observed-visible_from ?o - visualobject ?v - conegroup)
              (update-failed-related-to ?o - visualobject ?v - either_visualobject_room)
              (kd-virtual-category ?a - agent ?r - room)
              (update-failed-cg-relation ?c - conegroup ?v - spatial_relation)
              (neg-attributed-category ?a - agent ?r - room ?v - category)
              (kd-cg-place ?a - agent ?c - conegroup)
              (attributed-virtual-category ?a - agent ?r - room ?v - category)
              (observed-related-to ?o - visualobject ?v - either_visualobject_room)
              (in-domain-visible_from ?o - visualobject ?v - conegroup)
              (poss-virtual-category ?r - room ?v - category)
              (kd-cg-related-to ?a - agent ?c - conegroup)
              (neg-attributed-cg-label ?a - agent ?c - conegroup ?v - label)
              (observed-leads_to_room ?p - place ?c - category ?v - boolean)
              (poss-cg-label ?c - conegroup ?v - label)
              (update-cg-related-to ?c - conegroup ?v - either_visualobject_room)
              (cones_exist ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (neg-attributed-virtual-category ?a - agent ?r - room ?v - category)
              (neg-attributed-visible_from ?a - agent ?o - visualobject ?v - conegroup)
              (i_in-domain-is-in ?o - human ?v - place)
              (i_in-domain-is-in ?o - robot ?v - place)
              (observed-cg-place ?c - conegroup ?v - place)
              (committed-relation ?o - visualobject)
              (i_in-domain-cg-related-to ?c - conegroup ?v - either_visualobject_room)
              (cg-related-to ?c - conegroup ?value - either_visualobject_room)
              (kval-category ?a - agent ?r - room)
              (in-domain-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (neg-attributed-cg-related-to ?a - agent ?c - conegroup ?v - either_visualobject_room)
              (kd-placestatus ?a - agent ?n - place)
              (placestatus ?n - place ?value - place_status)
              (update-failed-visible_from ?o - visualobject ?v - conegroup)
              (update-failed-cg-related-to ?c - conegroup ?v - either_visualobject_room)
              (in-domain-category ?r - room ?v - category)
              (not-instantiated ?o - object)
              (defined-dora__inobject ?l1 - label ?l2 - label ?c - category)
              (update-failed-category ?r - room ?v - category)
              (kval-cg-label ?a - agent ?c - conegroup)
              (cg-place ?c - conegroup ?value - place)
              (update-failed-cg-label ?c - conegroup ?v - label)
              (defined-dora__on ?l1 - label ?l2 - label ?c - category)
              (kval-cg-relation ?a - agent ?c - conegroup)
              (attributed-leads_to_room ?a - agent ?p - place ?c - category ?v - boolean)
              (i_in-domain-selected ?n - node ?v - node_choice)
              (is-visited ?c - conegroup)
              (unused ?o - object)
              (in-domain-in-room ?p - place ?v - room)
              (connected ?p1 - place ?p2 - place)
              (observed-category ?r - room ?v - category)
              (kd-cg-label ?a - agent ?c - conegroup)
              (update-failed-cg-place ?c - conegroup ?v - place)
              (update-selected ?n - node ?v - node_choice)
              (kd-obj_exists ?a - agent ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
              (kd-category ?a - agent ?r - room)
              (i_in-domain-category ?r - room ?v - category)
              (defined-p-visible ?c - conegroup)
              (committed-related-to ?o - visualobject)
              (i_in-domain-cg-place ?c - conegroup ?v - place)
              (kd-leads_to_room ?a - agent ?p - place ?c - category)
              (in-domain-selected ?n - node ?v - node_choice)
              (kval-relation ?a - agent ?o - visualobject)
              (neg-attributed-in-room ?a - agent ?p - place ?v - room)
              (attributed-in-room ?a - agent ?p - place ?v - room)
              (update-failed-virtual-category ?r - room ?v - category)
              (committed-placestatus ?n - place)
              (in-room ?p - place ?value - room)
              (update-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?v - boolean)
              (poss-cg-related-to ?c - conegroup ?v - either_visualobject_room)
              (kd-selected ?a - agent ?n - node)
              (update-relation ?o - visualobject ?v - spatial_relation)
)

(:functions  (probability ) - number
             (total-p-cost ) - number
             (dora__inobject ?l1 - label ?l2 - label ?c - category) - number
             (dora__on ?l1 - label ?l2 - label ?c - category) - number
             (search_cost ?l - label ?rel - spatial_relation ?where - either_visualobject_room) - number
             (p-visible ?c - conegroup) - number
             (dora__cost_inroom ?l - label) - number
             (dora__inroom ?l - label ?c - category) - number
             (p-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room) - number
             (roomid ?r - room) - number
             (dora__cost_on ?l1 - label ?l2 - label) - number
             (dora__cost_inobject ?l1 - label ?l2 - label) - number
)

(:derived  (attached_to_room ?p - place ?r - room)
           (and  (exists (?p2 - place)  (and  (in-room ?p2 ?r)
                                              (connected ?p2 ?p)
                                        )
                 )
           )
)

(:derived  (not_fully_explored ?r - room)
           (and  (exists (?p - place)  (and  (not (placestatus ?p trueplace))
                                             (attached_to_room ?p ?r)
                                       )
                 )
           )
)

(:derived  (trans_related ?o - visualobject ?where - either_visualobject_room)
           (and  (or  (poss-related-to ?o ?where)
                      (exists (?o2 - visualobject)  (and  (poss-related-to ?o ?o2)
                                                          (trans_related ?o2 ?where)
                                                    )
                      )
                 )
           )
)

(:derived  (cones_exist ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
           (and  (exists (?c - conegroup)  (and  (cg-label ?c ?l)
                                                 (cg-related-to ?c ?where)
                                                 (cg-relation ?c ?rel)
                                           )
                 )
           )
)

(:derived  (kval-selected ?a - agent ?n - node)
           (and  (or  (kd-selected ?a ?n)
                      (exists (?val - node_choice)  (selected ?n ?val))
                 )
           )
)

(:derived  (kval-leads_to_room ?a - agent ?p - place ?c - category)
           (and  (or  (kd-leads_to_room ?a ?p ?c)
                      (exists (?val - boolean)  (leads_to_room ?p ?c ?val))
                 )
           )
)

(:derived  (kval-virtual-category ?a - agent ?r - room)
           (and  (or  (kd-virtual-category ?a ?r)
                      (exists (?val - category)  (virtual-category ?r ?val))
                 )
           )
)

(:derived  (kval-relation ?a - agent ?o - visualobject)
           (and  (or  (kd-relation ?a ?o)
                      (exists (?val - spatial_relation)  (relation ?o ?val))
                 )
           )
)

(:derived  (kval-cg-label ?a - agent ?c - conegroup)
           (and  (or  (kd-cg-label ?a ?c)
                      (exists (?val - label)  (cg-label ?c ?val))
                 )
           )
)

(:derived  (kval-category ?a - agent ?r - room)
           (and  (or  (kd-category ?a ?r)
                      (exists (?val - category)  (category ?r ?val))
                 )
           )
)

(:derived  (kval-cg-related-to ?a - agent ?c - conegroup)
           (and  (or  (kd-cg-related-to ?a ?c)
                      (exists (?val - either_visualobject_room)  (cg-related-to ?c ?val))
                 )
           )
)

(:derived  (kval-related-to ?a - agent ?o - visualobject)
           (and  (or  (kd-related-to ?a ?o)
                      (exists (?val - either_visualobject_room)  (related-to ?o ?val))
                 )
           )
)

(:derived  (kval-placestatus ?a - agent ?n - place)
           (and  (or  (kd-placestatus ?a ?n)
                      (exists (?val - place_status)  (placestatus ?n ?val))
                 )
           )
)

(:derived  (kval-label ?a - agent ?o - visualobject)
           (and  (or  (kd-label ?a ?o)
                      (exists (?val - label)  (label ?o ?val))
                 )
           )
)

(:derived  (kval-cg-place ?a - agent ?c - conegroup)
           (and  (or  (kd-cg-place ?a ?c)
                      (exists (?val - place)  (cg-place ?c ?val))
                 )
           )
)

(:derived  (kval-visible_from ?a - agent ?o - visualobject)
           (and  (or  (kd-visible_from ?a ?o)
                      (exists (?val - conegroup)  (visible_from ?o ?val))
                 )
           )
)

(:derived  (kval-obj_exists ?a - agent ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
           (and  (or  (kd-obj_exists ?a ?l ?rel ?where)
                      (exists (?val - boolean)  (obj_exists ?l ?rel ?where ?val))
                 )
           )
)

(:derived  (kval-is-in ?a - agent ?o - human)
           (and  (or  (kd-is-in ?a ?o)
                      (exists (?val - place)  (is-in ?o ?val))
                 )
           )
)

(:derived  (kval-is-in ?a - agent ?o - robot)
           (and  (or  (kd-is-in ?a ?o)
                      (exists (?val - place)  (is-in ?o ?val))
                 )
           )
)

(:derived  (kval-cg-relation ?a - agent ?c - conegroup)
           (and  (or  (kd-cg-relation ?a ?c)
                      (exists (?val - spatial_relation)  (cg-relation ?c ?val))
                 )
           )
)

(:derived  (kval-in-room ?a - agent ?p - place)
           (and  (or  (kd-in-room ?a ?p)
                      (exists (?val - room)  (in-room ?p ?val))
                 )
           )
)

(:derived  (in-domain-selected ?n - node ?val - node_choice)
           (and  (or  (selected ?n ?val)
                      (and  (i_in-domain-selected ?n ?val)
                            (forall (?val2 - node_choice)  (not (selected ?n ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-leads_to_room ?p - place ?c - category ?val - boolean)
           (and  (or  (leads_to_room ?p ?c ?val)
                      (and  (i_in-domain-leads_to_room ?p ?c ?val)
                            (forall (?val2 - boolean)  (not (leads_to_room ?p ?c ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-virtual-category ?r - room ?val - category)
           (and  (or  (virtual-category ?r ?val)
                      (and  (i_in-domain-virtual-category ?r ?val)
                            (forall (?val2 - category)  (not (virtual-category ?r ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-relation ?o - visualobject ?val - spatial_relation)
           (and  (or  (relation ?o ?val)
                      (and  (i_in-domain-relation ?o ?val)
                            (forall (?val2 - spatial_relation)  (not (relation ?o ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-cg-label ?c - conegroup ?val - label)
           (and  (or  (cg-label ?c ?val)
                      (and  (i_in-domain-cg-label ?c ?val)
                            (forall (?val2 - label)  (not (cg-label ?c ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-category ?r - room ?val - category)
           (and  (or  (category ?r ?val)
                      (and  (i_in-domain-category ?r ?val)
                            (forall (?val2 - category)  (not (category ?r ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-cg-related-to ?c - conegroup ?val - either_visualobject_room)
           (and  (or  (cg-related-to ?c ?val)
                      (and  (i_in-domain-cg-related-to ?c ?val)
                            (forall (?val2 - either_visualobject_room)  (not (cg-related-to ?c ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-related-to ?o - visualobject ?val - either_visualobject_room)
           (and  (or  (related-to ?o ?val)
                      (and  (i_in-domain-related-to ?o ?val)
                            (forall (?val2 - either_visualobject_room)  (not (related-to ?o ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-placestatus ?n - place ?val - place_status)
           (and  (or  (placestatus ?n ?val)
                      (and  (i_in-domain-placestatus ?n ?val)
                            (forall (?val2 - place_status)  (not (placestatus ?n ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-label ?o - visualobject ?val - label)
           (and  (or  (label ?o ?val)
                      (and  (i_in-domain-label ?o ?val)
                            (forall (?val2 - label)  (not (label ?o ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-cg-place ?c - conegroup ?val - place)
           (and  (or  (cg-place ?c ?val)
                      (and  (i_in-domain-cg-place ?c ?val)
                            (forall (?val2 - place)  (not (cg-place ?c ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-visible_from ?o - visualobject ?val - conegroup)
           (and  (or  (visible_from ?o ?val)
                      (and  (i_in-domain-visible_from ?o ?val)
                            (forall (?val2 - conegroup)  (not (visible_from ?o ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room ?val - boolean)
           (and  (or  (obj_exists ?l ?rel ?where ?val)
                      (and  (i_in-domain-obj_exists ?l ?rel ?where ?val)
                            (forall (?val2 - boolean)  (not (obj_exists ?l ?rel ?where ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-is-in ?o - human ?val - place)
           (and  (or  (is-in ?o ?val)
                      (and  (i_in-domain-is-in ?o ?val)
                            (forall (?val2 - place)  (not (is-in ?o ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-is-in ?o - robot ?val - place)
           (and  (or  (is-in ?o ?val)
                      (and  (i_in-domain-is-in ?o ?val)
                            (forall (?val2 - place)  (not (is-in ?o ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-cg-relation ?c - conegroup ?val - spatial_relation)
           (and  (or  (cg-relation ?c ?val)
                      (and  (i_in-domain-cg-relation ?c ?val)
                            (forall (?val2 - spatial_relation)  (not (cg-relation ?c ?val2)))
                      )
                 )
           )
)

(:derived  (in-domain-in-room ?p - place ?val - room)
           (and  (or  (in-room ?p ?val)
                      (and  (i_in-domain-in-room ?p ?val)
                            (forall (?val2 - room)  (not (in-room ?p ?val2)))
                      )
                 )
           )
)

(:derived  (committed-selected ?n - node)
           (and  (exists (?val - node_choice)  (or  (selected ?n ?val)
                                                    (poss-selected ?n ?val)
                                               )
                 )
           )
)

(:derived  (committed-leads_to_room ?p - place ?c - category)
           (and  (exists (?val - boolean)  (or  (leads_to_room ?p ?c ?val)
                                                (poss-leads_to_room ?p ?c ?val)
                                           )
                 )
           )
)

(:derived  (committed-virtual-category ?r - room)
           (and  (exists (?val - category)  (or  (virtual-category ?r ?val)
                                                 (poss-virtual-category ?r ?val)
                                            )
                 )
           )
)

(:derived  (committed-relation ?o - visualobject)
           (and  (exists (?val - spatial_relation)  (or  (relation ?o ?val)
                                                         (poss-relation ?o ?val)
                                                    )
                 )
           )
)

(:derived  (committed-cg-label ?c - conegroup)
           (and  (exists (?val - label)  (or  (cg-label ?c ?val)
                                              (poss-cg-label ?c ?val)
                                         )
                 )
           )
)

(:derived  (committed-category ?r - room)
           (and  (exists (?val - category)  (or  (category ?r ?val)
                                                 (poss-category ?r ?val)
                                            )
                 )
           )
)

(:derived  (committed-cg-related-to ?c - conegroup)
           (and  (exists (?val - either_visualobject_room)  (or  (cg-related-to ?c ?val)
                                                                 (poss-cg-related-to ?c ?val)
                                                            )
                 )
           )
)

(:derived  (committed-related-to ?o - visualobject)
           (and  (exists (?val - either_visualobject_room)  (or  (related-to ?o ?val)
                                                                 (poss-related-to ?o ?val)
                                                            )
                 )
           )
)

(:derived  (committed-placestatus ?n - place)
           (and  (exists (?val - place_status)  (or  (placestatus ?n ?val)
                                                     (poss-placestatus ?n ?val)
                                                )
                 )
           )
)

(:derived  (committed-label ?o - visualobject)
           (and  (exists (?val - label)  (or  (label ?o ?val)
                                              (poss-label ?o ?val)
                                         )
                 )
           )
)

(:derived  (committed-cg-place ?c - conegroup)
           (and  (exists (?val - place)  (or  (cg-place ?c ?val)
                                              (poss-cg-place ?c ?val)
                                         )
                 )
           )
)

(:derived  (committed-visible_from ?o - visualobject)
           (and  (exists (?val - conegroup)  (or  (visible_from ?o ?val)
                                                  (poss-visible_from ?o ?val)
                                             )
                 )
           )
)

(:derived  (committed-obj_exists ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
           (and  (exists (?val - boolean)  (or  (obj_exists ?l ?rel ?where ?val)
                                                (poss-obj_exists ?l ?rel ?where ?val)
                                           )
                 )
           )
)

(:derived  (committed-is-in ?o - human)
           (and  (exists (?val - place)  (or  (is-in ?o ?val)
                                              (poss-is-in ?o ?val)
                                         )
                 )
           )
)

(:derived  (committed-is-in ?o - robot)
           (and  (exists (?val - place)  (or  (is-in ?o ?val)
                                              (poss-is-in ?o ?val)
                                         )
                 )
           )
)

(:derived  (committed-cg-relation ?c - conegroup)
           (and  (exists (?val - spatial_relation)  (or  (cg-relation ?c ?val)
                                                         (poss-cg-relation ?c ?val)
                                                    )
                 )
           )
)

(:derived  (committed-in-room ?p - place)
           (and  (exists (?val - room)  (or  (in-room ?p ?val)
                                             (poss-in-room ?p ?val)
                                        )
                 )
           )
)

(:action  report_position
          :parameters  (?a - robot ?o - visualobject ?p - place)
          :precondition  (and  (kval-related-to ?a ?o)
                               (is-in ?a ?p)
                         )
          :effect  (and  (position-reported ?o)
                         (increase (total-cost ) 1.0000)
                         (started )
                   )
)

(:action  move
          :parameters  (?a - robot ?to - place ?from - place)
          :precondition  (and  (or  (connected ?from ?to)
                                    (connected ?to ?from)
                               )
                               (not (done ))
                               (is-in ?a ?from)
                         )
          :effect  (and  (not (is-in ?a ?from))
                         (is-in ?a ?to)
                         (placestatus ?to trueplace)
                         (kd-in-room ?a ?to)
                         (increase (total-cost ) 2.0000)
                         (started )
                   )
)

(:action  move_direct
          :parameters  (?a - robot ?to - place ?from - place ?via - place)
          :precondition  (and  (or  (connected ?from ?via)
                                    (connected ?via ?from)
                               )
                               (or  (connected ?via ?to)
                                    (connected ?to ?via)
                               )
                               (not (done ))
                               (is-in ?a ?from)
                         )
          :effect  (and  (not (is-in ?a ?from))
                         (is-in ?a ?to)
                         (placestatus ?to trueplace)
                         (kd-in-room ?a ?to)
                         (increase (total-cost ) 3.0000)
                         (started )
                   )
)

(:action  create_cones_in_room
          :parameters  (?a - robot ?l - label ?r - room ?p - place)
          :precondition  (and  (is-in ?a ?p)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                               (poss-obj_exists ?l in ?r true)
                               (not (not_fully_explored ?r))
                               (not (done ))
                         )
          :effect  (and  (cones_created ?l in ?r)
                         (increase (total-cost ) 1.0000)
                         (started )
                   )
)

(:action  create_cones_at_object
          :parameters  (?a - robot ?l - label ?lsupp - label ?rel - spatial_relation ?o - visualobject ?r - room ?p - place)
          :precondition  (and  (is-in ?a ?p)
                               (label ?o ?lsupp)
                               (poss-obj_exists ?l ?rel ?o true)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                               (poss-related-to ?o ?r)
                               (kval-related-to ?a ?o)
                               (not (done ))
                         )
          :effect  (and  (cones_created ?l ?rel ?o)
                         (increase (total-cost ) 1.0000)
                         (started )
                   )
)

(:action  search_for_object_in_room
          :parameters  (?a - robot ?l - label ?r - room ?p - place ?o - visualobject)
          :precondition  (and  (is-in ?a ?p)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                               (label ?o ?l)
                               (or  (cones_created ?l in ?r)
                                    (cones_exist ?l in ?r)
                               )
                               (poss-related-to ?o ?r)
                               (poss-relation ?o in)
                               (not (done ))
                         )
          :effect  (and  (increase (total-cost ) (search_cost ?l in ?r))
                         (started )
                         (kd-related-to ?a ?o)
                   )
)

(:action  search_for_object_at_object
          :parameters  (?a - robot ?l - label ?o - visualobject ?rel - spatial_relation ?p - place ?r - room ?o2 - visualobject)
          :precondition  (and  (is-in ?a ?p)
                               (poss-in-room ?p ?r)
                               (kval-in-room ?a ?p)
                               (poss-related-to ?o ?r)
                               (kval-related-to ?a ?o)
                               (label ?o2 ?l)
                               (or  (cones_created ?l ?rel ?o)
                                    (cones_exist ?l ?rel ?o)
                               )
                               (poss-related-to ?o2 ?o)
                               (poss-relation ?o2 ?rel)
                               (not (done ))
                         )
          :effect  (and  (increase (total-cost ) (search_cost ?l ?rel ?o))
                         (started )
                         (kd-related-to ?a ?o2)
                   )
)

(:action  process_conegroup
          :parameters  (?a - robot ?c - conegroup ?p - place ?o - visualobject)
          :precondition  (and  (not (done ))
                               (cg-place ?c ?p)
                               (is-in ?a ?p)
                         )
          :effect  (and  (increase (total-cost ) 15.0000)
                         (started )
                         (when  (poss-visible_from ?o ?c)
                                (kd-visible_from ?a ?o)
                         )
                   )
)

(:action  __commit-obj_in_room-0
          :parameters  (?a - agent ?l - label ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-category ?r ?c)
                               (defined-dora__inroom ?l ?c)
                               (not (defined-p-obj_exists ?l in ?r))
                               (not (committed-obj_exists ?l in ?r))
                         )
          :effect  (and  (poss-obj_exists ?l in ?r true)
                         (assign (probability ) (dora__inroom ?l ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-obj_in_obj-0
          :parameters  (?a - agent ?l1 - label ?l2 - label ?o - visualobject ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-category ?r ?c)
                               (label ?o ?l2)
                               (poss-related-to ?o ?r)
                               (poss-relation ?o in)
                               (defined-dora__inobject ?l1 ?l2 ?c)
                               (not (defined-p-obj_exists ?l1 in ?o))
                               (not (committed-obj_exists ?l1 in ?o))
                         )
          :effect  (and  (poss-obj_exists ?l1 in ?o true)
                         (assign (probability ) (dora__inobject ?l1 ?l2 ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-obj_on_obj-0
          :parameters  (?a - agent ?l1 - label ?l2 - label ?o - visualobject ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-category ?r ?c)
                               (label ?o ?l2)
                               (poss-related-to ?o ?r)
                               (poss-relation ?o in)
                               (defined-dora__on ?l1 ?l2 ?c)
                               (not (defined-p-obj_exists ?l1 on ?o))
                               (not (committed-obj_exists ?l1 on ?o))
                         )
          :effect  (and  (poss-obj_exists ?l1 on ?o true)
                         (assign (probability ) (dora__on ?l1 ?l2 ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-object_existence_room-0
          :parameters  (?a - agent ?l - label ?rel - spatial_relation ?where - room ?c - category)
          :precondition  (and  (not (started ))
                               (poss-category ?where ?c)
                               (defined-p-obj_exists ?l ?rel ?where)
                               (not (committed-obj_exists ?l ?rel ?where))
                         )
          :effect  (and  (poss-obj_exists ?l ?rel ?where true)
                         (assign (probability ) (p-obj_exists ?l ?rel ?where))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-object_existence_object-0
          :parameters  (?a - agent ?l - label ?rel - spatial_relation ?where - visualobject)
          :precondition  (and  (not (started ))
                               (defined-p-obj_exists ?l ?rel ?where)
                               (not (committed-obj_exists ?l ?rel ?where))
                         )
          :effect  (and  (poss-obj_exists ?l ?rel ?where true)
                         (assign (probability ) (p-obj_exists ?l ?rel ?where))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-sample_object_location-0
          :parameters  (?a - agent ?o - visualobject ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
          :precondition  (and  (not (started ))
                               (label ?o ?l)
                               (is-virtual ?o)
                               (poss-obj_exists ?l ?rel ?where true)
                               (not (committed-related-to ?o))
                               (not (committed-relation ?o))
                         )
          :effect  (and  (poss-related-to ?o ?where)
                         (poss-relation ?o ?rel)
                         (assign (probability ) 1.0000)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-sample_cone_visibility-0
          :parameters  (?a - agent ?o - visualobject ?c - conegroup ?l - label ?rel - spatial_relation ?where - either_visualobject_room)
          :precondition  (and  (not (started ))
                               (cg-relation ?c ?rel)
                               (cg-related-to ?c ?where)
                               (poss-relation ?o ?rel)
                               (poss-related-to ?o ?where)
                               (cg-label ?c ?l)
                               (label ?o ?l)
                               (not (is-visited ?c))
                               (not (committed-visible_from ?o))
                         )
          :effect  (and  (poss-visible_from ?o ?c)
                         (assign (probability ) (p-visible ?c))
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-room_from_placeholder-0
          :parameters  (?a - agent ?p - place ?r - room ?c - category)
          :precondition  (and  (not (started ))
                               (placestatus ?p placeholder)
                               (virtual-category ?r ?c)
                               (poss-leads_to_room ?p ?c true)
                               (is-virtual ?r)
                               (not (committed-in-room ?p))
                               (not (committed-category ?r))
                         )
          :effect  (and  (poss-in-room ?p ?r)
                         (poss-category ?r ?c)
                         (assign (probability ) 1.0000)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__g__f-corridor-true
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__g__f corridor))
                         )
          :effect  (and  (poss-leads_to_room place__g__f corridor true)
                         (poss-leads_to_room place__g__f corridor true)
                         (assign (probability ) 0.7875)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__f__f-corridor-true
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__f__f corridor))
                         )
          :effect  (and  (poss-leads_to_room place__f__f corridor true)
                         (poss-leads_to_room place__f__f corridor true)
                         (assign (probability ) 0.7875)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__f__f-kitchen-true
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__f__f kitchen))
                         )
          :effect  (and  (poss-leads_to_room place__f__f kitchen true)
                         (poss-leads_to_room place__f__f kitchen true)
                         (assign (probability ) 0.2009)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__g__f-meetingroom-true
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__g__f meetingroom))
                         )
          :effect  (and  (poss-leads_to_room place__g__f meetingroom true)
                         (poss-leads_to_room place__g__f meetingroom true)
                         (assign (probability ) 0.2009)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__g__f-office-true
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__g__f office))
                         )
          :effect  (and  (poss-leads_to_room place__g__f office true)
                         (poss-leads_to_room place__g__f office true)
                         (assign (probability ) 0.2340)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__f__f-office-true
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__f__f office))
                         )
          :effect  (and  (poss-leads_to_room place__f__f office true)
                         (poss-leads_to_room place__f__f office true)
                         (assign (probability ) 0.2340)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-category-room_0__t-corridor
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-category room_0__t))
                         )
          :effect  (and  (poss-category room_0__t corridor)
                         (poss-category room_0__t corridor)
                         (assign (probability ) 0.0658)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-category-room_0__t-office
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-category room_0__t))
                         )
          :effect  (and  (poss-category room_0__t office)
                         (poss-category room_0__t office)
                         (assign (probability ) 0.2607)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-category-room_0__t-kitchen
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-category room_0__t))
                         )
          :effect  (and  (poss-category room_0__t kitchen)
                         (poss-category room_0__t kitchen)
                         (assign (probability ) 0.4127)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-category-room_0__t-meetingroom
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-category room_0__t))
                         )
          :effect  (and  (poss-category room_0__t meetingroom)
                         (poss-category room_0__t meetingroom)
                         (assign (probability ) 0.2607)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__f__f-meetingroom-true
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__f__f meetingroom))
                         )
          :effect  (and  (poss-leads_to_room place__f__f meetingroom true)
                         (poss-leads_to_room place__f__f meetingroom true)
                         (assign (probability ) 0.2009)
                         (increase (total-cost ) 0)
                   )
)

(:action  __commit-leads_to_room-place__g__f-kitchen-true
          :parameters  (?a - agent)
          :precondition  (and  (not (started ))
                               (not (committed-leads_to_room place__g__f kitchen))
                         )
          :effect  (and  (poss-leads_to_room place__g__f kitchen true)
                         (poss-leads_to_room place__g__f kitchen true)
                         (assign (probability ) 0.2009)
                         (increase (total-cost ) 0)
                   )
)

)
