(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  robot_0__g - robot
           visualobject6 visualobject1 visualobject5 visualobject9 visualobject0 visualobject4 visualobject10 visualobject8 visualobject3 visualobject7 visualobject2 - visualobject
           book marker table stapler whiteboardmarker bookcase box mug counter paperclip cerealbox - label
           place_5__f place_0__f place_9__f place__b__f place_8__f place__d__f - place
           room1 room0 room3 room2 - room
)

(:init  (= (dora__cost_inobject book bookcase) 40.0000)
        (= (dora__cost_inobject book box) 50.0000)
        (= (dora__cost_inobject cerealbox bookcase) 40.0000)
        (= (dora__cost_inobject cerealbox box) 50.0000)
        (= (dora__cost_inobject marker bookcase) 40.0000)
        (= (dora__cost_inobject marker box) 50.0000)
        (= (dora__cost_inobject mug bookcase) 40.0000)
        (= (dora__cost_inobject mug box) 50.0000)
        (= (dora__cost_inobject paperclip bookcase) 40.0000)
        (= (dora__cost_inobject paperclip box) 50.0000)
        (= (dora__cost_inobject stapler bookcase) 40.0000)
        (= (dora__cost_inobject stapler box) 50.0000)
        (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom bookcase) 50.0000)
        (= (dora__cost_inroom box) 50.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom counter) 50.0000)
        (= (dora__cost_inroom marker) 200.0000)
        (= (dora__cost_inroom mug) 200.0000)
        (= (dora__cost_inroom paperclip) 200.0000)
        (= (dora__cost_inroom stapler) 200.0000)
        (= (dora__cost_inroom table) 50.0000)
        (= (dora__cost_on book counter) 30.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox counter) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on marker counter) 30.0000)
        (= (dora__cost_on marker table) 30.0000)
        (= (dora__cost_on mug counter) 30.0000)
        (= (dora__cost_on mug table) 30.0000)
        (= (dora__cost_on paperclip counter) 30.0000)
        (= (dora__cost_on paperclip table) 30.0000)
        (= (dora__cost_on stapler counter) 30.0000)
        (= (dora__cost_on stapler table) 30.0000)
        (= (dora__inobject book bookcase corridor) 0.2000)
        (= (dora__inobject book bookcase kitchen) 0.2000)
        (= (dora__inobject book bookcase meetingroom) 0.5000)
        (= (dora__inobject book bookcase office) 0.4000)
        (= (dora__inobject book box corridor) 0.1000)
        (= (dora__inobject book box kitchen) 0.0100)
        (= (dora__inobject book box meetingroom) 0.3000)
        (= (dora__inobject book box office) 0.0500)
        (= (dora__inobject cerealbox bookcase corridor) 0.0300)
        (= (dora__inobject cerealbox bookcase kitchen) 0.0300)
        (= (dora__inobject cerealbox bookcase meetingroom) 0.0300)
        (= (dora__inobject cerealbox bookcase office) 0.0300)
        (= (dora__inobject cerealbox box corridor) 0.0300)
        (= (dora__inobject cerealbox box kitchen) 0.4000)
        (= (dora__inobject cerealbox box meetingroom) 0.0300)
        (= (dora__inobject cerealbox box office) 0.0300)
        (= (dora__inobject marker bookcase corridor) 0.0300)
        (= (dora__inobject marker bookcase kitchen) 0.0300)
        (= (dora__inobject marker bookcase meetingroom) 0.3000)
        (= (dora__inobject marker bookcase office) 0.0300)
        (= (dora__inobject marker box corridor) 0.1000)
        (= (dora__inobject marker box kitchen) 0.0300)
        (= (dora__inobject marker box meetingroom) 0.3000)
        (= (dora__inobject marker box office) 0.1000)
        (= (dora__inobject mug bookcase corridor) 0)
        (= (dora__inobject mug bookcase kitchen) 0.0300)
        (= (dora__inobject mug bookcase meetingroom) 0.0100)
        (= (dora__inobject mug bookcase office) 0.1000)
        (= (dora__inobject mug box corridor) 0)
        (= (dora__inobject mug box kitchen) 0.0300)
        (= (dora__inobject mug box meetingroom) 0.0100)
        (= (dora__inobject mug box office) 0.0300)
        (= (dora__inobject paperclip bookcase corridor) 0.0300)
        (= (dora__inobject paperclip bookcase kitchen) 0.0300)
        (= (dora__inobject paperclip bookcase meetingroom) 0)
        (= (dora__inobject paperclip bookcase office) 0.1000)
        (= (dora__inobject paperclip box corridor) 0.0300)
        (= (dora__inobject paperclip box kitchen) 0.0300)
        (= (dora__inobject paperclip box meetingroom) 0)
        (= (dora__inobject paperclip box office) 0.1000)
        (= (dora__inobject stapler bookcase corridor) 0.0300)
        (= (dora__inobject stapler bookcase kitchen) 0.0300)
        (= (dora__inobject stapler bookcase meetingroom) 0.0100)
        (= (dora__inobject stapler bookcase office) 0.1000)
        (= (dora__inobject stapler box corridor) 0.0300)
        (= (dora__inobject stapler box kitchen) 0.0300)
        (= (dora__inobject stapler box meetingroom) 0.0100)
        (= (dora__inobject stapler box office) 0.0100)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book kitchen) 0.0366)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom bookcase corridor) 0.0878)
        (= (dora__inroom bookcase kitchen) 0.3554)
        (= (dora__inroom bookcase meetingroom) 0.0150)
        (= (dora__inroom bookcase office) 0.5327)
        (= (dora__inroom box corridor) 0)
        (= (dora__inroom box kitchen) 0.2546)
        (= (dora__inroom box meetingroom) 0.0111)
        (= (dora__inroom box office) 0.4993)
        (= (dora__inroom cerealbox corridor) 0.0219)
        (= (dora__inroom cerealbox kitchen) 0.0381)
        (= (dora__inroom cerealbox meetingroom) 0.0060)
        (= (dora__inroom cerealbox office) 0.0529)
        (= (dora__inroom counter corridor) 0.0587)
        (= (dora__inroom counter kitchen) 0.5562)
        (= (dora__inroom counter meetingroom) 0.0335)
        (= (dora__inroom counter office) 0.2781)
        (= (dora__inroom mug corridor) 0)
        (= (dora__inroom mug kitchen) 0.0402)
        (= (dora__inroom mug meetingroom) 0.0019)
        (= (dora__inroom mug office) 0.1429)
        (= (dora__inroom paperclip corridor) 0.0060)
        (= (dora__inroom paperclip kitchen) 0.0726)
        (= (dora__inroom paperclip meetingroom) 0)
        (= (dora__inroom paperclip office) 0.2399)
        (= (dora__inroom stapler corridor) 0.0035)
        (= (dora__inroom stapler kitchen) 0.1750)
        (= (dora__inroom stapler meetingroom) 0.0110)
        (= (dora__inroom stapler office) 0.4025)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table kitchen) 0.5536)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__inroom whiteboardmarker corridor) 0.0070)
        (= (dora__inroom whiteboardmarker kitchen) 0.0282)
        (= (dora__inroom whiteboardmarker meetingroom) 0.7770)
        (= (dora__inroom whiteboardmarker office) 0.0259)
        (= (dora__on book counter corridor) 0.1000)
        (= (dora__on book counter kitchen) 0.0300)
        (= (dora__on book counter meetingroom) 0.1000)
        (= (dora__on book counter office) 0.1000)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table kitchen) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox counter corridor) 0.0300)
        (= (dora__on cerealbox counter kitchen) 0.2000)
        (= (dora__on cerealbox counter meetingroom) 0.0300)
        (= (dora__on cerealbox counter office) 0.0300)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table kitchen) 0.3000)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on marker counter corridor) 0.0300)
        (= (dora__on marker counter kitchen) 0.0300)
        (= (dora__on marker counter meetingroom) 0.7000)
        (= (dora__on marker counter office) 0.2000)
        (= (dora__on marker table corridor) 0.0300)
        (= (dora__on marker table kitchen) 0.0300)
        (= (dora__on marker table meetingroom) 0.7000)
        (= (dora__on marker table office) 0.3000)
        (= (dora__on mug counter corridor) 0)
        (= (dora__on mug counter kitchen) 0.4000)
        (= (dora__on mug counter meetingroom) 0.0100)
        (= (dora__on mug counter office) 0.3000)
        (= (dora__on mug table corridor) 0)
        (= (dora__on mug table kitchen) 0.3000)
        (= (dora__on mug table meetingroom) 0.0200)
        (= (dora__on mug table office) 0.3000)
        (= (dora__on paperclip counter corridor) 0.2000)
        (= (dora__on paperclip counter kitchen) 0.0300)
        (= (dora__on paperclip counter meetingroom) 0)
        (= (dora__on paperclip counter office) 0.3000)
        (= (dora__on paperclip table corridor) 0.1000)
        (= (dora__on paperclip table kitchen) 0.0300)
        (= (dora__on paperclip table meetingroom) 0)
        (= (dora__on paperclip table office) 0.3000)
        (= (dora__on stapler counter corridor) 0.1500)
        (= (dora__on stapler counter kitchen) 0.0300)
        (= (dora__on stapler counter meetingroom) 0.0300)
        (= (dora__on stapler counter office) 0.3000)
        (= (dora__on stapler table corridor) 0.0500)
        (= (dora__on stapler table kitchen) 0.0300)
        (= (dora__on stapler table meetingroom) 0.0300)
        (= (dora__on stapler table office) 0.6000)
        (= (p-obj_exists cerealbox in room_0__t) 0.0325)
        (= (p-obj_exists table in room_0__t) 0.3951)
        (= (roomid room_0__t) 0)
        (= (search_cost book in room0) 200.0000)
        (= (search_cost book in room1) 200.0000)
        (= (search_cost book in room2) 200.0000)
        (= (search_cost book in room3) 200.0000)
        (= (search_cost book in room_0__t) 200.0000)
        (= (search_cost book in visualobject2) 40.0000)
        (= (search_cost book in visualobject6) 50.0000)
        (= (search_cost book on visualobject3) 30.0000)
        (= (search_cost book on visualobject8) 30.0000)
        (= (search_cost bookcase in room0) 50.0000)
        (= (search_cost bookcase in room1) 50.0000)
        (= (search_cost bookcase in room2) 50.0000)
        (= (search_cost bookcase in room3) 50.0000)
        (= (search_cost bookcase in room_0__t) 50.0000)
        (= (search_cost box in room0) 50.0000)
        (= (search_cost box in room1) 50.0000)
        (= (search_cost box in room2) 50.0000)
        (= (search_cost box in room3) 50.0000)
        (= (search_cost box in room_0__t) 50.0000)
        (= (search_cost cerealbox in room0) 200.0000)
        (= (search_cost cerealbox in room1) 200.0000)
        (= (search_cost cerealbox in room2) 200.0000)
        (= (search_cost cerealbox in room3) 200.0000)
        (= (search_cost cerealbox in room_0__t) 200.0000)
        (= (search_cost cerealbox in visualobject2) 40.0000)
        (= (search_cost cerealbox in visualobject6) 50.0000)
        (= (search_cost cerealbox on visualobject3) 30.0000)
        (= (search_cost cerealbox on visualobject8) 30.0000)
        (= (search_cost counter in room0) 50.0000)
        (= (search_cost counter in room1) 50.0000)
        (= (search_cost counter in room2) 50.0000)
        (= (search_cost counter in room3) 50.0000)
        (= (search_cost counter in room_0__t) 50.0000)
        (= (search_cost marker in room0) 200.0000)
        (= (search_cost marker in room1) 200.0000)
        (= (search_cost marker in room2) 200.0000)
        (= (search_cost marker in room3) 200.0000)
        (= (search_cost marker in room_0__t) 200.0000)
        (= (search_cost marker in visualobject2) 40.0000)
        (= (search_cost marker in visualobject6) 50.0000)
        (= (search_cost marker on visualobject3) 30.0000)
        (= (search_cost marker on visualobject8) 30.0000)
        (= (search_cost mug in room0) 200.0000)
        (= (search_cost mug in room1) 200.0000)
        (= (search_cost mug in room2) 200.0000)
        (= (search_cost mug in room3) 200.0000)
        (= (search_cost mug in room_0__t) 200.0000)
        (= (search_cost mug in visualobject2) 40.0000)
        (= (search_cost mug in visualobject6) 50.0000)
        (= (search_cost mug on visualobject3) 30.0000)
        (= (search_cost mug on visualobject8) 30.0000)
        (= (search_cost paperclip in room0) 200.0000)
        (= (search_cost paperclip in room1) 200.0000)
        (= (search_cost paperclip in room2) 200.0000)
        (= (search_cost paperclip in room3) 200.0000)
        (= (search_cost paperclip in room_0__t) 200.0000)
        (= (search_cost paperclip in visualobject2) 40.0000)
        (= (search_cost paperclip in visualobject6) 50.0000)
        (= (search_cost paperclip on visualobject3) 30.0000)
        (= (search_cost paperclip on visualobject8) 30.0000)
        (= (search_cost stapler in room0) 200.0000)
        (= (search_cost stapler in room1) 200.0000)
        (= (search_cost stapler in room2) 200.0000)
        (= (search_cost stapler in room3) 200.0000)
        (= (search_cost stapler in room_0__t) 200.0000)
        (= (search_cost stapler in visualobject2) 40.0000)
        (= (search_cost stapler in visualobject6) 50.0000)
        (= (search_cost stapler on visualobject3) 30.0000)
        (= (search_cost stapler on visualobject8) 30.0000)
        (= (search_cost table in room0) 50.0000)
        (= (search_cost table in room1) 50.0000)
        (= (search_cost table in room2) 50.0000)
        (= (search_cost table in room3) 50.0000)
        (= (search_cost table in room_0__t) 50.0000)
        (connected place_0__f place_5__f)
        (connected place_0__f place__d__f)
        (connected place_5__f place_0__f)
        (connected place_5__f place_8__f)
        (connected place_8__f place_5__f)
        (connected place_8__f place_9__f)
        (connected place_9__f place_8__f)
        (connected place_9__f place__b__f)
        (connected place__b__f place_9__f)
        (connected place__d__f place_0__f)
        (connected place__d__f place__f__f)
        (connected place__d__f place__g__f)
        (defined-dora__cost_inobject book bookcase)
        (defined-dora__cost_inobject book box)
        (defined-dora__cost_inobject cerealbox bookcase)
        (defined-dora__cost_inobject cerealbox box)
        (defined-dora__cost_inobject marker bookcase)
        (defined-dora__cost_inobject marker box)
        (defined-dora__cost_inobject mug bookcase)
        (defined-dora__cost_inobject mug box)
        (defined-dora__cost_inobject paperclip bookcase)
        (defined-dora__cost_inobject paperclip box)
        (defined-dora__cost_inobject stapler bookcase)
        (defined-dora__cost_inobject stapler box)
        (defined-dora__cost_inroom book)
        (defined-dora__cost_inroom bookcase)
        (defined-dora__cost_inroom box)
        (defined-dora__cost_inroom cerealbox)
        (defined-dora__cost_inroom counter)
        (defined-dora__cost_inroom marker)
        (defined-dora__cost_inroom mug)
        (defined-dora__cost_inroom paperclip)
        (defined-dora__cost_inroom stapler)
        (defined-dora__cost_inroom table)
        (defined-dora__cost_on book counter)
        (defined-dora__cost_on book table)
        (defined-dora__cost_on cerealbox counter)
        (defined-dora__cost_on cerealbox table)
        (defined-dora__cost_on marker counter)
        (defined-dora__cost_on marker table)
        (defined-dora__cost_on mug counter)
        (defined-dora__cost_on mug table)
        (defined-dora__cost_on paperclip counter)
        (defined-dora__cost_on paperclip table)
        (defined-dora__cost_on stapler counter)
        (defined-dora__cost_on stapler table)
        (defined-dora__inobject book bookcase corridor)
        (defined-dora__inobject book bookcase kitchen)
        (defined-dora__inobject book bookcase meetingroom)
        (defined-dora__inobject book bookcase office)
        (defined-dora__inobject book box corridor)
        (defined-dora__inobject book box kitchen)
        (defined-dora__inobject book box meetingroom)
        (defined-dora__inobject book box office)
        (defined-dora__inobject cerealbox bookcase corridor)
        (defined-dora__inobject cerealbox bookcase kitchen)
        (defined-dora__inobject cerealbox bookcase meetingroom)
        (defined-dora__inobject cerealbox bookcase office)
        (defined-dora__inobject cerealbox box corridor)
        (defined-dora__inobject cerealbox box kitchen)
        (defined-dora__inobject cerealbox box meetingroom)
        (defined-dora__inobject cerealbox box office)
        (defined-dora__inobject marker bookcase corridor)
        (defined-dora__inobject marker bookcase kitchen)
        (defined-dora__inobject marker bookcase meetingroom)
        (defined-dora__inobject marker bookcase office)
        (defined-dora__inobject marker box corridor)
        (defined-dora__inobject marker box kitchen)
        (defined-dora__inobject marker box meetingroom)
        (defined-dora__inobject marker box office)
        (defined-dora__inobject mug bookcase kitchen)
        (defined-dora__inobject mug bookcase meetingroom)
        (defined-dora__inobject mug bookcase office)
        (defined-dora__inobject mug box kitchen)
        (defined-dora__inobject mug box meetingroom)
        (defined-dora__inobject mug box office)
        (defined-dora__inobject paperclip bookcase corridor)
        (defined-dora__inobject paperclip bookcase kitchen)
        (defined-dora__inobject paperclip bookcase office)
        (defined-dora__inobject paperclip box corridor)
        (defined-dora__inobject paperclip box kitchen)
        (defined-dora__inobject paperclip box office)
        (defined-dora__inobject stapler bookcase corridor)
        (defined-dora__inobject stapler bookcase kitchen)
        (defined-dora__inobject stapler bookcase meetingroom)
        (defined-dora__inobject stapler bookcase office)
        (defined-dora__inobject stapler box corridor)
        (defined-dora__inobject stapler box kitchen)
        (defined-dora__inobject stapler box meetingroom)
        (defined-dora__inobject stapler box office)
        (defined-dora__inroom book corridor)
        (defined-dora__inroom book kitchen)
        (defined-dora__inroom book meetingroom)
        (defined-dora__inroom book office)
        (defined-dora__inroom bookcase corridor)
        (defined-dora__inroom bookcase kitchen)
        (defined-dora__inroom bookcase meetingroom)
        (defined-dora__inroom bookcase office)
        (defined-dora__inroom box kitchen)
        (defined-dora__inroom box meetingroom)
        (defined-dora__inroom box office)
        (defined-dora__inroom cerealbox corridor)
        (defined-dora__inroom cerealbox kitchen)
        (defined-dora__inroom cerealbox meetingroom)
        (defined-dora__inroom cerealbox office)
        (defined-dora__inroom counter corridor)
        (defined-dora__inroom counter kitchen)
        (defined-dora__inroom counter meetingroom)
        (defined-dora__inroom counter office)
        (defined-dora__inroom mug kitchen)
        (defined-dora__inroom mug meetingroom)
        (defined-dora__inroom mug office)
        (defined-dora__inroom paperclip corridor)
        (defined-dora__inroom paperclip kitchen)
        (defined-dora__inroom paperclip office)
        (defined-dora__inroom stapler corridor)
        (defined-dora__inroom stapler kitchen)
        (defined-dora__inroom stapler meetingroom)
        (defined-dora__inroom stapler office)
        (defined-dora__inroom table corridor)
        (defined-dora__inroom table kitchen)
        (defined-dora__inroom table meetingroom)
        (defined-dora__inroom table office)
        (defined-dora__inroom whiteboardmarker corridor)
        (defined-dora__inroom whiteboardmarker kitchen)
        (defined-dora__inroom whiteboardmarker meetingroom)
        (defined-dora__inroom whiteboardmarker office)
        (defined-dora__on book counter corridor)
        (defined-dora__on book counter kitchen)
        (defined-dora__on book counter meetingroom)
        (defined-dora__on book counter office)
        (defined-dora__on book table corridor)
        (defined-dora__on book table kitchen)
        (defined-dora__on book table meetingroom)
        (defined-dora__on book table office)
        (defined-dora__on cerealbox counter corridor)
        (defined-dora__on cerealbox counter kitchen)
        (defined-dora__on cerealbox counter meetingroom)
        (defined-dora__on cerealbox counter office)
        (defined-dora__on cerealbox table corridor)
        (defined-dora__on cerealbox table kitchen)
        (defined-dora__on cerealbox table meetingroom)
        (defined-dora__on cerealbox table office)
        (defined-dora__on marker counter corridor)
        (defined-dora__on marker counter kitchen)
        (defined-dora__on marker counter meetingroom)
        (defined-dora__on marker counter office)
        (defined-dora__on marker table corridor)
        (defined-dora__on marker table kitchen)
        (defined-dora__on marker table meetingroom)
        (defined-dora__on marker table office)
        (defined-dora__on mug counter kitchen)
        (defined-dora__on mug counter meetingroom)
        (defined-dora__on mug counter office)
        (defined-dora__on mug table kitchen)
        (defined-dora__on mug table meetingroom)
        (defined-dora__on mug table office)
        (defined-dora__on paperclip counter corridor)
        (defined-dora__on paperclip counter kitchen)
        (defined-dora__on paperclip counter office)
        (defined-dora__on paperclip table corridor)
        (defined-dora__on paperclip table kitchen)
        (defined-dora__on paperclip table office)
        (defined-dora__on stapler counter corridor)
        (defined-dora__on stapler counter kitchen)
        (defined-dora__on stapler counter meetingroom)
        (defined-dora__on stapler counter office)
        (defined-dora__on stapler table corridor)
        (defined-dora__on stapler table kitchen)
        (defined-dora__on stapler table meetingroom)
        (defined-dora__on stapler table office)
        (defined-p-obj_exists cerealbox in room_0__t)
        (defined-p-obj_exists table in room_0__t)
        (defined-search_cost book in room0)
        (defined-search_cost book in room1)
        (defined-search_cost book in room2)
        (defined-search_cost book in room3)
        (defined-search_cost book in room_0__t)
        (defined-search_cost book in visualobject2)
        (defined-search_cost book in visualobject6)
        (defined-search_cost book on visualobject3)
        (defined-search_cost book on visualobject8)
        (defined-search_cost bookcase in room0)
        (defined-search_cost bookcase in room1)
        (defined-search_cost bookcase in room2)
        (defined-search_cost bookcase in room3)
        (defined-search_cost bookcase in room_0__t)
        (defined-search_cost box in room0)
        (defined-search_cost box in room1)
        (defined-search_cost box in room2)
        (defined-search_cost box in room3)
        (defined-search_cost box in room_0__t)
        (defined-search_cost cerealbox in room0)
        (defined-search_cost cerealbox in room1)
        (defined-search_cost cerealbox in room2)
        (defined-search_cost cerealbox in room3)
        (defined-search_cost cerealbox in room_0__t)
        (defined-search_cost cerealbox in visualobject2)
        (defined-search_cost cerealbox in visualobject6)
        (defined-search_cost cerealbox on visualobject3)
        (defined-search_cost cerealbox on visualobject8)
        (defined-search_cost counter in room0)
        (defined-search_cost counter in room1)
        (defined-search_cost counter in room2)
        (defined-search_cost counter in room3)
        (defined-search_cost counter in room_0__t)
        (defined-search_cost marker in room0)
        (defined-search_cost marker in room1)
        (defined-search_cost marker in room2)
        (defined-search_cost marker in room3)
        (defined-search_cost marker in room_0__t)
        (defined-search_cost marker in visualobject2)
        (defined-search_cost marker in visualobject6)
        (defined-search_cost marker on visualobject3)
        (defined-search_cost marker on visualobject8)
        (defined-search_cost mug in room0)
        (defined-search_cost mug in room1)
        (defined-search_cost mug in room2)
        (defined-search_cost mug in room3)
        (defined-search_cost mug in room_0__t)
        (defined-search_cost mug in visualobject2)
        (defined-search_cost mug in visualobject6)
        (defined-search_cost mug on visualobject3)
        (defined-search_cost mug on visualobject8)
        (defined-search_cost paperclip in room0)
        (defined-search_cost paperclip in room1)
        (defined-search_cost paperclip in room2)
        (defined-search_cost paperclip in room3)
        (defined-search_cost paperclip in room_0__t)
        (defined-search_cost paperclip in visualobject2)
        (defined-search_cost paperclip in visualobject6)
        (defined-search_cost paperclip on visualobject3)
        (defined-search_cost paperclip on visualobject8)
        (defined-search_cost stapler in room0)
        (defined-search_cost stapler in room1)
        (defined-search_cost stapler in room2)
        (defined-search_cost stapler in room3)
        (defined-search_cost stapler in room_0__t)
        (defined-search_cost stapler in visualobject2)
        (defined-search_cost stapler in visualobject6)
        (defined-search_cost stapler on visualobject3)
        (defined-search_cost stapler on visualobject8)
        (defined-search_cost table in room0)
        (defined-search_cost table in room1)
        (defined-search_cost table in room2)
        (defined-search_cost table in room3)
        (defined-search_cost table in room_0__t)
        (i_in-domain-category room_0__t corridor)
        (i_in-domain-category room_0__t kitchen)
        (i_in-domain-category room_0__t meetingroom)
        (i_in-domain-category room_0__t office)
        (i_in-domain-leads_to_room place__f__f corridor true)
        (i_in-domain-leads_to_room place__f__f kitchen true)
        (i_in-domain-leads_to_room place__f__f meetingroom true)
        (i_in-domain-leads_to_room place__f__f office true)
        (i_in-domain-leads_to_room place__g__f corridor true)
        (i_in-domain-leads_to_room place__g__f kitchen true)
        (i_in-domain-leads_to_room place__g__f meetingroom true)
        (i_in-domain-leads_to_room place__g__f office true)
        (i_in-domain-related-to visualobject0 room0)
        (i_in-domain-related-to visualobject0 room1)
        (i_in-domain-related-to visualobject0 room2)
        (i_in-domain-related-to visualobject0 room3)
        (i_in-domain-related-to visualobject0 room_0__t)
        (i_in-domain-related-to visualobject0 visualobject0)
        (i_in-domain-related-to visualobject0 visualobject1)
        (i_in-domain-related-to visualobject0 visualobject10)
        (i_in-domain-related-to visualobject0 visualobject2)
        (i_in-domain-related-to visualobject0 visualobject3)
        (i_in-domain-related-to visualobject0 visualobject4)
        (i_in-domain-related-to visualobject0 visualobject5)
        (i_in-domain-related-to visualobject0 visualobject6)
        (i_in-domain-related-to visualobject0 visualobject7)
        (i_in-domain-related-to visualobject0 visualobject8)
        (i_in-domain-related-to visualobject0 visualobject9)
        (i_in-domain-related-to visualobject1 room0)
        (i_in-domain-related-to visualobject1 room1)
        (i_in-domain-related-to visualobject1 room2)
        (i_in-domain-related-to visualobject1 room3)
        (i_in-domain-related-to visualobject1 room_0__t)
        (i_in-domain-related-to visualobject1 visualobject0)
        (i_in-domain-related-to visualobject1 visualobject1)
        (i_in-domain-related-to visualobject1 visualobject10)
        (i_in-domain-related-to visualobject1 visualobject2)
        (i_in-domain-related-to visualobject1 visualobject3)
        (i_in-domain-related-to visualobject1 visualobject4)
        (i_in-domain-related-to visualobject1 visualobject5)
        (i_in-domain-related-to visualobject1 visualobject6)
        (i_in-domain-related-to visualobject1 visualobject7)
        (i_in-domain-related-to visualobject1 visualobject8)
        (i_in-domain-related-to visualobject1 visualobject9)
        (i_in-domain-related-to visualobject10 room0)
        (i_in-domain-related-to visualobject10 room1)
        (i_in-domain-related-to visualobject10 room2)
        (i_in-domain-related-to visualobject10 room3)
        (i_in-domain-related-to visualobject10 room_0__t)
        (i_in-domain-related-to visualobject10 visualobject0)
        (i_in-domain-related-to visualobject10 visualobject1)
        (i_in-domain-related-to visualobject10 visualobject10)
        (i_in-domain-related-to visualobject10 visualobject2)
        (i_in-domain-related-to visualobject10 visualobject3)
        (i_in-domain-related-to visualobject10 visualobject4)
        (i_in-domain-related-to visualobject10 visualobject5)
        (i_in-domain-related-to visualobject10 visualobject6)
        (i_in-domain-related-to visualobject10 visualobject7)
        (i_in-domain-related-to visualobject10 visualobject8)
        (i_in-domain-related-to visualobject10 visualobject9)
        (i_in-domain-related-to visualobject2 room0)
        (i_in-domain-related-to visualobject2 room1)
        (i_in-domain-related-to visualobject2 room2)
        (i_in-domain-related-to visualobject2 room3)
        (i_in-domain-related-to visualobject2 room_0__t)
        (i_in-domain-related-to visualobject2 visualobject0)
        (i_in-domain-related-to visualobject2 visualobject1)
        (i_in-domain-related-to visualobject2 visualobject10)
        (i_in-domain-related-to visualobject2 visualobject2)
        (i_in-domain-related-to visualobject2 visualobject3)
        (i_in-domain-related-to visualobject2 visualobject4)
        (i_in-domain-related-to visualobject2 visualobject5)
        (i_in-domain-related-to visualobject2 visualobject6)
        (i_in-domain-related-to visualobject2 visualobject7)
        (i_in-domain-related-to visualobject2 visualobject8)
        (i_in-domain-related-to visualobject2 visualobject9)
        (i_in-domain-related-to visualobject3 room0)
        (i_in-domain-related-to visualobject3 room1)
        (i_in-domain-related-to visualobject3 room2)
        (i_in-domain-related-to visualobject3 room3)
        (i_in-domain-related-to visualobject3 room_0__t)
        (i_in-domain-related-to visualobject3 visualobject0)
        (i_in-domain-related-to visualobject3 visualobject1)
        (i_in-domain-related-to visualobject3 visualobject10)
        (i_in-domain-related-to visualobject3 visualobject2)
        (i_in-domain-related-to visualobject3 visualobject3)
        (i_in-domain-related-to visualobject3 visualobject4)
        (i_in-domain-related-to visualobject3 visualobject5)
        (i_in-domain-related-to visualobject3 visualobject6)
        (i_in-domain-related-to visualobject3 visualobject7)
        (i_in-domain-related-to visualobject3 visualobject8)
        (i_in-domain-related-to visualobject3 visualobject9)
        (i_in-domain-related-to visualobject4 room0)
        (i_in-domain-related-to visualobject4 room1)
        (i_in-domain-related-to visualobject4 room2)
        (i_in-domain-related-to visualobject4 room3)
        (i_in-domain-related-to visualobject4 room_0__t)
        (i_in-domain-related-to visualobject4 visualobject0)
        (i_in-domain-related-to visualobject4 visualobject1)
        (i_in-domain-related-to visualobject4 visualobject10)
        (i_in-domain-related-to visualobject4 visualobject2)
        (i_in-domain-related-to visualobject4 visualobject3)
        (i_in-domain-related-to visualobject4 visualobject4)
        (i_in-domain-related-to visualobject4 visualobject5)
        (i_in-domain-related-to visualobject4 visualobject6)
        (i_in-domain-related-to visualobject4 visualobject7)
        (i_in-domain-related-to visualobject4 visualobject8)
        (i_in-domain-related-to visualobject4 visualobject9)
        (i_in-domain-related-to visualobject5 room0)
        (i_in-domain-related-to visualobject5 room1)
        (i_in-domain-related-to visualobject5 room2)
        (i_in-domain-related-to visualobject5 room3)
        (i_in-domain-related-to visualobject5 room_0__t)
        (i_in-domain-related-to visualobject5 visualobject0)
        (i_in-domain-related-to visualobject5 visualobject1)
        (i_in-domain-related-to visualobject5 visualobject10)
        (i_in-domain-related-to visualobject5 visualobject2)
        (i_in-domain-related-to visualobject5 visualobject3)
        (i_in-domain-related-to visualobject5 visualobject4)
        (i_in-domain-related-to visualobject5 visualobject5)
        (i_in-domain-related-to visualobject5 visualobject6)
        (i_in-domain-related-to visualobject5 visualobject7)
        (i_in-domain-related-to visualobject5 visualobject8)
        (i_in-domain-related-to visualobject5 visualobject9)
        (i_in-domain-related-to visualobject6 room0)
        (i_in-domain-related-to visualobject6 room1)
        (i_in-domain-related-to visualobject6 room2)
        (i_in-domain-related-to visualobject6 room3)
        (i_in-domain-related-to visualobject6 room_0__t)
        (i_in-domain-related-to visualobject6 visualobject0)
        (i_in-domain-related-to visualobject6 visualobject1)
        (i_in-domain-related-to visualobject6 visualobject10)
        (i_in-domain-related-to visualobject6 visualobject2)
        (i_in-domain-related-to visualobject6 visualobject3)
        (i_in-domain-related-to visualobject6 visualobject4)
        (i_in-domain-related-to visualobject6 visualobject5)
        (i_in-domain-related-to visualobject6 visualobject6)
        (i_in-domain-related-to visualobject6 visualobject7)
        (i_in-domain-related-to visualobject6 visualobject8)
        (i_in-domain-related-to visualobject6 visualobject9)
        (i_in-domain-related-to visualobject7 room0)
        (i_in-domain-related-to visualobject7 room1)
        (i_in-domain-related-to visualobject7 room2)
        (i_in-domain-related-to visualobject7 room3)
        (i_in-domain-related-to visualobject7 room_0__t)
        (i_in-domain-related-to visualobject7 visualobject0)
        (i_in-domain-related-to visualobject7 visualobject1)
        (i_in-domain-related-to visualobject7 visualobject10)
        (i_in-domain-related-to visualobject7 visualobject2)
        (i_in-domain-related-to visualobject7 visualobject3)
        (i_in-domain-related-to visualobject7 visualobject4)
        (i_in-domain-related-to visualobject7 visualobject5)
        (i_in-domain-related-to visualobject7 visualobject6)
        (i_in-domain-related-to visualobject7 visualobject7)
        (i_in-domain-related-to visualobject7 visualobject8)
        (i_in-domain-related-to visualobject7 visualobject9)
        (i_in-domain-related-to visualobject8 room0)
        (i_in-domain-related-to visualobject8 room1)
        (i_in-domain-related-to visualobject8 room2)
        (i_in-domain-related-to visualobject8 room3)
        (i_in-domain-related-to visualobject8 room_0__t)
        (i_in-domain-related-to visualobject8 visualobject0)
        (i_in-domain-related-to visualobject8 visualobject1)
        (i_in-domain-related-to visualobject8 visualobject10)
        (i_in-domain-related-to visualobject8 visualobject2)
        (i_in-domain-related-to visualobject8 visualobject3)
        (i_in-domain-related-to visualobject8 visualobject4)
        (i_in-domain-related-to visualobject8 visualobject5)
        (i_in-domain-related-to visualobject8 visualobject6)
        (i_in-domain-related-to visualobject8 visualobject7)
        (i_in-domain-related-to visualobject8 visualobject8)
        (i_in-domain-related-to visualobject8 visualobject9)
        (i_in-domain-related-to visualobject9 room0)
        (i_in-domain-related-to visualobject9 room1)
        (i_in-domain-related-to visualobject9 room2)
        (i_in-domain-related-to visualobject9 room3)
        (i_in-domain-related-to visualobject9 room_0__t)
        (i_in-domain-related-to visualobject9 visualobject0)
        (i_in-domain-related-to visualobject9 visualobject1)
        (i_in-domain-related-to visualobject9 visualobject10)
        (i_in-domain-related-to visualobject9 visualobject2)
        (i_in-domain-related-to visualobject9 visualobject3)
        (i_in-domain-related-to visualobject9 visualobject4)
        (i_in-domain-related-to visualobject9 visualobject5)
        (i_in-domain-related-to visualobject9 visualobject6)
        (i_in-domain-related-to visualobject9 visualobject7)
        (i_in-domain-related-to visualobject9 visualobject8)
        (i_in-domain-related-to visualobject9 visualobject9)
        (in-room place_0__f room_0__t)
        (in-room place_5__f room_0__t)
        (in-room place_8__f room_0__t)
        (in-room place_9__f room_0__t)
        (in-room place__b__f room_0__t)
        (is-in robot_0__g place__d__f)
        (is-virtual room0)
        (is-virtual room1)
        (is-virtual room2)
        (is-virtual room3)
        (is-virtual visualobject0)
        (is-virtual visualobject1)
        (is-virtual visualobject10)
        (is-virtual visualobject2)
        (is-virtual visualobject3)
        (is-virtual visualobject4)
        (is-virtual visualobject5)
        (is-virtual visualobject6)
        (is-virtual visualobject7)
        (is-virtual visualobject8)
        (is-virtual visualobject9)
        (label visualobject0 book)
        (label visualobject1 marker)
        (label visualobject10 cerealbox)
        (label visualobject2 bookcase)
        (label visualobject3 table)
        (label visualobject4 stapler)
        (label visualobject5 whiteboardmarker)
        (label visualobject6 box)
        (label visualobject7 mug)
        (label visualobject8 counter)
        (label visualobject9 paperclip)
        (placestatus place_0__f trueplace)
        (placestatus place_5__f trueplace)
        (placestatus place_8__f trueplace)
        (placestatus place_9__f trueplace)
        (placestatus place__b__f trueplace)
        (placestatus place__d__f trueplace)
        (placestatus place__f__f placeholder)
        (placestatus place__g__f placeholder)
        (poss-in-room place_0__f room_0__t)
        (poss-in-room place_5__f room_0__t)
        (poss-in-room place_8__f room_0__t)
        (poss-in-room place_9__f room_0__t)
        (poss-in-room place__b__f room_0__t)
        (virtual-category room0 corridor)
        (virtual-category room1 office)
        (virtual-category room2 kitchen)
        (virtual-category room3 meetingroom)
)

(:goal  (and  (exists (?o - visualobject)  (and  (label ?o cerealbox)
                                                 (position-reported ?o)
                                           )
              )
        )
)
(:metric minimize (total-cost ))

)
