package BindingFeatures;


/**
* BindingFeatures/RectangularAreaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingFeatures.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class RectangularAreaHelper
{
  private static String  _id = "IDL:BindingFeatures/RectangularArea:1.0";

  public static void insert (org.omg.CORBA.Any a, BindingFeatures.RectangularArea that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BindingFeatures.RectangularArea extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = BindingFeaturesCommon.Vector2Helper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_corner1",
            _tcOf_members0,
            null);
          _tcOf_members0 = BindingFeaturesCommon.Vector2Helper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "m_corner2",
            _tcOf_members0,
            null);
          _tcOf_members0 = BindingFeaturesCommon.ReferenceFrameHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "m_frame",
            _tcOf_members0,
            null);
          _tcOf_members0 = BindingFeaturesCommon.ParentFeatureHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "m_parent",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (BindingFeatures.RectangularAreaHelper.id (), "RectangularArea", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BindingFeatures.RectangularArea read (org.omg.CORBA.portable.InputStream istream)
  {
    BindingFeatures.RectangularArea value = new BindingFeatures.RectangularArea ();
    value.m_corner1 = BindingFeaturesCommon.Vector2Helper.read (istream);
    value.m_corner2 = BindingFeaturesCommon.Vector2Helper.read (istream);
    value.m_frame = BindingFeaturesCommon.ReferenceFrameHelper.read (istream);
    value.m_parent = BindingFeaturesCommon.ParentFeatureHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BindingFeatures.RectangularArea value)
  {
    BindingFeaturesCommon.Vector2Helper.write (ostream, value.m_corner1);
    BindingFeaturesCommon.Vector2Helper.write (ostream, value.m_corner2);
    BindingFeaturesCommon.ReferenceFrameHelper.write (ostream, value.m_frame);
    BindingFeaturesCommon.ParentFeatureHelper.write (ostream, value.m_parent);
  }

}
