package BindingFeatures;

/**
* BindingFeatures/RectangularAreaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingFeatures.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class RectangularAreaHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingFeatures.RectangularArea value = null;

  public RectangularAreaHolder ()
  {
  }

  public RectangularAreaHolder (BindingFeatures.RectangularArea initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingFeatures.RectangularAreaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingFeatures.RectangularAreaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingFeatures.RectangularAreaHelper.type ();
  }

}
