package balt.corba.autogen.FrameworkBasics;


/**
* balt/corba/autogen/FrameworkBasics/BALTTimeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrameworkBasics.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class BALTTimeHelper
{
  private static String  _id = "IDL:FrameworkBasics/BALTTime:1.0";

  public static void insert (org.omg.CORBA.Any a, balt.corba.autogen.FrameworkBasics.BALTTime that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static balt.corba.autogen.FrameworkBasics.BALTTime extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_s",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "m_us",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (balt.corba.autogen.FrameworkBasics.BALTTimeHelper.id (), "BALTTime", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static balt.corba.autogen.FrameworkBasics.BALTTime read (org.omg.CORBA.portable.InputStream istream)
  {
    balt.corba.autogen.FrameworkBasics.BALTTime value = new balt.corba.autogen.FrameworkBasics.BALTTime ();
    value.m_s = istream.read_long ();
    value.m_us = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, balt.corba.autogen.FrameworkBasics.BALTTime value)
  {
    ostream.write_long (value.m_s);
    ostream.write_long (value.m_us);
  }

}
