package balt.corba.autogen.FrameworkBasics;


/**
* balt/corba/autogen/FrameworkBasics/FrameworkProcessManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrameworkBasics.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/**
   * The process that sits on each machines and launches processes
   **/
public interface FrameworkProcessManagerOperations 
{
  void createGraph (balt.corba.autogen.FrameworkBasics.ProcessConnection[] _graph);
  void createRemoteConnections ();
  void connectGraph ();
  void startGraph ();
  void runGraph ();
  void stopGraph ();

  //send a ping to tell all processes to reset clocks to 0
  void synchroniseWatches ();
} // interface FrameworkProcessManagerOperations
