package balt.corba.autogen.FrameworkBasics;

/**
* balt/corba/autogen/FrameworkBasics/FrameworkConnectionTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrameworkBasics.idl
* Donnerstag, 14. Mai 2009 22.09 Uhr CEST
*/


/**
   * Definition of connection types.
   */
public final class FrameworkConnectionTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public balt.corba.autogen.FrameworkBasics.FrameworkConnectionType value = null;

  public FrameworkConnectionTypeHolder ()
  {
  }

  public FrameworkConnectionTypeHolder (balt.corba.autogen.FrameworkBasics.FrameworkConnectionType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = balt.corba.autogen.FrameworkBasics.FrameworkConnectionTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    balt.corba.autogen.FrameworkBasics.FrameworkConnectionTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return balt.corba.autogen.FrameworkBasics.FrameworkConnectionTypeHelper.type ();
  }

}
