package NavData;


/**
* NavData/LineMapEndPt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NavData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class LineMapEndPt implements org.omg.CORBA.portable.IDLEntity
{
  public int m_id = (int)0;
  public double m_x = (double)0;
  public double m_y = (double)0;

  public LineMapEndPt ()
  {
  } // ctor

  public LineMapEndPt (int _m_id, double _m_x, double _m_y)
  {
    m_id = _m_id;
    m_x = _m_x;
    m_y = _m_y;
  } // ctor

} // class LineMapEndPt
