package NavData;


/**
* NavData/Person.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NavData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Person implements org.omg.CORBA.portable.IDLEntity
{
  public balt.corba.autogen.FrameworkBasics.BALTTime m_time = null;

  // timestamp when last updated
  public int m_id = (int)0;
  public double m_x = (double)0;
  public double m_y = (double)0;
  public double m_theta = (double)0;
  public double m_speed = (double)0;
  public double m_visibility = (double)0;
  public int m_areaID = (int)0;

  public Person ()
  {
  } // ctor

  public Person (balt.corba.autogen.FrameworkBasics.BALTTime _m_time, int _m_id, double _m_x, double _m_y, double _m_theta, double _m_speed, double _m_visibility, int _m_areaID)
  {
    m_time = _m_time;
    m_id = _m_id;
    m_x = _m_x;
    m_y = _m_y;
    m_theta = _m_theta;
    m_speed = _m_speed;
    m_visibility = _m_visibility;
    m_areaID = _m_areaID;
  } // ctor

} // class Person
