GARNAME = cast
GARVERSION = svn
CATEGORIES = bootstrap
DISTFILES = 
MAINTAINER = n.hawes



LIBDEPS = cogx/cast-c++ cogx/cast-java

CONFIGURE_SCRIPTS = 
BUILD_SCRIPTS = 
INSTALL_SCRIPTS = 


include ../../gar.extend.mk

	
clean2:
	make -C ../cast-c++ clean
	make -C ../cast-java clean
