GARNAME = peak-linux-driver
GARVERSION = 7.6
CATEGORIES = bootstrap
DISTFILES = $(GARNAME).${GARVERSION}.tar.gz


DEB_PACKAGES=\
	libpopt-dev@ubuntu


BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

include ../../gar.extend.mk

