GARNAME = peak-linux-driver
GARVERSION = 6.20
CATEGORIES = bootstrap
DISTFILES = $(GARNAME).${GARVERSION}.tar.gz




BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

include ../../gar.extend.mk

