# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configdlg.ui'
#
# Created: Sun Apr 25 16:33:11 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ConfigDlg(object):
    def setupUi(self, ConfigDlg):
        ConfigDlg.setObjectName("ConfigDlg")
        ConfigDlg.resize(513, 350)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ConfigDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(ConfigDlg)
        self.tabWidget.setObjectName("tabWidget")
        self.tabHost = QtGui.QWidget()
        self.tabHost.setObjectName("tabHost")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabHost)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ServerListView = QtGui.QListView(self.tabHost)
        self.ServerListView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.ServerListView.setObjectName("ServerListView")
        self.verticalLayout.addWidget(self.ServerListView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btAddHost = QtGui.QPushButton(self.tabHost)
        self.btAddHost.setObjectName("btAddHost")
        self.horizontalLayout.addWidget(self.btAddHost)
        self.btRemoveHost = QtGui.QPushButton(self.tabHost)
        self.btRemoveHost.setObjectName("btRemoveHost")
        self.horizontalLayout.addWidget(self.btRemoveHost)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabHost, "")
        self.tabConfig = QtGui.QWidget()
        self.tabConfig.setObjectName("tabConfig")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabConfig)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtGui.QFrame(self.tabConfig)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.clientHostCmbx = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientHostCmbx.sizePolicy().hasHeightForWidth())
        self.clientHostCmbx.setSizePolicy(sizePolicy)
        self.clientHostCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.clientHostCmbx.setObjectName("clientHostCmbx")
        self.horizontalLayout_7.addWidget(self.clientHostCmbx)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.clientConfigCmbx = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientConfigCmbx.sizePolicy().hasHeightForWidth())
        self.clientConfigCmbx.setSizePolicy(sizePolicy)
        self.clientConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.clientConfigCmbx.setObjectName("clientConfigCmbx")
        self.horizontalLayout_5.addWidget(self.clientConfigCmbx)
        self.btBrowseCastFile = QtGui.QPushButton(self.frame_2)
        self.btBrowseCastFile.setObjectName("btBrowseCastFile")
        self.horizontalLayout_5.addWidget(self.btBrowseCastFile)
        self.btEditClientConfig = QtGui.QPushButton(self.frame_2)
        self.btEditClientConfig.setObjectName("btEditClientConfig")
        self.horizontalLayout_5.addWidget(self.btEditClientConfig)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.tabConfig)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.playerHostCmbx = QtGui.QComboBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerHostCmbx.sizePolicy().hasHeightForWidth())
        self.playerHostCmbx.setSizePolicy(sizePolicy)
        self.playerHostCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.playerHostCmbx.setObjectName("playerHostCmbx")
        self.horizontalLayout_8.addWidget(self.playerHostCmbx)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.playerConfigCmbx = QtGui.QComboBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerConfigCmbx.sizePolicy().hasHeightForWidth())
        self.playerConfigCmbx.setSizePolicy(sizePolicy)
        self.playerConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.playerConfigCmbx.setObjectName("playerConfigCmbx")
        self.horizontalLayout_6.addWidget(self.playerConfigCmbx)
        self.btBrowsePlayerFile = QtGui.QPushButton(self.frame_3)
        self.btBrowsePlayerFile.setObjectName("btBrowsePlayerFile")
        self.horizontalLayout_6.addWidget(self.btBrowsePlayerFile)
        self.btEditPlayerConfig = QtGui.QPushButton(self.frame_3)
        self.btEditPlayerConfig.setObjectName("btEditPlayerConfig")
        self.horizontalLayout_6.addWidget(self.btEditPlayerConfig)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.frame_3)
        spacerItem3 = QtGui.QSpacerItem(20, 87, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tabWidget.addTab(self.tabConfig, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(ConfigDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(ConfigDlg)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ConfigDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ConfigDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigDlg)

    def retranslateUi(self, ConfigDlg):
        ConfigDlg.setWindowTitle(QtGui.QApplication.translate("ConfigDlg", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btAddHost.setText(QtGui.QApplication.translate("ConfigDlg", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.btRemoveHost.setText(QtGui.QApplication.translate("ConfigDlg", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHost), QtGui.QApplication.translate("ConfigDlg", "Hosts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ConfigDlg", "Client", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ConfigDlg", "Run on host", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ConfigDlg", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.clientConfigCmbx.setStatusTip(QtGui.QApplication.translate("ConfigDlg", "CAST configuration file ", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowseCastFile.setText(QtGui.QApplication.translate("ConfigDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditClientConfig.setText(QtGui.QApplication.translate("ConfigDlg", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ConfigDlg", "Player", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ConfigDlg", "Run on host", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ConfigDlg", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.playerConfigCmbx.setStatusTip(QtGui.QApplication.translate("ConfigDlg", "Player configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowsePlayerFile.setText(QtGui.QApplication.translate("ConfigDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditPlayerConfig.setText(QtGui.QApplication.translate("ConfigDlg", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfig), QtGui.QApplication.translate("ConfigDlg", "Configuration", None, QtGui.QApplication.UnicodeUTF8))

