#!/bin/bash

file=$1
fn=${file%.*}
extension=${file##*.}
path=`dirname $0`

if [ $extension == "dot" ]
then
  "$path/gen_graph_pdf" $file
  file="$fn.pdf"
  extension="pdf"
fi
# select appropriate viewer
if [ $extension == "ps" -o $extension == "ps2" ]
then
   viewer="gv"
elif [ $extension == "pdf" ]
then
   viewer="gv" #xpdf? kpdf?
else
   viewer="xv"
fi
echo "$viewer $file"
$viewer $file
exit