#!/bin/bash
#sudo ifconfig eth0 down
#sudo rmmod sky2
sudo ifconfig eth0 192.168.0.10  mtu 4114  txqueuelen 10000
sudo route del -net 192.168.0.0 netmask 255.255.255.0 dev eth0
sudo route add -net 192.168.0.0 netmask 255.255.255.0 dev eth0
sudo ifconfig eth0 192.168.0.10  mtu 9000  txqueuelen 10000
sudo /sbin/sysctl -w net.ipv4.tcp_sack=0

