(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  visualobject0 visualobject1 visualobject2 visualobject_6_w visualobject_7_w - visualobject
           person0 person_0__s - person
           robot_0__c - robot
           place_0__b place_1__b place_2__b place_3__b place_4__b place_6__b place_7__b - place
           book cerealbox magazine table - label
           corridor meetingroom office - category
           conegroup_0__l conegroup_1__l conegroup_2__l conegroup_3__l conegroup_4__l conegroup_5__l conegroup_6__l conegroup_7__l conegroup_8__l conegroup_9__l - conegroup
           room_0__a1 - room
)

(:init  (= (associated-with person0) dummy-room)
        (= (associated-with person_0__s) room_0__a1)
        (= (cg-label conegroup_0__l) magazine)
        (= (cg-label conegroup_1__l) magazine)
        (= (cg-label conegroup_2__l) magazine)
        (= (cg-label conegroup_3__l) magazine)
        (= (cg-label conegroup_4__l) magazine)
        (= (cg-label conegroup_5__l) magazine)
        (= (cg-label conegroup_6__l) magazine)
        (= (cg-label conegroup_7__l) magazine)
        (= (cg-label conegroup_8__l) magazine)
        (= (cg-label conegroup_9__l) magazine)
        (= (cg-place conegroup_0__l) place_0__b)
        (= (cg-place conegroup_1__l) place_1__b)
        (= (cg-place conegroup_2__l) place_2__b)
        (= (cg-place conegroup_3__l) place_3__b)
        (= (cg-place conegroup_4__l) place_3__b)
        (= (cg-place conegroup_5__l) place_4__b)
        (= (cg-place conegroup_6__l) place_6__b)
        (= (cg-place conegroup_7__l) place_6__b)
        (= (cg-place conegroup_8__l) place_7__b)
        (= (cg-place conegroup_9__l) place_7__b)
        (= (cg-related-to conegroup_0__l) room_0__a1)
        (= (cg-related-to conegroup_1__l) room_0__a1)
        (= (cg-related-to conegroup_2__l) room_0__a1)
        (= (cg-related-to conegroup_3__l) room_0__a1)
        (= (cg-related-to conegroup_4__l) room_0__a1)
        (= (cg-related-to conegroup_5__l) room_0__a1)
        (= (cg-related-to conegroup_6__l) room_0__a1)
        (= (cg-related-to conegroup_7__l) room_0__a1)
        (= (cg-related-to conegroup_8__l) room_0__a1)
        (= (cg-related-to conegroup_9__l) room_0__a1)
        (= (cg-relation conegroup_0__l) in)
        (= (cg-relation conegroup_1__l) in)
        (= (cg-relation conegroup_2__l) in)
        (= (cg-relation conegroup_3__l) in)
        (= (cg-relation conegroup_4__l) in)
        (= (cg-relation conegroup_5__l) in)
        (= (cg-relation conegroup_6__l) in)
        (= (cg-relation conegroup_7__l) in)
        (= (cg-relation conegroup_8__l) in)
        (= (cg-relation conegroup_9__l) in)
        (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom magazine) 200.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on magazine table) 30.0000)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom cerealbox corridor) 0.0519)
        (= (dora__inroom cerealbox meetingroom) 0.0600)
        (= (dora__inroom cerealbox office) 0.0253)
        (= (dora__inroom magazine corridor) 0.0025)
        (= (dora__inroom magazine meetingroom) 0.8000)
        (= (dora__inroom magazine office) 0.1800)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__not_inroom book corridor) 0.9975)
        (= (dora__not_inroom book meetingroom) 0.9846)
        (= (dora__not_inroom book office) 0.8715)
        (= (dora__not_inroom cerealbox corridor) 0.9481)
        (= (dora__not_inroom cerealbox meetingroom) 0.9400)
        (= (dora__not_inroom cerealbox office) 0.9747)
        (= (dora__not_inroom magazine corridor) 0.9975)
        (= (dora__not_inroom magazine meetingroom) 0.2000)
        (= (dora__not_inroom magazine office) 0.8200)
        (= (dora__not_inroom table corridor) 0.9406)
        (= (dora__not_inroom table meetingroom) 0.8958)
        (= (dora__not_inroom table office) 0.4800)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on magazine table corridor) 0.0300)
        (= (dora__on magazine table meetingroom) 0.8000)
        (= (dora__on magazine table office) 0.1000)
        (= (entity-exists conegroup_0__l) true)
        (= (entity-exists conegroup_1__l) true)
        (= (entity-exists conegroup_2__l) true)
        (= (entity-exists conegroup_3__l) true)
        (= (entity-exists conegroup_4__l) true)
        (= (entity-exists conegroup_5__l) true)
        (= (entity-exists conegroup_6__l) true)
        (= (entity-exists conegroup_7__l) true)
        (= (entity-exists conegroup_8__l) true)
        (= (entity-exists conegroup_9__l) true)
        (= (entity-exists person_0__s) true)
        (= (entity-exists place_0__b) true)
        (= (entity-exists place_1__b) true)
        (= (entity-exists place_2__b) true)
        (= (entity-exists place_3__b) true)
        (= (entity-exists place_4__b) true)
        (= (entity-exists place_6__b) true)
        (= (entity-exists place_7__b) true)
        (= (entity-exists robot_0__c) true)
        (= (entity-exists room_0__a1) true)
        (= (in-room place_0__b) room_0__a1)
        (= (in-room place_1__b) room_0__a1)
        (= (in-room place_2__b) room_0__a1)
        (= (in-room place_3__b) room_0__a1)
        (= (in-room place_4__b) room_0__a1)
        (= (in-room place_6__b) room_0__a1)
        (= (in-room place_7__b) room_0__a1)
        (= (is-in robot_0__c) place_0__b)
        (= (label visualobject0) cerealbox)
        (= (label visualobject1) table)
        (= (label visualobject2) book)
        (= (label visualobject_6_w) magazine)
        (= (label visualobject_7_w) container)
        (= (p-obj_exists cerealbox in room_0__a1 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_0__a1 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_0__a1 office) 0.0253)
        (= (p-obj_exists magazine in room_0__a1 corridor) 0.0000)
        (= (p-obj_exists magazine in room_0__a1 meetingroom) 0.0000)
        (= (p-obj_exists magazine in room_0__a1 office) 0.0000)
        (= (p-visible conegroup_0__l) 0.0618)
        (= (p-visible conegroup_1__l) 0.0577)
        (= (p-visible conegroup_2__l) 0.1071)
        (= (p-visible conegroup_3__l) 0.0762)
        (= (p-visible conegroup_4__l) 0.1238)
        (= (p-visible conegroup_5__l) 0.1831)
        (= (p-visible conegroup_6__l) 0.0803)
        (= (p-visible conegroup_7__l) 0.0893)
        (= (p-visible conegroup_8__l) 0.1217)
        (= (p-visible conegroup_9__l) 0.0990)
        (= (placestatus place_0__b) trueplace)
        (= (placestatus place_1__b) trueplace)
        (= (placestatus place_2__b) trueplace)
        (= (placestatus place_3__b) trueplace)
        (= (placestatus place_4__b) trueplace)
        (= (placestatus place_6__b) trueplace)
        (= (placestatus place_7__b) trueplace)
        (= (related-to visualobject0) unknown)
        (= (related-to visualobject1) unknown)
        (= (related-to visualobject2) unknown)
        (= (related-to visualobject_6_w) visualobject_7_w)
        (= (related-to visualobject_7_w) room_0__a1)
        (= (relation visualobject_6_w) in)
        (= (relation visualobject_7_w) in)
        (= (roomid room_0__a1) 0)
        (= (search_cost book in dummy-room) 200.0000)
        (= (search_cost book in room_0__a1) 200.0000)
        (= (search_cost book in visualobject0) unknown)
        (= (search_cost book in visualobject1) unknown)
        (= (search_cost book in visualobject2) unknown)
        (= (search_cost book in visualobject_6_w) unknown)
        (= (search_cost book in visualobject_7_w) unknown)
        (= (search_cost book on visualobject0) unknown)
        (= (search_cost book on visualobject1) 30.0000)
        (= (search_cost book on visualobject2) unknown)
        (= (search_cost book on visualobject_6_w) unknown)
        (= (search_cost book on visualobject_7_w) unknown)
        (= (search_cost cerealbox in dummy-room) 200.0000)
        (= (search_cost cerealbox in room_0__a1) 200.0000)
        (= (search_cost cerealbox in visualobject0) unknown)
        (= (search_cost cerealbox in visualobject1) unknown)
        (= (search_cost cerealbox in visualobject2) unknown)
        (= (search_cost cerealbox in visualobject_6_w) unknown)
        (= (search_cost cerealbox in visualobject_7_w) unknown)
        (= (search_cost cerealbox on visualobject0) unknown)
        (= (search_cost cerealbox on visualobject1) 30.0000)
        (= (search_cost cerealbox on visualobject2) unknown)
        (= (search_cost cerealbox on visualobject_6_w) unknown)
        (= (search_cost cerealbox on visualobject_7_w) unknown)
        (= (search_cost container in dummy-room) unknown)
        (= (search_cost container in room_0__a1) unknown)
        (= (search_cost container in visualobject0) unknown)
        (= (search_cost container in visualobject1) unknown)
        (= (search_cost container in visualobject2) unknown)
        (= (search_cost container in visualobject_6_w) unknown)
        (= (search_cost container in visualobject_7_w) unknown)
        (= (search_cost container on visualobject0) unknown)
        (= (search_cost container on visualobject1) unknown)
        (= (search_cost container on visualobject2) unknown)
        (= (search_cost container on visualobject_6_w) unknown)
        (= (search_cost container on visualobject_7_w) unknown)
        (= (search_cost magazine in dummy-room) 200.0000)
        (= (search_cost magazine in room_0__a1) 200.0000)
        (= (search_cost magazine in visualobject0) unknown)
        (= (search_cost magazine in visualobject1) unknown)
        (= (search_cost magazine in visualobject2) unknown)
        (= (search_cost magazine in visualobject_6_w) unknown)
        (= (search_cost magazine in visualobject_7_w) unknown)
        (= (search_cost magazine on visualobject0) unknown)
        (= (search_cost magazine on visualobject1) 30.0000)
        (= (search_cost magazine on visualobject2) unknown)
        (= (search_cost magazine on visualobject_6_w) unknown)
        (= (search_cost magazine on visualobject_7_w) unknown)
        (= (search_cost table in dummy-room) unknown)
        (= (search_cost table in room_0__a1) unknown)
        (= (search_cost table in visualobject0) unknown)
        (= (search_cost table in visualobject1) unknown)
        (= (search_cost table in visualobject2) unknown)
        (= (search_cost table in visualobject_6_w) unknown)
        (= (search_cost table in visualobject_7_w) unknown)
        (= (search_cost table on visualobject0) unknown)
        (= (search_cost table on visualobject1) unknown)
        (= (search_cost table on visualobject2) unknown)
        (= (search_cost table on visualobject_6_w) unknown)
        (= (search_cost table on visualobject_7_w) unknown)
        (= (unresponsive person_0__s) true)
        (connected place_0__b place_1__b)
        (connected place_0__b place_2__b)
        (connected place_0__b place_3__b)
        (connected place_1__b place_0__b)
        (connected place_1__b place_2__b)
        (connected place_1__b place_3__b)
        (connected place_1__b place_4__b)
        (connected place_1__b place_6__b)
        (connected place_2__b place_0__b)
        (connected place_2__b place_1__b)
        (connected place_3__b place_0__b)
        (connected place_3__b place_1__b)
        (connected place_3__b place_6__b)
        (connected place_4__b place_1__b)
        (connected place_4__b place_6__b)
        (connected place_4__b place_7__b)
        (connected place_6__b place_1__b)
        (connected place_6__b place_3__b)
        (connected place_6__b place_4__b)
        (connected place_7__b place_4__b)
        (is-virtual person0)
        (is-virtual visualobject0)
        (is-virtual visualobject1)
        (is-virtual visualobject2)
        (is-virtual visualobject_6_w)
        (is-virtual visualobject_7_w)
        (not (engaged person_0__s))
        (not (is-visited conegroup_0__l))
        (not (is-visited conegroup_1__l))
        (not (is-visited conegroup_2__l))
        (not (is-visited conegroup_3__l))
        (not (is-visited conegroup_4__l))
        (not (is-visited conegroup_5__l))
        (not (is-visited conegroup_6__l))
        (not (is-visited conegroup_7__l))
        (not (is-visited conegroup_8__l))
        (not (is-visited conegroup_9__l))
        (probabilistic  0.6982  (assign (leads_to_room place_4__b corridor) true))
        (probabilistic  0.3240  (assign (leads_to_room place_1__b office) true))
        (probabilistic  0.2000  (assign (contains-a-person-prior room_0__a1) true))
        (probabilistic  0.0027  (assign (is-in person_0__s) place_7__b)
                        0.0027  (assign (is-in person_0__s) place_6__b)
                        0.0027  (assign (is-in person_0__s) place_3__b)
                        0.0027  (assign (is-in person_0__s) place_4__b)
                        0.0010  (assign (is-in person_0__s) place_1__b)
                        0.0027  (assign (is-in person_0__s) place_2__b)
                        0.9839  (assign (is-in person_0__s) place_0__b)
        )
        (probabilistic  0.3548  (assign (leads_to_room place_4__b office) true))
        (probabilistic  0.0013  (assign (category room_0__a1) office)
                        0.1895  (assign (category room_0__a1) meetingroom)
                        0.8091  (assign (category room_0__a1) corridor)
        )
        (probabilistic  0.3497  (assign (leads_to_room place_2__b corridor) true))
        (probabilistic  0.0316  (assign (leads_to_room place_3__b meetingroom) true))
        (probabilistic  0.0316  (assign (leads_to_room place_3__b office) true))
        (probabilistic  0.7602  (assign (leads_to_room place_1__b corridor) true))
        (probabilistic  0.3548  (assign (leads_to_room place_4__b meetingroom) true))
        (probabilistic  0.1425  (assign (leads_to_room place_2__b office) true))
        (probabilistic  0.1425  (assign (leads_to_room place_2__b meetingroom) true))
        (probabilistic  )
        (probabilistic  )
        (probabilistic  0.9981  (assign (does-exist person_0__s) true))
        (probabilistic  )
        (probabilistic  0.3240  (assign (leads_to_room place_1__b meetingroom) true))
        (probabilistic  0.0710  (assign (leads_to_room place_3__b corridor) true))
        (probabilistic  )
        (probabilistic  )
        (probabilistic  )
)

(:goal  (and  (exists (?o - visualobject)  (kval robot_0__c (entity-exists visualobject_7_w)))
              (exists (?o - visualobject)  (kval robot_0__c (entity-exists visualobject_6_w)))
        )
)
(:metric minimize (total-cost ))

)
END_PROBLEM
END_PLAN
actions:
END_POPLAN
