package cast.cdl.guitypes;

/**
* cast/cdl/guitypes/Box3DHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from guitypes.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Box3DHolder implements org.omg.CORBA.portable.Streamable
{
  public cast.cdl.guitypes.Box3D value = null;

  public Box3DHolder ()
  {
  }

  public Box3DHolder (cast.cdl.guitypes.Box3D initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cast.cdl.guitypes.Box3DHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cast.cdl.guitypes.Box3DHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cast.cdl.guitypes.Box3DHelper.type ();
  }

}
