package cast.cdl.guitypes;


/**
* cast/cdl/guitypes/Frame3D.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from guitypes.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Frame3D implements org.omg.CORBA.portable.IDLEntity
{
  public double m_px = (double)0;
  public double m_py = (double)0;
  public double m_pz = (double)0;
  public double m_rx = (double)0;
  public double m_ry = (double)0;
  public double m_rz = (double)0;
  public cast.cdl.guitypes.RGBColor m_color = null;
  public int m_flags = (int)0;

  public Frame3D ()
  {
  } // ctor

  public Frame3D (double _m_px, double _m_py, double _m_pz, double _m_rx, double _m_ry, double _m_rz, cast.cdl.guitypes.RGBColor _m_color, int _m_flags)
  {
    m_px = _m_px;
    m_py = _m_py;
    m_pz = _m_pz;
    m_rx = _m_rx;
    m_ry = _m_ry;
    m_rz = _m_rz;
    m_color = _m_color;
    m_flags = _m_flags;
  } // ctor

} // class Frame3D
