package cast.cdl.guitypes;


/**
* cast/cdl/guitypes/Point3D.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from guitypes.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Point3D implements org.omg.CORBA.portable.IDLEntity
{
  public double m_x = (double)0;
  public double m_y = (double)0;
  public double m_z = (double)0;
  public cast.cdl.guitypes.RGBColor m_color = null;
  public int m_flags = (int)0;

  public Point3D ()
  {
  } // ctor

  public Point3D (double _m_x, double _m_y, double _m_z, cast.cdl.guitypes.RGBColor _m_color, int _m_flags)
  {
    m_x = _m_x;
    m_y = _m_y;
    m_z = _m_z;
    m_color = _m_color;
    m_flags = _m_flags;
  } // ctor

} // class Point3D
