package ComaData;


/**
* ComaData/ComaReasonerFunction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComaData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class ComaReasonerFunction implements org.omg.CORBA.portable.IDLEntity
{
  public ComaData.ComaReasonerFunctionType m_functiontype = null;
  public cast.cdl.WorkingMemoryPointer m_arg1ptr = null;
  public cast.cdl.WorkingMemoryPointer m_arg2ptr = null;
  public cast.cdl.WorkingMemoryPointer m_resultptr = null;
  public cast.cdl.WorkingMemoryPointer m_add_info_ptr = null;

  public ComaReasonerFunction ()
  {
  } // ctor

  public ComaReasonerFunction (ComaData.ComaReasonerFunctionType _m_functiontype, cast.cdl.WorkingMemoryPointer _m_arg1ptr, cast.cdl.WorkingMemoryPointer _m_arg2ptr, cast.cdl.WorkingMemoryPointer _m_resultptr, cast.cdl.WorkingMemoryPointer _m_add_info_ptr)
  {
    m_functiontype = _m_functiontype;
    m_arg1ptr = _m_arg1ptr;
    m_arg2ptr = _m_arg2ptr;
    m_resultptr = _m_resultptr;
    m_add_info_ptr = _m_add_info_ptr;
  } // ctor

} // class ComaReasonerFunction
