package ComaData;


/**
* ComaData/ComaRelation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComaData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class ComaRelation implements org.omg.CORBA.portable.IDLEntity
{
  public String m_namespace = null;
  public String m_sep = null;
  public String m_name = null;
  public cast.cdl.WorkingMemoryPointer m_ins1ptr = null;
  public cast.cdl.WorkingMemoryPointer m_ins2ptr = null;

  public ComaRelation ()
  {
  } // ctor

  public ComaRelation (String _m_namespace, String _m_sep, String _m_name, cast.cdl.WorkingMemoryPointer _m_ins1ptr, cast.cdl.WorkingMemoryPointer _m_ins2ptr)
  {
    m_namespace = _m_namespace;
    m_sep = _m_sep;
    m_name = _m_name;
    m_ins1ptr = _m_ins1ptr;
    m_ins2ptr = _m_ins2ptr;
  } // ctor

} // class ComaRelation
