package ComaData;


/**
* ComaData/ComaRelationListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComaData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


// typedef sequence < ComaRelation > ComaRelationList;
public final class ComaRelationListHolder implements org.omg.CORBA.portable.Streamable
{
  public cast.cdl.WorkingMemoryPointer value[] = null;

  public ComaRelationListHolder ()
  {
  }

  public ComaRelationListHolder (cast.cdl.WorkingMemoryPointer[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ComaData.ComaRelationListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ComaData.ComaRelationListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ComaData.ComaRelationListHelper.type ();
  }

}
