package ComaData;


/**
* ComaData/ComaConcept.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComaData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class ComaConcept implements org.omg.CORBA.portable.IDLEntity
{
  public String m_namespace = null;
  public String m_sep = null;
  public String m_name = null;

  public ComaConcept ()
  {
  } // ctor

  public ComaConcept (String _m_namespace, String _m_sep, String _m_name)
  {
    m_namespace = _m_namespace;
    m_sep = _m_sep;
    m_name = _m_name;
  } // ctor

} // class ComaConcept
