package Planner;

/**
* Planner/CCPStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Planner.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class CCPStateHolder implements org.omg.CORBA.portable.Streamable
{
  public Planner.CCPState value = null;

  public CCPStateHolder ()
  {
  }

  public CCPStateHolder (Planner.CCPState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Planner.CCPStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Planner.CCPStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Planner.CCPStateHelper.type ();
  }

}
