package Planner;


/**
* Planner/PlanningTaskHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Planner.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class PlanningTaskHelper
{
  private static String  _id = "IDL:Planner/PlanningTask:1.0";

  public static void insert (org.omg.CORBA.Any a, Planner.PlanningTask that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Planner.PlanningTask extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (Planner.TaskIDHelper.id (), "TaskID", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "task_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "planning_agent",
            _tcOf_members0,
            null);
          _tcOf_members0 = Planner.ObjectDeclarationHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (Planner.ObjectListHelper.id (), "ObjectList", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "objects",
            _tcOf_members0,
            null);
          _tcOf_members0 = Planner.FactHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (Planner.FactListHelper.id (), "FactList", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "facts",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (Planner.GoalHelper.id (), "Goal", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "goals",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "domain_name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "domain_fn",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Planner.PlanningTaskHelper.id (), "PlanningTask", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Planner.PlanningTask read (org.omg.CORBA.portable.InputStream istream)
  {
    Planner.PlanningTask value = new Planner.PlanningTask ();
    value.task_id = istream.read_string ();
    value.planning_agent = istream.read_string ();
    value.objects = Planner.ObjectListHelper.read (istream);
    value.facts = Planner.FactListHelper.read (istream);
    int _len0 = istream.read_long ();
    value.goals = new String[_len0];
    for (int _o1 = 0;_o1 < value.goals.length; ++_o1)
      value.goals[_o1] = Planner.GoalHelper.read (istream);
    value.domain_name = istream.read_string ();
    value.domain_fn = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Planner.PlanningTask value)
  {
    ostream.write_string (value.task_id);
    ostream.write_string (value.planning_agent);
    Planner.ObjectListHelper.write (ostream, value.objects);
    Planner.FactListHelper.write (ostream, value.facts);
    ostream.write_long (value.goals.length);
    for (int _i0 = 0;_i0 < value.goals.length; ++_i0)
      Planner.GoalHelper.write (ostream, value.goals[_i0]);
    ostream.write_string (value.domain_name);
    ostream.write_string (value.domain_fn);
  }

}
