INCLUDE(UniqueList)

MACRO (ADD_IDL _sources _headers _idlFile)

  GET_FILENAME_COMPONENT(idlName ${_idlFile} NAME_WE)
  GET_FILENAME_COMPONENT(idlPath ${_idlFile} PATH)

  EXTEND_LIST("-I${idlPath}" ALL_IDL)

      #SET(IDL_INCLUDE_ARGS "")
      #SPACE_LIST(ALL_IDL IDL_INCLUDE_ARGS)
      #MESSAGE("include args: ${IDL_INCLUDE_ARGS}")
      #SET(IDL_MAPPING_ARGS "")
      #SPACE_LIST(ALL_IDL_MAPPINGS IDL_MAPPING_ARGS)
      #MESSAGE("mapping args: ${IDL_MAPPING_ARGS}")

      #MESSAGE("${ARGN} -bcxx -Wba -Wbh=.hh -Wbs=.cc -Wbkeep_inc_path ${IDL_MAPPING_ARGS} ${IDL_INCLUDE_ARGS} -C${CMAKE_CURRENT_SOURCE_DIR} ${_idlFile}")
      
  ADD_CUSTOM_COMMAND(
      OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/${idlName}.hh 
      ${CMAKE_CURRENT_SOURCE_DIR}/${idlName}.cc 
      ${CMAKE_CURRENT_SOURCE_DIR}/${idlName}DynSK.cc
      COMMAND ${COSY_ROOT}/cosyidl.py
		#ARGS ${ARGN} -bcxx -Wba -Wbh=.hh -Wbs=.cc -Wbkeep_inc_path -I${OUTPUT}/include/idl -C${CMAKE_CURRENT_SOURCE_DIR} ${_idlFile}
		#ARGS ${ARGN} -bcxx -Wba -Wbh=.hh -Wbs=.cc -Wbkeep_inc_path ${IDL_MAPPING_ARGS} ${IDL_INCLUDE_ARGS} -C${CMAKE_CURRENT_SOURCE_DIR} ${_idlFile}
      ARGS ${ARGN} -bcxx -Wba -Wbh=.hh -Wbs=.cc -Wbkeep_inc_path ${ALL_IDL_MAPPINGS} ${ALL_IDL} -C${CMAKE_CURRENT_SOURCE_DIR} ${_idlFile}
		
      DEPENDS ${_idlFile}
  )
	
  SET(${_sources} ${${_sources}}
      ${CMAKE_CURRENT_SOURCE_DIR}/${idlName}.cc 
      ${CMAKE_CURRENT_SOURCE_DIR}/${idlName}DynSK.cc)
  
  SET(${_headers} ${${_headers}} ${idlName}.hh)
  
	
	

ENDMACRO (ADD_IDL)

# adds a mapping for autogenerated header files
# e.g. _module.idl becomes _path.hh
# so CAST.idl to cast/cdl/CAST.hh 
MACRO (ADD_IDL_MAPPING _module _path)



        #MESSAGE("-pn${_module}=${_path}")
EXTEND_LIST("-pn${_module}=${_path}" ALL_IDL_MAPPINGS)

	#MESSAGE("mappings")
	#FOREACH(MAP ${ALL_IDL_MAPPINGS})
	#	MESSAGE("map: " ${MAP})
	#ENDFOREACH(MAP ${ALL_IDL_MAPPINGS})

ENDMACRO (ADD_IDL_MAPPING _module _path)

