(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  person0 person1 - person
           room0 room1 room_0_91 - room
           book cerealbox magazine table - label
           robot_0__c - robot
           corridor meetingroom office - category
           visualobject0 visualobject1 visualobject2 visualobject3 visualobject4 - visualobject
           place_0__b place_1__b place_2__b place_4__b place_7__b place__b__b place__d__b - place
)

(:init  (= (associated-with person0) dummy-room)
        (= (associated-with person1) room_0_91)
        (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom magazine) 200.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on magazine table) 30.0000)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom cerealbox corridor) 0.0519)
        (= (dora__inroom cerealbox meetingroom) 0.0600)
        (= (dora__inroom cerealbox office) 0.0253)
        (= (dora__inroom magazine corridor) 0.0025)
        (= (dora__inroom magazine meetingroom) 0.8000)
        (= (dora__inroom magazine office) 0.1800)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__not_inroom book corridor) 0.9975)
        (= (dora__not_inroom book meetingroom) 0.9846)
        (= (dora__not_inroom book office) 0.8715)
        (= (dora__not_inroom cerealbox corridor) 0.9481)
        (= (dora__not_inroom cerealbox meetingroom) 0.9400)
        (= (dora__not_inroom cerealbox office) 0.9747)
        (= (dora__not_inroom magazine corridor) 0.9975)
        (= (dora__not_inroom magazine meetingroom) 0.2000)
        (= (dora__not_inroom magazine office) 0.8200)
        (= (dora__not_inroom table corridor) 0.9406)
        (= (dora__not_inroom table meetingroom) 0.8958)
        (= (dora__not_inroom table office) 0.4800)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on magazine table corridor) 0.0300)
        (= (dora__on magazine table meetingroom) 0.8000)
        (= (dora__on magazine table office) 0.1000)
        (= (entity-exists place_0__b) true)
        (= (entity-exists place_1__b) true)
        (= (entity-exists place_2__b) true)
        (= (entity-exists place_4__b) true)
        (= (entity-exists place_7__b) true)
        (= (entity-exists place__b__b) true)
        (= (entity-exists place__d__b) true)
        (= (entity-exists robot_0__c) true)
        (= (entity-exists room_0_91) true)
        (= (in-room place_0__b) room_0_91)
        (= (in-room place_1__b) room_0_91)
        (= (in-room place_2__b) room_0_91)
        (= (in-room place_4__b) room_0_91)
        (= (is-in robot_0__c) place_7__b)
        (= (label visualobject0) container)
        (= (label visualobject1) book)
        (= (label visualobject2) cerealbox)
        (= (label visualobject3) magazine)
        (= (label visualobject4) table)
        (= (p-obj_exists cerealbox in room_0_91 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_0_91 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_0_91 office) 0.0253)
        (= (p-obj_exists magazine in room_0_91 corridor) 0.0025)
        (= (p-obj_exists magazine in room_0_91 meetingroom) 0.8000)
        (= (p-obj_exists magazine in room_0_91 office) 0.1800)
        (= (placestatus place_0__b) trueplace)
        (= (placestatus place_1__b) trueplace)
        (= (placestatus place_2__b) trueplace)
        (= (placestatus place_4__b) trueplace)
        (= (placestatus place_7__b) trueplace)
        (= (placestatus place__b__b) placeholder)
        (= (placestatus place__d__b) placeholder)
        (= (related-to visualobject0) unknown)
        (= (related-to visualobject1) unknown)
        (= (related-to visualobject2) unknown)
        (= (related-to visualobject3) unknown)
        (= (related-to visualobject4) unknown)
        (= (roomid room_0_91) 0)
        (= (search_cost book in dummy-room) 200.0000)
        (= (search_cost book in room0) 200.0000)
        (= (search_cost book in room1) 200.0000)
        (= (search_cost book in room_0_91) 200.0000)
        (= (search_cost book in visualobject0) unknown)
        (= (search_cost book in visualobject1) unknown)
        (= (search_cost book in visualobject2) unknown)
        (= (search_cost book in visualobject3) unknown)
        (= (search_cost book in visualobject4) unknown)
        (= (search_cost book on visualobject0) unknown)
        (= (search_cost book on visualobject1) unknown)
        (= (search_cost book on visualobject2) unknown)
        (= (search_cost book on visualobject3) unknown)
        (= (search_cost book on visualobject4) 30.0000)
        (= (search_cost cerealbox in dummy-room) 200.0000)
        (= (search_cost cerealbox in room0) 200.0000)
        (= (search_cost cerealbox in room1) 200.0000)
        (= (search_cost cerealbox in room_0_91) 200.0000)
        (= (search_cost cerealbox in visualobject0) unknown)
        (= (search_cost cerealbox in visualobject1) unknown)
        (= (search_cost cerealbox in visualobject2) unknown)
        (= (search_cost cerealbox in visualobject3) unknown)
        (= (search_cost cerealbox in visualobject4) unknown)
        (= (search_cost cerealbox on visualobject0) unknown)
        (= (search_cost cerealbox on visualobject1) unknown)
        (= (search_cost cerealbox on visualobject2) unknown)
        (= (search_cost cerealbox on visualobject3) unknown)
        (= (search_cost cerealbox on visualobject4) 30.0000)
        (= (search_cost container in dummy-room) unknown)
        (= (search_cost container in room0) unknown)
        (= (search_cost container in room1) unknown)
        (= (search_cost container in room_0_91) unknown)
        (= (search_cost container in visualobject0) unknown)
        (= (search_cost container in visualobject1) unknown)
        (= (search_cost container in visualobject2) unknown)
        (= (search_cost container in visualobject3) unknown)
        (= (search_cost container in visualobject4) unknown)
        (= (search_cost container on visualobject0) unknown)
        (= (search_cost container on visualobject1) unknown)
        (= (search_cost container on visualobject2) unknown)
        (= (search_cost container on visualobject3) unknown)
        (= (search_cost container on visualobject4) unknown)
        (= (search_cost magazine in dummy-room) 200.0000)
        (= (search_cost magazine in room0) 200.0000)
        (= (search_cost magazine in room1) 200.0000)
        (= (search_cost magazine in room_0_91) 200.0000)
        (= (search_cost magazine in visualobject0) unknown)
        (= (search_cost magazine in visualobject1) unknown)
        (= (search_cost magazine in visualobject2) unknown)
        (= (search_cost magazine in visualobject3) unknown)
        (= (search_cost magazine in visualobject4) unknown)
        (= (search_cost magazine on visualobject0) unknown)
        (= (search_cost magazine on visualobject1) unknown)
        (= (search_cost magazine on visualobject2) unknown)
        (= (search_cost magazine on visualobject3) unknown)
        (= (search_cost magazine on visualobject4) 30.0000)
        (= (search_cost table in dummy-room) unknown)
        (= (search_cost table in room0) unknown)
        (= (search_cost table in room1) unknown)
        (= (search_cost table in room_0_91) unknown)
        (= (search_cost table in visualobject0) unknown)
        (= (search_cost table in visualobject1) unknown)
        (= (search_cost table in visualobject2) unknown)
        (= (search_cost table in visualobject3) unknown)
        (= (search_cost table in visualobject4) unknown)
        (= (search_cost table on visualobject0) unknown)
        (= (search_cost table on visualobject1) unknown)
        (= (search_cost table on visualobject2) unknown)
        (= (search_cost table on visualobject3) unknown)
        (= (search_cost table on visualobject4) unknown)
        (= (virtual-place room0) place__b__b)
        (= (virtual-place room1) place__d__b)
        (connected place_0__b place_1__b)
        (connected place_0__b place_2__b)
        (connected place_1__b place_0__b)
        (connected place_1__b place_2__b)
        (connected place_2__b place_0__b)
        (connected place_2__b place_1__b)
        (connected place_2__b place_4__b)
        (connected place_4__b place_2__b)
        (connected place_4__b place_7__b)
        (connected place_7__b place_4__b)
        (connected place_7__b place__b__b)
        (connected place_7__b place__d__b)
        (is-virtual person0)
        (is-virtual person1)
        (is-virtual room0)
        (is-virtual room1)
        (is-virtual visualobject0)
        (is-virtual visualobject1)
        (is-virtual visualobject2)
        (is-virtual visualobject3)
        (is-virtual visualobject4)
        (probabilistic  0.2574  (assign (leads_to_room place__b__b office) true))
        (probabilistic  0.2574  (assign (leads_to_room place__d__b office) true))
        (probabilistic  0.2631  (assign (leads_to_room place_4__b office) true))
        (probabilistic  0.0228  (assign (category room_0_91) meetingroom)
                        0.0245  (assign (category room_0_91) corridor)
                        0.9527  (assign (category room_0_91) office)
        )
        (probabilistic  0.2000  (assign (contains-a-person-prior room_0_91) true))
        (probabilistic  0.2574  (assign (leads_to_room place__b__b meetingroom) true))
        (probabilistic  0.0297  (assign (leads_to_room place_1__b meetingroom) true))
        (probabilistic  0.2631  (assign (leads_to_room place_4__b meetingroom) true))
        (probabilistic  0.8838  (assign (leads_to_room place__d__b corridor) true))
        (probabilistic  0.2908  (assign (leads_to_room place_2__b office) true))
        (probabilistic  0.8731  (assign (leads_to_room place_4__b corridor) true))
        (probabilistic  0.0745  (assign (leads_to_room place_1__b corridor) true))
        (probabilistic  0.8838  (assign (leads_to_room place__b__b corridor) true))
        (probabilistic  0.8214  (assign (leads_to_room place_2__b corridor) true))
        (probabilistic  0.2574  (assign (leads_to_room place__d__b meetingroom) true))
        (probabilistic  0.0297  (assign (leads_to_room place_1__b office) true))
        (probabilistic  0.2908  (assign (leads_to_room place_2__b meetingroom) true))
)

(:goal  (and  (exists (?p - person)  (kval robot_0__c (is-in ?p)))))
(:metric minimize (total-cost ))

)
END_PROBLEM
(init ), EXECUTED
(__commit-contains-a-person-prior-room_0_91-true robot_0__c), EXECUTED
(__commit-person_in_room-0 robot_0__c person1 place_4__b room_0_91), EXECUTED
(move robot_0__c place_4__b place_7__b), FAILED
(look-for-people robot_0__c place_4__b room_0_91 person1), EXECUTABLE
(goal ), EXECUTABLE
END_PLAN
actions:
0: SUCCEEDED init 
1: SUCCEEDED __commit-contains-a-person-prior-room_0_91-true 0:C@spatial.sa
2: SUCCEEDED __commit-person_in_room-0 0:C@spatial.sa person1 4:B@spatial.sa 0:91@coma
3: FAILED move 0:C@spatial.sa 4:B@spatial.sa 7:B@spatial.sa
4: PENDING look-for-people 0:C@spatial.sa 4:B@spatial.sa 0:91@coma person1
5: PENDING goal 
links:
1 2 DEPENDS contains-a-person-prior 0:91@coma MODALITY: poss true VALUE: true
1 3 THREATENS started  VALUE: true
4 5 DEPENDS is-in person1 MODALITY: kd 0:C@spatial.sa VALUE: true
3 4 DEPENDS is-in 0:C@spatial.sa VALUE: 4:B@spatial.sa
3 4 DEPENDS in-room 4:B@spatial.sa MODALITY: kval 0:C@spatial.sa VALUE: true
2 4 DEPENDS is-in person1 MODALITY: poss 4:B@spatial.sa VALUE: true
2 3 THREATENS started  VALUE: true
0 4 DEPENDS done  VALUE: false
0 4 DEPENDS not_fully_explored 0:91@coma VALUE: false
0 4 DEPENDS in-room 4:B@spatial.sa MODALITY: poss 0:91@coma VALUE: true
0 1 DEPENDS contains-a-person-prior 0:91@coma MODALITY: committed  VALUE: false
0 1 DEPENDS started  VALUE: false
0 3 DEPENDS is-in 0:C@spatial.sa VALUE: 7:B@spatial.sa
0 3 DEPENDS done  VALUE: false
0 3 DEPENDS connected 7:B@spatial.sa 4:B@spatial.sa VALUE: true
0 2 DEPENDS associated-with person1 VALUE: 0:91@coma
0 2 DEPENDS is-in person1 MODALITY: committed  VALUE: false
0 2 DEPENDS is-virtual person1 VALUE: true
0 2 DEPENDS started  VALUE: false
0 2 DEPENDS in-room 4:B@spatial.sa MODALITY: poss 0:91@coma VALUE: true
END_POPLAN
(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  person0 person1 - person
           room0 room1 room_0_91 - room
           book cerealbox magazine table - label
           robot_0__c - robot
           corridor meetingroom office - category
           visualobject0 visualobject1 visualobject2 visualobject3 visualobject4 - visualobject
           place_0__b place_1__b place_2__b place_4__b place_7__b place__b__b place__d__b - place
)

(:init  (= (associated-with person0) dummy-room)
        (= (associated-with person1) room_0_91)
        (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom magazine) 200.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on magazine table) 30.0000)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom cerealbox corridor) 0.0519)
        (= (dora__inroom cerealbox meetingroom) 0.0600)
        (= (dora__inroom cerealbox office) 0.0253)
        (= (dora__inroom magazine corridor) 0.0025)
        (= (dora__inroom magazine meetingroom) 0.8000)
        (= (dora__inroom magazine office) 0.1800)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__not_inroom book corridor) 0.9975)
        (= (dora__not_inroom book meetingroom) 0.9846)
        (= (dora__not_inroom book office) 0.8715)
        (= (dora__not_inroom cerealbox corridor) 0.9481)
        (= (dora__not_inroom cerealbox meetingroom) 0.9400)
        (= (dora__not_inroom cerealbox office) 0.9747)
        (= (dora__not_inroom magazine corridor) 0.9975)
        (= (dora__not_inroom magazine meetingroom) 0.2000)
        (= (dora__not_inroom magazine office) 0.8200)
        (= (dora__not_inroom table corridor) 0.9406)
        (= (dora__not_inroom table meetingroom) 0.8958)
        (= (dora__not_inroom table office) 0.4800)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on magazine table corridor) 0.0300)
        (= (dora__on magazine table meetingroom) 0.8000)
        (= (dora__on magazine table office) 0.1000)
        (= (entity-exists place_0__b) true)
        (= (entity-exists place_1__b) true)
        (= (entity-exists place_2__b) true)
        (= (entity-exists place_4__b) true)
        (= (entity-exists place_7__b) true)
        (= (entity-exists place__b__b) true)
        (= (entity-exists place__d__b) true)
        (= (entity-exists robot_0__c) true)
        (= (entity-exists room_0_91) true)
        (= (in-room place_0__b) room_0_91)
        (= (in-room place_1__b) room_0_91)
        (= (in-room place_2__b) room_0_91)
        (= (in-room place_4__b) room_0_91)
        (= (is-in robot_0__c) place_7__b)
        (= (label visualobject0) container)
        (= (label visualobject1) book)
        (= (label visualobject2) cerealbox)
        (= (label visualobject3) magazine)
        (= (label visualobject4) table)
        (= (p-obj_exists cerealbox in room_0_91 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_0_91 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_0_91 office) 0.0253)
        (= (p-obj_exists magazine in room_0_91 corridor) 0.0025)
        (= (p-obj_exists magazine in room_0_91 meetingroom) 0.8000)
        (= (p-obj_exists magazine in room_0_91 office) 0.1800)
        (= (placestatus place_0__b) trueplace)
        (= (placestatus place_1__b) trueplace)
        (= (placestatus place_2__b) trueplace)
        (= (placestatus place_4__b) trueplace)
        (= (placestatus place_7__b) trueplace)
        (= (placestatus place__b__b) placeholder)
        (= (placestatus place__d__b) placeholder)
        (= (related-to visualobject0) unknown)
        (= (related-to visualobject1) unknown)
        (= (related-to visualobject2) unknown)
        (= (related-to visualobject3) unknown)
        (= (related-to visualobject4) unknown)
        (= (roomid room_0_91) 0)
        (= (search_cost book in dummy-room) 200.0000)
        (= (search_cost book in room0) 200.0000)
        (= (search_cost book in room1) 200.0000)
        (= (search_cost book in room_0_91) 200.0000)
        (= (search_cost book in visualobject0) unknown)
        (= (search_cost book in visualobject1) unknown)
        (= (search_cost book in visualobject2) unknown)
        (= (search_cost book in visualobject3) unknown)
        (= (search_cost book in visualobject4) unknown)
        (= (search_cost book on visualobject0) unknown)
        (= (search_cost book on visualobject1) unknown)
        (= (search_cost book on visualobject2) unknown)
        (= (search_cost book on visualobject3) unknown)
        (= (search_cost book on visualobject4) 30.0000)
        (= (search_cost cerealbox in dummy-room) 200.0000)
        (= (search_cost cerealbox in room0) 200.0000)
        (= (search_cost cerealbox in room1) 200.0000)
        (= (search_cost cerealbox in room_0_91) 200.0000)
        (= (search_cost cerealbox in visualobject0) unknown)
        (= (search_cost cerealbox in visualobject1) unknown)
        (= (search_cost cerealbox in visualobject2) unknown)
        (= (search_cost cerealbox in visualobject3) unknown)
        (= (search_cost cerealbox in visualobject4) unknown)
        (= (search_cost cerealbox on visualobject0) unknown)
        (= (search_cost cerealbox on visualobject1) unknown)
        (= (search_cost cerealbox on visualobject2) unknown)
        (= (search_cost cerealbox on visualobject3) unknown)
        (= (search_cost cerealbox on visualobject4) 30.0000)
        (= (search_cost container in dummy-room) unknown)
        (= (search_cost container in room0) unknown)
        (= (search_cost container in room1) unknown)
        (= (search_cost container in room_0_91) unknown)
        (= (search_cost container in visualobject0) unknown)
        (= (search_cost container in visualobject1) unknown)
        (= (search_cost container in visualobject2) unknown)
        (= (search_cost container in visualobject3) unknown)
        (= (search_cost container in visualobject4) unknown)
        (= (search_cost container on visualobject0) unknown)
        (= (search_cost container on visualobject1) unknown)
        (= (search_cost container on visualobject2) unknown)
        (= (search_cost container on visualobject3) unknown)
        (= (search_cost container on visualobject4) unknown)
        (= (search_cost magazine in dummy-room) 200.0000)
        (= (search_cost magazine in room0) 200.0000)
        (= (search_cost magazine in room1) 200.0000)
        (= (search_cost magazine in room_0_91) 200.0000)
        (= (search_cost magazine in visualobject0) unknown)
        (= (search_cost magazine in visualobject1) unknown)
        (= (search_cost magazine in visualobject2) unknown)
        (= (search_cost magazine in visualobject3) unknown)
        (= (search_cost magazine in visualobject4) unknown)
        (= (search_cost magazine on visualobject0) unknown)
        (= (search_cost magazine on visualobject1) unknown)
        (= (search_cost magazine on visualobject2) unknown)
        (= (search_cost magazine on visualobject3) unknown)
        (= (search_cost magazine on visualobject4) 30.0000)
        (= (search_cost table in dummy-room) unknown)
        (= (search_cost table in room0) unknown)
        (= (search_cost table in room1) unknown)
        (= (search_cost table in room_0_91) unknown)
        (= (search_cost table in visualobject0) unknown)
        (= (search_cost table in visualobject1) unknown)
        (= (search_cost table in visualobject2) unknown)
        (= (search_cost table in visualobject3) unknown)
        (= (search_cost table in visualobject4) unknown)
        (= (search_cost table on visualobject0) unknown)
        (= (search_cost table on visualobject1) unknown)
        (= (search_cost table on visualobject2) unknown)
        (= (search_cost table on visualobject3) unknown)
        (= (search_cost table on visualobject4) unknown)
        (= (virtual-place room0) place__b__b)
        (= (virtual-place room1) place__d__b)
        (connected place_0__b place_1__b)
        (connected place_0__b place_2__b)
        (connected place_1__b place_0__b)
        (connected place_1__b place_2__b)
        (connected place_2__b place_0__b)
        (connected place_2__b place_1__b)
        (connected place_2__b place_4__b)
        (connected place_4__b place_2__b)
        (connected place_4__b place_7__b)
        (connected place_7__b place_4__b)
        (connected place_7__b place__b__b)
        (connected place_7__b place__d__b)
        (is-virtual person0)
        (is-virtual person1)
        (is-virtual room0)
        (is-virtual room1)
        (is-virtual visualobject0)
        (is-virtual visualobject1)
        (is-virtual visualobject2)
        (is-virtual visualobject3)
        (is-virtual visualobject4)
        (probabilistic  0.2574  (assign (leads_to_room place__b__b office) true))
        (probabilistic  0.2574  (assign (leads_to_room place__d__b office) true))
        (probabilistic  0.2631  (assign (leads_to_room place_4__b office) true))
        (probabilistic  0.0228  (assign (category room_0_91) meetingroom)
                        0.0245  (assign (category room_0_91) corridor)
                        0.9527  (assign (category room_0_91) office)
        )
        (probabilistic  0.2000  (assign (contains-a-person-prior room_0_91) true))
        (probabilistic  0.2574  (assign (leads_to_room place__b__b meetingroom) true))
        (probabilistic  0.0297  (assign (leads_to_room place_1__b meetingroom) true))
        (probabilistic  0.2631  (assign (leads_to_room place_4__b meetingroom) true))
        (probabilistic  0.8838  (assign (leads_to_room place__d__b corridor) true))
        (probabilistic  0.2908  (assign (leads_to_room place_2__b office) true))
        (probabilistic  0.8731  (assign (leads_to_room place_4__b corridor) true))
        (probabilistic  0.0745  (assign (leads_to_room place_1__b corridor) true))
        (probabilistic  0.8838  (assign (leads_to_room place__b__b corridor) true))
        (probabilistic  0.8214  (assign (leads_to_room place_2__b corridor) true))
        (probabilistic  0.2574  (assign (leads_to_room place__d__b meetingroom) true))
        (probabilistic  0.0297  (assign (leads_to_room place_1__b office) true))
        (probabilistic  0.2908  (assign (leads_to_room place_2__b meetingroom) true))
)

(:goal  (and  (exists (?p - person)  (kval robot_0__c (is-in ?p)))))
(:metric minimize (total-cost ))

)
END_PROBLEM
(init ), EXECUTED
(__commit-contains-a-person-prior-room_0_91-true robot_0__c), EXECUTED
(__commit-person_in_room-0 robot_0__c person1 place_4__b room_0_91), EXECUTED
(move robot_0__c place_4__b place_7__b), FAILED
(look-for-people robot_0__c place_4__b room_0_91 person1), EXECUTABLE
(goal ), EXECUTABLE
END_PLAN
actions:
0: SUCCEEDED init 
1: SUCCEEDED __commit-contains-a-person-prior-room_0_91-true 0:C@spatial.sa
2: SUCCEEDED __commit-person_in_room-0 0:C@spatial.sa person1 4:B@spatial.sa 0:91@coma
3: FAILED move 0:C@spatial.sa 4:B@spatial.sa 7:B@spatial.sa
4: PENDING look-for-people 0:C@spatial.sa 4:B@spatial.sa 0:91@coma person1
5: PENDING goal 
links:
1 2 DEPENDS contains-a-person-prior 0:91@coma MODALITY: poss true VALUE: true
1 3 THREATENS started  VALUE: true
4 5 DEPENDS is-in person1 MODALITY: kd 0:C@spatial.sa VALUE: true
3 4 DEPENDS is-in 0:C@spatial.sa VALUE: 4:B@spatial.sa
3 4 DEPENDS in-room 4:B@spatial.sa MODALITY: kval 0:C@spatial.sa VALUE: true
2 3 THREATENS started  VALUE: true
2 4 DEPENDS is-in person1 MODALITY: poss 4:B@spatial.sa VALUE: true
0 1 DEPENDS contains-a-person-prior 0:91@coma MODALITY: committed  VALUE: false
0 1 DEPENDS started  VALUE: false
0 4 DEPENDS done  VALUE: false
0 4 DEPENDS not_fully_explored 0:91@coma VALUE: false
0 4 DEPENDS in-room 4:B@spatial.sa MODALITY: poss 0:91@coma VALUE: true
0 3 DEPENDS is-in 0:C@spatial.sa VALUE: 7:B@spatial.sa
0 3 DEPENDS done  VALUE: false
0 3 DEPENDS connected 7:B@spatial.sa 4:B@spatial.sa VALUE: true
0 2 DEPENDS associated-with person1 VALUE: 0:91@coma
0 2 DEPENDS is-in person1 MODALITY: committed  VALUE: false
0 2 DEPENDS is-virtual person1 VALUE: true
0 2 DEPENDS started  VALUE: false
0 2 DEPENDS in-room 4:B@spatial.sa MODALITY: poss 0:91@coma VALUE: true
END_POPLAN
(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  person0 person1 - person
           room0 room1 room_0_91 - room
           book cerealbox magazine table - label
           robot_0__c - robot
           corridor meetingroom office - category
           visualobject0 visualobject1 visualobject2 visualobject3 visualobject4 - visualobject
           place_0__b place_1__b place_2__b place_4__b place_7__b place__b__b place__d__b - place
)

(:init  (= (associated-with person0) dummy-room)
        (= (associated-with person1) room_0_91)
        (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom magazine) 200.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on magazine table) 30.0000)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom cerealbox corridor) 0.0519)
        (= (dora__inroom cerealbox meetingroom) 0.0600)
        (= (dora__inroom cerealbox office) 0.0253)
        (= (dora__inroom magazine corridor) 0.0025)
        (= (dora__inroom magazine meetingroom) 0.8000)
        (= (dora__inroom magazine office) 0.1800)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__not_inroom book corridor) 0.9975)
        (= (dora__not_inroom book meetingroom) 0.9846)
        (= (dora__not_inroom book office) 0.8715)
        (= (dora__not_inroom cerealbox corridor) 0.9481)
        (= (dora__not_inroom cerealbox meetingroom) 0.9400)
        (= (dora__not_inroom cerealbox office) 0.9747)
        (= (dora__not_inroom magazine corridor) 0.9975)
        (= (dora__not_inroom magazine meetingroom) 0.2000)
        (= (dora__not_inroom magazine office) 0.8200)
        (= (dora__not_inroom table corridor) 0.9406)
        (= (dora__not_inroom table meetingroom) 0.8958)
        (= (dora__not_inroom table office) 0.4800)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on magazine table corridor) 0.0300)
        (= (dora__on magazine table meetingroom) 0.8000)
        (= (dora__on magazine table office) 0.1000)
        (= (entity-exists place_0__b) true)
        (= (entity-exists place_1__b) true)
        (= (entity-exists place_2__b) true)
        (= (entity-exists place_4__b) true)
        (= (entity-exists place_7__b) true)
        (= (entity-exists place__b__b) true)
        (= (entity-exists place__d__b) true)
        (= (entity-exists robot_0__c) true)
        (= (entity-exists room_0_91) true)
        (= (in-room place_0__b) room_0_91)
        (= (in-room place_1__b) room_0_91)
        (= (in-room place_2__b) room_0_91)
        (= (in-room place_4__b) room_0_91)
        (= (is-in robot_0__c) place_7__b)
        (= (label visualobject0) container)
        (= (label visualobject1) book)
        (= (label visualobject2) cerealbox)
        (= (label visualobject3) magazine)
        (= (label visualobject4) table)
        (= (p-obj_exists cerealbox in room_0_91 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_0_91 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_0_91 office) 0.0253)
        (= (p-obj_exists magazine in room_0_91 corridor) 0.0025)
        (= (p-obj_exists magazine in room_0_91 meetingroom) 0.8000)
        (= (p-obj_exists magazine in room_0_91 office) 0.1800)
        (= (placestatus place_0__b) trueplace)
        (= (placestatus place_1__b) trueplace)
        (= (placestatus place_2__b) trueplace)
        (= (placestatus place_4__b) trueplace)
        (= (placestatus place_7__b) trueplace)
        (= (placestatus place__b__b) placeholder)
        (= (placestatus place__d__b) placeholder)
        (= (related-to visualobject0) unknown)
        (= (related-to visualobject1) unknown)
        (= (related-to visualobject2) unknown)
        (= (related-to visualobject3) unknown)
        (= (related-to visualobject4) unknown)
        (= (roomid room_0_91) 0)
        (= (search_cost book in dummy-room) 200.0000)
        (= (search_cost book in room0) 200.0000)
        (= (search_cost book in room1) 200.0000)
        (= (search_cost book in room_0_91) 200.0000)
        (= (search_cost book in visualobject0) unknown)
        (= (search_cost book in visualobject1) unknown)
        (= (search_cost book in visualobject2) unknown)
        (= (search_cost book in visualobject3) unknown)
        (= (search_cost book in visualobject4) unknown)
        (= (search_cost book on visualobject0) unknown)
        (= (search_cost book on visualobject1) unknown)
        (= (search_cost book on visualobject2) unknown)
        (= (search_cost book on visualobject3) unknown)
        (= (search_cost book on visualobject4) 30.0000)
        (= (search_cost cerealbox in dummy-room) 200.0000)
        (= (search_cost cerealbox in room0) 200.0000)
        (= (search_cost cerealbox in room1) 200.0000)
        (= (search_cost cerealbox in room_0_91) 200.0000)
        (= (search_cost cerealbox in visualobject0) unknown)
        (= (search_cost cerealbox in visualobject1) unknown)
        (= (search_cost cerealbox in visualobject2) unknown)
        (= (search_cost cerealbox in visualobject3) unknown)
        (= (search_cost cerealbox in visualobject4) unknown)
        (= (search_cost cerealbox on visualobject0) unknown)
        (= (search_cost cerealbox on visualobject1) unknown)
        (= (search_cost cerealbox on visualobject2) unknown)
        (= (search_cost cerealbox on visualobject3) unknown)
        (= (search_cost cerealbox on visualobject4) 30.0000)
        (= (search_cost container in dummy-room) unknown)
        (= (search_cost container in room0) unknown)
        (= (search_cost container in room1) unknown)
        (= (search_cost container in room_0_91) unknown)
        (= (search_cost container in visualobject0) unknown)
        (= (search_cost container in visualobject1) unknown)
        (= (search_cost container in visualobject2) unknown)
        (= (search_cost container in visualobject3) unknown)
        (= (search_cost container in visualobject4) unknown)
        (= (search_cost container on visualobject0) unknown)
        (= (search_cost container on visualobject1) unknown)
        (= (search_cost container on visualobject2) unknown)
        (= (search_cost container on visualobject3) unknown)
        (= (search_cost container on visualobject4) unknown)
        (= (search_cost magazine in dummy-room) 200.0000)
        (= (search_cost magazine in room0) 200.0000)
        (= (search_cost magazine in room1) 200.0000)
        (= (search_cost magazine in room_0_91) 200.0000)
        (= (search_cost magazine in visualobject0) unknown)
        (= (search_cost magazine in visualobject1) unknown)
        (= (search_cost magazine in visualobject2) unknown)
        (= (search_cost magazine in visualobject3) unknown)
        (= (search_cost magazine in visualobject4) unknown)
        (= (search_cost magazine on visualobject0) unknown)
        (= (search_cost magazine on visualobject1) unknown)
        (= (search_cost magazine on visualobject2) unknown)
        (= (search_cost magazine on visualobject3) unknown)
        (= (search_cost magazine on visualobject4) 30.0000)
        (= (search_cost table in dummy-room) unknown)
        (= (search_cost table in room0) unknown)
        (= (search_cost table in room1) unknown)
        (= (search_cost table in room_0_91) unknown)
        (= (search_cost table in visualobject0) unknown)
        (= (search_cost table in visualobject1) unknown)
        (= (search_cost table in visualobject2) unknown)
        (= (search_cost table in visualobject3) unknown)
        (= (search_cost table in visualobject4) unknown)
        (= (search_cost table on visualobject0) unknown)
        (= (search_cost table on visualobject1) unknown)
        (= (search_cost table on visualobject2) unknown)
        (= (search_cost table on visualobject3) unknown)
        (= (search_cost table on visualobject4) unknown)
        (= (virtual-place room0) place__b__b)
        (= (virtual-place room1) place__d__b)
        (connected place_0__b place_1__b)
        (connected place_0__b place_2__b)
        (connected place_1__b place_0__b)
        (connected place_1__b place_2__b)
        (connected place_2__b place_0__b)
        (connected place_2__b place_1__b)
        (connected place_2__b place_4__b)
        (connected place_4__b place_2__b)
        (connected place_4__b place_7__b)
        (connected place_7__b place_4__b)
        (connected place_7__b place__b__b)
        (connected place_7__b place__d__b)
        (is-virtual person0)
        (is-virtual person1)
        (is-virtual room0)
        (is-virtual room1)
        (is-virtual visualobject0)
        (is-virtual visualobject1)
        (is-virtual visualobject2)
        (is-virtual visualobject3)
        (is-virtual visualobject4)
        (probabilistic  0.2574  (assign (leads_to_room place__b__b office) true))
        (probabilistic  0.2574  (assign (leads_to_room place__d__b office) true))
        (probabilistic  0.2631  (assign (leads_to_room place_4__b office) true))
        (probabilistic  0.0228  (assign (category room_0_91) meetingroom)
                        0.0245  (assign (category room_0_91) corridor)
                        0.9527  (assign (category room_0_91) office)
        )
        (probabilistic  0.2000  (assign (contains-a-person-prior room_0_91) true))
        (probabilistic  0.2574  (assign (leads_to_room place__b__b meetingroom) true))
        (probabilistic  0.0297  (assign (leads_to_room place_1__b meetingroom) true))
        (probabilistic  0.2631  (assign (leads_to_room place_4__b meetingroom) true))
        (probabilistic  0.8838  (assign (leads_to_room place__d__b corridor) true))
        (probabilistic  0.2908  (assign (leads_to_room place_2__b office) true))
        (probabilistic  0.8731  (assign (leads_to_room place_4__b corridor) true))
        (probabilistic  0.0745  (assign (leads_to_room place_1__b corridor) true))
        (probabilistic  0.8838  (assign (leads_to_room place__b__b corridor) true))
        (probabilistic  0.8214  (assign (leads_to_room place_2__b corridor) true))
        (probabilistic  0.2574  (assign (leads_to_room place__d__b meetingroom) true))
        (probabilistic  0.0297  (assign (leads_to_room place_1__b office) true))
        (probabilistic  0.2908  (assign (leads_to_room place_2__b meetingroom) true))
)

(:goal  (and  (exists (?p - person)  (kval robot_0__c (is-in ?p)))))
(:metric minimize (total-cost ))

)
END_PROBLEM
(init ), EXECUTED
(__commit-contains-a-person-prior-room_0_91-true robot_0__c), EXECUTED
(__commit-person_in_room-0 robot_0__c person1 place_4__b room_0_91), EXECUTED
(move robot_0__c place_4__b place_7__b), FAILED
(look-for-people robot_0__c place_4__b room_0_91 person1), EXECUTABLE
(goal ), EXECUTABLE
END_PLAN
actions:
0: SUCCEEDED init 
1: SUCCEEDED __commit-contains-a-person-prior-room_0_91-true 0:C@spatial.sa
2: SUCCEEDED __commit-person_in_room-0 0:C@spatial.sa person1 4:B@spatial.sa 0:91@coma
3: FAILED move 0:C@spatial.sa 4:B@spatial.sa 7:B@spatial.sa
4: PENDING look-for-people 0:C@spatial.sa 4:B@spatial.sa 0:91@coma person1
5: PENDING goal 
links:
3 4 DEPENDS is-in 0:C@spatial.sa VALUE: 4:B@spatial.sa
3 4 DEPENDS in-room 4:B@spatial.sa MODALITY: kval 0:C@spatial.sa VALUE: true
2 3 THREATENS started  VALUE: true
2 4 DEPENDS is-in person1 MODALITY: poss 4:B@spatial.sa VALUE: true
1 2 DEPENDS contains-a-person-prior 0:91@coma MODALITY: poss true VALUE: true
1 3 THREATENS started  VALUE: true
4 5 DEPENDS is-in person1 MODALITY: kd 0:C@spatial.sa VALUE: true
0 2 DEPENDS associated-with person1 VALUE: 0:91@coma
0 2 DEPENDS is-in person1 MODALITY: committed  VALUE: false
0 2 DEPENDS is-virtual person1 VALUE: true
0 2 DEPENDS started  VALUE: false
0 2 DEPENDS in-room 4:B@spatial.sa MODALITY: poss 0:91@coma VALUE: true
0 4 DEPENDS done  VALUE: false
0 4 DEPENDS not_fully_explored 0:91@coma VALUE: false
0 4 DEPENDS in-room 4:B@spatial.sa MODALITY: poss 0:91@coma VALUE: true
0 1 DEPENDS contains-a-person-prior 0:91@coma MODALITY: committed  VALUE: false
0 1 DEPENDS started  VALUE: false
0 3 DEPENDS is-in 0:C@spatial.sa VALUE: 7:B@spatial.sa
0 3 DEPENDS done  VALUE: false
0 3 DEPENDS connected 7:B@spatial.sa 4:B@spatial.sa VALUE: true
END_POPLAN
(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  person0 person1 - person
           room0 room1 room_0_91 - room
           book cerealbox magazine table - label
           robot_0__c - robot
           corridor meetingroom office - category
           visualobject0 visualobject1 visualobject2 visualobject3 visualobject4 - visualobject
           place_0__b place_1__b place_2__b place_4__b place_7__b place__b__b place__d__b - place
)

(:init  (= (associated-with person0) dummy-room)
        (= (associated-with person1) room_0_91)
        (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom magazine) 200.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on magazine table) 30.0000)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom cerealbox corridor) 0.0519)
        (= (dora__inroom cerealbox meetingroom) 0.0600)
        (= (dora__inroom cerealbox office) 0.0253)
        (= (dora__inroom magazine corridor) 0.0025)
        (= (dora__inroom magazine meetingroom) 0.8000)
        (= (dora__inroom magazine office) 0.1800)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__not_inroom book corridor) 0.9975)
        (= (dora__not_inroom book meetingroom) 0.9846)
        (= (dora__not_inroom book office) 0.8715)
        (= (dora__not_inroom cerealbox corridor) 0.9481)
        (= (dora__not_inroom cerealbox meetingroom) 0.9400)
        (= (dora__not_inroom cerealbox office) 0.9747)
        (= (dora__not_inroom magazine corridor) 0.9975)
        (= (dora__not_inroom magazine meetingroom) 0.2000)
        (= (dora__not_inroom magazine office) 0.8200)
        (= (dora__not_inroom table corridor) 0.9406)
        (= (dora__not_inroom table meetingroom) 0.8958)
        (= (dora__not_inroom table office) 0.4800)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on magazine table corridor) 0.0300)
        (= (dora__on magazine table meetingroom) 0.8000)
        (= (dora__on magazine table office) 0.1000)
        (= (entity-exists place_0__b) true)
        (= (entity-exists place_1__b) true)
        (= (entity-exists place_2__b) true)
        (= (entity-exists place_4__b) true)
        (= (entity-exists place_7__b) true)
        (= (entity-exists place__b__b) true)
        (= (entity-exists place__d__b) true)
        (= (entity-exists robot_0__c) true)
        (= (entity-exists room_0_91) true)
        (= (in-room place_0__b) room_0_91)
        (= (in-room place_1__b) room_0_91)
        (= (in-room place_2__b) room_0_91)
        (= (in-room place_4__b) room_0_91)
        (= (is-in robot_0__c) place_7__b)
        (= (label visualobject0) container)
        (= (label visualobject1) book)
        (= (label visualobject2) cerealbox)
        (= (label visualobject3) magazine)
        (= (label visualobject4) table)
        (= (p-obj_exists cerealbox in room_0_91 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_0_91 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_0_91 office) 0.0253)
        (= (p-obj_exists magazine in room_0_91 corridor) 0.0025)
        (= (p-obj_exists magazine in room_0_91 meetingroom) 0.8000)
        (= (p-obj_exists magazine in room_0_91 office) 0.1800)
        (= (placestatus place_0__b) trueplace)
        (= (placestatus place_1__b) trueplace)
        (= (placestatus place_2__b) trueplace)
        (= (placestatus place_4__b) trueplace)
        (= (placestatus place_7__b) trueplace)
        (= (placestatus place__b__b) placeholder)
        (= (placestatus place__d__b) placeholder)
        (= (related-to visualobject0) unknown)
        (= (related-to visualobject1) unknown)
        (= (related-to visualobject2) unknown)
        (= (related-to visualobject3) unknown)
        (= (related-to visualobject4) unknown)
        (= (roomid room_0_91) 0)
        (= (search_cost book in dummy-room) 200.0000)
        (= (search_cost book in room0) 200.0000)
        (= (search_cost book in room1) 200.0000)
        (= (search_cost book in room_0_91) 200.0000)
        (= (search_cost book in visualobject0) unknown)
        (= (search_cost book in visualobject1) unknown)
        (= (search_cost book in visualobject2) unknown)
        (= (search_cost book in visualobject3) unknown)
        (= (search_cost book in visualobject4) unknown)
        (= (search_cost book on visualobject0) unknown)
        (= (search_cost book on visualobject1) unknown)
        (= (search_cost book on visualobject2) unknown)
        (= (search_cost book on visualobject3) unknown)
        (= (search_cost book on visualobject4) 30.0000)
        (= (search_cost cerealbox in dummy-room) 200.0000)
        (= (search_cost cerealbox in room0) 200.0000)
        (= (search_cost cerealbox in room1) 200.0000)
        (= (search_cost cerealbox in room_0_91) 200.0000)
        (= (search_cost cerealbox in visualobject0) unknown)
        (= (search_cost cerealbox in visualobject1) unknown)
        (= (search_cost cerealbox in visualobject2) unknown)
        (= (search_cost cerealbox in visualobject3) unknown)
        (= (search_cost cerealbox in visualobject4) unknown)
        (= (search_cost cerealbox on visualobject0) unknown)
        (= (search_cost cerealbox on visualobject1) unknown)
        (= (search_cost cerealbox on visualobject2) unknown)
        (= (search_cost cerealbox on visualobject3) unknown)
        (= (search_cost cerealbox on visualobject4) 30.0000)
        (= (search_cost container in dummy-room) unknown)
        (= (search_cost container in room0) unknown)
        (= (search_cost container in room1) unknown)
        (= (search_cost container in room_0_91) unknown)
        (= (search_cost container in visualobject0) unknown)
        (= (search_cost container in visualobject1) unknown)
        (= (search_cost container in visualobject2) unknown)
        (= (search_cost container in visualobject3) unknown)
        (= (search_cost container in visualobject4) unknown)
        (= (search_cost container on visualobject0) unknown)
        (= (search_cost container on visualobject1) unknown)
        (= (search_cost container on visualobject2) unknown)
        (= (search_cost container on visualobject3) unknown)
        (= (search_cost container on visualobject4) unknown)
        (= (search_cost magazine in dummy-room) 200.0000)
        (= (search_cost magazine in room0) 200.0000)
        (= (search_cost magazine in room1) 200.0000)
        (= (search_cost magazine in room_0_91) 200.0000)
        (= (search_cost magazine in visualobject0) unknown)
        (= (search_cost magazine in visualobject1) unknown)
        (= (search_cost magazine in visualobject2) unknown)
        (= (search_cost magazine in visualobject3) unknown)
        (= (search_cost magazine in visualobject4) unknown)
        (= (search_cost magazine on visualobject0) unknown)
        (= (search_cost magazine on visualobject1) unknown)
        (= (search_cost magazine on visualobject2) unknown)
        (= (search_cost magazine on visualobject3) unknown)
        (= (search_cost magazine on visualobject4) 30.0000)
        (= (search_cost table in dummy-room) unknown)
        (= (search_cost table in room0) unknown)
        (= (search_cost table in room1) unknown)
        (= (search_cost table in room_0_91) unknown)
        (= (search_cost table in visualobject0) unknown)
        (= (search_cost table in visualobject1) unknown)
        (= (search_cost table in visualobject2) unknown)
        (= (search_cost table in visualobject3) unknown)
        (= (search_cost table in visualobject4) unknown)
        (= (search_cost table on visualobject0) unknown)
        (= (search_cost table on visualobject1) unknown)
        (= (search_cost table on visualobject2) unknown)
        (= (search_cost table on visualobject3) unknown)
        (= (search_cost table on visualobject4) unknown)
        (= (virtual-place room0) place__b__b)
        (= (virtual-place room1) place__d__b)
        (connected place_0__b place_1__b)
        (connected place_0__b place_2__b)
        (connected place_1__b place_0__b)
        (connected place_1__b place_2__b)
        (connected place_2__b place_0__b)
        (connected place_2__b place_1__b)
        (connected place_2__b place_4__b)
        (connected place_4__b place_2__b)
        (connected place_4__b place_7__b)
        (connected place_7__b place_4__b)
        (connected place_7__b place__b__b)
        (connected place_7__b place__d__b)
        (is-virtual person0)
        (is-virtual person1)
        (is-virtual room0)
        (is-virtual room1)
        (is-virtual visualobject0)
        (is-virtual visualobject1)
        (is-virtual visualobject2)
        (is-virtual visualobject3)
        (is-virtual visualobject4)
        (probabilistic  0.2574  (assign (leads_to_room place__b__b office) true))
        (probabilistic  0.2574  (assign (leads_to_room place__d__b office) true))
        (probabilistic  0.2631  (assign (leads_to_room place_4__b office) true))
        (probabilistic  0.0228  (assign (category room_0_91) meetingroom)
                        0.0245  (assign (category room_0_91) corridor)
                        0.9527  (assign (category room_0_91) office)
        )
        (probabilistic  0.2000  (assign (contains-a-person-prior room_0_91) true))
        (probabilistic  0.2574  (assign (leads_to_room place__b__b meetingroom) true))
        (probabilistic  0.0297  (assign (leads_to_room place_1__b meetingroom) true))
        (probabilistic  0.2631  (assign (leads_to_room place_4__b meetingroom) true))
        (probabilistic  0.8838  (assign (leads_to_room place__d__b corridor) true))
        (probabilistic  0.2908  (assign (leads_to_room place_2__b office) true))
        (probabilistic  0.8731  (assign (leads_to_room place_4__b corridor) true))
        (probabilistic  0.0745  (assign (leads_to_room place_1__b corridor) true))
        (probabilistic  0.8838  (assign (leads_to_room place__b__b corridor) true))
        (probabilistic  0.8214  (assign (leads_to_room place_2__b corridor) true))
        (probabilistic  0.2574  (assign (leads_to_room place__d__b meetingroom) true))
        (probabilistic  0.0297  (assign (leads_to_room place_1__b office) true))
        (probabilistic  0.2908  (assign (leads_to_room place_2__b meetingroom) true))
)

(:goal  (and  (exists (?p - person)  (kval robot_0__c (is-in ?p)))))
(:metric minimize (total-cost ))

)
END_PROBLEM
(init ), EXECUTED
(__commit-contains-a-person-prior-room_0_91-true robot_0__c), EXECUTED
(__commit-person_in_room-0 robot_0__c person1 place_4__b room_0_91), EXECUTED
(move robot_0__c place_4__b place_7__b), IN_PROGRESS
(look-for-people robot_0__c place_4__b room_0_91 person1), EXECUTABLE
(goal ), EXECUTABLE
END_PLAN
actions:
0: SUCCEEDED init 
1: SUCCEEDED __commit-contains-a-person-prior-room_0_91-true 0:C@spatial.sa
2: SUCCEEDED __commit-person_in_room-0 0:C@spatial.sa person1 4:B@spatial.sa 0:91@coma
3: INPROGRESS move 0:C@spatial.sa 4:B@spatial.sa 7:B@spatial.sa
4: PENDING look-for-people 0:C@spatial.sa 4:B@spatial.sa 0:91@coma person1
5: PENDING goal 
links:
2 3 THREATENS started  VALUE: true
2 4 DEPENDS is-in person1 MODALITY: poss 4:B@spatial.sa VALUE: true
4 5 DEPENDS is-in person1 MODALITY: kd 0:C@spatial.sa VALUE: true
0 1 DEPENDS contains-a-person-prior 0:91@coma MODALITY: committed  VALUE: false
0 1 DEPENDS started  VALUE: false
0 3 DEPENDS is-in 0:C@spatial.sa VALUE: 7:B@spatial.sa
0 3 DEPENDS done  VALUE: false
0 3 DEPENDS connected 7:B@spatial.sa 4:B@spatial.sa VALUE: true
0 4 DEPENDS done  VALUE: false
0 4 DEPENDS not_fully_explored 0:91@coma VALUE: false
0 4 DEPENDS in-room 4:B@spatial.sa MODALITY: poss 0:91@coma VALUE: true
0 2 DEPENDS associated-with person1 VALUE: 0:91@coma
0 2 DEPENDS is-in person1 MODALITY: committed  VALUE: false
0 2 DEPENDS is-virtual person1 VALUE: true
0 2 DEPENDS started  VALUE: false
0 2 DEPENDS in-room 4:B@spatial.sa MODALITY: poss 0:91@coma VALUE: true
1 2 DEPENDS contains-a-person-prior 0:91@coma MODALITY: poss true VALUE: true
1 3 THREATENS started  VALUE: true
3 4 DEPENDS is-in 0:C@spatial.sa VALUE: 4:B@spatial.sa
3 4 DEPENDS in-room 4:B@spatial.sa MODALITY: kval 0:C@spatial.sa VALUE: true
END_POPLAN
