(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  room_0__s room_1__s - room
           robot_0__f - robot
           whiteboardmarker paperclip box cerealbox bookcase marker mug table stapler counter book - label
           place_4__e place_3__e place_2__e place_7__e place__c__e place_6__e place_5__e place__b__e place_9__e place_8__e place__a__e place_1__e place__d__e place_0__e - place
           corridor office kitchen meetingroom - category
)

(:init  (= (dora__cost_inobject book bookcase) 40.0000)
        (= (dora__cost_inobject book box) 50.0000)
        (= (dora__cost_inobject cerealbox bookcase) 40.0000)
        (= (dora__cost_inobject cerealbox box) 50.0000)
        (= (dora__cost_inobject marker bookcase) 40.0000)
        (= (dora__cost_inobject marker box) 50.0000)
        (= (dora__cost_inobject mug bookcase) 40.0000)
        (= (dora__cost_inobject mug box) 50.0000)
        (= (dora__cost_inobject paperclip bookcase) 40.0000)
        (= (dora__cost_inobject paperclip box) 50.0000)
        (= (dora__cost_inobject stapler bookcase) 40.0000)
        (= (dora__cost_inobject stapler box) 50.0000)
        (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom bookcase) 50.0000)
        (= (dora__cost_inroom box) 50.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom counter) 50.0000)
        (= (dora__cost_inroom marker) 200.0000)
        (= (dora__cost_inroom mug) 200.0000)
        (= (dora__cost_inroom paperclip) 200.0000)
        (= (dora__cost_inroom stapler) 200.0000)
        (= (dora__cost_inroom table) 50.0000)
        (= (dora__cost_on book counter) 30.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox counter) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on marker counter) 30.0000)
        (= (dora__cost_on marker table) 30.0000)
        (= (dora__cost_on mug counter) 30.0000)
        (= (dora__cost_on mug table) 30.0000)
        (= (dora__cost_on paperclip counter) 30.0000)
        (= (dora__cost_on paperclip table) 30.0000)
        (= (dora__cost_on stapler counter) 30.0000)
        (= (dora__cost_on stapler table) 30.0000)
        (= (dora__inobject book bookcase corridor) 0.2000)
        (= (dora__inobject book bookcase kitchen) 0.2000)
        (= (dora__inobject book bookcase meetingroom) 0.5000)
        (= (dora__inobject book bookcase office) 0.4000)
        (= (dora__inobject book box corridor) 0.1000)
        (= (dora__inobject book box kitchen) 0.0100)
        (= (dora__inobject book box meetingroom) 0.3000)
        (= (dora__inobject book box office) 0.0500)
        (= (dora__inobject cerealbox bookcase corridor) 0.0300)
        (= (dora__inobject cerealbox bookcase kitchen) 0.0300)
        (= (dora__inobject cerealbox bookcase meetingroom) 0.0300)
        (= (dora__inobject cerealbox bookcase office) 0.0300)
        (= (dora__inobject cerealbox box corridor) 0.0300)
        (= (dora__inobject cerealbox box kitchen) 0.4000)
        (= (dora__inobject cerealbox box meetingroom) 0.0300)
        (= (dora__inobject cerealbox box office) 0.0300)
        (= (dora__inobject marker bookcase corridor) 0.0300)
        (= (dora__inobject marker bookcase kitchen) 0.0300)
        (= (dora__inobject marker bookcase meetingroom) 0.3000)
        (= (dora__inobject marker bookcase office) 0.0300)
        (= (dora__inobject marker box corridor) 0.1000)
        (= (dora__inobject marker box kitchen) 0.0300)
        (= (dora__inobject marker box meetingroom) 0.3000)
        (= (dora__inobject marker box office) 0.1000)
        (= (dora__inobject mug bookcase corridor) 0.0000)
        (= (dora__inobject mug bookcase kitchen) 0.0300)
        (= (dora__inobject mug bookcase meetingroom) 0.0100)
        (= (dora__inobject mug bookcase office) 0.1000)
        (= (dora__inobject mug box corridor) 0.0000)
        (= (dora__inobject mug box kitchen) 0.0300)
        (= (dora__inobject mug box meetingroom) 0.0100)
        (= (dora__inobject mug box office) 0.0300)
        (= (dora__inobject paperclip bookcase corridor) 0.0300)
        (= (dora__inobject paperclip bookcase kitchen) 0.0300)
        (= (dora__inobject paperclip bookcase meetingroom) 0.0000)
        (= (dora__inobject paperclip bookcase office) 0.1000)
        (= (dora__inobject paperclip box corridor) 0.0300)
        (= (dora__inobject paperclip box kitchen) 0.0300)
        (= (dora__inobject paperclip box meetingroom) 0.0000)
        (= (dora__inobject paperclip box office) 0.1000)
        (= (dora__inobject stapler bookcase corridor) 0.0300)
        (= (dora__inobject stapler bookcase kitchen) 0.0300)
        (= (dora__inobject stapler bookcase meetingroom) 0.0100)
        (= (dora__inobject stapler bookcase office) 0.1000)
        (= (dora__inobject stapler box corridor) 0.0300)
        (= (dora__inobject stapler box kitchen) 0.0300)
        (= (dora__inobject stapler box meetingroom) 0.0100)
        (= (dora__inobject stapler box office) 0.0100)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book kitchen) 0.0366)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom bookcase corridor) 0.0878)
        (= (dora__inroom bookcase kitchen) 0.3554)
        (= (dora__inroom bookcase meetingroom) 0.0150)
        (= (dora__inroom bookcase office) 0.5327)
        (= (dora__inroom box corridor) 0.0000)
        (= (dora__inroom box kitchen) 0.2546)
        (= (dora__inroom box meetingroom) 0.0111)
        (= (dora__inroom box office) 0.4993)
        (= (dora__inroom cerealbox corridor) 0.0219)
        (= (dora__inroom cerealbox kitchen) 0.0381)
        (= (dora__inroom cerealbox meetingroom) 0.0060)
        (= (dora__inroom cerealbox office) 0.0529)
        (= (dora__inroom counter corridor) 0.0587)
        (= (dora__inroom counter kitchen) 0.5562)
        (= (dora__inroom counter meetingroom) 0.0335)
        (= (dora__inroom counter office) 0.2781)
        (= (dora__inroom mug corridor) 0.0000)
        (= (dora__inroom mug kitchen) 0.0402)
        (= (dora__inroom mug meetingroom) 0.0019)
        (= (dora__inroom mug office) 0.1429)
        (= (dora__inroom paperclip corridor) 0.0060)
        (= (dora__inroom paperclip kitchen) 0.0726)
        (= (dora__inroom paperclip meetingroom) 0.0000)
        (= (dora__inroom paperclip office) 0.2399)
        (= (dora__inroom stapler corridor) 0.0035)
        (= (dora__inroom stapler kitchen) 0.1750)
        (= (dora__inroom stapler meetingroom) 0.0110)
        (= (dora__inroom stapler office) 0.4025)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table kitchen) 0.5536)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__inroom whiteboardmarker corridor) 0.0070)
        (= (dora__inroom whiteboardmarker kitchen) 0.0282)
        (= (dora__inroom whiteboardmarker meetingroom) 0.7770)
        (= (dora__inroom whiteboardmarker office) 0.0259)
        (= (dora__on book counter corridor) 0.1000)
        (= (dora__on book counter kitchen) 0.0300)
        (= (dora__on book counter meetingroom) 0.1000)
        (= (dora__on book counter office) 0.1000)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table kitchen) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox counter corridor) 0.0300)
        (= (dora__on cerealbox counter kitchen) 0.2000)
        (= (dora__on cerealbox counter meetingroom) 0.0300)
        (= (dora__on cerealbox counter office) 0.0300)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table kitchen) 0.3000)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on marker counter corridor) 0.0300)
        (= (dora__on marker counter kitchen) 0.0300)
        (= (dora__on marker counter meetingroom) 0.7000)
        (= (dora__on marker counter office) 0.2000)
        (= (dora__on marker table corridor) 0.0300)
        (= (dora__on marker table kitchen) 0.0300)
        (= (dora__on marker table meetingroom) 0.7000)
        (= (dora__on marker table office) 0.3000)
        (= (dora__on mug counter corridor) 0.0000)
        (= (dora__on mug counter kitchen) 0.4000)
        (= (dora__on mug counter meetingroom) 0.0100)
        (= (dora__on mug counter office) 0.3000)
        (= (dora__on mug table corridor) 0.0000)
        (= (dora__on mug table kitchen) 0.3000)
        (= (dora__on mug table meetingroom) 0.0200)
        (= (dora__on mug table office) 0.3000)
        (= (dora__on paperclip counter corridor) 0.2000)
        (= (dora__on paperclip counter kitchen) 0.0300)
        (= (dora__on paperclip counter meetingroom) 0.0000)
        (= (dora__on paperclip counter office) 0.3000)
        (= (dora__on paperclip table corridor) 0.1000)
        (= (dora__on paperclip table kitchen) 0.0300)
        (= (dora__on paperclip table meetingroom) 0.0000)
        (= (dora__on paperclip table office) 0.3000)
        (= (dora__on stapler counter corridor) 0.1500)
        (= (dora__on stapler counter kitchen) 0.0300)
        (= (dora__on stapler counter meetingroom) 0.0300)
        (= (dora__on stapler counter office) 0.3000)
        (= (dora__on stapler table corridor) 0.0500)
        (= (dora__on stapler table kitchen) 0.0300)
        (= (dora__on stapler table meetingroom) 0.0300)
        (= (dora__on stapler table office) 0.6000)
        (= (in-room place_0__e) room_0__s)
        (= (in-room place_3__e) room_0__s)
        (= (in-room place_4__e) room_0__s)
        (= (in-room place_8__e) room_1__s)
        (= (in-room place__a__e) room_1__s)
        (= (in-room place__b__e) room_1__s)
        (= (in-room place__c__e) room_1__s)
        (= (in-room place__d__e) room_1__s)
        (= (is-in robot_0__f) place__b__e)
        (= (p-obj_exists cerealbox in room_0__s) 0.0295)
        (= (p-obj_exists cerealbox in room_1__s) 0.0318)
        (= (p-obj_exists table in room_0__s) 0.2725)
        (= (p-obj_exists table in room_1__s) 0.3438)
        (= (placestatus place_0__e) trueplace)
        (= (placestatus place_1__e) placeholder)
        (= (placestatus place_2__e) placeholder)
        (= (placestatus place_3__e) trueplace)
        (= (placestatus place_4__e) trueplace)
        (= (placestatus place_5__e) placeholder)
        (= (placestatus place_6__e) trueplace)
        (= (placestatus place_7__e) placeholder)
        (= (placestatus place_8__e) trueplace)
        (= (placestatus place_9__e) placeholder)
        (= (placestatus place__a__e) trueplace)
        (= (placestatus place__b__e) trueplace)
        (= (placestatus place__c__e) trueplace)
        (= (placestatus place__d__e) trueplace)
        (= (roomid room_0__s) 0.0000)
        (= (roomid room_1__s) 1)
        (connected place_0__e place_1__e)
        (connected place_0__e place_2__e)
        (connected place_0__e place_3__e)
        (connected place_3__e place_0__e)
        (connected place_3__e place_4__e)
        (connected place_3__e place_6__e)
        (connected place_4__e place_3__e)
        (connected place_4__e place_5__e)
        (connected place_6__e place_3__e)
        (connected place_6__e place_7__e)
        (connected place_6__e place_8__e)
        (connected place_8__e place_6__e)
        (connected place_8__e place_9__e)
        (connected place_8__e place__a__e)
        (connected place_8__e place__b__e)
        (connected place_8__e place__d__e)
        (connected place__a__e place_8__e)
        (connected place__a__e place__b__e)
        (connected place__b__e place_8__e)
        (connected place__b__e place__a__e)
        (connected place__b__e place__c__e)
        (connected place__b__e place__d__e)
        (connected place__c__e place__b__e)
        (connected place__d__e place_8__e)
        (connected place__d__e place__b__e)
        (probabilistic  0.5963  (assign (leads_to_room place_1__e corridor) true))
        (probabilistic  0.2505  (assign (leads_to_room place_1__e kitchen) true))
        (probabilistic  0.2505  (assign (leads_to_room place_1__e meetingroom) true))
        (probabilistic  0.2776  (assign (leads_to_room place_1__e office) true))
        (probabilistic  0.6186  (assign (leads_to_room place_2__e corridor) true))
        (probabilistic  0.2599  (assign (leads_to_room place_2__e meetingroom) true))
        (probabilistic  0.2599  (assign (leads_to_room place_2__e kitchen) true))
        (probabilistic  0.2880  (assign (leads_to_room place_2__e office) true))
        (probabilistic  0.3094  (assign (leads_to_room place_5__e corridor) true))
        (probabilistic  0.1300  (assign (leads_to_room place_5__e kitchen) true))
        (probabilistic  0.1300  (assign (leads_to_room place_5__e meetingroom) true))
        (probabilistic  0.1440  (assign (leads_to_room place_5__e office) true))
        (probabilistic  0.6186  (assign (leads_to_room place_7__e corridor) true))
        (probabilistic  0.2599  (assign (leads_to_room place_7__e kitchen) true))
        (probabilistic  0.2599  (assign (leads_to_room place_7__e meetingroom) true))
        (probabilistic  0.2880  (assign (leads_to_room place_7__e office) true))
        (probabilistic  0.6937  (assign (leads_to_room place_9__e corridor) true))
        (probabilistic  0.2332  (assign (leads_to_room place_9__e kitchen) true))
        (probabilistic  0.2332  (assign (leads_to_room place_9__e meetingroom) true))
        (probabilistic  0.2647  (assign (leads_to_room place_9__e office) true))

        (probabilistic  0.2565  (assign (category room_1__s) office)
                        0.2242  (assign (category room_1__s) corridor)
                        0.3183  (assign (category room_1__s) kitchen)
                        0.2011  (assign (category room_1__s) meetingroom)
        )
        (probabilistic  0.2176  (assign (category room_0__s) office)
                        0.4065  (assign (category room_0__s) corridor)
                        0.2137  (assign (category room_0__s) kitchen)
                        0.1622  (assign (category room_0__s) meetingroom)
        )
)

(:goal  (and  (exists (?o - visualobject)  (and  (= (label ?o) cerealbox)
                                                 (kval robot_0__f (related-to ?o))
                                                 ;; (position-reported ?o)
                                           )
              )
        )
)

)
