(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  book cerealbox magazine table - label
           place_0__b place_1__b place_2__b place_3__b place_4__b place_5__b place_6__b place_7__b place_8__b place_9__b place__a__b place__b__b place__c__b place__d__b place__e__b place__f__b place__g__b place__h__b place__i__b place__j__b place__k__b place__l__b place__m__b place__n__b place__o__b place__p__b place__q__b place__r__b place__s__b place__t__b place__u__b place__v__b place__w__b place__x__b - place
           corridor meetingroom office - category
           room_0_61 room_1_61 room_2_61 room_3_61 - room
           visualobject0 visualobject1 visualobject2 visualobject3 visualobject4 - visualobject
           person0 person1 person2 person3 person4 - person
           robot_0__c - robot
)

(:init  (= (associated-with person0) dummy-room)
        (= (associated-with person1) room_2_61)
        (= (associated-with person2) room_0_61)
        (= (associated-with person3) room_3_61)
        (= (associated-with person4) room_1_61)
        (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom magazine) 200.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on magazine table) 30.0000)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom cerealbox corridor) 0.0519)
        (= (dora__inroom cerealbox meetingroom) 0.0600)
        (= (dora__inroom cerealbox office) 0.0253)
        (= (dora__inroom magazine corridor) 0.0025)
        (= (dora__inroom magazine meetingroom) 0.8000)
        (= (dora__inroom magazine office) 0.1800)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__not_inroom book corridor) 0.9975)
        (= (dora__not_inroom book meetingroom) 0.9846)
        (= (dora__not_inroom book office) 0.8715)
        (= (dora__not_inroom cerealbox corridor) 0.9481)
        (= (dora__not_inroom cerealbox meetingroom) 0.9400)
        (= (dora__not_inroom cerealbox office) 0.9747)
        (= (dora__not_inroom magazine corridor) 0.9975)
        (= (dora__not_inroom magazine meetingroom) 0.2000)
        (= (dora__not_inroom magazine office) 0.8200)
        (= (dora__not_inroom table corridor) 0.9406)
        (= (dora__not_inroom table meetingroom) 0.8958)
        (= (dora__not_inroom table office) 0.4800)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on magazine table corridor) 0.0300)
        (= (dora__on magazine table meetingroom) 0.8000)
        (= (dora__on magazine table office) 0.1000)
        (= (entity-exists place_0__b) true)
        (= (entity-exists place_1__b) true)
        (= (entity-exists place_2__b) true)
        (= (entity-exists place_3__b) true)
        (= (entity-exists place_4__b) true)
        (= (entity-exists place_5__b) true)
        (= (entity-exists place_6__b) true)
        (= (entity-exists place_7__b) true)
        (= (entity-exists place_8__b) true)
        (= (entity-exists place_9__b) true)
        (= (entity-exists place__a__b) true)
        (= (entity-exists place__b__b) true)
        (= (entity-exists place__c__b) true)
        (= (entity-exists place__d__b) true)
        (= (entity-exists place__e__b) true)
        (= (entity-exists place__f__b) true)
        (= (entity-exists place__g__b) true)
        (= (entity-exists place__h__b) true)
        (= (entity-exists place__i__b) true)
        (= (entity-exists place__j__b) true)
        (= (entity-exists place__k__b) true)
        (= (entity-exists place__l__b) true)
        (= (entity-exists place__m__b) true)
        (= (entity-exists place__n__b) true)
        (= (entity-exists place__o__b) true)
        (= (entity-exists place__p__b) true)
        (= (entity-exists place__q__b) true)
        (= (entity-exists place__r__b) true)
        (= (entity-exists place__s__b) true)
        (= (entity-exists place__t__b) true)
        (= (entity-exists place__u__b) true)
        (= (entity-exists place__v__b) true)
        (= (entity-exists place__w__b) true)
        (= (entity-exists place__x__b) true)
        (= (entity-exists robot_0__c) true)
        (= (entity-exists room_0_61) true)
        (= (entity-exists room_1_61) true)
        (= (entity-exists room_2_61) true)
        (= (entity-exists room_3_61) true)
        (= (in-room place_0__b) room_0_61)
        (= (in-room place_1__b) room_0_61)
        (= (in-room place_2__b) room_0_61)
        (= (in-room place_3__b) room_0_61)
        (= (in-room place_5__b) room_1_61)
        (= (in-room place_6__b) room_1_61)
        (= (in-room place_7__b) room_1_61)
        (= (in-room place_8__b) room_1_61)
        (= (in-room place_9__b) room_1_61)
        (= (in-room place__a__b) room_1_61)
        (= (in-room place__b__b) room_1_61)
        (= (in-room place__c__b) room_1_61)
        (= (in-room place__e__b) room_2_61)
        (= (in-room place__f__b) room_2_61)
        (= (in-room place__g__b) room_2_61)
        (= (in-room place__h__b) room_2_61)
        (= (in-room place__i__b) room_2_61)
        (= (in-room place__j__b) room_2_61)
        (= (in-room place__k__b) room_2_61)
        (= (in-room place__l__b) room_2_61)
        (= (in-room place__m__b) room_2_61)
        (= (in-room place__n__b) room_2_61)
        (= (in-room place__o__b) room_1_61)
        (= (in-room place__q__b) room_3_61)
        (= (in-room place__r__b) room_3_61)
        (= (in-room place__s__b) room_3_61)
        (= (in-room place__t__b) room_3_61)
        (= (in-room place__u__b) room_3_61)
        (= (in-room place__v__b) room_1_61)
        (= (in-room place__w__b) room_1_61)
        (= (in-room place__x__b) room_1_61)
        (= (is-in robot_0__c) place_0__b)
        (= (label visualobject0) container)
        (= (label visualobject1) book)
        (= (label visualobject2) magazine)
        (= (label visualobject3) table)
        (= (label visualobject4) cerealbox)
        (= (p-obj_exists cerealbox in room_0_61 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_0_61 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_0_61 office) 0.0253)
        (= (p-obj_exists cerealbox in room_1_61 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_1_61 meetingroom) 0.0000)
        (= (p-obj_exists cerealbox in room_1_61 office) 0.0000)
        (= (p-obj_exists cerealbox in room_2_61 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_2_61 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_2_61 office) 0.0253)
        (= (p-obj_exists cerealbox in room_3_61 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_3_61 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_3_61 office) 0.0253)
        (= (p-obj_exists magazine in room_0_61 corridor) 0.0025)
        (= (p-obj_exists magazine in room_0_61 meetingroom) 0.8000)
        (= (p-obj_exists magazine in room_0_61 office) 0.1800)
        (= (p-obj_exists magazine in room_1_61 corridor) 0.0025)
        (= (p-obj_exists magazine in room_1_61 meetingroom) 0.0000)
        (= (p-obj_exists magazine in room_1_61 office) 0.0000)
        (= (p-obj_exists magazine in room_2_61 corridor) 0.0025)
        (= (p-obj_exists magazine in room_2_61 meetingroom) 0.8000)
        (= (p-obj_exists magazine in room_2_61 office) 0.1800)
        (= (p-obj_exists magazine in room_3_61 corridor) 0.0025)
        (= (p-obj_exists magazine in room_3_61 meetingroom) 0.8000)
        (= (p-obj_exists magazine in room_3_61 office) 0.1800)
        (= (placestatus place_0__b) trueplace)
        (= (placestatus place_1__b) trueplace)
        (= (placestatus place_2__b) trueplace)
        (= (placestatus place_3__b) trueplace)
        (= (placestatus place_4__b) trueplace)
        (= (placestatus place_5__b) trueplace)
        (= (placestatus place_6__b) trueplace)
        (= (placestatus place_7__b) trueplace)
        (= (placestatus place_8__b) trueplace)
        (= (placestatus place_9__b) trueplace)
        (= (placestatus place__a__b) trueplace)
        (= (placestatus place__b__b) trueplace)
        (= (placestatus place__c__b) trueplace)
        (= (placestatus place__d__b) trueplace)
        (= (placestatus place__e__b) trueplace)
        (= (placestatus place__f__b) trueplace)
        (= (placestatus place__g__b) trueplace)
        (= (placestatus place__h__b) trueplace)
        (= (placestatus place__i__b) trueplace)
        (= (placestatus place__j__b) trueplace)
        (= (placestatus place__k__b) trueplace)
        (= (placestatus place__l__b) trueplace)
        (= (placestatus place__m__b) trueplace)
        (= (placestatus place__n__b) trueplace)
        (= (placestatus place__o__b) trueplace)
        (= (placestatus place__p__b) trueplace)
        (= (placestatus place__q__b) trueplace)
        (= (placestatus place__r__b) trueplace)
        (= (placestatus place__s__b) trueplace)
        (= (placestatus place__t__b) trueplace)
        (= (placestatus place__u__b) trueplace)
        (= (placestatus place__v__b) trueplace)
        (= (placestatus place__w__b) trueplace)
        (= (placestatus place__x__b) trueplace)
        (= (related-to visualobject0) unknown)
        (= (related-to visualobject1) unknown)
        (= (related-to visualobject2) unknown)
        (= (related-to visualobject3) unknown)
        (= (related-to visualobject4) unknown)
        (= (roomid room_0_61) 0)
        (= (roomid room_1_61) 1)
        (= (roomid room_2_61) 2)
        (= (roomid room_3_61) 3)
        (= (search_cost book in dummy-room) 200.0000)
        (= (search_cost book in room_0_61) 200.0000)
        (= (search_cost book in room_1_61) 200.0000)
        (= (search_cost book in room_2_61) 200.0000)
        (= (search_cost book in room_3_61) 200.0000)
        (= (search_cost book in visualobject0) 200.0000)
        (= (search_cost book in visualobject1) 200.0000)
        (= (search_cost book in visualobject2) 200.0000)
        (= (search_cost book in visualobject3) 200.0000)
        (= (search_cost book in visualobject4) 200.0000)
        (= (search_cost book on visualobject0) 200.0000)
        (= (search_cost book on visualobject1) 200.0000)
        (= (search_cost book on visualobject2) 200.0000)
        (= (search_cost book on visualobject3) 30.0000)
        (= (search_cost book on visualobject4) 200.0000)
        (= (search_cost cerealbox in dummy-room) 200.0000)
        (= (search_cost cerealbox in room_0_61) 200.0000)
        (= (search_cost cerealbox in room_1_61) 200.0000)
        (= (search_cost cerealbox in room_2_61) 200.0000)
        (= (search_cost cerealbox in room_3_61) 200.0000)
        (= (search_cost cerealbox in visualobject0) 200.0000)
        (= (search_cost cerealbox in visualobject1) 200.0000)
        (= (search_cost cerealbox in visualobject2) 200.0000)
        (= (search_cost cerealbox in visualobject3) 200.0000)
        (= (search_cost cerealbox in visualobject4) 200.0000)
        (= (search_cost cerealbox on visualobject0) 200.0000)
        (= (search_cost cerealbox on visualobject1) 200.0000)
        (= (search_cost cerealbox on visualobject2) 200.0000)
        (= (search_cost cerealbox on visualobject3) 30.0000)
        (= (search_cost cerealbox on visualobject4) 200.0000)
        (= (search_cost container in dummy-room) 200.0000)
        (= (search_cost container in room_0_61) 200.0000)
        (= (search_cost container in room_1_61) 200.0000)
        (= (search_cost container in room_2_61) 200.0000)
        (= (search_cost container in room_3_61) 200.0000)
        (= (search_cost container in visualobject0) 200.0000)
        (= (search_cost container in visualobject1) 200.0000)
        (= (search_cost container in visualobject2) 200.0000)
        (= (search_cost container in visualobject3) 200.0000)
        (= (search_cost container in visualobject4) 200.0000)
        (= (search_cost container on visualobject0) 200.0000)
        (= (search_cost container on visualobject1) 200.0000)
        (= (search_cost container on visualobject2) 200.0000)
        (= (search_cost container on visualobject3) 200.0000)
        (= (search_cost container on visualobject4) 200.0000)
        (= (search_cost magazine in dummy-room) 200.0000)
        (= (search_cost magazine in room_0_61) 200.0000)
        (= (search_cost magazine in room_1_61) 200.0000)
        (= (search_cost magazine in room_2_61) 200.0000)
        (= (search_cost magazine in room_3_61) 200.0000)
        (= (search_cost magazine in visualobject0) 200.0000)
        (= (search_cost magazine in visualobject1) 200.0000)
        (= (search_cost magazine in visualobject2) 200.0000)
        (= (search_cost magazine in visualobject3) 200.0000)
        (= (search_cost magazine in visualobject4) 200.0000)
        (= (search_cost magazine on visualobject0) 200.0000)
        (= (search_cost magazine on visualobject1) 200.0000)
        (= (search_cost magazine on visualobject2) 200.0000)
        (= (search_cost magazine on visualobject3) 30.0000)
        (= (search_cost magazine on visualobject4) 200.0000)
        (= (search_cost table in dummy-room) 200.0000)
        (= (search_cost table in room_0_61) 200.0000)
        (= (search_cost table in room_1_61) 200.0000)
        (= (search_cost table in room_2_61) 200.0000)
        (= (search_cost table in room_3_61) 200.0000)
        (= (search_cost table in visualobject0) 200.0000)
        (= (search_cost table in visualobject1) 200.0000)
        (= (search_cost table in visualobject2) 200.0000)
        (= (search_cost table in visualobject3) 200.0000)
        (= (search_cost table in visualobject4) 200.0000)
        (= (search_cost table on visualobject0) 200.0000)
        (= (search_cost table on visualobject1) 200.0000)
        (= (search_cost table on visualobject2) 200.0000)
        (= (search_cost table on visualobject3) 200.0000)
        (= (search_cost table on visualobject4) 200.0000)
        (connected place_0__b place_1__b)
        (connected place_1__b place_0__b)
        (connected place_1__b place_2__b)
        (connected place_2__b place_1__b)
        (connected place_2__b place_3__b)
        (connected place_3__b place_2__b)
        (connected place_3__b place_4__b)
        (connected place_4__b place_3__b)
        (connected place_4__b place_5__b)
        (connected place_5__b place_4__b)
        (connected place_5__b place_6__b)
        (connected place_6__b place_5__b)
        (connected place_6__b place_7__b)
        (connected place_6__b place__v__b)
        (connected place_7__b place_6__b)
        (connected place_7__b place_8__b)
        (connected place_7__b place__o__b)
        (connected place_8__b place_7__b)
        (connected place_8__b place_9__b)
        (connected place_9__b place_8__b)
        (connected place_9__b place__a__b)
        (connected place__a__b place_9__b)
        (connected place__a__b place__b__b)
        (connected place__b__b place__a__b)
        (connected place__b__b place__c__b)
        (connected place__c__b place__b__b)
        (connected place__c__b place__d__b)
        (connected place__d__b place__c__b)
        (connected place__d__b place__e__b)
        (connected place__e__b place__d__b)
        (connected place__e__b place__f__b)
        (connected place__f__b place__e__b)
        (connected place__f__b place__g__b)
        (connected place__g__b place__f__b)
        (connected place__g__b place__h__b)
        (connected place__h__b place__g__b)
        (connected place__h__b place__i__b)
        (connected place__i__b place__h__b)
        (connected place__i__b place__j__b)
        (connected place__j__b place__i__b)
        (connected place__j__b place__k__b)
        (connected place__j__b place__n__b)
        (connected place__k__b place__j__b)
        (connected place__k__b place__l__b)
        (connected place__l__b place__k__b)
        (connected place__l__b place__m__b)
        (connected place__m__b place__l__b)
        (connected place__n__b place__j__b)
        (connected place__o__b place_7__b)
        (connected place__o__b place__p__b)
        (connected place__p__b place__o__b)
        (connected place__p__b place__q__b)
        (connected place__q__b place__p__b)
        (connected place__q__b place__r__b)
        (connected place__r__b place__q__b)
        (connected place__r__b place__s__b)
        (connected place__r__b place__u__b)
        (connected place__s__b place__r__b)
        (connected place__s__b place__t__b)
        (connected place__t__b place__s__b)
        (connected place__u__b place__r__b)
        (connected place__v__b place_6__b)
        (connected place__v__b place__w__b)
        (connected place__w__b place__v__b)
        (connected place__w__b place__x__b)
        (connected place__x__b place__w__b)
        (is-virtual person0)
        (is-virtual person1)
        (is-virtual person2)
        (is-virtual person3)
        (is-virtual person4)
        (is-virtual visualobject0)
        (is-virtual visualobject1)
        (is-virtual visualobject2)
        (is-virtual visualobject3)
        (is-virtual visualobject4)
        (probabilistic  0.0148  (assign (category room_2_61) corridor)
                        0.7891  (assign (category room_2_61) meetingroom)
                        0.1961  (assign (category room_2_61) office)
        )
        ;; (probabilistic  0.2000  (assign (contains-a-person-prior room_0_61) true))
        (probabilistic  1.0000  (assign (category room_1_61) corridor)
                        0.0000  (assign (category room_1_61) meetingroom)
                        0.0000  (assign (category room_1_61) office)
        )
        ;; (probabilistic  0.2000  (assign (contains-a-person-prior room_3_61) true))
        (probabilistic  0.0065  (assign (category room_3_61) corridor)
                        0.0142  (assign (category room_3_61) meetingroom)
                        0.9793  (assign (category room_3_61) office)
        )
        ;; (probabilistic  0.2000  (assign (contains-a-person-prior room_1_61) true))
        (probabilistic  0.0087  (assign (category room_0_61) corridor)
                        0.0224  (assign (category room_0_61) meetingroom)
                        0.9689  (assign (category room_0_61) office)
        )
        ;; (probabilistic  0.2000  (assign (contains-a-person-prior room_2_61) true))
)

(:goal  (and  (kval robot_0__c (dora__inroom container meetingroom))))
(:metric minimize (total-cost ))

)
