package ComaData;

/**
* ComaData/ComaReasonerFunctionTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComaData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/// These are the coma reasoner function types
public final class ComaReasonerFunctionTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ComaData.ComaReasonerFunctionType value = null;

  public ComaReasonerFunctionTypeHolder ()
  {
  }

  public ComaReasonerFunctionTypeHolder (ComaData.ComaReasonerFunctionType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ComaData.ComaReasonerFunctionTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ComaData.ComaReasonerFunctionTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ComaData.ComaReasonerFunctionTypeHelper.type ();
  }

}
