package org.cognitivesystems.common.autogen.Math;


/**
* org/cognitivesystems/common/autogen/Math/Vector3DWithConfidenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Math.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class Vector3DWithConfidenceHelper
{
  private static String  _id = "IDL:Math/Vector3DWithConfidence:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cognitivesystems.common.autogen.Math.Vector3DWithConfidence that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cognitivesystems.common.autogen.Math.Vector3DWithConfidence extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.cognitivesystems.common.autogen.Math.Vector3DHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_vector",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "m_confidence",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.cognitivesystems.common.autogen.Math.Vector3DWithConfidenceHelper.id (), "Vector3DWithConfidence", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cognitivesystems.common.autogen.Math.Vector3DWithConfidence read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cognitivesystems.common.autogen.Math.Vector3DWithConfidence value = new org.cognitivesystems.common.autogen.Math.Vector3DWithConfidence ();
    value.m_vector = org.cognitivesystems.common.autogen.Math.Vector3DHelper.read (istream);
    value.m_confidence = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cognitivesystems.common.autogen.Math.Vector3DWithConfidence value)
  {
    org.cognitivesystems.common.autogen.Math.Vector3DHelper.write (ostream, value.m_vector);
    ostream.write_float (value.m_confidence);
  }

}
