//=================================================================
// Copyright (C) 2007 Geert-Jan M. Kruijff (gj@dfki.de)
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 2.1 of
// the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
// 02111-1307, USA.
//=================================================================

//=================================================================
// PACKAGE DEFINITION 
//=================================================================

package org.cognitivesystems.comsys.monitors;

//=================================================================
// IMPORTS
//=================================================================//

// ----------------------------------------------------------------
// JAVA imports
// ----------------------------------------------------------------
import java.util.Iterator;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.Vector;

import BindingData.FeaturePointer;
// DEPRECATED IN BINDER RELEASE7 import BindingData.CommunicativeGoals.CommunicativeGoal;

//=================================================================
// JAVADOC CLASS DOCUMENTATION 
//=================================================================

/** 
The class <b>ProxyFactoryResults</b> encapsulates three basic results
from a proxy factory: the list of added proxies (by address), the 
list of relations pending to be added to working memory, and the list
of excludes (nominal variables no longer to be considered). 

@version 071003 (started 071002)
@author  Geert-Jan M. Kruijff (gj@dfki.de)
*/ 

//=================================================================
// CLASS DEFINITION 
//=================================================================


public class ProxyFactoryResults {

	//=================================================================
    // CLASS-INTERNAL GLOBAL VARIABLES
    //=================================================================

	public TreeSet addedNominals; 
	private Vector<PendingProxyRelation> pendingProxyRelations; 
	private TreeSet excludes;
// DEPRECATED IN BINDER RELEASE7 	private TreeMap<String, CommunicativeGoal> commGoals;
	private boolean generateProxy; 
	private LocalProxyStructure proxyStructure ;

    //=================================================================
    // CONSTRUCTOR METHODS
    //=================================================================

	public ProxyFactoryResults () { 
		init();
	} // end constructor

	private void init () { 
		addedNominals = new TreeSet();
		pendingProxyRelations = new Vector<PendingProxyRelation>();
		excludes = new TreeSet();
		generateProxy = true;
		proxyStructure = new LocalProxyStructure();
	} // end init

	//=================================================================
    // ACCESSOR METHODS
    //=================================================================
	
	/** Returns an iterator (String) over the added nominals (by nominal variable) */ 	
	public Iterator<String> getAddedNominals () { return addedNominals.iterator(); } 
	
	public TreeSet<String> getAddedNominalsSet ()  { return addedNominals; }
	
	
	/** Returns the number of added nominals */
	public int getAddedNominalsSize() { return addedNominals.size(); }
	
	
	/** Returns whether to generate a proxy (separate from the general NULL result; there may be relations to generate) */ 
	public boolean generateProxy() { return generateProxy; }
	
	/** Returns a TreeSet with nominal variables (String) to be excluded from further consideration when creating proxies */
	public TreeSet getExcludes () { return excludes; }	
	
	/** Returns a Vector of PendingProxyRelation representing the proxy relations to be added */ 		
	public Vector getPendingProxyRelations () { return pendingProxyRelations; }
	
	/** Returns the stored local proxy structure, generated by the factory */ 
	public LocalProxyStructure getProxyStructure () { return proxyStructure; } 
	
	/** Sets the list of added nominals (by variable) */
	public void setAddedNominals (TreeSet ap) { addedNominals = ap; }

	/** Sets the excludes list */
	public void setExcludes (TreeSet ex) { excludes = ex; } 
	
	/** Sets the flag whether to generate a proxy -- by default, the generation is "true". */ 
	public void setGenerateProxy (boolean gp) { generateProxy = gp; } 
	
	/** Sets the list of relations to be added */ 
	public void setPendingProxyRelations (Vector<PendingProxyRelation> ppr) { pendingProxyRelations = ppr; }

	/** Sets the proxy structure as generated by the proxy factory */
	public void setProxyStructure (LocalProxyStructure localPRX) { proxyStructure = localPRX; }


} // end ProxyFactoryResults
