(define (problem cogxtask)

(:domain dora-avs-iros11)

(:objects  place_0__b place_1__b place_2__b place_3__b - place
           room_0_61 - room
           book cerealbox magazine table - label
           corridor meetingroom office - category
           robot_0__c - robot
)

(:init  (= (dora__cost_inroom book) 200.0000)
        (= (dora__cost_inroom cerealbox) 200.0000)
        (= (dora__cost_inroom magazine) 200.0000)
        (= (dora__cost_on book table) 30.0000)
        (= (dora__cost_on cerealbox table) 30.0000)
        (= (dora__cost_on magazine table) 30.0000)
        (= (dora__inroom book corridor) 0.0025)
        (= (dora__inroom book meetingroom) 0.0154)
        (= (dora__inroom book office) 0.1285)
        (= (dora__inroom cerealbox corridor) 0.0519)
        (= (dora__inroom cerealbox meetingroom) 0.0600)
        (= (dora__inroom cerealbox office) 0.0253)
        (= (dora__inroom magazine corridor) 0.0025)
        (= (dora__inroom magazine meetingroom) 0.8000)
        (= (dora__inroom magazine office) 0.1800)
        (= (dora__inroom table corridor) 0.0594)
        (= (dora__inroom table meetingroom) 0.1042)
        (= (dora__inroom table office) 0.5200)
        (= (dora__on book table corridor) 0.0300)
        (= (dora__on book table meetingroom) 0.3000)
        (= (dora__on book table office) 0.1000)
        (= (dora__on cerealbox table corridor) 0.0300)
        (= (dora__on cerealbox table meetingroom) 0.0300)
        (= (dora__on cerealbox table office) 0.0300)
        (= (dora__on magazine table corridor) 0.0300)
        (= (dora__on magazine table meetingroom) 0.8000)
        (= (dora__on magazine table office) 0.1000)
        (= (entity-exists place_0__b) true)
        (= (entity-exists place_1__b) true)
        (= (entity-exists place_2__b) true)
        (= (entity-exists place_3__b) true)
        (= (entity-exists robot_0__c) true)
        (= (entity-exists room_0_61) true)
        (= (in-room place_0__b) room_0_61)
        (= (is-in robot_0__c) place_0__b)
        (= (p-obj_exists cerealbox in room_0_61 corridor) 0.0519)
        (= (p-obj_exists cerealbox in room_0_61 meetingroom) 0.0600)
        (= (p-obj_exists cerealbox in room_0_61 office) 0.0253)
        (= (p-obj_exists magazine in room_0_61 corridor) 0.0025)
        (= (p-obj_exists magazine in room_0_61 meetingroom) 0.8000)
        (= (p-obj_exists magazine in room_0_61 office) 0.1800)
        (= (placestatus place_0__b) trueplace)
        (= (placestatus place_1__b) placeholder)
        (= (placestatus place_2__b) placeholder)
        (= (placestatus place_3__b) placeholder)
        (= (roomid room_0_61) 0)
        (connected place_0__b place_1__b)
        (connected place_0__b place_2__b)
        (connected place_0__b place_3__b)
        (probabilistic  0.7430  (assign (leads_to_room place_3__b corridor) true))
        (probabilistic  0.3333  (assign (leads_to_room place_2__b meetingroom) true))
        (probabilistic  0.3333  (assign (leads_to_room place_1__b office) true))
        (probabilistic  0.3333  (assign (leads_to_room place_1__b meetingroom) true))
        (probabilistic  0.3333  (assign (leads_to_room place_2__b office) true))
        (probabilistic  0.4851  (assign (category room_0_61) meetingroom)
                        0.2212  (assign (category room_0_61) office)
                        0.2937  (assign (category room_0_61) corridor)
        )
        (probabilistic  0.3333  (assign (leads_to_room place_3__b office) true))
        (probabilistic  0.3333  (assign (leads_to_room place_3__b meetingroom) true))
        (probabilistic  0.2000  (assign (contains-a-person-prior room_0_61) true))
        (probabilistic  0.7430  (assign (leads_to_room place_1__b corridor) true))
        (probabilistic  0.7430  (assign (leads_to_room place_2__b corridor) true))
)

(:goal  (and  (kval robot_0__c (dora__inroom cerealbox office))))
(:metric minimize (total-cost ))

)
