package org.cognitivesystems.common.autogen.Matlab;


/**
* org/cognitivesystems/common/autogen/Matlab/longSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Matlab.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class longSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public longSeqHolder ()
  {
  }

  public longSeqHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cognitivesystems.common.autogen.Matlab.longSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cognitivesystems.common.autogen.Matlab.longSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cognitivesystems.common.autogen.Matlab.longSeqHelper.type ();
  }

}
