package motivation.idl;


/**
* motivation/idl/AttentionMotive.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MotivationData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public class AttentionMotive implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static motivation.idl.AttentionMotive[] __array = new motivation.idl.AttentionMotive [__size];

  public static final int _ATTENTION_HELP = 0;
  public static final motivation.idl.AttentionMotive ATTENTION_HELP = new motivation.idl.AttentionMotive(_ATTENTION_HELP);
  public static final int _ATTENTION_GREET = 1;
  public static final motivation.idl.AttentionMotive ATTENTION_GREET = new motivation.idl.AttentionMotive(_ATTENTION_GREET);
  public static final int _ATTENTION_CLOSE = 2;
  public static final motivation.idl.AttentionMotive ATTENTION_CLOSE = new motivation.idl.AttentionMotive(_ATTENTION_CLOSE);
  public static final int _ATTENTION_KILL = 3;
  public static final motivation.idl.AttentionMotive ATTENTION_KILL = new motivation.idl.AttentionMotive(_ATTENTION_KILL);

  public int value ()
  {
    return __value;
  }

  public static motivation.idl.AttentionMotive from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AttentionMotive (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AttentionMotive
