package motivation.idl;


/**
* motivation/idl/MotiveType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MotivationData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/**
     * A useful shortcut to represent what type of behaviour the
     * motive is intended to generate
     */
public class MotiveType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static motivation.idl.MotiveType[] __array = new motivation.idl.MotiveType [__size];

  public static final int _POLAR_QUESTION = 0;
  public static final motivation.idl.MotiveType POLAR_QUESTION = new motivation.idl.MotiveType(_POLAR_QUESTION);
  public static final int _FACTUAL_QUESTION = 1;
  public static final motivation.idl.MotiveType FACTUAL_QUESTION = new motivation.idl.MotiveType(_FACTUAL_QUESTION);
  public static final int _CLARIFICATION = 2;
  public static final motivation.idl.MotiveType CLARIFICATION = new motivation.idl.MotiveType(_CLARIFICATION);
  public static final int _PHYSICAL_ACTION = 3;
  public static final motivation.idl.MotiveType PHYSICAL_ACTION = new motivation.idl.MotiveType(_PHYSICAL_ACTION);

  public int value ()
  {
    return __value;
  }

  public static motivation.idl.MotiveType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected MotiveType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class MotiveType
