# This file was auto generated
RELEASE = $(shell lsb_release -si)-$(shell lsb_release -sr)
default: build

clean: clean-$(RELEASE)

fetch: fetch-$(RELEASE)

checksum: checksum-$(RELEASE)

extract: extract-$(RELEASE)

patch: patch-$(RELEASE)

configure: configure-$(RELEASE)

build: build-$(RELEASE)

install: install-$(RELEASE)

clean-Ubuntu-11.04:
	cd gazebo-0.9 && make clean

fetch-Ubuntu-11.04:
	cd gazebo-0.9 && make fetch

checksum-Ubuntu-11.04:
	cd gazebo-0.9 && make checksum

extract-Ubuntu-11.04:
	cd gazebo-0.9 && make extract

patch-Ubuntu-11.04:
	cd gazebo-0.9 && make patch

configure-Ubuntu-11.04:
	cd gazebo-0.9 && make configure

build-Ubuntu-11.04:
	cd gazebo-0.9 && make build

install-Ubuntu-11.04:
	cd gazebo-0.9 && make install

clean-Ubuntu-11.10:
	cd gazebo-trunk && make clean

fetch-Ubuntu-11.10:
	cd gazebo-trunk && make fetch

checksum-Ubuntu-11.10:
	cd gazebo-trunk && make checksum

extract-Ubuntu-11.10:
	cd gazebo-trunk && make extract

patch-Ubuntu-11.10:
	cd gazebo-trunk && make patch

configure-Ubuntu-11.10:
	cd gazebo-trunk && make configure

build-Ubuntu-11.10:
	cd gazebo-trunk && make build

install-Ubuntu-11.10:
	cd gazebo-trunk && make install

