package org.cognitivesystems.comsys.autogen.ComsysEssentials;

/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/EventDiscRefRelationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class EventDiscRefRelationHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.EventDiscRefRelation value = null;

  public EventDiscRefRelationHolder ()
  {
  }

  public EventDiscRefRelationHolder (org.cognitivesystems.comsys.autogen.ComsysEssentials.EventDiscRefRelation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cognitivesystems.comsys.autogen.ComsysEssentials.EventDiscRefRelationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cognitivesystems.comsys.autogen.ComsysEssentials.EventDiscRefRelationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cognitivesystems.comsys.autogen.ComsysEssentials.EventDiscRefRelationHelper.type ();
  }

}
