package org.cognitivesystems.comsys.autogen.ComsysEssentials;


/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/EventDiscRefRelation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class EventDiscRefRelation implements org.omg.CORBA.portable.IDLEntity
{
  public String eventId = null;
  public String discRefId = null;
  public String mode = null;

  public EventDiscRefRelation ()
  {
  } // ctor

  public EventDiscRefRelation (String _eventId, String _discRefId, String _mode)
  {
    eventId = _eventId;
    discRefId = _discRefId;
    mode = _mode;
  } // ctor

} // class EventDiscRefRelation
