package org.cognitivesystems.comsys.autogen.ComsysEssentials;


/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/SDRSTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class SDRSTypeHelper
{
  private static String  _id = "IDL:org/cognitivesystems/comsys/autogen/ComsysEssentials/SDRSType:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [2];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for relation (case label 1)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)1);
      _tcOf_members0 = org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSRelationHelper.type ();
      _members0[0] = new org.omg.CORBA.UnionMember (
        "relation",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for plf (case label 2)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)2);
      _tcOf_members0 = org.cognitivesystems.comsys.autogen.ComsysEssentials.PackedLFsHelper.type ();
      _members0[1] = new org.omg.CORBA.UnionMember (
        "plf",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSTypeHelper.id (), "SDRSType", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSType read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSType value = new org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSType ();
    short _dis0 = (short)0;
    _dis0 = istream.read_short ();
    switch (_dis0)
    {
      case 1:
        org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSRelation _relation = null;
        _relation = org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSRelationHelper.read (istream);
        value.relation (_relation);
        break;
      case 2:
        org.cognitivesystems.comsys.autogen.ComsysEssentials.PackedLFs _plf = null;
        _plf = org.cognitivesystems.comsys.autogen.ComsysEssentials.PackedLFsHelper.read (istream);
        value.plf (_plf);
        break;
      default:
        value._default( _dis0 ) ;
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSType value)
  {
    ostream.write_short (value.discriminator ());
    switch (value.discriminator ())
    {
      case 1:
        org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSRelationHelper.write (ostream, value.relation ());
        break;
      case 2:
        org.cognitivesystems.comsys.autogen.ComsysEssentials.PackedLFsHelper.write (ostream, value.plf ());
        break;
    }
  }

}
