package org.cognitivesystems.comsys.autogen.ComsysEssentials;


/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/TemporalRelation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class TemporalRelation implements org.omg.CORBA.portable.IDLEntity
{
  public String eventSourceId = null;
  public String stateTargetId = null;
  public String tempRelation = null;

  public TemporalRelation ()
  {
  } // ctor

  public TemporalRelation (String _eventSourceId, String _stateTargetId, String _tempRelation)
  {
    eventSourceId = _eventSourceId;
    stateTargetId = _stateTargetId;
    tempRelation = _tempRelation;
  } // ctor

} // class TemporalRelation
