(define (domain ytilanoitisoporp)
(:requirements :action-costs :typing)
(:types boolean - object)
(:predicates (on ?b - boolean)
(off ?b - boolean)
(related ?b1 ?b2 - boolean)
(unrelated ?b - boolean))
(:functions (total-cost) - number
(switch-cost ?b - boolean) - number )
(:action switch-on
:parameters (?b1 ?b2 - boolean)
:precondition (and (off ?b1) (related ?b1 ?b2) )
:effect (and (not (off ?b1)) 
(off ?b2)
 (not (on ?b2))
(on ?b1)
(increase (total-cost) (switch-cost ?b1))
)
)
(:action unrelated-switch-on
:parameters (?b - boolean)
:precondition (and (off ?b) (unrelated ?b) )
:effect (and (not (off ?b)) 
(on ?b)
(increase (total-cost) (switch-cost ?b))
)
)
(:action switch-off
:parameters (?b - boolean)
:precondition (and (on ?b) )
:effect (and (not (on ?b))
(off ?b)
(increase (total-cost) (switch-cost ?b))
)
)
(:action super-switch
:parameters ()
:precondition ()
:effect (and 
(on o1 )
(not (off o1 ))
(not (on o2 ))
(off o2 )
(not (on o3 ))
(off o3 )
(not (on o4 ))
(off o4 )
(on o5 )
(not (off o5 ))
(not (on o6 ))
(off o6 )
(on o7 )
(not (off o7 ))
(on o8 )
(not (off o8 ))
(on o9 )
(not (off o9 ))
(on o10 )
(not (off o10 ))
(on o11 )
(not (off o11 ))
(not (on o12 ))
(off o12 )
(not (on o13 ))
(off o13 )
(not (on o14 ))
(off o14 )
(on o15 )
(not (off o15 ))
(not (on o16 ))
(off o16 )
(on o17 )
(not (off o17 ))
(not (on o18 ))
(off o18 )
(not (on o19 ))
(off o19 )
(on o20 )
(not (off o20 ))
(not (on o21 ))
(off o21 )
(on o22 )
(not (off o22 ))
(on o23 )
(not (off o23 ))
(on o24 )
(not (off o24 ))
(on o25 )
(not (off o25 ))
(not (on o26 ))
(off o26 )
(on o27 )
(not (off o27 ))
(on o28 )
(not (off o28 ))
(on o29 )
(not (off o29 ))
(on o30 )
(not (off o30 ))
(increase (total-cost) 100000))) 
)
