package BindingFeaturesCommon;


/**
* BindingFeaturesCommon/StartTime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingFeaturesCommon.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class StartTime implements org.omg.CORBA.portable.IDLEntity
{
  public balt.corba.autogen.FrameworkBasics.BALTTime m_t[] = null;

  public StartTime ()
  {
  } // ctor

  public StartTime (balt.corba.autogen.FrameworkBasics.BALTTime[] _m_t)
  {
    m_t = _m_t;
  } // ctor

} // class StartTime
