package cast.cdl;


/**
* cast/cdl/WorkingMemoryChangeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class WorkingMemoryChangeHelper
{
  private static String  _id = "IDL:cast/cdl/WorkingMemoryChange:1.0";

  public static void insert (org.omg.CORBA.Any a, cast.cdl.WorkingMemoryChange that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cast.cdl.WorkingMemoryChange extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = cast.cdl.WorkingMemoryOperationHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_operation",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (balt.corba.autogen.FrameworkBasics.FrameworkProcessIDHelper.id (), "FrameworkProcessID", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "m_src",
            _tcOf_members0,
            null);
          _tcOf_members0 = cast.cdl.WorkingMemoryAddressHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "m_address",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (cast.cdl.OntologyEntryHelper.id (), "OntologyEntry", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "m_type",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (cast.cdl.WorkingMemoryChangeHelper.id (), "WorkingMemoryChange", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cast.cdl.WorkingMemoryChange read (org.omg.CORBA.portable.InputStream istream)
  {
    cast.cdl.WorkingMemoryChange value = new cast.cdl.WorkingMemoryChange ();
    value.m_operation = cast.cdl.WorkingMemoryOperationHelper.read (istream);
    value.m_src = istream.read_string ();
    value.m_address = cast.cdl.WorkingMemoryAddressHelper.read (istream);
    value.m_type = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cast.cdl.WorkingMemoryChange value)
  {
    cast.cdl.WorkingMemoryOperationHelper.write (ostream, value.m_operation);
    ostream.write_string (value.m_src);
    cast.cdl.WorkingMemoryAddressHelper.write (ostream, value.m_address);
    ostream.write_string (value.m_type);
  }

}
