package cast.cdl;

/**
* cast/cdl/WorkingMemoryOperationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class WorkingMemoryOperationHolder implements org.omg.CORBA.portable.Streamable
{
  public cast.cdl.WorkingMemoryOperation value = null;

  public WorkingMemoryOperationHolder ()
  {
  }

  public WorkingMemoryOperationHolder (cast.cdl.WorkingMemoryOperation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cast.cdl.WorkingMemoryOperationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cast.cdl.WorkingMemoryOperationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cast.cdl.WorkingMemoryOperationHelper.type ();
  }

}
