package org.cognitivesystems.repr.lf.autogen.LFPacking;


/**
* org/cognitivesystems/repr/lf/autogen/LFPacking/PackingEdgeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LFPacking.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class PackingEdgeHelper
{
  private static String  _id = "IDL:org/cognitivesystems/repr/lf/autogen/LFPacking/PackingEdge:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cognitivesystems.repr.lf.autogen.LFPacking.PackingEdge that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cognitivesystems.repr.lf.autogen.LFPacking.PackingEdge extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.cognitivesystems.repr.lf.autogen.LFPacking.PackingEdgeIdHelper.id (), "PackingEdgeId", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "peId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "mode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.cognitivesystems.repr.lf.autogen.LFEssentials.nominalVariableHelper.id (), "nominalVariable", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.cognitivesystems.repr.lf.autogen.LFPacking.nominalVariableHelper.id (), "nominalVariable", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "head",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.cognitivesystems.repr.lf.autogen.LFPacking.PackingNodeTargetHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.cognitivesystems.repr.lf.autogen.LFPacking.PackingNodeTargetsHelper.id (), "PackingNodeTargets", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "targets",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[4] = new org.omg.CORBA.StructMember (
            "coIndexedDep",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[5] = new org.omg.CORBA.StructMember (
            "preferenceScore",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.cognitivesystems.repr.lf.autogen.LFPacking.PackingEdgeHelper.id (), "PackingEdge", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cognitivesystems.repr.lf.autogen.LFPacking.PackingEdge read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cognitivesystems.repr.lf.autogen.LFPacking.PackingEdge value = new org.cognitivesystems.repr.lf.autogen.LFPacking.PackingEdge ();
    value.peId = istream.read_string ();
    value.mode = istream.read_string ();
    value.head = istream.read_string ();
    value.targets = org.cognitivesystems.repr.lf.autogen.LFPacking.PackingNodeTargetsHelper.read (istream);
    value.coIndexedDep = istream.read_boolean ();
    value.preferenceScore = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cognitivesystems.repr.lf.autogen.LFPacking.PackingEdge value)
  {
    ostream.write_string (value.peId);
    ostream.write_string (value.mode);
    ostream.write_string (value.head);
    org.cognitivesystems.repr.lf.autogen.LFPacking.PackingNodeTargetsHelper.write (ostream, value.targets);
    ostream.write_boolean (value.coIndexedDep);
    ostream.write_float (value.preferenceScore);
  }

}
