# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Dec 23 09:21:03 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!
from cctextedit import CCastTextEdit

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(780, 550)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CAST Control", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tabWidget = QtGui.QTabWidget(self.frame_6)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabLogs = QtGui.QWidget()
        self.tabLogs.setObjectName(_fromUtf8("tabLogs"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabLogs)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.messageSourceCmbx = QtGui.QComboBox(self.tabLogs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageSourceCmbx.sizePolicy().hasHeightForWidth())
        self.messageSourceCmbx.setSizePolicy(sizePolicy)
        self.messageSourceCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.messageSourceCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "Active log", None, QtGui.QApplication.UnicodeUTF8))
        self.messageSourceCmbx.setMaxVisibleItems(20)
        self.messageSourceCmbx.setObjectName(_fromUtf8("messageSourceCmbx"))
        self.horizontalLayout_2.addWidget(self.messageSourceCmbx)
        self.componentFilterCmbx = QtGui.QComboBox(self.tabLogs)
        self.componentFilterCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.componentFilterCmbx.setObjectName(_fromUtf8("componentFilterCmbx"))
        self.horizontalLayout_2.addWidget(self.componentFilterCmbx)
        self.btEditFilterComponents = QtGui.QPushButton(self.tabLogs)
        self.btEditFilterComponents.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditFilterComponents.setObjectName(_fromUtf8("btEditFilterComponents"))
        self.horizontalLayout_2.addWidget(self.btEditFilterComponents)
        spacerItem = QtGui.QSpacerItem(88, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btClearMainLog = QtGui.QPushButton(self.tabLogs)
        self.btClearMainLog.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btClearMainLog.setObjectName(_fromUtf8("btClearMainLog"))
        self.horizontalLayout_2.addWidget(self.btClearMainLog)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.ckShowInternalMsgs = QtGui.QCheckBox(self.tabLogs)
        self.ckShowInternalMsgs.setToolTip(QtGui.QApplication.translate("MainWindow", "Show messages produced by CAST Control", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowInternalMsgs.setText(QtGui.QApplication.translate("MainWindow", "Internal", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowInternalMsgs.setChecked(True)
        self.ckShowInternalMsgs.setObjectName(_fromUtf8("ckShowInternalMsgs"))
        self.horizontalLayout_21.addWidget(self.ckShowInternalMsgs)
        self.ckShowFlushMsgs = QtGui.QCheckBox(self.tabLogs)
        self.ckShowFlushMsgs.setToolTip(QtGui.QApplication.translate("MainWindow", "Flush messages from the message queue after a process has terminated", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowFlushMsgs.setText(QtGui.QApplication.translate("MainWindow", "Flushed", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowFlushMsgs.setChecked(True)
        self.ckShowFlushMsgs.setObjectName(_fromUtf8("ckShowFlushMsgs"))
        self.horizontalLayout_21.addWidget(self.ckShowFlushMsgs)
        self.ckAutoClearLog = QtGui.QCheckBox(self.tabLogs)
        self.ckAutoClearLog.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear the log output when the client process starts", None, QtGui.QApplication.UnicodeUTF8))
        self.ckAutoClearLog.setText(QtGui.QApplication.translate("MainWindow", "AutoClear", None, QtGui.QApplication.UnicodeUTF8))
        self.ckAutoClearLog.setObjectName(_fromUtf8("ckAutoClearLog"))
        self.horizontalLayout_21.addWidget(self.ckAutoClearLog)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.tabLogs)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Levels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_21.addWidget(self.label_2)
        self.txtFnComponentLevels = QtGui.QLineEdit(self.tabLogs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtFnComponentLevels.sizePolicy().hasHeightForWidth())
        self.txtFnComponentLevels.setSizePolicy(sizePolicy)
        self.txtFnComponentLevels.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Liberation Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Set the filename of the file with logging levels for individual components. These settings will be appended to the log4j.properties file for clients. The file contains log4j options in the form:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&lt;sa-id&gt;.&lt;component-id&gt;=LOGLEVEL</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">eg.:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\';\">vision.sa.videoserver=INFO</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New,courier\';\"></p>\n"
"<p>Log levels:</p>\n"
"<p>ALL, TRACE, DEBUG, INFO, WARN, ERROR, FATAL</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.txtFnComponentLevels.setObjectName(_fromUtf8("txtFnComponentLevels"))
        self.horizontalLayout_21.addWidget(self.txtFnComponentLevels)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.mainLogfileTxt = CCastTextEdit(self.tabLogs)
        self.mainLogfileTxt.setUndoRedoEnabled(False)
        self.mainLogfileTxt.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.mainLogfileTxt.setObjectName(_fromUtf8("mainLogfileTxt"))
        self.verticalLayout.addWidget(self.mainLogfileTxt)
        self.tabWidget.addTab(self.tabLogs, _fromUtf8(""))
        self.tabBuildLog = QtGui.QWidget()
        self.tabBuildLog.setObjectName(_fromUtf8("tabBuildLog"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabBuildLog)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 4, -1, 4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblBuildMode = QtGui.QLabel(self.tabBuildLog)
        self.lblBuildMode.setText(QtGui.QApplication.translate("MainWindow", "Build:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBuildMode.setObjectName(_fromUtf8("lblBuildMode"))
        self.horizontalLayout_5.addWidget(self.lblBuildMode)
        self.cbRemoteBuildMode = QtGui.QComboBox(self.tabBuildLog)
        self.cbRemoteBuildMode.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cbRemoteBuildMode.setObjectName(_fromUtf8("cbRemoteBuildMode"))
        self.cbRemoteBuildMode.addItem(_fromUtf8(""))
        self.cbRemoteBuildMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Local and Remote", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_5.addWidget(self.cbRemoteBuildMode)
        self.ckAutoSyncCode = QtGui.QCheckBox(self.tabBuildLog)
        self.ckAutoSyncCode.setToolTip(QtGui.QApplication.translate("MainWindow", "Synchronize the code on remote hosts before every build", None, QtGui.QApplication.UnicodeUTF8))
        self.ckAutoSyncCode.setText(QtGui.QApplication.translate("MainWindow", "Auto Synchronize", None, QtGui.QApplication.UnicodeUTF8))
        self.ckAutoSyncCode.setChecked(True)
        self.ckAutoSyncCode.setObjectName(_fromUtf8("ckAutoSyncCode"))
        self.horizontalLayout_5.addWidget(self.ckAutoSyncCode)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btSynchronize = QtGui.QPushButton(self.tabBuildLog)
        self.btSynchronize.setToolTip(QtGui.QApplication.translate("MainWindow", "Synchronize the code on remote hosts", None, QtGui.QApplication.UnicodeUTF8))
        self.btSynchronize.setText(QtGui.QApplication.translate("MainWindow", "Synchronize", None, QtGui.QApplication.UnicodeUTF8))
        self.btSynchronize.setObjectName(_fromUtf8("btSynchronize"))
        self.horizontalLayout_5.addWidget(self.btSynchronize)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.buildLogfileTxt = CCastTextEdit(self.tabBuildLog)
        self.buildLogfileTxt.setUndoRedoEnabled(False)
        self.buildLogfileTxt.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.buildLogfileTxt.setObjectName(_fromUtf8("buildLogfileTxt"))
        self.verticalLayout_6.addWidget(self.buildLogfileTxt)
        self.tabWidget.addTab(self.tabBuildLog, _fromUtf8(""))
        self.tabConfigure = QtGui.QWidget()
        self.tabConfigure.setObjectName(_fromUtf8("tabConfigure"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabConfigure)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_4 = QtGui.QFrame(self.tabConfigure)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_4 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Hosts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_15.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "localhost:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_15.addWidget(self.label_5)
        self.txtLocalHost = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLocalHost.sizePolicy().hasHeightForWidth())
        self.txtLocalHost.setSizePolicy(sizePolicy)
        self.txtLocalHost.setMinimumSize(QtCore.QSize(160, 0))
        self.txtLocalHost.setText(_fromUtf8(""))
        self.txtLocalHost.setMaxLength(128)
        self.txtLocalHost.setObjectName(_fromUtf8("txtLocalHost"))
        self.horizontalLayout_15.addWidget(self.txtLocalHost)
        self.btDetectLocalHost = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDetectLocalHost.sizePolicy().hasHeightForWidth())
        self.btDetectLocalHost.setSizePolicy(sizePolicy)
        self.btDetectLocalHost.setToolTip(QtGui.QApplication.translate("MainWindow", "Detect the address of the local machine.", None, QtGui.QApplication.UnicodeUTF8))
        self.btDetectLocalHost.setText(QtGui.QApplication.translate("MainWindow", "Detect", None, QtGui.QApplication.UnicodeUTF8))
        self.btDetectLocalHost.setObjectName(_fromUtf8("btDetectLocalHost"))
        self.horizontalLayout_15.addWidget(self.btDetectLocalHost)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.btDiscoverRemote = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDiscoverRemote.sizePolicy().hasHeightForWidth())
        self.btDiscoverRemote.setSizePolicy(sizePolicy)
        self.btDiscoverRemote.setToolTip(QtGui.QApplication.translate("MainWindow", "Discover CASTControl Agents on remote machines. See the Logs for results.", None, QtGui.QApplication.UnicodeUTF8))
        self.btDiscoverRemote.setText(QtGui.QApplication.translate("MainWindow", "Discover Agents", None, QtGui.QApplication.UnicodeUTF8))
        self.btDiscoverRemote.setObjectName(_fromUtf8("btDiscoverRemote"))
        self.horizontalLayout_15.addWidget(self.btDiscoverRemote)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_16.addWidget(self.label_10)
        self.hostConfigCmbx = QtGui.QComboBox(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostConfigCmbx.sizePolicy().hasHeightForWidth())
        self.hostConfigCmbx.setSizePolicy(sizePolicy)
        self.hostConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.hostConfigCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "CAST configuration file ", None, QtGui.QApplication.UnicodeUTF8))
        self.hostConfigCmbx.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.hostConfigCmbx.setMinimumContentsLength(32)
        self.hostConfigCmbx.setObjectName(_fromUtf8("hostConfigCmbx"))
        self.horizontalLayout_16.addWidget(self.hostConfigCmbx)
        self.btBrowseHostFile = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btBrowseHostFile.sizePolicy().hasHeightForWidth())
        self.btBrowseHostFile.setSizePolicy(sizePolicy)
        self.btBrowseHostFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowseHostFile.setObjectName(_fromUtf8("btBrowseHostFile"))
        self.horizontalLayout_16.addWidget(self.btBrowseHostFile)
        self.btEditHostConfig = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btEditHostConfig.sizePolicy().hasHeightForWidth())
        self.btEditHostConfig.setSizePolicy(sizePolicy)
        self.btEditHostConfig.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditHostConfig.setObjectName(_fromUtf8("btEditHostConfig"))
        self.horizontalLayout_16.addWidget(self.btEditHostConfig)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_11 = QtGui.QFrame(self.tabConfigure)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.frame_11)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_3 = QtGui.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Client", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_17.addWidget(self.label_3)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_6 = QtGui.QLabel(self.frame_11)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_14.addWidget(self.label_6)
        self.clientConfigCmbx = QtGui.QComboBox(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientConfigCmbx.sizePolicy().hasHeightForWidth())
        self.clientConfigCmbx.setSizePolicy(sizePolicy)
        self.clientConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.clientConfigCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "CAST configuration file ", None, QtGui.QApplication.UnicodeUTF8))
        self.clientConfigCmbx.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.clientConfigCmbx.setMinimumContentsLength(32)
        self.clientConfigCmbx.setObjectName(_fromUtf8("clientConfigCmbx"))
        self.horizontalLayout_14.addWidget(self.clientConfigCmbx)
        self.btBrowseCastFile = QtGui.QPushButton(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btBrowseCastFile.sizePolicy().hasHeightForWidth())
        self.btBrowseCastFile.setSizePolicy(sizePolicy)
        self.btBrowseCastFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowseCastFile.setObjectName(_fromUtf8("btBrowseCastFile"))
        self.horizontalLayout_14.addWidget(self.btBrowseCastFile)
        self.btEditClientConfig = QtGui.QPushButton(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btEditClientConfig.sizePolicy().hasHeightForWidth())
        self.btEditClientConfig.setSizePolicy(sizePolicy)
        self.btEditClientConfig.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditClientConfig.setObjectName(_fromUtf8("btEditClientConfig"))
        self.horizontalLayout_14.addWidget(self.btEditClientConfig)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.frmLoggingSettings = QtGui.QFrame(self.tabConfigure)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmLoggingSettings.sizePolicy().hasHeightForWidth())
        self.frmLoggingSettings.setSizePolicy(sizePolicy)
        self.frmLoggingSettings.setMinimumSize(QtCore.QSize(0, 0))
        self.frmLoggingSettings.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmLoggingSettings.setFrameShadow(QtGui.QFrame.Raised)
        self.frmLoggingSettings.setObjectName(_fromUtf8("frmLoggingSettings"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frmLoggingSettings)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_19 = QtGui.QLabel(self.frmLoggingSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Logging", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_4.addWidget(self.label_19)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label_9 = QtGui.QLabel(self.frmLoggingSettings)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.cbLog4jMode = QtGui.QComboBox(self.frmLoggingSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbLog4jMode.sizePolicy().hasHeightForWidth())
        self.cbLog4jMode.setSizePolicy(sizePolicy)
        self.cbLog4jMode.setMinimumSize(QtCore.QSize(212, 0))
        self.cbLog4jMode.setObjectName(_fromUtf8("cbLog4jMode"))
        self.cbLog4jMode.addItem(_fromUtf8(""))
        self.cbLog4jMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Log4j Server", None, QtGui.QApplication.UnicodeUTF8))
        self.cbLog4jMode.addItem(_fromUtf8(""))
        self.cbLog4jMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "CAST Log Server", None, QtGui.QApplication.UnicodeUTF8))
        self.cbLog4jMode.addItem(_fromUtf8(""))
        self.cbLog4jMode.setItemText(2, QtGui.QApplication.translate("MainWindow", "Log to Console (No Server)", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_4.addWidget(self.cbLog4jMode)
        self.ckStartLogServer = QtGui.QCheckBox(self.frmLoggingSettings)
        self.ckStartLogServer.setText(QtGui.QApplication.translate("MainWindow", "Start server", None, QtGui.QApplication.UnicodeUTF8))
        self.ckStartLogServer.setObjectName(_fromUtf8("ckStartLogServer"))
        self.horizontalLayout_4.addWidget(self.ckStartLogServer)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horzLayoutHost = QtGui.QHBoxLayout()
        self.horzLayoutHost.setObjectName(_fromUtf8("horzLayoutHost"))
        self.label = QtGui.QLabel(self.frmLoggingSettings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Log4j Server Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horzLayoutHost.addWidget(self.label)
        self.cbLog4jServerHost = QtGui.QComboBox(self.frmLoggingSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbLog4jServerHost.sizePolicy().hasHeightForWidth())
        self.cbLog4jServerHost.setSizePolicy(sizePolicy)
        self.cbLog4jServerHost.setMinimumSize(QtCore.QSize(212, 0))
        self.cbLog4jServerHost.setEditable(True)
        self.cbLog4jServerHost.setObjectName(_fromUtf8("cbLog4jServerHost"))
        self.horzLayoutHost.addWidget(self.cbLog4jServerHost)
        self.label_7 = QtGui.QLabel(self.frmLoggingSettings)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horzLayoutHost.addWidget(self.label_7)
        self.edLog4jServerPort = QtGui.QLineEdit(self.frmLoggingSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edLog4jServerPort.sizePolicy().hasHeightForWidth())
        self.edLog4jServerPort.setSizePolicy(sizePolicy)
        self.edLog4jServerPort.setMinimumSize(QtCore.QSize(0, 0))
        self.edLog4jServerPort.setMaximumSize(QtCore.QSize(120, 16777215))
        self.edLog4jServerPort.setText(QtGui.QApplication.translate("MainWindow", "48143", None, QtGui.QApplication.UnicodeUTF8))
        self.edLog4jServerPort.setMaxLength(8)
        self.edLog4jServerPort.setObjectName(_fromUtf8("edLog4jServerPort"))
        self.horzLayoutHost.addWidget(self.edLog4jServerPort)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horzLayoutHost.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horzLayoutHost)
        self.horzLayoutConsoleLevel = QtGui.QHBoxLayout()
        self.horzLayoutConsoleLevel.setObjectName(_fromUtf8("horzLayoutConsoleLevel"))
        self.label_12 = QtGui.QLabel(self.frmLoggingSettings)
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Console Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horzLayoutConsoleLevel.addWidget(self.label_12)
        self.log4jConsoleLevelCmbx = QtGui.QComboBox(self.frmLoggingSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log4jConsoleLevelCmbx.sizePolicy().hasHeightForWidth())
        self.log4jConsoleLevelCmbx.setSizePolicy(sizePolicy)
        self.log4jConsoleLevelCmbx.setMinimumSize(QtCore.QSize(0, 0))
        self.log4jConsoleLevelCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "The logging level for the console.", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.setObjectName(_fromUtf8("log4jConsoleLevelCmbx"))
        self.log4jConsoleLevelCmbx.addItem(_fromUtf8(""))
        self.log4jConsoleLevelCmbx.setItemText(0, QtGui.QApplication.translate("MainWindow", "ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.addItem(_fromUtf8(""))
        self.log4jConsoleLevelCmbx.setItemText(1, QtGui.QApplication.translate("MainWindow", "TRACE", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.addItem(_fromUtf8(""))
        self.log4jConsoleLevelCmbx.setItemText(2, QtGui.QApplication.translate("MainWindow", "DEBUG", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.addItem(_fromUtf8(""))
        self.log4jConsoleLevelCmbx.setItemText(3, QtGui.QApplication.translate("MainWindow", "INFO", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.addItem(_fromUtf8(""))
        self.log4jConsoleLevelCmbx.setItemText(4, QtGui.QApplication.translate("MainWindow", "WARN", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.addItem(_fromUtf8(""))
        self.log4jConsoleLevelCmbx.setItemText(5, QtGui.QApplication.translate("MainWindow", "ERROR", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.addItem(_fromUtf8(""))
        self.log4jConsoleLevelCmbx.setItemText(6, QtGui.QApplication.translate("MainWindow", "FATAL", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jConsoleLevelCmbx.addItem(_fromUtf8(""))
        self.log4jConsoleLevelCmbx.setItemText(7, QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.horzLayoutConsoleLevel.addWidget(self.log4jConsoleLevelCmbx)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horzLayoutConsoleLevel.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horzLayoutConsoleLevel)
        self.horzLayoutXmlLevel = QtGui.QHBoxLayout()
        self.horzLayoutXmlLevel.setObjectName(_fromUtf8("horzLayoutXmlLevel"))
        self.label_16 = QtGui.QLabel(self.frmLoggingSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "XML File Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horzLayoutXmlLevel.addWidget(self.label_16)
        self.log4jFileLevelCmbx = QtGui.QComboBox(self.frmLoggingSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log4jFileLevelCmbx.sizePolicy().hasHeightForWidth())
        self.log4jFileLevelCmbx.setSizePolicy(sizePolicy)
        self.log4jFileLevelCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "The logging level for the XML file (only available when log4j server is used)", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jFileLevelCmbx.setObjectName(_fromUtf8("log4jFileLevelCmbx"))
        self.log4jFileLevelCmbx.addItem(_fromUtf8(""))
        self.log4jFileLevelCmbx.setItemText(0, QtGui.QApplication.translate("MainWindow", "ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jFileLevelCmbx.addItem(_fromUtf8(""))
        self.log4jFileLevelCmbx.setItemText(1, QtGui.QApplication.translate("MainWindow", "TRACE", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jFileLevelCmbx.addItem(_fromUtf8(""))
        self.log4jFileLevelCmbx.setItemText(2, QtGui.QApplication.translate("MainWindow", "DEBUG", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jFileLevelCmbx.addItem(_fromUtf8(""))
        self.log4jFileLevelCmbx.setItemText(3, QtGui.QApplication.translate("MainWindow", "INFO", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jFileLevelCmbx.addItem(_fromUtf8(""))
        self.log4jFileLevelCmbx.setItemText(4, QtGui.QApplication.translate("MainWindow", "WARN", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jFileLevelCmbx.addItem(_fromUtf8(""))
        self.log4jFileLevelCmbx.setItemText(5, QtGui.QApplication.translate("MainWindow", "ERROR", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jFileLevelCmbx.addItem(_fromUtf8(""))
        self.log4jFileLevelCmbx.setItemText(6, QtGui.QApplication.translate("MainWindow", "FATAL", None, QtGui.QApplication.UnicodeUTF8))
        self.log4jFileLevelCmbx.addItem(_fromUtf8(""))
        self.log4jFileLevelCmbx.setItemText(7, QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.horzLayoutXmlLevel.addWidget(self.log4jFileLevelCmbx)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horzLayoutXmlLevel.addItem(spacerItem9)
        self.label_11 = QtGui.QLabel(self.frmLoggingSettings)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horzLayoutXmlLevel.addWidget(self.label_11)
        self.edLog4jOutfile = QtGui.QLineEdit(self.frmLoggingSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edLog4jOutfile.sizePolicy().hasHeightForWidth())
        self.edLog4jOutfile.setSizePolicy(sizePolicy)
        self.edLog4jOutfile.setMinimumSize(QtCore.QSize(212, 0))
        self.edLog4jOutfile.setText(QtGui.QApplication.translate("MainWindow", "logs/log.xml", None, QtGui.QApplication.UnicodeUTF8))
        self.edLog4jOutfile.setMaxLength(256)
        self.edLog4jOutfile.setObjectName(_fromUtf8("edLog4jOutfile"))
        self.horzLayoutXmlLevel.addWidget(self.edLog4jOutfile)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horzLayoutXmlLevel.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horzLayoutXmlLevel)
        self.verticalLayout_3.addWidget(self.frmLoggingSettings)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.tabWidget.addTab(self.tabConfigure, _fromUtf8(""))
        self.tabProcessConfig = QtGui.QWidget()
        self.tabProcessConfig.setObjectName(_fromUtf8("tabProcessConfig"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.tabProcessConfig)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.processGroupPanel = QtGui.QWidget(self.tabProcessConfig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processGroupPanel.sizePolicy().hasHeightForWidth())
        self.processGroupPanel.setSizePolicy(sizePolicy)
        self.processGroupPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.processGroupPanel.setObjectName(_fromUtf8("processGroupPanel"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.processGroupPanel)
        self.verticalLayout_20.setMargin(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_17 = QtGui.QLabel(self.processGroupPanel)
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_27.addWidget(self.label_17)
        self.processHostCmbx = QtGui.QComboBox(self.processGroupPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processHostCmbx.sizePolicy().hasHeightForWidth())
        self.processHostCmbx.setSizePolicy(sizePolicy)
        self.processHostCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.processHostCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "Player configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.processHostCmbx.setObjectName(_fromUtf8("processHostCmbx"))
        self.horizontalLayout_27.addWidget(self.processHostCmbx)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem12)
        self.label_18 = QtGui.QLabel(self.processGroupPanel)
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Group:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_27.addWidget(self.label_18)
        self.processGroupCmbx = QtGui.QComboBox(self.processGroupPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processGroupCmbx.sizePolicy().hasHeightForWidth())
        self.processGroupCmbx.setSizePolicy(sizePolicy)
        self.processGroupCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.processGroupCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "Player configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.processGroupCmbx.setObjectName(_fromUtf8("processGroupCmbx"))
        self.horizontalLayout_27.addWidget(self.processGroupCmbx)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem13)
        self.verticalLayout_20.addLayout(self.horizontalLayout_27)
        self.verticalLayout_21.addWidget(self.processGroupPanel)
        self.applicationTreeView = QtGui.QWidget(self.tabProcessConfig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applicationTreeView.sizePolicy().hasHeightForWidth())
        self.applicationTreeView.setSizePolicy(sizePolicy)
        self.applicationTreeView.setObjectName(_fromUtf8("applicationTreeView"))
        self.verticalLayout_21.addWidget(self.applicationTreeView)
        self.tabWidget.addTab(self.tabProcessConfig, _fromUtf8(""))
        self.tabOldInterface = QtGui.QWidget()
        self.tabOldInterface.setEnabled(False)
        self.tabOldInterface.setObjectName(_fromUtf8("tabOldInterface"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.tabOldInterface)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.frame_10 = QtGui.QFrame(self.tabOldInterface)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.widget_3 = QtGui.QWidget(self.frame_10)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_23.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.ckRunPlayer = QtGui.QCheckBox(self.widget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ckRunPlayer.setFont(font)
        self.ckRunPlayer.setToolTip(QtGui.QApplication.translate("MainWindow", "Run Player/Stage with External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunPlayer.setText(QtGui.QApplication.translate("MainWindow", "Run Player", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunPlayer.setChecked(False)
        self.ckRunPlayer.setObjectName(_fromUtf8("ckRunPlayer"))
        self.horizontalLayout_23.addWidget(self.ckRunPlayer)
        spacerItem14 = QtGui.QSpacerItem(473, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem14)
        self.verticalLayout_14.addWidget(self.widget_3)
        self.playerConfigPanel = QtGui.QWidget(self.frame_10)
        self.playerConfigPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.playerConfigPanel.setObjectName(_fromUtf8("playerConfigPanel"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.playerConfigPanel)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_8 = QtGui.QLabel(self.playerConfigPanel)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_12.addWidget(self.label_8)
        self.playerConfigCmbx = QtGui.QComboBox(self.playerConfigPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerConfigCmbx.sizePolicy().hasHeightForWidth())
        self.playerConfigCmbx.setSizePolicy(sizePolicy)
        self.playerConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.playerConfigCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "Player configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.playerConfigCmbx.setObjectName(_fromUtf8("playerConfigCmbx"))
        self.horizontalLayout_12.addWidget(self.playerConfigCmbx)
        self.btBrowsePlayerFile = QtGui.QPushButton(self.playerConfigPanel)
        self.btBrowsePlayerFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowsePlayerFile.setObjectName(_fromUtf8("btBrowsePlayerFile"))
        self.horizontalLayout_12.addWidget(self.btBrowsePlayerFile)
        self.btEditPlayerConfig = QtGui.QPushButton(self.playerConfigPanel)
        self.btEditPlayerConfig.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditPlayerConfig.setObjectName(_fromUtf8("btEditPlayerConfig"))
        self.horizontalLayout_12.addWidget(self.btEditPlayerConfig)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout_14.addWidget(self.playerConfigPanel)
        self.verticalLayout_19.addWidget(self.frame_10)
        self.frame_7 = QtGui.QFrame(self.tabOldInterface)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.widget = QtGui.QWidget(self.frame_7)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_20.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.ckRunPeekabot = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ckRunPeekabot.setFont(font)
        self.ckRunPeekabot.setToolTip(QtGui.QApplication.translate("MainWindow", "Run Peekabot with External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunPeekabot.setText(QtGui.QApplication.translate("MainWindow", "Run Peekabot", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunPeekabot.setChecked(False)
        self.ckRunPeekabot.setObjectName(_fromUtf8("ckRunPeekabot"))
        self.horizontalLayout_20.addWidget(self.ckRunPeekabot)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem15)
        self.verticalLayout_12.addWidget(self.widget)
        self.verticalLayout_19.addWidget(self.frame_7)
        self.frame_9 = QtGui.QFrame(self.tabOldInterface)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.widget_4 = QtGui.QWidget(self.frame_9)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_24.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.ckRunDisplaySrv = QtGui.QCheckBox(self.widget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ckRunDisplaySrv.setFont(font)
        self.ckRunDisplaySrv.setText(QtGui.QApplication.translate("MainWindow", "Run Standalone Display Server", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunDisplaySrv.setChecked(False)
        self.ckRunDisplaySrv.setObjectName(_fromUtf8("ckRunDisplaySrv"))
        self.horizontalLayout_24.addWidget(self.ckRunDisplaySrv)
        spacerItem16 = QtGui.QSpacerItem(360, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem16)
        self.verticalLayout_11.addWidget(self.widget_4)
        self.verticalLayout_19.addWidget(self.frame_9)
        self.frame_12 = QtGui.QFrame(self.tabOldInterface)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frame_12)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.widget_5 = QtGui.QWidget(self.frame_12)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_25.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.ckRunAbducerServer = QtGui.QCheckBox(self.widget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ckRunAbducerServer.setFont(font)
        self.ckRunAbducerServer.setText(QtGui.QApplication.translate("MainWindow", "Run Abducer Server", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunAbducerServer.setObjectName(_fromUtf8("ckRunAbducerServer"))
        self.horizontalLayout_25.addWidget(self.ckRunAbducerServer)
        spacerItem17 = QtGui.QSpacerItem(420, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem17)
        self.verticalLayout_15.addWidget(self.widget_5)
        self.verticalLayout_19.addWidget(self.frame_12)
        self.frame_13 = QtGui.QFrame(self.tabOldInterface)
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.frame_13)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.widget_6 = QtGui.QWidget(self.frame_13)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_26.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.ckRunSpeechServer = QtGui.QCheckBox(self.widget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ckRunSpeechServer.setFont(font)
        self.ckRunSpeechServer.setText(QtGui.QApplication.translate("MainWindow", "Run Mary TTS Server", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunSpeechServer.setObjectName(_fromUtf8("ckRunSpeechServer"))
        self.horizontalLayout_26.addWidget(self.ckRunSpeechServer)
        spacerItem18 = QtGui.QSpacerItem(420, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem18)
        self.verticalLayout_18.addWidget(self.widget_6)
        self.verticalLayout_19.addWidget(self.frame_13)
        self.frame_golem = QtGui.QFrame(self.tabOldInterface)
        self.frame_golem.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_golem.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_golem.setObjectName(_fromUtf8("frame_golem"))
        self.verticalLayout_golem = QtGui.QVBoxLayout(self.frame_golem)
        self.verticalLayout_golem.setObjectName(_fromUtf8("verticalLayout_golem"))
        self.widget_golem = QtGui.QWidget(self.frame_golem)
        self.widget_golem.setObjectName(_fromUtf8("widget_golem"))
        self.horizontalLayout_golem = QtGui.QHBoxLayout(self.widget_golem)
        self.horizontalLayout_golem.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_golem.setObjectName(_fromUtf8("horizontalLayout_golem"))
        self.ckRunGolem = QtGui.QCheckBox(self.widget_golem)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ckRunGolem.setFont(font)
        self.ckRunGolem.setToolTip(QtGui.QApplication.translate("MainWindow", "Run Golem with External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunGolem.setText(QtGui.QApplication.translate("MainWindow", "Run Golem", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRunGolem.setChecked(False)
        self.ckRunGolem.setObjectName(_fromUtf8("ckRunGolem"))
        self.horizontalLayout_golem.addWidget(self.ckRunGolem)
        spacerItem19 = QtGui.QSpacerItem(473, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_golem.addItem(spacerItem19)
        self.verticalLayout_golem.addWidget(self.widget_golem)
        self.golemConfigPanel = QtGui.QWidget(self.frame_golem)
        self.golemConfigPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.golemConfigPanel.setObjectName(_fromUtf8("golemConfigPanel"))
        self.verticalLayout_golem1 = QtGui.QVBoxLayout(self.golemConfigPanel)
        self.verticalLayout_golem1.setMargin(0)
        self.verticalLayout_golem1.setObjectName(_fromUtf8("verticalLayout_golem1"))
        self.horizontalLayout_golem1 = QtGui.QHBoxLayout()
        self.horizontalLayout_golem1.setObjectName(_fromUtf8("horizontalLayout_golem1"))
        self.label_golem = QtGui.QLabel(self.golemConfigPanel)
        self.label_golem.setText(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_golem.setObjectName(_fromUtf8("label_golem"))
        self.horizontalLayout_golem1.addWidget(self.label_golem)
        self.golemConfigCmbx = QtGui.QComboBox(self.golemConfigPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.golemConfigCmbx.sizePolicy().hasHeightForWidth())
        self.golemConfigCmbx.setSizePolicy(sizePolicy)
        self.golemConfigCmbx.setMinimumSize(QtCore.QSize(200, 0))
        self.golemConfigCmbx.setStatusTip(QtGui.QApplication.translate("MainWindow", "Golem configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.golemConfigCmbx.setObjectName(_fromUtf8("golemConfigCmbx"))
        self.horizontalLayout_golem1.addWidget(self.golemConfigCmbx)
        self.btBrowseGolemFile = QtGui.QPushButton(self.golemConfigPanel)
        self.btBrowseGolemFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btBrowseGolemFile.setObjectName(_fromUtf8("btBrowseGolemFile"))
        self.horizontalLayout_golem1.addWidget(self.btBrowseGolemFile)
        self.btEditGolemConfig = QtGui.QPushButton(self.golemConfigPanel)
        self.btEditGolemConfig.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btEditGolemConfig.setObjectName(_fromUtf8("btEditGolemConfig"))
        self.horizontalLayout_golem1.addWidget(self.btEditGolemConfig)
        self.verticalLayout_golem1.addLayout(self.horizontalLayout_golem1)
        self.verticalLayout_golem.addWidget(self.golemConfigPanel)
        self.verticalLayout_19.addWidget(self.frame_golem)
        spacerItem20 = QtGui.QSpacerItem(20, 176, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem20)
        self.tabWidget.addTab(self.tabOldInterface, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.frame_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCast = QtGui.QMenu(self.menubar)
        self.menuCast.setTitle(QtGui.QApplication.translate("MainWindow", "&Cast", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCast.setObjectName(_fromUtf8("menuCast"))
        self.menu_Process = QtGui.QMenu(self.menubar)
        self.menu_Process.setTitle(QtGui.QApplication.translate("MainWindow", "&Process", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Process.setObjectName(_fromUtf8("menu_Process"))
        self.menu_Build = QtGui.QMenu(self.menubar)
        self.menu_Build.setTitle(QtGui.QApplication.translate("MainWindow", "&Build", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Build.setObjectName(_fromUtf8("menu_Build"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Process tree", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.processTree = QtGui.QTreeView(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processTree.sizePolicy().hasHeightForWidth())
        self.processTree.setSizePolicy(sizePolicy)
        self.processTree.setMinimumSize(QtCore.QSize(200, 0))
        self.processTree.setMaximumSize(QtCore.QSize(400, 16777215))
        self.processTree.setObjectName(_fromUtf8("processTree"))
        self.verticalLayout_9.addWidget(self.processTree)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.processBar = QtGui.QToolBar(MainWindow)
        self.processBar.setMinimumSize(QtCore.QSize(0, 0))
        self.processBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.processBar.setIconSize(QtCore.QSize(24, 24))
        self.processBar.setObjectName(_fromUtf8("processBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.processBar)
        self.buildBar = QtGui.QToolBar(MainWindow)
        self.buildBar.setMinimumSize(QtCore.QSize(0, 0))
        self.buildBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.buildBar.setIconSize(QtCore.QSize(24, 24))
        self.buildBar.setObjectName(_fromUtf8("buildBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.buildBar)
        self.actQuit = QtGui.QAction(MainWindow)
        self.actQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actQuit.setObjectName(_fromUtf8("actQuit"))
        self.actOpenClientConfig = QtGui.QAction(MainWindow)
        self.actOpenClientConfig.setText(QtGui.QApplication.translate("MainWindow", "Select Client Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenClientConfig.setObjectName(_fromUtf8("actOpenClientConfig"))
        self.actOpenPlayerConfig = QtGui.QAction(MainWindow)
        self.actOpenPlayerConfig.setText(QtGui.QApplication.translate("MainWindow", "Select Player Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenPlayerConfig.setObjectName(_fromUtf8("actOpenPlayerConfig"))
        self.actSelectLog4jHost = QtGui.QAction(MainWindow)
        self.actSelectLog4jHost.setText(QtGui.QApplication.translate("MainWindow", "Select Log4j Host", None, QtGui.QApplication.UnicodeUTF8))
        self.actSelectLog4jHost.setToolTip(QtGui.QApplication.translate("MainWindow", "Select Log4j Host", None, QtGui.QApplication.UnicodeUTF8))
        self.actSelectLog4jHost.setObjectName(_fromUtf8("actSelectLog4jHost"))
        self.actShowEnv = QtGui.QAction(MainWindow)
        self.actShowEnv.setText(QtGui.QApplication.translate("MainWindow", "Show environment in log", None, QtGui.QApplication.UnicodeUTF8))
        self.actShowEnv.setToolTip(QtGui.QApplication.translate("MainWindow", "Write the environment to the log window", None, QtGui.QApplication.UnicodeUTF8))
        self.actShowEnv.setObjectName(_fromUtf8("actShowEnv"))
        self.actCtxShowBuildError = QtGui.QAction(MainWindow)
        self.actCtxShowBuildError.setText(QtGui.QApplication.translate("MainWindow", "Show code", None, QtGui.QApplication.UnicodeUTF8))
        self.actCtxShowBuildError.setObjectName(_fromUtf8("actCtxShowBuildError"))
        self.actStartTerminal = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/terminal.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStartTerminal.setIcon(icon)
        self.actStartTerminal.setText(QtGui.QApplication.translate("MainWindow", "Start Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartTerminal.setToolTip(QtGui.QApplication.translate("MainWindow", "Start Terminal (Configured in castcontrol.conf)", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartTerminal.setObjectName(_fromUtf8("actStartTerminal"))
        self.actOpenHostConfig = QtGui.QAction(MainWindow)
        self.actOpenHostConfig.setText(QtGui.QApplication.translate("MainWindow", "Select Host Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenHostConfig.setObjectName(_fromUtf8("actOpenHostConfig"))
        self.actStartCastServers = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/castStart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/system-run.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStartCastServers.setIcon(icon1)
        self.actStartCastServers.setText(QtGui.QApplication.translate("MainWindow", "Start CAST Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartCastServers.setShortcut(QtGui.QApplication.translate("MainWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartCastServers.setObjectName(_fromUtf8("actStartCastServers"))
        self.actStopCastServers = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/castStop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/system-suspend.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStopCastServers.setIcon(icon2)
        self.actStopCastServers.setText(QtGui.QApplication.translate("MainWindow", "Stop CAST Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopCastServers.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopCastServers.setObjectName(_fromUtf8("actStopCastServers"))
        self.actStartCastClient = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/cogxStart.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStartCastClient.setIcon(icon3)
        self.actStartCastClient.setText(QtGui.QApplication.translate("MainWindow", "Start CAST Client", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartCastClient.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartCastClient.setObjectName(_fromUtf8("actStartCastClient"))
        self.actStopCastClient = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/cogxStop.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStopCastClient.setIcon(icon4)
        self.actStopCastClient.setText(QtGui.QApplication.translate("MainWindow", "Stop CAST Client", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopCastClient.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopCastClient.setObjectName(_fromUtf8("actStopCastClient"))
        self.actStartExternalServers = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/serverStart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/go-up.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStartExternalServers.setIcon(icon5)
        self.actStartExternalServers.setText(QtGui.QApplication.translate("MainWindow", "Start External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartExternalServers.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actStartExternalServers.setObjectName(_fromUtf8("actStartExternalServers"))
        self.actStopExternalServers = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/serverStop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/go-down.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actStopExternalServers.setIcon(icon6)
        self.actStopExternalServers.setText(QtGui.QApplication.translate("MainWindow", "Stop External Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopExternalServers.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopExternalServers.setObjectName(_fromUtf8("actStopExternalServers"))
        self.actEnableCleanupScript = QtGui.QAction(MainWindow)
        self.actEnableCleanupScript.setCheckable(True)
        self.actEnableCleanupScript.setChecked(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/shellscriptOff.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/shellscriptOn.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actEnableCleanupScript.setIcon(icon7)
        self.actEnableCleanupScript.setText(QtGui.QApplication.translate("MainWindow", "Enable Cleanup Script", None, QtGui.QApplication.UnicodeUTF8))
        self.actEnableCleanupScript.setToolTip(QtGui.QApplication.translate("MainWindow", "Enable Cleanup Script (will be executed before CAST servers start)", None, QtGui.QApplication.UnicodeUTF8))
        self.actEnableCleanupScript.setObjectName(_fromUtf8("actEnableCleanupScript"))
        self.actRunMake = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/iconBuild.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/svn-update.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actRunMake.setIcon(icon8)
        self.actRunMake.setText(QtGui.QApplication.translate("MainWindow", "Make", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMake.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F8", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMake.setObjectName(_fromUtf8("actRunMake"))
        self.actRunMakeInstall = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/iconBuildInstall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/svn-commit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actRunMakeInstall.setIcon(icon9)
        self.actRunMakeInstall.setText(QtGui.QApplication.translate("MainWindow", "Make Install", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMakeInstall.setShortcut(QtGui.QApplication.translate("MainWindow", "F8", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMakeInstall.setObjectName(_fromUtf8("actRunMakeInstall"))
        self.actRunMakeClean = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/runMakeClean.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actRunMakeClean.setIcon(icon10)
        self.actRunMakeClean.setText(QtGui.QApplication.translate("MainWindow", "Make Clean", None, QtGui.QApplication.UnicodeUTF8))
        self.actRunMakeClean.setObjectName(_fromUtf8("actRunMakeClean"))
        self.actConfigureWithCMake = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/CMakeSetup128.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actConfigureWithCMake.setIcon(icon11)
        self.actConfigureWithCMake.setText(QtGui.QApplication.translate("MainWindow", "Configure With CMake", None, QtGui.QApplication.UnicodeUTF8))
        self.actConfigureWithCMake.setObjectName(_fromUtf8("actConfigureWithCMake"))
        self.actEditUserSettings = QtGui.QAction(MainWindow)
        self.actEditUserSettings.setText(QtGui.QApplication.translate("MainWindow", "&User settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actEditUserSettings.setObjectName(_fromUtf8("actEditUserSettings"))
        self.actEditCastEnvironment = QtGui.QAction(MainWindow)
        self.actEditCastEnvironment.setText(QtGui.QApplication.translate("MainWindow", "&Cast environment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actEditCastEnvironment.setObjectName(_fromUtf8("actEditCastEnvironment"))
        self.actRemoteBuild = QtGui.QAction(MainWindow)
        self.actRemoteBuild.setCheckable(True)
        self.actRemoteBuild.setText(QtGui.QApplication.translate("MainWindow", "Remote Build", None, QtGui.QApplication.UnicodeUTF8))
        self.actRemoteBuild.setToolTip(QtGui.QApplication.translate("MainWindow", "Build the code on remote machines", None, QtGui.QApplication.UnicodeUTF8))
        self.actRemoteBuild.setObjectName(_fromUtf8("actRemoteBuild"))
        self.actSynchronizeCode = QtGui.QAction(MainWindow)
        self.actSynchronizeCode.setText(QtGui.QApplication.translate("MainWindow", "Synchronize Code", None, QtGui.QApplication.UnicodeUTF8))
        self.actSynchronizeCode.setToolTip(QtGui.QApplication.translate("MainWindow", "Synchronize the code on remote machines", None, QtGui.QApplication.UnicodeUTF8))
        self.actSynchronizeCode.setObjectName(_fromUtf8("actSynchronizeCode"))
        self.actCancelBuild = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/iconBuildStop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actCancelBuild.setIcon(icon12)
        self.actCancelBuild.setText(QtGui.QApplication.translate("MainWindow", "Cancel Build", None, QtGui.QApplication.UnicodeUTF8))
        self.actCancelBuild.setObjectName(_fromUtf8("actCancelBuild"))
        self.actCreateEnvScript = QtGui.QAction(MainWindow)
        self.actCreateEnvScript.setText(QtGui.QApplication.translate("MainWindow", "Create env script BUILD/castenv.sh", None, QtGui.QApplication.UnicodeUTF8))
        self.actCreateEnvScript.setToolTip(QtGui.QApplication.translate("MainWindow", "Create an environment script in Build directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actCreateEnvScript.setObjectName(_fromUtf8("actCreateEnvScript"))
        self.menuCast.addAction(self.actShowEnv)
        self.menuCast.addAction(self.actCreateEnvScript)
        self.menuCast.addSeparator()
        self.menuCast.addAction(self.actStartTerminal)
        self.menuCast.addSeparator()
        self.menuCast.addAction(self.actQuit)
        self.menu_Process.addAction(self.actStartCastServers)
        self.menu_Process.addAction(self.actStopCastServers)
        self.menu_Process.addAction(self.actStartCastClient)
        self.menu_Process.addAction(self.actStopCastClient)
        self.menu_Process.addAction(self.actStartExternalServers)
        self.menu_Process.addAction(self.actStopExternalServers)
        self.menu_Process.addSeparator()
        self.menu_Process.addAction(self.actEnableCleanupScript)
        self.menu_Build.addAction(self.actRunMake)
        self.menu_Build.addAction(self.actRunMakeInstall)
        self.menu_Build.addAction(self.actCancelBuild)
        self.menu_Build.addAction(self.actConfigureWithCMake)
        self.menu_Build.addSeparator()
        self.menu_Build.addAction(self.actRunMakeClean)
        self.menu_Build.addAction(self.actSynchronizeCode)
        self.menu_Edit.addAction(self.actEditUserSettings)
        self.menu_Edit.addAction(self.actEditCastEnvironment)
        self.menubar.addAction(self.menuCast.menuAction())
        self.menubar.addAction(self.menu_Process.menuAction())
        self.menubar.addAction(self.menu_Build.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.processBar.addAction(self.actEnableCleanupScript)
        self.processBar.addSeparator()
        self.processBar.addAction(self.actStartExternalServers)
        self.processBar.addAction(self.actStartCastServers)
        self.processBar.addAction(self.actStartCastClient)
        self.processBar.addSeparator()
        self.processBar.addAction(self.actStopExternalServers)
        self.processBar.addAction(self.actStopCastServers)
        self.processBar.addAction(self.actStopCastClient)
        self.processBar.addSeparator()
        self.processBar.addAction(self.actStartTerminal)
        self.buildBar.addAction(self.actConfigureWithCMake)
        self.buildBar.addAction(self.actRunMake)
        self.buildBar.addAction(self.actRunMakeInstall)
        self.buildBar.addAction(self.actCancelBuild)
        self.buildBar.addSeparator()
        self.buildBar.addAction(self.actRunMakeClean)
        self.label_2.setBuddy(self.txtFnComponentLevels)
        self.label_5.setBuddy(self.txtLocalHost)
        self.label_10.setBuddy(self.hostConfigCmbx)
        self.label_6.setBuddy(self.clientConfigCmbx)
        self.label_9.setBuddy(self.cbLog4jMode)
        self.label.setBuddy(self.cbLog4jServerHost)
        self.label_7.setBuddy(self.edLog4jServerPort)
        self.label_12.setBuddy(self.log4jConsoleLevelCmbx)
        self.label_16.setBuddy(self.log4jFileLevelCmbx)
        self.label_11.setBuddy(self.edLog4jOutfile)
        self.label_17.setBuddy(self.processHostCmbx)
        self.label_18.setBuddy(self.processGroupCmbx)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.btBrowseCastFile, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actOpenClientConfig.trigger)
        QtCore.QObject.connect(self.btBrowseHostFile, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actOpenHostConfig.trigger)
        QtCore.QObject.connect(self.btSynchronize, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actSynchronizeCode.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLogs), QtGui.QApplication.translate("MainWindow", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBuildLog), QtGui.QApplication.translate("MainWindow", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfigure), QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProcessConfig), QtGui.QApplication.translate("MainWindow", "Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOldInterface), QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))

import castcontrol_rc
