package TestingData;

/**
* TestingData/TestingCommandHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class TestingCommandHolder implements org.omg.CORBA.portable.Streamable
{
  public TestingData.TestingCommand value = null;

  public TestingCommandHolder ()
  {
  }

  public TestingCommandHolder (TestingData.TestingCommand initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestingData.TestingCommandHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestingData.TestingCommandHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestingData.TestingCommandHelper.type ();
  }

}
