package TestingData;


/**
* TestingData/TESTING_COMMAND_DELIMITER.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TestingData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public interface TESTING_COMMAND_DELIMITER
{

  /// Character used to terminate a command string in the input file
  public static final char value = (char)(';');
}
