INC_DIR= ../../include
LIB_DIR= ../../lib
BIN_DIR= ../../bin

LDFLAG=-L/usr/X11R6/lib -L$(LIB_DIR)
LIBS= -lARgsub_lite -lARvideo -lAR -lglut -lGLU -lGL -lXi -lXmu -lX11 -lm -ljpeg
CFLAG= -O -I/usr/X11R6/include -DUSE_EYETOY -I/usr/src/linux-headers-2.6.38.2-hpusb/include -I/usr/src/linux-headers-2.6.38.2-hpusb/arch/x86/include -I$(INC_DIR)


all: $(BIN_DIR)/calib_dist

$(BIN_DIR)/calib_dist: calib_dist.o check_dist.o
	cc -o $(BIN_DIR)/calib_dist calib_dist.o check_dist.o\
	   $(LDFLAG) $(LIBS)

calib_dist.o: calib_dist.c calib_dist.h
	cc -c $(CFLAG) calib_dist.c

check_dist.o: check_dist.c calib_dist.h
	cc -c $(CFLAG) check_dist.c

clean:
	rm -f calib_dist.o check_dist.o
	rm -f $(BIN_DIR)/calib_dist

allclean:
	rm -f calib_dist.o check_dist.o
	rm -f $(BIN_DIR)/calib_dist
	rm -f Makefile
