package cast.cdl;


/**
* cast/cdl/ReceiverDeleteConditionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class ReceiverDeleteConditionHelper
{
  private static String  _id = "IDL:cast/cdl/ReceiverDeleteCondition:1.0";

  public static void insert (org.omg.CORBA.Any a, cast.cdl.ReceiverDeleteCondition that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cast.cdl.ReceiverDeleteCondition extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (cast.cdl.ReceiverDeleteConditionHelper.id (), "ReceiverDeleteCondition", new String[] { "DELETE_RECEIVER", "DO_NOT_DELETE_RECEIVER"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cast.cdl.ReceiverDeleteCondition read (org.omg.CORBA.portable.InputStream istream)
  {
    return cast.cdl.ReceiverDeleteCondition.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cast.cdl.ReceiverDeleteCondition value)
  {
    ostream.write_long (value.value ());
  }

}
