package cast.cdl;


/**
* cast/cdl/TaskOutcome.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public class TaskOutcome implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static cast.cdl.TaskOutcome[] __array = new cast.cdl.TaskOutcome [__size];

  public static final int _PROCESSING_INCOMPLETE = 0;
  public static final cast.cdl.TaskOutcome PROCESSING_INCOMPLETE = new cast.cdl.TaskOutcome(_PROCESSING_INCOMPLETE);
  public static final int _PROCESSING_COMPLETE = 1;
  public static final cast.cdl.TaskOutcome PROCESSING_COMPLETE = new cast.cdl.TaskOutcome(_PROCESSING_COMPLETE);
  public static final int _PROCESSING_COMPLETE_SUCCESS = 2;
  public static final cast.cdl.TaskOutcome PROCESSING_COMPLETE_SUCCESS = new cast.cdl.TaskOutcome(_PROCESSING_COMPLETE_SUCCESS);
  public static final int _PROCESSING_COMPLETE_FAILURE = 3;
  public static final cast.cdl.TaskOutcome PROCESSING_COMPLETE_FAILURE = new cast.cdl.TaskOutcome(_PROCESSING_COMPLETE_FAILURE);

  public int value ()
  {
    return __value;
  }

  public static cast.cdl.TaskOutcome from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TaskOutcome (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TaskOutcome
