package cast.cdl;


/**
* cast/cdl/TaskManagementDecision.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public class TaskManagementDecision implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static cast.cdl.TaskManagementDecision[] __array = new cast.cdl.TaskManagementDecision [__size];

  public static final int _GOAL_ADOPTED = 0;
  public static final cast.cdl.TaskManagementDecision GOAL_ADOPTED = new cast.cdl.TaskManagementDecision(_GOAL_ADOPTED);
  public static final int _GOAL_REJECTED = 1;
  public static final cast.cdl.TaskManagementDecision GOAL_REJECTED = new cast.cdl.TaskManagementDecision(_GOAL_REJECTED);
  public static final int _GOAL_WAITING = 2;
  public static final cast.cdl.TaskManagementDecision GOAL_WAITING = new cast.cdl.TaskManagementDecision(_GOAL_WAITING);

  public int value ()
  {
    return __value;
  }

  public static cast.cdl.TaskManagementDecision from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TaskManagementDecision (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TaskManagementDecision
