package cast.cdl;


/**
* cast/cdl/WorkingMemoryPointer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class WorkingMemoryPointer implements org.omg.CORBA.portable.IDLEntity
{

  /** The type of the data **/
  public String m_type = null;

  /** Points to the data **/
  public cast.cdl.WorkingMemoryAddress m_address = null;

  public WorkingMemoryPointer ()
  {
  } // ctor

  public WorkingMemoryPointer (String _m_type, cast.cdl.WorkingMemoryAddress _m_address)
  {
    m_type = _m_type;
    m_address = _m_address;
  } // ctor

} // class WorkingMemoryPointer
