package cast.cdl;

/**
* cast/cdl/WorkingMemoryPermissionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/*
     * Enum indicating the result of a wm lock query.
     */
public final class WorkingMemoryPermissionsHolder implements org.omg.CORBA.portable.Streamable
{
  public cast.cdl.WorkingMemoryPermissions value = null;

  public WorkingMemoryPermissionsHolder ()
  {
  }

  public WorkingMemoryPermissionsHolder (cast.cdl.WorkingMemoryPermissions initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cast.cdl.WorkingMemoryPermissionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cast.cdl.WorkingMemoryPermissionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cast.cdl.WorkingMemoryPermissionsHelper.type ();
  }

}
