package cast.cdl;

/**
* cast/cdl/WorkingMemoryChangeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class WorkingMemoryChangeHolder implements org.omg.CORBA.portable.Streamable
{
  public cast.cdl.WorkingMemoryChange value = null;

  public WorkingMemoryChangeHolder ()
  {
  }

  public WorkingMemoryChangeHolder (cast.cdl.WorkingMemoryChange initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cast.cdl.WorkingMemoryChangeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cast.cdl.WorkingMemoryChangeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cast.cdl.WorkingMemoryChangeHelper.type ();
  }

}
