package planning.autogen;


/**
* planning/autogen/PlanningStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlanningData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/


/**
     * Various states that planning processes can be in.
     **/
public class PlanningStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 8;
  private static planning.autogen.PlanningStatus[] __array = new planning.autogen.PlanningStatus [__size];

  public static final int _PROPOSED = 0;
  public static final planning.autogen.PlanningStatus PROPOSED = new planning.autogen.PlanningStatus(_PROPOSED);
  public static final int _ADOPTED = 1;
  public static final planning.autogen.PlanningStatus ADOPTED = new planning.autogen.PlanningStatus(_ADOPTED);
  public static final int _INCOMPLETE = 2;
  public static final planning.autogen.PlanningStatus INCOMPLETE = new planning.autogen.PlanningStatus(_INCOMPLETE);
  public static final int _COMPLETE = 3;
  public static final planning.autogen.PlanningStatus COMPLETE = new planning.autogen.PlanningStatus(_COMPLETE);
  public static final int _PREPARING = 4;
  public static final planning.autogen.PlanningStatus PREPARING = new planning.autogen.PlanningStatus(_PREPARING);
  public static final int _PLANNING = 5;
  public static final planning.autogen.PlanningStatus PLANNING = new planning.autogen.PlanningStatus(_PLANNING);
  public static final int _REPLANNING = 6;
  public static final planning.autogen.PlanningStatus REPLANNING = new planning.autogen.PlanningStatus(_REPLANNING);
  public static final int _EXECUTING = 7;
  public static final planning.autogen.PlanningStatus EXECUTING = new planning.autogen.PlanningStatus(_EXECUTING);

  public int value ()
  {
    return __value;
  }

  public static planning.autogen.PlanningStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected PlanningStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class PlanningStatus
