package planning.autogen;


/**
* planning/autogen/PlanningProblem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlanningData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class PlanningProblem implements org.omg.CORBA.portable.IDLEntity
{

  //bstring m_goalDescID;
  public String m_maplGoal = null;

  // the MAPL goal string
  public Planner.ObjectDeclaration m_objectList[] = null;
  public Planner.Fact m_factList[] = null;
  public String m_domainFile = null;

  public PlanningProblem ()
  {
  } // ctor

  public PlanningProblem (String _m_maplGoal, Planner.ObjectDeclaration[] _m_objectList, Planner.Fact[] _m_factList, String _m_domainFile)
  {
    m_maplGoal = _m_maplGoal;
    m_objectList = _m_objectList;
    m_factList = _m_factList;
    m_domainFile = _m_domainFile;
  } // ctor

} // class PlanningProblem
