package planning.autogen;


/**
* planning/autogen/PlanningStateRequest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlanningData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class PlanningStateRequest implements org.omg.CORBA.portable.IDLEntity
{

  //lists to contain the state
  public planning.autogen.PlanningStateLists m_state = null;

  //the address of the planning process request that generated this request
  public cast.cdl.WorkingMemoryAddress m_pprAddr = null;

  public PlanningStateRequest ()
  {
  } // ctor

  public PlanningStateRequest (planning.autogen.PlanningStateLists _m_state, cast.cdl.WorkingMemoryAddress _m_pprAddr)
  {
    m_state = _m_state;
    m_pprAddr = _m_pprAddr;
  } // ctor

} // class PlanningStateRequest
