(define (domain ytilanoitisoporp)
(:requirements :action-costs :typing)
(:types boolean - object)
(:predicates (on ?b - boolean)
(off ?b - boolean)
(related ?b1 ?b2 - boolean)
(unrelated ?b - boolean))
(:functions (total-cost) - number
(switch-cost ?b - boolean) - number )
(:action switch-on
:parameters (?b1 ?b2 - boolean)
:precondition (and (off ?b1) (related ?b1 ?b2) )
:effect (and (not (off ?b1)) 
(off ?b2)
 (not (on ?b2))
(on ?b1)
(increase (total-cost) (switch-cost ?b1))
)
)
(:action unrelated-switch-on
:parameters (?b - boolean)
:precondition (and (off ?b) (unrelated ?b) )
:effect (and (not (off ?b)) 
(on ?b)
(increase (total-cost) (switch-cost ?b))
)
)
(:action switch-off
:parameters (?b - boolean)
:precondition (and (on ?b) )
:effect (and (not (on ?b))
(off ?b)
(increase (total-cost) (switch-cost ?b))
)
)
(:action super-switch
:parameters ()
:precondition ()
:effect (and 
(not (on o1 ))
(off o1 )
(not (on o2 ))
(off o2 )
(not (on o3 ))
(off o3 )
(on o4 )
(not (off o4 ))
(not (on o5 ))
(off o5 )
(on o6 )
(not (off o6 ))
(not (on o7 ))
(off o7 )
(not (on o8 ))
(off o8 )
(on o9 )
(not (off o9 ))
(not (on o10 ))
(off o10 )
(not (on o11 ))
(off o11 )
(on o12 )
(not (off o12 ))
(on o13 )
(not (off o13 ))
(on o14 )
(not (off o14 ))
(on o15 )
(not (off o15 ))
(not (on o16 ))
(off o16 )
(not (on o17 ))
(off o17 )
(not (on o18 ))
(off o18 )
(on o19 )
(not (off o19 ))
(not (on o20 ))
(off o20 )
(not (on o21 ))
(off o21 )
(not (on o22 ))
(off o22 )
(not (on o23 ))
(off o23 )
(on o24 )
(not (off o24 ))
(on o25 )
(not (off o25 ))
(not (on o26 ))
(off o26 )
(not (on o27 ))
(off o27 )
(not (on o28 ))
(off o28 )
(on o29 )
(not (off o29 ))
(not (on o30 ))
(off o30 )
(on o31 )
(not (off o31 ))
(not (on o32 ))
(off o32 )
(on o33 )
(not (off o33 ))
(on o34 )
(not (off o34 ))
(on o35 )
(not (off o35 ))
(on o36 )
(not (off o36 ))
(on o37 )
(not (off o37 ))
(not (on o38 ))
(off o38 )
(not (on o39 ))
(off o39 )
(on o40 )
(not (off o40 ))
(on o41 )
(not (off o41 ))
(not (on o42 ))
(off o42 )
(not (on o43 ))
(off o43 )
(on o44 )
(not (off o44 ))
(not (on o45 ))
(off o45 )
(not (on o46 ))
(off o46 )
(on o47 )
(not (off o47 ))
(on o48 )
(not (off o48 ))
(on o49 )
(not (off o49 ))
(on o50 )
(not (off o50 ))
(increase (total-cost) 1000))) 
)
