% Container-in-room
tableLambda_kitchen = computeExclusive(0.55362135, []);
tableLambda_office = computeExclusive(0.51997805, []);
tableLambda_meeting_room = computeExclusive(0.10420009, []);
tableLambda_corridor = computeExclusive(0.059427146, []);

bookcaseLambda_kitchen = computeExclusive(0.35544333, []);
bookcaseLambda_office = computeExclusive(0.5326703, []);
bookcaseLambda_meeting_room = computeExclusive(0.015040721, []);
bookcaseLambda_corridor = computeExclusive(0.08778912, []);

counterLambda_kitchen = computeExclusive(0.33616346, []);
counterLambda_office = computeExclusive(0.27807754, []);
counterLambda_meeting_room = computeExclusive(0.03347149, []);
counterLambda_corridor = computeExclusive(0.058676492, []);

boxLambda_kitchen = computeExclusive(0.15457517, []);
boxLambda_office = computeExclusive(0.19933626, []);
boxLambda_meeting_room = computeExclusive(0.011069357, []);
boxLambda_corridor = computeExclusive(0.0, []);

% Mug-in/on-object
mugOnTableLambda_kitchen = computeExclusive(0.3, []);
mugOnTableLambda_office = computeExclusive(0.3, []);
mugOnTableLambda_meeting_room = computeExclusive(0.02, []);
mugOnTableLambda_corridor = computeExclusive(0, []);

mugInBookcaseLambda_kitchen = computeExclusive(0.03, []);
mugInBookcaseLambda_office = computeExclusive(0.1, []);
mugInBookcaseLambda_meeting_room = computeExclusive(0.01, []);
mugInBookcaseLambda_corridor = computeExclusive(0, []);

mugOnCounterLambda_kitchen = computeExclusive(0.4, []);
mugOnCounterLambda_office = computeExclusive(0.3, []);
mugOnCounterLambda_meeting_room = computeExclusive(0.01, []);
mugOnCounterLambda_corridor = computeExclusive(0, []);

mugInBoxLambda_kitchen = computeExclusive(0.03, []);
mugInBoxLambda_office = computeExclusive(0.03, []);
mugInBoxLambda_meeting_room = computeExclusive(0.01, []);
mugInBoxLambda_corridor = computeExclusive(0, []);

% Cereal-in/on-object
cerealOnTableLambda_kitchen = computeExclusive(0.3, []);
cerealOnTableLambda_office = computeExclusive(0.03, []);
cerealOnTableLambda_meeting_room = computeExclusive(0.03, []);
cerealOnTableLambda_corridor = computeExclusive(0.03, []);

cerealInBookcaseLambda_kitchen = computeExclusive(0.03, []);
cerealInBookcaseLambda_office = computeExclusive(0.03, []);
cerealInBookcaseLambda_meeting_room = computeExclusive(0.03, []);
cerealInBookcaseLambda_corridor = computeExclusive(0.03, []);

cerealOnCounterLambda_kitchen = computeExclusive(0.2, []);
cerealOnCounterLambda_office = computeExclusive(0.03, []);
cerealOnCounterLambda_meeting_room = computeExclusive(0.03, []);
cerealOnCounterLambda_corridor = computeExclusive(0.03, []);

cerealInBoxLambda_kitchen = computeExclusive(0.2, []);
cerealInBoxLambda_office = computeExclusive(0.03, []);
cerealInBoxLambda_meeting_room = computeExclusive(0.03, []);
cerealInBoxLambda_corridor = computeExclusive(0.03, []);

% Book-in/on-object
holePuncherOnTableLambda_kitchen = computeExclusive(0.03, []);
holePuncherOnTableLambda_office = computeExclusive(0.3, []);
holePuncherOnTableLambda_meeting_room = computeExclusive(0, []);
holePuncherOnTableLambda_corridor = computeExclusive(0.1, []);

holePuncherInBookcaseLambda_kitchen = computeExclusive(0.03, []);
holePuncherInBookcaseLambda_office = computeExclusive(0.1, []);
holePuncherInBookcaseLambda_meeting_room = computeExclusive(0, []);
holePuncherInBookcaseLambda_corridor = computeExclusive(0.03, []);

holePuncherOnCounterLambda_kitchen = computeExclusive(0.03, []);
holePuncherOnCounterLambda_office = computeExclusive(0.3, []);
holePuncherOnCounterLambda_meeting_room = computeExclusive(0, []);
holePuncherOnCounterLambda_corridor = computeExclusive(0.2, []);

holePuncherInBoxLambda_kitchen = computeExclusive(0.03, []);
holePuncherInBoxLambda_office = computeExclusive(0.1, []);
holePuncherInBoxLambda_meeting_room = computeExclusive(0, []);
holePuncherInBoxLambda_corridor = computeExclusive(0.03, []);

% Book-in/on-object
staplerOnTableLambda_kitchen = computeExclusive(0.03, []);
staplerOnTableLambda_office = computeExclusive(0.3, []);
staplerOnTableLambda_meeting_room = computeExclusive(0.03, []);
staplerOnTableLambda_corridor = computeExclusive(0.05, []);

staplerInBookcaseLambda_kitchen = computeExclusive(0.03, []);
staplerInBookcaseLambda_office = computeExclusive(0.1, []);
staplerInBookcaseLambda_meeting_room = computeExclusive(0.01, []);
staplerInBookcaseLambda_corridor = computeExclusive(0.03, []);

staplerOnCounterLambda_kitchen = computeExclusive(0.03, []);
staplerOnCounterLambda_office = computeExclusive(0.3, []);
staplerOnCounterLambda_meeting_room = computeExclusive(0.03, []);
staplerOnCounterLambda_corridor = computeExclusive(0.15, []);

staplerInBoxLambda_kitchen = computeExclusive(0.03, []);
staplerInBoxLambda_office = computeExclusive(0.1, []);
staplerInBoxLambda_meeting_room = computeExclusive(0.01, []);
staplerInBoxLambda_corridor = computeExclusive(0.03, []);

% Book-in/on-object
markerOnTableLambda_kitchen = computeExclusive(0.03, []);
markerOnTableLambda_office = computeExclusive(0.3, []);
markerOnTableLambda_meeting_room = computeExclusive(0.7, []);
markerOnTableLambda_corridor = computeExclusive(0.03, []);

markerInBookcaseLambda_kitchen = computeExclusive(0.03, []);
markerInBookcaseLambda_office = computeExclusive(0.03, []);
markerInBookcaseLambda_meeting_room = computeExclusive(0.3, []);
markerInBookcaseLambda_corridor = computeExclusive(0.03, []);

markerOnCounterLambda_kitchen = computeExclusive(0.03, []);
markerOnCounterLambda_office = computeExclusive(0.2, []);
markerOnCounterLambda_meeting_room = computeExclusive(0.7, []);
markerOnCounterLambda_corridor = computeExclusive(0.03, []);

markerInBoxLambda_kitchen = computeExclusive(0.03, []);
markerInBoxLambda_office = computeExclusive(0.1, []);
markerInBoxLambda_meeting_room = computeExclusive(0.3, []);
markerInBoxLambda_corridor = computeExclusive(0.1, []);

% Book-in/on-object
bookOnTableLambda_kitchen = computeExclusive(0.03, []);
bookOnTableLambda_office = computeExclusive(0.1, []);
bookOnTableLambda_meeting_room = computeExclusive(0.3, []);
bookOnTableLambda_corridor = computeExclusive(0.03, []);

bookInBookcaseLambda_kitchen = computeExclusive(0.2, []);
bookInBookcaseLambda_office = computeExclusive(0.4, []);
bookInBookcaseLambda_meeting_room = computeExclusive(0.5, []);
bookInBookcaseLambda_corridor = computeExclusive(0.2, []);

bookOnCounterLambda_kitchen = computeExclusive(0.03, []);
bookOnCounterLambda_office = computeExclusive(0.1, []);
bookOnCounterLambda_meeting_room = computeExclusive(0.1, []);
bookOnCounterLambda_corridor = computeExclusive(0.1, []);

bookInBoxLambda_kitchen = computeExclusive(0.01, []);
bookInBoxLambda_office = computeExclusive(0.05, []);
bookInBoxLambda_meeting_room = computeExclusive(0.3, []);
bookInBoxLambda_corridor = computeExclusive(0.1, []);

% Mug-in-room
mugInKitchenLambda = computeExclusive(0.3719192, ...
    [tableLambda_kitchen ...
    counterLambda_kitchen ...
    bookcaseLambda_kitchen ...
    boxLambda_kitchen], ...
    [mugOnTableLambda_kitchen ...
    mugOnCounterLambda_kitchen ...
    mugInBookcaseLambda_kitchen ...
    mugInBoxLambda_kitchen]);

mugInOfficeLambda = computeExclusive(0.42584524, ...
    [tableLambda_office ...
    counterLambda_office ...
    bookcaseLambda_office ...
    boxLambda_office], ...
    [mugOnTableLambda_office ...
    mugOnCounterLambda_office ...
    mugInBookcaseLambda_office ...
    mugInBoxLambda_office]);

mugInMeetingroomLambda = computeExclusive(0.004682286, ...
    [tableLambda_meeting_room ...
    counterLambda_meeting_room ...
    bookcaseLambda_meeting_room ...
    boxLambda_meeting_room], ...
    [mugOnTableLambda_meeting_room ...
    mugOnCounterLambda_meeting_room ...
    mugInBookcaseLambda_meeting_room ...
    mugInBoxLambda_meeting_room]);

mugInCorridorLambda = computeExclusive(0, ...
    [tableLambda_corridor ...
    counterLambda_corridor ...
    bookcaseLambda_corridor ...
    boxLambda_corridor], ...
    [mugOnTableLambda_corridor ...
    mugOnCounterLambda_corridor ...
    mugInBookcaseLambda_corridor ...
    mugInBoxLambda_corridor]);

% Cereal-in-room
cerealInKitchenLambda = computeExclusive(0.33602318, ...
    [tableLambda_kitchen ...
    counterLambda_kitchen ...
    bookcaseLambda_kitchen ...
    boxLambda_kitchen], ...
    [cerealOnTableLambda_kitchen ...
    cerealOnCounterLambda_kitchen ...
    cerealInBookcaseLambda_kitchen ...
    cerealInBoxLambda_kitchen]);

cerealInOfficeLambda = computeExclusive(0.10920405, ...
    [tableLambda_office ...
    counterLambda_office ...
    bookcaseLambda_office ...
    boxLambda_office], ...
    [cerealOnTableLambda_office ...
    cerealOnCounterLambda_office ...
    cerealInBookcaseLambda_office ...
    cerealInBoxLambda_office]);

cerealInMeetingroomLambda = computeExclusive(0.011045372, ...
    [tableLambda_meeting_room ...
    counterLambda_meeting_room ...
    bookcaseLambda_meeting_room ...
    boxLambda_meeting_room], ...
    [cerealOnTableLambda_meeting_room ...
    cerealOnCounterLambda_meeting_room ...
    cerealInBookcaseLambda_meeting_room ...
    cerealInBoxLambda_meeting_room]);

cerealInCorridorLambda = computeExclusive(0.028160283, ...
    [tableLambda_corridor ...
    counterLambda_corridor ...
    bookcaseLambda_corridor ...
    boxLambda_corridor], ...
    [cerealOnTableLambda_corridor ...
    cerealOnCounterLambda_corridor ...
    cerealInBookcaseLambda_corridor ...
    cerealInBoxLambda_corridor]);

% Hole-puncher-in-room
holePuncherInKitchenLambda = computeExclusive(0.12200364, ...
    [tableLambda_kitchen ...
    counterLambda_kitchen ...
    bookcaseLambda_kitchen ...
    boxLambda_kitchen], ...
    [holePuncherOnTableLambda_kitchen ...
    holePuncherOnCounterLambda_kitchen ...
    holePuncherInBookcaseLambda_kitchen ...
    holePuncherInBoxLambda_kitchen]);

holePuncherInOfficeLambda = computeExclusive(0.49868113, ...
    [tableLambda_office ...
    counterLambda_office ...
    bookcaseLambda_office ...
    boxLambda_office], ...
    [holePuncherOnTableLambda_office ...
    holePuncherOnCounterLambda_office ...
    holePuncherInBookcaseLambda_office ...
    holePuncherInBoxLambda_office]);

holePuncherInMeetingroomLambda = computeExclusive(0, ...
    [tableLambda_meeting_room ...
    counterLambda_meeting_room ...
    bookcaseLambda_meeting_room ...
    boxLambda_meeting_room], ...
    [holePuncherOnTableLambda_meeting_room ...
    holePuncherOnCounterLambda_meeting_room ...
    holePuncherInBookcaseLambda_meeting_room ...
    holePuncherInBoxLambda_meeting_room]);

holePuncherInCorridorLambda = computeExclusive(0.026623378, ...
    [tableLambda_corridor ...
    counterLambda_corridor ...
    bookcaseLambda_corridor ...
    boxLambda_corridor], ...
    [holePuncherOnTableLambda_corridor ...
    holePuncherOnCounterLambda_corridor ...
    holePuncherInBookcaseLambda_corridor ...
    holePuncherInBoxLambda_corridor]);

% Stapler-in-room
staplerInKitchenLambda = computeExclusive(0.21891372, ...
    [tableLambda_kitchen ...
    counterLambda_kitchen ...
    bookcaseLambda_kitchen ...
    boxLambda_kitchen], ...
    [staplerOnTableLambda_kitchen ...
    staplerOnCounterLambda_kitchen ...
    staplerInBookcaseLambda_kitchen ...
    staplerInBoxLambda_kitchen]);

staplerInOfficeLambda = computeExclusive(0.8038152, ...
    [tableLambda_office ...
    counterLambda_office ...
    bookcaseLambda_office ...
    boxLambda_office], ...
    [staplerOnTableLambda_office ...
    staplerOnCounterLambda_office ...
    staplerInBookcaseLambda_office ...
    staplerInBoxLambda_office]);

staplerInMeetingroomLambda = computeExclusive(0.015497998, ...
    [tableLambda_meeting_room ...
    counterLambda_meeting_room ...
    bookcaseLambda_meeting_room ...
    boxLambda_meeting_room], ...
    [staplerOnTableLambda_meeting_room ...
    staplerOnCounterLambda_meeting_room ...
    staplerInBookcaseLambda_meeting_room ...
    staplerInBoxLambda_meeting_room]);

staplerInCorridorLambda = computeExclusive(0.018212307, ...
    [tableLambda_corridor ...
    counterLambda_corridor ...
    bookcaseLambda_corridor ...
    boxLambda_corridor], ...
    [staplerOnTableLambda_corridor ...
    staplerOnCounterLambda_corridor ...
    staplerInBookcaseLambda_corridor ...
    staplerInBoxLambda_corridor]);

% Marker-in-room
markerInKitchenLambda = computeExclusive(0.079940535, ...
    [tableLambda_kitchen ...
    counterLambda_kitchen ...
    bookcaseLambda_kitchen ...
    boxLambda_kitchen], ...
    [markerOnTableLambda_kitchen ...
    markerOnCounterLambda_kitchen ...
    markerInBookcaseLambda_kitchen ...
    markerInBoxLambda_kitchen]);

markerInOfficeLambda = computeExclusive(0.29999897, ...
    [tableLambda_office ...
    counterLambda_office ...
    bookcaseLambda_office ...
    boxLambda_office], ...
    [markerOnTableLambda_office ...
    markerOnCounterLambda_office ...
    markerInBookcaseLambda_office ...
    markerInBoxLambda_office]);

markerInMeetingroomLambda = computeExclusive(0.8, ... %0.03768433, ...
    [tableLambda_meeting_room ...
    counterLambda_meeting_room ...
    bookcaseLambda_meeting_room ...
    boxLambda_meeting_room], ...
    [markerOnTableLambda_meeting_room ...
    markerOnCounterLambda_meeting_room ...
    markerInBookcaseLambda_meeting_room ...
    markerInBoxLambda_meeting_room]);

markerInCorridorLambda = computeExclusive(0.013323422, ...
    [tableLambda_corridor ...
    counterLambda_corridor ...
    bookcaseLambda_corridor ...
    boxLambda_corridor], ...
    [markerOnTableLambda_corridor ...
    markerOnCounterLambda_corridor ...
    markerInBookcaseLambda_corridor ...
    markerInBoxLambda_corridor]);

% Book-in-room
bookInKitchenLambda = computeExclusive(0.15062384, ...
    [tableLambda_kitchen ...
    counterLambda_kitchen ...
    bookcaseLambda_kitchen ...
    boxLambda_kitchen], ...
    [bookOnTableLambda_kitchen ...
    bookOnCounterLambda_kitchen ...
    bookInBookcaseLambda_kitchen ...
    bookInBoxLambda_kitchen]);

bookInOfficeLambda = computeExclusive(0.42819896, ...
    [tableLambda_office ...
    counterLambda_office ...
    bookcaseLambda_office ...
    boxLambda_office], ...
    [bookOnTableLambda_office ...
    bookOnCounterLambda_office ...
    bookInBookcaseLambda_office ...
    bookInBoxLambda_office]);

bookInMeetingroomLambda = computeExclusive(0.06093035, ...
    [tableLambda_meeting_room ...
    counterLambda_meeting_room ...
    bookcaseLambda_meeting_room ...
    boxLambda_meeting_room], ...
    [bookOnTableLambda_meeting_room ...
    bookOnCounterLambda_meeting_room ...
    bookInBookcaseLambda_meeting_room ...
    bookInBoxLambda_meeting_room]);

bookInCorridorLambda = computeExclusive(0.028361533, ...
    [tableLambda_corridor ...
    counterLambda_corridor ...
    bookcaseLambda_corridor ...
    boxLambda_corridor], ...
    [bookOnTableLambda_corridor ...
    bookOnCounterLambda_corridor ...
    bookInBookcaseLambda_corridor ...
    bookInBoxLambda_corridor]);

