//=================================================================
//Copyright (C) 2010 Pierre Lison (plison@dfki.de)

//This library is free software; you can redistribute it and/or
//modify it under the terms of the GNU Lesser General Public License
//as published by the Free Software Foundation; either version 2.1 of
//the License, or (at your option) any later version.

//This library is distributed in the hope that it will be useful, but
//WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
//Lesser General Public License for more details.

//You should have received a copy of the GNU Lesser General Public
//License along with this program; if not, write to the Free Software
//Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
//02111-1307, USA.
//=================================================================

//=================================================================
//PACKAGE DEFINITION
package de.dfki.lt.tr.dialogue.parse.examplegeneration;

//=================================================================
//IMPORTS

/* Generated By:JavaCC: Do not edit this line. SemCorpusParserConstants.java */
public interface SemCorpusParserConstants {

  int EOF = 0;
  int LBRACE = 5;
  int COLON = 6;
  int RBRACE = 7;
  int LBRACKET = 8;
  int RBRACKET = 9;
  int LPAR = 10;
  int RPAR = 11;
  int NT = 12;
  int T = 13;
  int MOD = 14;
  int IND = 15;
  int LAND = 16;
  int NOMINAL = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\":\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<NT>",
    "<T>",
    "<MOD>",
    "<IND>",
    "\"^\"",
    "<NOMINAL>",
    "\"?\"",
  };

}
