(define (problem BLOCKS-6-0)
(:domain BLOCKS)
(:objects E A B C F D  - block )
(:INIT  (= (total-cost) 0) (CLEAR D) (CLEAR F) (ONTABLE C) (ONTABLE B) (ON D A) (ON A C) (ON F E)
 (ON E B) (HANDEMPTY))
(:goal (AND (ON C B) (ON B A) (ON A E) (ON E F) (ON F D)))
(:metric minimize (total-cost))
)
