GARNAME = cogx-distro
GARVERSION =
CATEGORIES = distributions
DISTFILES =
MAINTAINER = mhanheid

DEB_PACKAGES=	libqt4-opengl-dev@ubuntu \
		libqt4-webkit@ubuntu \
		python-qt4@ubuntu \
		libboost-python1.40-dev@ubuntu \
		libqt4-dev@ubuntu \
		libgl1-mesa-dev@ubuntu \
		libglu1-mesa-dev@ubuntu \
		libftgl-dev@ubuntu \
		liblua5.1-0-dev@ubuntu \
		libtolua++5.1-dev@ubuntu \
		libboost-serialization-dev@ubuntu \
		libboost-iostreams-dev@ubuntu \
		libqt4-dev@ubuntu \
		libtolua++5.1-dev@ubuntu \
		libprotobuf-dev@ubuntu \
		python-pygraphviz@ubuntu \
		libglew1.5-dev@ubuntu \
		libdevil-dev@ubuntu \
		nvidia-cg-toolkit@ubuntu



LIBDEPS = 			contrib/peekabot \
		cogx/cast-c++ \
		cogx/cast-java \
		cogx/cosycure \
		contrib/opencv \
		contrib/player-3.0.2 \
		contrib/stage \
		contrib/avin2-SensorKinect

DESCRIPTION = agai-distro

CONFIGURE_SCRIPTS = 
BUILD_SCRIPTS = 
INSTALL_SCRIPTS = 

CONFIGURE_ARGS = 

include ../../gar.extend.mk

checksum-$(DISTFILES):	
	true
