GARNAME = cogx-distro
GARVERSION =
CATEGORIES = distributions
DISTFILES =
MAINTAINER = mhanheid

DEB_PACKAGES=


LIBDEPS = 	contrib/opencv-trunk \
		contrib/peekabot \
		contrib/player-2.1.2 \
		contrib/stage \
		cogx/cast-c++ \
		cogx/cast-java \
		cogx/cosycure

DESCRIPTION = agai-distro

CONFIGURE_SCRIPTS = 
BUILD_SCRIPTS = 
INSTALL_SCRIPTS = 

CONFIGURE_ARGS = 

include ../../gar.extend.mk

checksum-$(DISTFILES):	
	true
