#ifndef TESTING_DATA_IDL_
#define TESTING_DATA_IDL

#include <CAST.idl>

/// module for IDLs relating to the multi-SA testing component
module TestingData {
  /// String used to identify the testing subarch in the configuration options
  const string TESTING_SUBARCH_CONFIG_KEY = "-tsa";
  /// Character used to terminate a command string in the input file
  const char TESTING_COMMAND_DELIMITER = ';';
  /// Character used to terminate command string header
  const char TESTING_HEADER_DELIMITER = ':';
  /// String used instead of subarchitecture identifier to indicate a command to the
  /// testing component itself
  const string TESTING_METACOMMAND_PREFIX = "self";

  /// Represents the state of a testing command 
  enum TestingCommandStatus {
    ISSUED, ///< The command is not yet completed
    COMPLETED ///< The command has been completed and can be deleted
  };

  /// Represents a command from the Tester component to a listener component
  /// in a subarchitecture.
  struct TestingCommand {
    /// Status 
    TestingCommandStatus m_status;
    /// The command string. The format and contents of this string is entirely
    /// up to the individual subarchitectures' different testing components
    string m_command;
  };
};
#endif
