package balt.corba.autogen.RemoteConnectors;


/**
* balt/corba/autogen/RemoteConnectors/RemotePullConnectorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConnector.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public interface RemotePullConnectorOperations 
{

  /**
       * Pull data from the connector.
       *
       * @param _src The ID of the process doing the pulling.
       * @param _query The query attached to the pull.
       */
  org.omg.CORBA.Any pull (String _src, String _query);

  /**
       * Register a pull receiver process with the connector.
       * 
       * @param _pr The process that receives pulls.
       */
  void registerPullReceiver (balt.corba.autogen.RemoteConnectors.RemotePullReceiver _pr);
} // interface RemotePullConnectorOperations
