package balt.corba.autogen.RemoteConnectors;

/**
* balt/corba/autogen/RemoteConnectors/RemotePushConnectorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConnector.idl
* Donnerstag, 14. Mai 2009 22.09 Uhr CEST
*/


/**
     * Interface to define an object that connects two processes in a
     * push-based manner..
    **/
public final class RemotePushConnectorHolder implements org.omg.CORBA.portable.Streamable
{
  public balt.corba.autogen.RemoteConnectors.RemotePushConnector value = null;

  public RemotePushConnectorHolder ()
  {
  }

  public RemotePushConnectorHolder (balt.corba.autogen.RemoteConnectors.RemotePushConnector initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = balt.corba.autogen.RemoteConnectors.RemotePushConnectorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    balt.corba.autogen.RemoteConnectors.RemotePushConnectorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return balt.corba.autogen.RemoteConnectors.RemotePushConnectorHelper.type ();
  }

}
