package balt.corba.autogen.RemoteConnectors;


/**
* balt/corba/autogen/RemoteConnectors/RemotePushReceiverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConnector.idl
* Donnerstag, 14. Mai 2009 22.09 Uhr CEST
*/


/**
     * Interface to define a object that can receive data in a
     * push-based manner from a remote object.
     *
     *
     */
public interface RemotePushReceiverOperations 
{

  /**
           * Receive the push data.
           * 
           * @param  _src The process that has pushed the data.
           * @param _data The actual data.
           */
  void receivePushData (String _src, org.omg.CORBA.Any _data);
} // interface RemotePushReceiverOperations
