package balt.corba.autogen.RemoteConnectors;


/**
* balt/corba/autogen/RemoteConnectors/RemotePullSenderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConnector.idl
* Donnerstag, 14. Mai 2009 22.09 Uhr CEST
*/

public interface RemotePullSenderOperations 
{

  /**
       * Set the connection object to be used. "set" is not correct, as
       * it could be many-to-many.
       *
       * \todo Fix this,
       *
       * @param _out The connector to use.
       */
  void setPullConnector (balt.corba.autogen.RemoteConnectors.RemotePullConnector _out);
} // interface RemotePullSenderOperations
