/**
 * Some mathematics types.
 * 
 * @version
 */

#ifndef MATH_IDL
#define MATH_IDL

module Math {

  struct Vector2D {
    float m_x;
    float m_y;
  };

  struct Vector3D {
    float m_x;
    float m_y;
    float m_z;
  };

  struct Vector3DWithConfidence {
    Vector3D m_vector;
    float m_confidence;
  };

  typedef sequence <Vector3DWithConfidence> Vector3DWithConfidenceSeq;

  struct Pose3D {
    Vector3D m_position;     // in [m]
    Vector3D m_orientation;  // orientation vector: direction is rotation axis
                             // length is rotation angle in [rad]
  };

};

#endif
