
#!/bin/bash

mkdir -p ../../../../binding_test/dotfiles_coma_$1

echo "HOST localhost"
echo ""
echo "SUBARCHITECTURE binding.sa localhost"
echo "CPP  WM BindingWorkingMemory"
echo "CPP  TM AlwaysPositiveTaskManager"
echo "CPP  GD binding.scorer BindingScorer -nth 0 -maxN 1 --log true"
echo "CPP  GD binding.judge BindingJudge "
echo "CPP  GD binding.binder Binder "
echo "CPP  GD binding.groups BindingGroupManager"
echo "CPP  GD binding.state BindingStatusMonitor --log"
echo "CPP  GD binding.dot BindingDotViewer -visfile vis_binding.dot -d binding_test/dotfiles_coma_$1 --log --proxy short --union short "
echo "CPP  GD binding.garbage GarbageCollector --log --police-mode strict"
echo "CPP  GD binding.ambiguity AmbiguityIdentifier --log"
echo "CPP  GD binding.coma_tester ComaTester --test $1 --coma coma.sa --log"
echo ""
echo ""
echo ""
echo ""
echo " SUBARCHITECTURE coma.sa"
echo "JAVA WM coma.components.ComaWorkingMemory --log true"
echo "JAVA TM cast.architecture.subarchitecture.AlwaysPositiveTaskManager"
echo "JAVA GD coma.reasoner coma.components.ComaReasoner --onto_file subarchitectures/coma.sa/ontologies/coma_office.owl --onto_ns oe --onto_sep : --reasoner crowl --crowl_cfg subarchitectures/coma.sa/ontologies/crowl.cfg --log true "
echo "#JAVA GD coma.tester coma.components.ComaTester --log true --onto_ns oe --onto_sep : --testfile subarchitectures/coma.sa/config/test9.coma --debug false"
echo "JAVA GD coma.conconcompawriter coma.comparators.ConceptVsConceptBindingFeatureComparisonWriter -bsa binding.sa --log true --debug false"
echo "JAVA GD coma.conconcompareader coma.comparators.ConceptVsConceptBindingFeatureComparisonReader -bsa binding.sa --log true --debug false"
echo "JAVA GD coma.areaconcompawriter coma.comparators.AreaVsConceptComparisonWriter -bsa binding.sa --log true --debug false"
echo "JAVA GD coma.areaconcompareader coma.comparators.AreaVsConceptComparisonReader -bsa binding.sa --log true --debug false"
echo "JAVA GD coma.fakeevents coma.components.ComaFakeEventGenerator --log true --onto_ns oe --onto_sep : --eventfile subarchitectures/coma.sa/config/event9.coma --debug false"
