
#!/bin/bash

mkdir -p ../../../../binding_test/dotfiles_comsys_$1

echo "HOST localhost"
echo ""
echo "SUBARCHITECTURE binding.sa localhost"
echo "CPP  WM BindingWorkingMemory"
echo "CPP  TM AlwaysPositiveTaskManager"
echo "CPP  GD binding.scorer BindingScorer -nth 0 -maxN 1"
echo "CPP  GD binding.judge BindingJudge "
echo "CPP  GD binding.binder Binder "
echo "CPP  GD binding.groups BindingGroupManager"
echo "CPP  GD binding.state BindingStatusMonitor --log"
echo "CPP  GD binding.dot BindingDotViewer -visfile vis_binding.dot -d binding_test/dotfiles_comsys_$1 --log --proxy short --union short "
echo "CPP  GD binding.garbage GarbageCollector --log --police-mode strict"
echo "CPP  GD binding.ambiguity AmbiguityIdentifier --log"
echo "CPP  GD binding.comsys_tester ComsysTester --test $1 --comsys comsys.sa --log"
echo ""
echo ""
echo ""
echo "SUBARCHITECTURE motiv.sa localhost"
echo "CPP  WM BindingWorkingMemory"
echo "CPP  TM AlwaysPositiveTaskManager"
echo "CPP  GD motiv.binder Binder "
echo "CPP  GD binding.scorer_dummy BindingScorer -nth 0 -maxN 1 --dummy"
echo "CPP  GD motiv.state BindingStatusMonitor --log"
echo "CPP  GD motiv.dot BindingDotViewer -visfile vis_motiv.dot -d binding_test/dotfiles_comsys_$1 --log --proxy short --union short "
echo "CPP  GD motiv.garbage GarbageCollector --log --police-mode strict"
echo ""
echo "## Comments to the COMSYS configuration"
echo "## - one binding monitor, on the main [ binding.sa ]"
echo "## - the monitor for the main binding working memory works only with completely parsed, pruned packed logical forms, as per the option [ --incrementalBinding 2 ]. "
echo "##   the value \"2\" means \"parsed, and pruned\" (\"1\" means just completely parsed; \"0\" is equal to incremental binding). "
echo "## - the flag [ --hypoProxies false ] for a binding monitor means that no proxies are generated for variables in a packed logical form. "
echo ""
echo "SUBARCHITECTURE comsys.sa localhost"
echo "JAVA WM             org.cognitivesystems.comsys.workingmemory.ComsysWorkingMemory --log true"
echo "JAVA TM             org.cognitivesystems.comsys.general.ComsysTaskManager --file ./subarchitectures/comsys.mk4/config/test-suite/general-TM.sync #--log true"
echo "#JAVA GD speech.rec  org.cognitivesystems.comsys.components.asr.ASR --src gui #--log true --playback"
echo "JAVA GD parser      org.cognitivesystems.comsys.components.UtteranceInterpretation --grammar ./subarchitectures/comsys.mk4/grammars/openccg/moloko.v5/grammar.xml --log true "
echo "#JAVA GD plfviz      org.cognitivesystems.comsys.components.PackedLFVisualizer --dir ./subarchitectures/comsys.mk4/graphs/parser/ --series true --sdrs true --dirSDRS ./subarchitectures/comsys.mk4/graphs/sdrs/ # --log true "
echo "JAVA GD comsys.binding.monitor	org.cognitivesystems.comsys.monitors.ComSysBindingMonitor -bsa binding.sa --msa motiv.sa --incrementalBinding false --syncModel sync_one --log true"
echo "#JAVA GD eventInt	org.cognitivesystems.comsys.components.EventStructureInterpretation --incrementalInterpretation false #--log true"
echo "JAVA GD discRefBindings org.cognitivesystems.comsys.components.DiscRefBindingsComponent #--log true"
echo "JAVA GD dialInt org.cognitivesystems.comsys.components.DialInt #--log true"
echo "#JAVA GD testing		org.cognitivesystems.comsys.general.ComsysTester --test parsing6 --log"
