(define (domain ytilanoitisoporp)
(:requirements :action-costs :typing)
(:types boolean - object)
(:predicates (on ?b - boolean)
(off ?b - boolean)
(related ?b1 ?b2 - boolean)
(unrelated ?b - boolean))
(:functions (total-cost) - number
(switch-cost ?b - boolean) - number )
(:action switch-on
:parameters (?b1 ?b2 - boolean)
:precondition (and (off ?b1) (related ?b1 ?b2) )
:effect (and (not (off ?b1)) 
(off ?b2)
 (not (on ?b2))
(on ?b1)
(increase (total-cost) (switch-cost ?b1))
)
)
(:action unrelated-switch-on
:parameters (?b - boolean)
:precondition (and (off ?b) (unrelated ?b) )
:effect (and (not (off ?b)) 
(on ?b)
(increase (total-cost) (switch-cost ?b))
)
)
(:action switch-off
:parameters (?b - boolean)
:precondition (and (on ?b) )
:effect (and (not (on ?b))
(off ?b)
(increase (total-cost) (switch-cost ?b))
)
)
(:action super-switch
:parameters ()
:precondition ()
:effect (and 
(not (on o1 ))
(off o1 )
(not (on o2 ))
(off o2 )
(on o3 )
(not (off o3 ))
(not (on o4 ))
(off o4 )
(on o5 )
(not (off o5 ))
(on o6 )
(not (off o6 ))
(not (on o7 ))
(off o7 )
(not (on o8 ))
(off o8 )
(on o9 )
(not (off o9 ))
(on o10 )
(not (off o10 ))
(not (on o11 ))
(off o11 )
(not (on o12 ))
(off o12 )
(on o13 )
(not (off o13 ))
(not (on o14 ))
(off o14 )
(on o15 )
(not (off o15 ))
(not (on o16 ))
(off o16 )
(increase (total-cost) 100000))) 
)
