/**
 * A bunch of enums used to represent features that are mapped into
 * and out of vision. These aren't needed for vision, but for the
 * central mechanisms, and it's the kind of thing you end up
 * reimplementing regularly anyway!
 *
 * These should probably be referred to as linguistically assigned
 * visual attributes ;)
 */


#ifndef VISUAL_ATTRIBUTES_IDL
#define VISUAL_ATTRIBUTES_IDL

module VisualAttributes {

  /**
   * Colour enumeration.
   */

  enum Colour {
    RED,
    ORANGE,
    YELLOW,
    GREEN,
    BLUE,
    INDIGO,
    VIOLET,
    PINK,
    BLACK,
    WHITE,
    BROWN,
    GREY,
    PURPLE,
    UNKNOWN_COLOUR
  };

  /**
   * Sounds like a haircare product.
   */
  struct ColourWithConfidence {
    Colour m_colour;
    float m_confidence;
  };


  /**
   * Shape enumeration.
   */
  enum Shape {
    SQUARE,
    CUBE,
    TRIANGLE,
    PYRAMID,
    CIRCLE,
    SPHERE,
    CYLINDER,
    UNKNOWN_SHAPE
  };


  /**
   * Size enumeration
   */
  enum Size {
    TINY,
    SMALL,
    BIG,
    LARGE,
    HUGE,
    UNKNOW_SIZE
  };



};

#endif