function pdf=kdeFromData(data)

initializationMethod = 'Plugin' ; %'Silverman'; %
%initializationMethod = 'Silverman'; 
scaleErrorThreshold = 1/0.7 ; 1/0.7 ;1.5 ;
hellErrorGlobal = 0.1 ;% 0.11 / scaleErrorThreshold ;
nMaxComponents = 10 ;
nMaxComponentsPrior = nMaxComponents ;
pdf = updateIKDE( [], data, ...
   'initialize', 1 ,...
   'nMaxComponentsPrior', nMaxComponentsPrior,...
   'scaleErrorThreshold', scaleErrorThreshold,...
   'hellErrorGlobal', hellErrorGlobal,...
   'initializationMethod', initializationMethod);
