package cast.cdl.ui;


/**
* cast/cdl/ui/ComponentEventType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CAST.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public class ComponentEventType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 7;
  private static cast.cdl.ui.ComponentEventType[] __array = new cast.cdl.ui.ComponentEventType [__size];

  public static final int _ADD = 0;
  public static final cast.cdl.ui.ComponentEventType ADD = new cast.cdl.ui.ComponentEventType(_ADD);
  public static final int _OVERWRITE = 1;
  public static final cast.cdl.ui.ComponentEventType OVERWRITE = new cast.cdl.ui.ComponentEventType(_OVERWRITE);
  public static final int _DELETE = 2;
  public static final cast.cdl.ui.ComponentEventType DELETE = new cast.cdl.ui.ComponentEventType(_DELETE);
  public static final int _GET = 3;
  public static final cast.cdl.ui.ComponentEventType GET = new cast.cdl.ui.ComponentEventType(_GET);
  public static final int _START = 4;
  public static final cast.cdl.ui.ComponentEventType START = new cast.cdl.ui.ComponentEventType(_START);
  public static final int _END = 5;
  public static final cast.cdl.ui.ComponentEventType END = new cast.cdl.ui.ComponentEventType(_END);
  public static final int _PROPOSED = 6;
  public static final cast.cdl.ui.ComponentEventType PROPOSED = new cast.cdl.ui.ComponentEventType(_PROPOSED);

  public int value ()
  {
    return __value;
  }

  public static cast.cdl.ui.ComponentEventType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ComponentEventType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ComponentEventType
