package motivation.idl;


/**
* motivation/idl/AchieveGoalMotiveHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MotivationData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class AchieveGoalMotiveHelper
{
  private static String  _id = "IDL:motivation/idl/AchieveGoalMotive:1.0";

  public static void insert (org.omg.CORBA.Any a, motivation.idl.AchieveGoalMotive that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static motivation.idl.AchieveGoalMotive extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = planning.autogen.PlanningProcessRequestHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "m_ppr",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (motivation.idl.AchieveGoalMotiveHelper.id (), "AchieveGoalMotive", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static motivation.idl.AchieveGoalMotive read (org.omg.CORBA.portable.InputStream istream)
  {
    motivation.idl.AchieveGoalMotive value = new motivation.idl.AchieveGoalMotive ();
    value.m_ppr = planning.autogen.PlanningProcessRequestHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, motivation.idl.AchieveGoalMotive value)
  {
    planning.autogen.PlanningProcessRequestHelper.write (ostream, value.m_ppr);
  }

}
