package motivation.idl;

/**
* motivation/idl/AttentionMotiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MotivationData.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class AttentionMotiveHolder implements org.omg.CORBA.portable.Streamable
{
  public motivation.idl.AttentionMotive value = null;

  public AttentionMotiveHolder ()
  {
  }

  public AttentionMotiveHolder (motivation.idl.AttentionMotive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = motivation.idl.AttentionMotiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    motivation.idl.AttentionMotiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return motivation.idl.AttentionMotiveHelper.type ();
  }

}
