package BindingQueries;

/**
* BindingQueries/BasicQueryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BindingQueries.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class BasicQueryHolder implements org.omg.CORBA.portable.Streamable
{
  public BindingQueries.BasicQuery value = null;

  public BasicQueryHolder ()
  {
  }

  public BasicQueryHolder (BindingQueries.BasicQuery initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BindingQueries.BasicQueryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BindingQueries.BasicQueryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BindingQueries.BasicQueryHelper.type ();
  }

}
