#!/usr/bin/env python
import os, sys
output = os.path.abspath("../" * 7 + "output")
try: ldl = os.environ["LD_LIBRARY_PATH"] + ":%s"
except: ldl = "%s"
os.environ["LD_LIBRARY_PATH"] = ldl % (output + "/lib")
os.execlp("python", "python", "mbuilder.py")
