package org.cognitivesystems.comsys.autogen.ComsysEssentials;


/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/CacheMapping.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class CacheMapping implements org.omg.CORBA.portable.IDLEntity
{
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.IndexAssociation associations[] = null;

  public CacheMapping ()
  {
  } // ctor

  public CacheMapping (org.cognitivesystems.comsys.autogen.ComsysEssentials.IndexAssociation[] _associations)
  {
    associations = _associations;
  } // ctor

} // class CacheMapping
