package org.cognitivesystems.comsys.autogen.ComsysEssentials;


/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/CacheMappingHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

abstract public class CacheMappingHelper
{
  private static String  _id = "IDL:org/cognitivesystems/comsys/autogen/ComsysEssentials/CacheMapping:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cognitivesystems.comsys.autogen.ComsysEssentials.CacheMapping that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cognitivesystems.comsys.autogen.ComsysEssentials.CacheMapping extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.cognitivesystems.comsys.autogen.ComsysEssentials.IndexAssociationHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "associations",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.cognitivesystems.comsys.autogen.ComsysEssentials.CacheMappingHelper.id (), "CacheMapping", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cognitivesystems.comsys.autogen.ComsysEssentials.CacheMapping read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cognitivesystems.comsys.autogen.ComsysEssentials.CacheMapping value = new org.cognitivesystems.comsys.autogen.ComsysEssentials.CacheMapping ();
    int _len0 = istream.read_long ();
    value.associations = new org.cognitivesystems.comsys.autogen.ComsysEssentials.IndexAssociation[_len0];
    for (int _o1 = 0;_o1 < value.associations.length; ++_o1)
      value.associations[_o1] = org.cognitivesystems.comsys.autogen.ComsysEssentials.IndexAssociationHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cognitivesystems.comsys.autogen.ComsysEssentials.CacheMapping value)
  {
    ostream.write_long (value.associations.length);
    for (int _i0 = 0;_i0 < value.associations.length; ++_i0)
      org.cognitivesystems.comsys.autogen.ComsysEssentials.IndexAssociationHelper.write (ostream, value.associations[_i0]);
  }

}
