package org.cognitivesystems.comsys.autogen.ComsysEssentials;


/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/Nucleus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class Nucleus implements org.omg.CORBA.portable.IDLEntity
{
  public String nucleusId = null;
  public String plfId = null;
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.Cache discRefs = null;
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.Event events[] = null;
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.State states[] = null;
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.AspectualRelation aspectualRelations[] = null;
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.TemporalRelation temporalRelations[] = null;

  public Nucleus ()
  {
  } // ctor

  public Nucleus (String _nucleusId, String _plfId, org.cognitivesystems.comsys.autogen.ComsysEssentials.Cache _discRefs, org.cognitivesystems.comsys.autogen.ComsysEssentials.Event[] _events, org.cognitivesystems.comsys.autogen.ComsysEssentials.State[] _states, org.cognitivesystems.comsys.autogen.ComsysEssentials.AspectualRelation[] _aspectualRelations, org.cognitivesystems.comsys.autogen.ComsysEssentials.TemporalRelation[] _temporalRelations)
  {
    nucleusId = _nucleusId;
    plfId = _plfId;
    discRefs = _discRefs;
    events = _events;
    states = _states;
    aspectualRelations = _aspectualRelations;
    temporalRelations = _temporalRelations;
  } // ctor

} // class Nucleus
