package org.cognitivesystems.comsys.autogen.ComsysEssentials;


/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/SDRSType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class SDRSType implements org.omg.CORBA.portable.IDLEntity
{
  private org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSRelation ___relation;
  private org.cognitivesystems.comsys.autogen.ComsysEssentials.PackedLFs ___plf;
  private short __discriminator;
  private boolean __uninitialized = true;

  public SDRSType ()
  {
  }

  public short discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSRelation relation ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyrelation (__discriminator);
    return ___relation;
  }

  public void relation (org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSRelation value)
  {
    __discriminator = 1;
    ___relation = value;
    __uninitialized = false;
  }

  public void relation (short discriminator, org.cognitivesystems.comsys.autogen.ComsysEssentials.SDRSRelation value)
  {
    verifyrelation (discriminator);
    __discriminator = discriminator;
    ___relation = value;
    __uninitialized = false;
  }

  private void verifyrelation (short discriminator)
  {
    if (discriminator != 1)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public org.cognitivesystems.comsys.autogen.ComsysEssentials.PackedLFs plf ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyplf (__discriminator);
    return ___plf;
  }

  public void plf (org.cognitivesystems.comsys.autogen.ComsysEssentials.PackedLFs value)
  {
    __discriminator = 2;
    ___plf = value;
    __uninitialized = false;
  }

  public void plf (short discriminator, org.cognitivesystems.comsys.autogen.ComsysEssentials.PackedLFs value)
  {
    verifyplf (discriminator);
    __discriminator = discriminator;
    ___plf = value;
    __uninitialized = false;
  }

  private void verifyplf (short discriminator)
  {
    if (discriminator != 2)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public void _default ()
  {
    __discriminator = -32768;
    __uninitialized = false;
  }

  public void _default (short discriminator)
  {
    verifyDefault( discriminator ) ;
    __discriminator = discriminator ;
    __uninitialized = false;
  }

  private void verifyDefault( short value )
  {
    switch (value) {
      case 1:
      case 2:
        throw new org.omg.CORBA.BAD_OPERATION() ;

      default:
        return;
    }
  }

} // class SDRSType
