package org.cognitivesystems.comsys.autogen.ComsysEssentials;


/**
* org/cognitivesystems/comsys/autogen/ComsysEssentials/SpatioTemporalRepresentation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ComsysEssentials.idl
* Freitag, 13. MŠrz 2009 17.31 Uhr CET
*/

public final class SpatioTemporalRepresentation implements org.omg.CORBA.portable.IDLEntity
{
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.Nucleus nuclei[] = null;
  public org.cognitivesystems.comsys.autogen.ComsysEssentials.InterNucleusRelation interNucleusRelations[] = null;
  public String currentNucleusId = null;

  public SpatioTemporalRepresentation ()
  {
  } // ctor

  public SpatioTemporalRepresentation (org.cognitivesystems.comsys.autogen.ComsysEssentials.Nucleus[] _nuclei, org.cognitivesystems.comsys.autogen.ComsysEssentials.InterNucleusRelation[] _interNucleusRelations, String _currentNucleusId)
  {
    nuclei = _nuclei;
    interNucleusRelations = _interNucleusRelations;
    currentNucleusId = _currentNucleusId;
  } // ctor

} // class SpatioTemporalRepresentation
