#! /usr/bin/env python

if __name__ == "__main__":
    import sys, os
    import eng2mapl
    assert len(sys.argv) == 2, "Only accepts one english phrase as input."
    phrase = sys.argv[1]
    IN = os.path.join(os.getcwd(), "examples/problem1.mapl.tmpl")
    OUT = "examples/problem1.mapl"
    tmpl = open(IN).read()
    prob = open(OUT, "w")
    goal = eng2mapl.eng2goal(phrase)
    comment = ";; Logical form for '%s':" % phrase
    prob.write(tmpl % (comment, goal))
