#ifndef _CANOPEN_PDO_H_
#define _CANOPEN_PDO_H_

enum ECANopenPdo
{
	TPDO_NOP,

	// Axis
	TPDO_DYNAMICS,
	TPDO_POWER,
	TPDO_VERSION,

	// Controller
	RPDO_CONTROL_PARAMETERS_1,
	RPDO_CONTROL_PARAMETERS_2,
	RPDO_COLLISION_DETECTION,

	// Axis FSM
	TPDO_AXIS_FSM_STATE,
	RPDO_AXIS_FSM_COMMAND,

	// Axis FSM parameters
	RPDO_P2P_SETUP,
	RPDO_KNI_RNI_ENC_FACTORS,
	RPDO_ENCODER_SETUP,

	// MoveBuffer
	RPDO_MOVE_BUFFER_FSM_COMMAND,
//	TPDO_MOVE_BUFFER_FSM_STATE,
	RPDO_POLY_PARAMETERS_1,
	RPDO_POLY_PARAMETERS_2,

	// Debug
	RPDO_DEBUG,
	TPDO_DEVIATION,
	TPDO_DEBUG_1,
	TPDO_DEBUG_2,
	
	// Analysis
	TPDO_ANALYSIS,
	RPDO_ANALYSIS_COMMAND,

	// Step
	RPDO_STEP_DETAILS,

	// Controller
	RPDO_CONTROL_PARAMETERS_3
};

#endif // _CANOPEN_PDO_H_
